package main

import (
	"fmt"
	"strings"
)

func zigKeySet(name string, ks *KeySet, sf *SigFile, b *strings.Builder) {
	fmt.Fprintf(b, "pub const %s: KeySet = .{\n", name)
	fmt.Fprintf(b, "    .t = %d,\n    .n = %d,\n    .public_key = %q,\n", ks.T, ks.N, ks.PublicKey)
	b.WriteString("    .parties = &.{\n")
	for _, p := range ks.Parties {
		b.WriteString("        .{\n")
		fmt.Fprintf(b, "            .index = %d,\n", p.Index)
		for _, f := range [][2]string{
			{"x", p.X}, {"big_x", p.BigX}, {"paillier_p", p.PaillierP}, {"paillier_q", p.PaillierQ},
			{"n_tilde", p.NTilde}, {"h1", p.H1}, {"h2", p.H2},
			{"aux_p_safe", p.AuxPSafe}, {"aux_q_safe", p.AuxQSafe}, {"aux_lambda", p.AuxLambda},
		} {
			fmt.Fprintf(b, "            .%s = %q,\n", f[0], f[1])
		}
		b.WriteString("        },\n")
	}
	b.WriteString("    },\n")
	fmt.Fprintf(b, "    .message = %q,\n", sf.Message)
	b.WriteString("    .signatures = &.{\n")
	for _, s := range sf.Signatures {
		sg := make([]string, len(s.Signers))
		for i, v := range s.Signers {
			sg[i] = fmt.Sprint(v)
		}
		fmt.Fprintf(b, "        .{ .signers = &.{ %s }, .r = %q, .s = %q },\n", strings.Join(sg, ", "), s.R, s.S)
	}
	b.WriteString("    },\n};\n")
}

func cmdZigVectors(tk, ts, zk, zs string) {
	if tk == "" || ts == "" || zk == "" || zs == "" {
		fatal("zigvectors needs -tsslib-keys -tsslib-sigs -zig-keys -zig-sigs")
	}
	var a, c KeySet
	var b, d SigFile
	for _, x := range []struct {
		p string
		v any
	}{{tk, &a}, {ts, &b}, {zk, &c}, {zs, &d}} {
		if err := readJSON(x.p, x.v); err != nil {
			fatal("%v", err)
		}
	}
	var sb strings.Builder
	sb.WriteString("// SPDX-License-Identifier: MIT\n// Generated by tools/tsslib — do not edit.\n\n")
	sb.WriteString(`pub const Party = struct {
    index: u32,
    x: []const u8,
    big_x: []const u8,
    paillier_p: []const u8,
    paillier_q: []const u8,
    n_tilde: []const u8,
    h1: []const u8,
    h2: []const u8,
    aux_p_safe: []const u8,
    aux_q_safe: []const u8,
    aux_lambda: []const u8,
};

pub const Sig = struct {
    signers: []const u32,
    r: []const u8,
    s: []const u8,
};

pub const KeySet = struct {
    t: u32,
    n: u32,
    public_key: []const u8,
    parties: []const Party,
    message: []const u8,
    signatures: []const Sig,
};

`)
	zigKeySet("tsslib_keygen", &a, &b, &sb)
	sb.WriteString("\n")
	zigKeySet("zig_keys_tsslib_signed", &c, &d, &sb)
	fmt.Print(sb.String())
}
