// SPDX-License-Identifier: MIT
// Reference-vector generator for zig-libs `modules/coconut`.
//
// Runs docknetwork/crypto's `coconut-crypto` 0.14 (Apache-2.0, arkworks
// BLS12-381) as a black box and prints a Zig source file with the values it
// computed. No coconut-crypto source is copied.
//
// Only the plain Pointcheval-Sanders core is exercised: threshold key
// dealing (Shamir), deterministic signing `sigma = (h, h^(x + sum y_j m_j))`
// per authority (h = hash of the messages, identical for all authorities),
// and Lagrange-at-0 aggregation. The foreign `SignatureParams.g_tilde` is
// replaced by the standard G2 generator (its fields are public).

use ark_bls12_381::{Bls12_381, Fq, Fq2, Fr, G1Affine, G2Affine};
use ark_ec::AffineRepr;
use ark_ff::{BigInteger, Field, PrimeField, UniformRand, Zero};
use ark_serialize::CanonicalSerialize;
use ark_std::rand::{rngs::StdRng, SeedableRng};
use blake2::Blake2b512;
use coconut_crypto::keygen::common::Threshold;
use coconut_crypto::keygen::shamir_ss::deal;
use coconut_crypto::setup::{PublicKey, SignatureParams};
use coconut_crypto::{AggregatedSignature, Signature};
use std::fmt::Write;

fn hex(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

fn fq_be(f: &Fq) -> [u8; 48] {
    f.into_bigint().to_bytes_be().try_into().unwrap()
}

fn fq_sign(y: &Fq) -> bool {
    y.into_bigint() > (-*y).into_bigint()
}

// ZCash compressed G1: flags(3 bits) | x (48 BE). 0x80 compressed, 0x40
// infinity, 0x20 "y is the larger root".
fn g1_enc(p: &G1Affine) -> String {
    let mut out = [0u8; 48];
    if p.is_zero() {
        out[0] = 0xC0;
        return hex(&out);
    }
    out = fq_be(&p.x);
    out[0] |= 0x80;
    if fq_sign(&p.y) {
        out[0] |= 0x20;
    }
    hex(&out)
}

// ZCash compressed G2: flags | x.c1 (48 BE) || x.c0 (48 BE); the sign flag
// is decided lexicographically on (y.c1, y.c0).
fn g2_enc(p: &G2Affine) -> String {
    let mut out = [0u8; 96];
    if p.is_zero() {
        out[0] = 0xC0;
        return hex(&out);
    }
    let x: &Fq2 = &p.x;
    out[..48].copy_from_slice(&fq_be(&x.c1));
    out[48..].copy_from_slice(&fq_be(&x.c0));
    out[0] |= 0x80;
    let y: &Fq2 = &p.y;
    let big = if !y.c1.is_zero() { fq_sign(&y.c1) } else { fq_sign(&y.c0) };
    if big {
        out[0] |= 0x20;
    }
    hex(&out)
}

fn fr_enc(f: &Fr) -> String {
    hex(&f.into_bigint().to_bytes_be())
}

/// (sigma_1, sigma_2) of a foreign signature, via its arkworks serialisation
/// (the fields are crate-private): 48 + 48 compressed bytes.
fn split_sig(s: &Signature<Bls12_381>) -> (G1Affine, G1Affine) {
    use ark_serialize::CanonicalDeserialize;
    let mut buf = Vec::new();
    s.serialize_compressed(&mut buf).unwrap();
    assert_eq!(buf.len(), 96);
    (
        G1Affine::deserialize_compressed(&buf[..48]).unwrap(),
        G1Affine::deserialize_compressed(&buf[48..]).unwrap(),
    )
}

fn zstr_list(items: &[String]) -> String {
    let v: Vec<String> = items.iter().map(|s| format!("\"{}\"", s)).collect();
    format!("&.{{ {} }}", v.join(", "))
}

fn subsets(n: u16, t: u16) -> Vec<Vec<u16>> {
    // A few distinct size-t subsets of 1..=n: the first t, the last t, and
    // one that skips index 1.
    let first: Vec<u16> = (1..=t).collect();
    let last: Vec<u16> = (n - t + 1..=n).collect();
    let mut skip: Vec<u16> = (2..=n).step_by(if n > 3 { 2 } else { 1 }).collect();
    skip.truncate(t as usize);
    let mut out = vec![first, last];
    if skip.len() == t as usize && !out.contains(&skip) {
        out.push(skip);
    }
    out
}

fn main() {
    // Codec self-check against the published ZCash generator encodings.
    assert_eq!(
        g1_enc(&G1Affine::generator()),
        "97f1d3a73197d7942695638c4fa9ac0fc3688c4f9774b905a14e3a3f171bac586c55e83ff97a1aeffb3af00adb22c6bb"
    );
    assert_eq!(
        g2_enc(&G2Affine::generator()),
        "93e02b6052719f607dacd3a088274f65596bd0d09920b61ab5da61bbdc7f5049334cf11213945d57e5ac7d055d042b7e024aa2b2f08f0a91260805272dc51051c6e47ad4fa403b02b4510b647ae3d1770bac0326a805bbefd48056c8c121bdb8"
    );

    let mut rng = StdRng::seed_from_u64(0xC0C0_0001);
    let mut o = String::new();
    writeln!(o, "// SPDX-License-Identifier: MIT").unwrap();
    writeln!(o, "//").unwrap();
    writeln!(o, "// GENERATED by tools/vectors (Cargo project) -- do not edit. Regenerate:").unwrap();
    writeln!(o, "//   hw run -- cargo run -q --release --manifest-path modules/coconut/tools/vectors/Cargo.toml > modules/coconut/src/interop_vectors.zig").unwrap();
    writeln!(o, "//").unwrap();
    writeln!(o, "// Source: coconut-crypto 0.14.0 (docknetwork/crypto, Apache-2.0, arkworks BLS12-381),").unwrap();
    writeln!(o, "// run as a black box with StdRng seed 0xC0C00001. Foreign operations: Shamir dealing of").unwrap();
    writeln!(o, "// (x, y_1..y_q), Signature::new_deterministic per authority (h = hash of the messages,").unwrap();
    writeln!(o, "// common to all authorities), AggregatedSignature::new (Lagrange at 0), PublicKey::new,").unwrap();
    writeln!(o, "// and the foreign verify (asserted here before printing). SignatureParams.g_tilde is the").unwrap();
    writeln!(o, "// standard G2 generator. Authority indices are 1..=n.").unwrap();
    writeln!(o, "//").unwrap();
    writeln!(o, "// Encodings. Points: ZCash compressed, converted explicitly from arkworks affine").unwrap();
    writeln!(o, "// coordinates (NOT arkworks' native little-endian format): G1 = flags|x (48 B BE),").unwrap();
    writeln!(o, "// G2 = flags|x.c1||x.c0 (96 B BE); flag 0x80 compressed, 0x40 infinity, 0x20 y is the").unwrap();
    writeln!(o, "// larger root (lexicographic on (c1, c0) for G2). The tool asserts the codec on both").unwrap();
    writeln!(o, "// generators. Attributes: Fr scalars as 32-byte big-endian canonical hex (uniformly").unwrap();
    writeln!(o, "// random, not small integers). All values are lowercase hex strings.\n").unwrap();
    writeln!(o, "// zig fmt: off\n").unwrap();
    writeln!(o, "pub const VkShare = struct {{ index: u64, alpha: []const u8, betas: []const []const u8 }};").unwrap();
    writeln!(o, "pub const Partial = struct {{ index: u64, s: []const u8 }};").unwrap();
    writeln!(o, "pub const Subset = struct {{ indices: []const u64, sigma_s: []const u8 }};").unwrap();
    writeln!(o, "pub const Case = struct {{").unwrap();
    writeln!(o, "    q: usize,\n    t: u64,\n    n: u64,\n    vk_alpha: []const u8,\n    vk_betas: []const []const u8,\n    vk_shares: []const VkShare,\n    attributes: []const []const u8,\n    h: []const u8,\n    partials: []const Partial,\n    subsets: []const Subset,\n}};\n").unwrap();
    writeln!(o, "pub const cases = [_]Case{{").unwrap();

    let g_tilde = G2Affine::generator();
    for &(t, n, q) in &[(2u16, 3u16, 1usize), (2, 3, 3), (3, 5, 2), (3, 5, 4), (2, 3, 4)] {
        let params = SignatureParams::<Bls12_381> {
            g: G1Affine::generator(),
            g_tilde,
            h: vec![],
        };
        let (sk, sks) = deal::<_, Fr>(&mut rng, q as u32, Threshold::new(t, n).unwrap()).unwrap();
        let vk = PublicKey::<Bls12_381>::new(&sk, &params);
        let msgs: Vec<Fr> = (0..q).map(|_| Fr::rand(&mut rng)).collect();

        let sigs: Vec<Signature<Bls12_381>> = sks
            .iter()
            .map(|s| Signature::new_deterministic::<Blake2b512>(&msgs, s).unwrap())
            .collect();
        let (h, _) = split_sig(&sigs[0]);
        let mut partial_s = Vec::new();
        for (i, s) in sigs.iter().enumerate() {
            let (h_i, s2) = split_sig(s);
            assert_eq!(h_i, h);
            let pk_i = PublicKey::<Bls12_381>::new(&sks[i], &params);
            let _ = pk_i;
            partial_s.push(s2);
        }

        writeln!(o, "    .{{").unwrap();
        writeln!(o, "        .q = {q}, .t = {t}, .n = {n},").unwrap();
        writeln!(o, "        .vk_alpha = \"{}\",", g2_enc(&vk.alpha_tilde)).unwrap();
        let betas: Vec<String> = vk.beta_tilde.iter().map(g2_enc).collect();
        writeln!(o, "        .vk_betas = {},", zstr_list(&betas)).unwrap();
        writeln!(o, "        .vk_shares = &.{{").unwrap();
        for (i, s) in sks.iter().enumerate() {
            let pk = PublicKey::<Bls12_381>::new(s, &params);
            let b: Vec<String> = pk.beta_tilde.iter().map(g2_enc).collect();
            writeln!(o, "            .{{ .index = {}, .alpha = \"{}\", .betas = {} }},", i + 1, g2_enc(&pk.alpha_tilde), zstr_list(&b)).unwrap();
        }
        writeln!(o, "        }},").unwrap();
        let attrs: Vec<String> = msgs.iter().map(fr_enc).collect();
        writeln!(o, "        .attributes = {},", zstr_list(&attrs)).unwrap();
        writeln!(o, "        .h = \"{}\",", g1_enc(&h)).unwrap();
        writeln!(o, "        .partials = &.{{").unwrap();
        for (i, s) in partial_s.iter().enumerate() {
            writeln!(o, "            .{{ .index = {}, .s = \"{}\" }},", i + 1, g1_enc(s)).unwrap();
        }
        writeln!(o, "        }},").unwrap();
        writeln!(o, "        .subsets = &.{{").unwrap();
        for sub in subsets(n, t) {
            let it = sub.iter().map(|&i| (i, &sigs[i as usize - 1]));
            let agg = AggregatedSignature::<Bls12_381>::new(it, &h).unwrap();
            // foreign verification of its own aggregate
            agg.verify(&msgs, &vk, &params).unwrap();
            let mut buf = Vec::new();
            (*agg).serialize_compressed(&mut buf).unwrap();
            use ark_serialize::CanonicalDeserialize;
            let s = G1Affine::deserialize_compressed(&buf[48..]).unwrap();
            let idx: Vec<String> = sub.iter().map(|i| i.to_string()).collect();
            writeln!(o, "            .{{ .indices = &.{{ {} }}, .sigma_s = \"{}\" }},", idx.join(", "), g1_enc(&s)).unwrap();
        }
        writeln!(o, "        }},").unwrap();
        writeln!(o, "    }},").unwrap();
        let _ = Fq::ONE;
    }
    writeln!(o, "}};").unwrap();
    print!("{o}");
}
