// SPDX-License-Identifier: MIT
//! Bitcoin Core's official plain-base58 conformance corpus, transcribed
//! verbatim (not hand-typed, generated by script from the fetched JSON) from
//! `src/test/data/base58_encode_decode.json` (fetched 2026-08 from the
//! `bitcoin/bitcoin` `master` branch) -- see `../NOTICE` for the copyright
//! notice this reproduction owes.
//!
//! Until this file, `base58.zig`'s only known-answer test was a single
//! address independently derived by the same author who wrote the encoder
//! (a Python bignum script, "while authoring this module" -- see the comment
//! above `p2pkh_vector_address` in `base58.zig`), which proves self-
//! consistency, not correctness against an outside implementation. These 21
//! pairs are Bitcoin Core's own test suite for `EncodeBase58`/`DecodeBase58`
//! -- an external oracle this module has never been checked against before.

pub const Vector = struct {
    /// The raw payload, as a hex string (even length, no `0x`).
    hex: []const u8,
    /// The base58 encoding Bitcoin Core's `EncodeBase58` produces for it.
    base58: []const u8,
};

pub const vectors = [_]Vector{
    .{
        .hex = "",
        .base58 = "",
    },
    .{
        .hex = "61",
        .base58 = "2g",
    },
    .{
        .hex = "626262",
        .base58 = "a3gV",
    },
    .{
        .hex = "636363",
        .base58 = "aPEr",
    },
    .{
        .hex = "73696d706c792061206c6f6e6720737472696e67",
        .base58 = "2cFupjhnEsSn59qHXstmK2ffpLv2",
    },
    .{
        .hex = "00eb15231dfceb60925886b67d065299925915aeb172c06647",
        .base58 = "1NS17iag9jJgTHD1VXjvLCEnZuQ3rJDE9L",
    },
    .{
        .hex = "516b6fcd0f",
        .base58 = "ABnLTmg",
    },
    .{
        .hex = "bf4f89001e670274dd",
        .base58 = "3SEo3LWLoPntC",
    },
    .{
        .hex = "572e4794",
        .base58 = "3EFU7m",
    },
    .{
        .hex = "ecac89cad93923c02321",
        .base58 = "EJDM8drfXA6uyA",
    },
    .{
        .hex = "10c8511e",
        .base58 = "Rt5zm",
    },
    .{
        .hex = "00000000000000000000",
        .base58 = "1111111111",
    },
    .{
        .hex = "00000000000000000000000000000000000000000000000000000000000000000000000000000000",
        .base58 = "1111111111111111111111111111111111111111",
    },
    .{
        .hex = "00000000000000000000000000000000000000000000000000000000000000000000000000000001",
        .base58 = "1111111111111111111111111111111111111112",
    },
    .{
        .hex = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000" ++
            "000000000000000000000000000000000000000000000000000000000000000000000000000000000000ec39" ++
            "d04c37e71e5d591881f6",
        .base58 = "111111111111111111111111111111111111111111111111111111111111111111111111111111111111115T" ++
            "YzLYH1udmLdzCLM",
    },
    .{
        .hex = "000111d38e5fc9071ffcd20b4a763cc9ae4f252bb4e48fd66a835e252ada93ff480d6dd43dc62a641155a5",
        .base58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz",
    },
    .{
        .hex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b" ++
            "2c2d2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f5051525354555657" ++
            "58595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80818283" ++
            "8485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeaf" ++
            "b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadb" ++
            "dcdddedfe0e1e2e3e4e5e6e7e8e9eaebecedeeeff0f1f2f3f4f5f6f7f8f9fafbfcfdfeff",
        .base58 = "1cWB5HCBdLjAuqGGReWE3R3CguuwSjw6RHn39s2yuDRTS5NsBgNiFpWgAnEx6VQi8csexkgYw3mdYrMHr8x9i7aE" ++
            "wP8kZ7vccXWqKDvGv3u1GxFKPuAkn8JCPPGDMf3vMMnbzm6Nh9zh1gcNsMvH3ZNLmP5fSG6DGbbi2tuwMWPthr4b" ++
            "oWwCxf7ewSgNQeacyozhKDDQQ1qL5fQFUW52QKUZDZ5fw3KXNQJMcNTcaB723LchjeKun7MuGW5qyCBZYzA1Kjof" ++
            "N1gYBV3NqyhQJ3Ns746GNuf9N2pQPmHz4xpnSrrfCvy6TVVz5d4PdrjeshsWQwpZsZGzvbdAdN8MKV5QsBDY",
    },
    .{
        .hex = "271F359E",
        .base58 = "zzzzy",
    },
    .{
        .hex = "271F359F",
        .base58 = "zzzzz",
    },
    .{
        .hex = "271F35A0",
        .base58 = "211111",
    },
    .{
        .hex = "271F35A1",
        .base58 = "211112",
    },
};
