// SPDX-License-Identifier: MIT
// Reference-vector generator for zig-libs `modules/bulletproofs`.
//
// Runs dalek-cryptography/bulletproofs 4.0.0 and merlin 3.0.0 (both MIT) as
// black boxes and prints a Zig source file holding what they computed. No
// crate source is copied; only run-time outputs are recorded.
//
//   A. Merlin transcripts: scripted append/challenge sequences and the
//      challenge bytes `merlin::Transcript` produced.
//   B. dalek's `PedersenGens::default().B_blinding`.
//   C. Range proofs made by dalek (`prove_single_with_rng`, ChaCha20 seeded,
//      so the output is reproducible), each verified by dalek first.
//   D. Range proofs made by zig-libs, read from stdin (`zig_proofs.txt`,
//      one `<n> <label hex> <V hex> <proof hex>` per line), each VERIFIED BY
//      DALEK here; the tool aborts if dalek rejects one. They are re-emitted
//      so the Zig test holds them too.
//
// Usage: see ../README.md.

use bulletproofs::{BulletproofGens, PedersenGens, RangeProof};
use curve25519_dalek_ng::ristretto::CompressedRistretto;
use curve25519_dalek_ng::scalar::Scalar;
use merlin::Transcript;
use rand_chacha::rand_core::SeedableRng;
use rand_chacha::ChaCha20Rng;
use std::io::BufRead;

const LABEL: &[u8] = b"zig-libs bulletproofs interop";

enum Op {
    Append(&'static [u8], Vec<u8>),
    AppendU64(&'static [u8], u64),
    Challenge(&'static [u8], usize),
}

struct Script {
    label: &'static [u8],
    ops: Vec<Op>,
}

fn zstr(b: &[u8]) -> String {
    let mut s = String::from("\"");
    for &c in b {
        s.push_str(&format!("\\x{:02x}", c));
    }
    s.push('"');
    s
}

fn scripts() -> Vec<Script> {
    vec![
        // merlin's own README/test example.
        Script {
            label: b"test protocol",
            ops: vec![
                Op::Append(b"some label", b"some data".to_vec()),
                Op::Challenge(b"challenge", 32),
            ],
        },
        // Crosses the 166-byte STROBE rate in both AD and PRF.
        Script {
            label: b"Conformance Test Protocol",
            ops: vec![
                Op::Append(b"step1", vec![99u8; 1024]),
                Op::Challenge(b"challenge", 300),
                Op::Append(b"step2", vec![]),
                Op::Challenge(b"c2", 64),
            ],
        },
        // The shapes dalek uses: dom-sep, u64s, 32-byte points/scalars,
        // back-to-back 64-byte challenges.
        Script {
            label: b"",
            ops: vec![
                Op::Append(b"dom-sep", b"rangeproof v1".to_vec()),
                Op::AppendU64(b"n", 64),
                Op::AppendU64(b"m", 1),
                Op::Append(b"V", (0u8..32).collect()),
                Op::Challenge(b"y", 64),
                Op::Challenge(b"z", 64),
                Op::Append(b"", (0u8..200).collect()),
                Op::Challenge(b"", 1),
                Op::Challenge(b"x", 165),
                Op::Challenge(b"w", 167),
            ],
        },
    ]
}

fn main() {
    let mut out = String::new();
    out.push_str("// SPDX-License-Identifier: MIT\n");
    out.push_str("// GENERATED by modules/bulletproofs/tools/dalek (see tools/README.md) -- do not edit.\n");
    out.push_str("// Producers: merlin 3.0.0 and bulletproofs 4.0.0 (dalek-cryptography, MIT), run as black boxes.\n");
    out.push_str("// Hex strings: points are 32-byte compressed Ristretto255, proofs are RangeProof::to_bytes().\n\n");

    // A. Merlin.
    out.push_str("pub const MerlinOp = union(enum) {\n    append: struct { label: []const u8, msg: []const u8 },\n    append_u64: struct { label: []const u8, v: u64 },\n    /// `out` is what merlin returned from `challenge_bytes(label, out.len)`.\n    challenge: struct { label: []const u8, out: []const u8 },\n};\n\n");
    out.push_str("pub const MerlinScript = struct { label: []const u8, ops: []const MerlinOp };\n\n");
    out.push_str("pub const merlin_scripts = [_]MerlinScript{\n");
    for sc in scripts() {
        let mut t = Transcript::new(sc.label);
        out.push_str(&format!("    .{{ .label = {}, .ops = &.{{\n", zstr(sc.label)));
        for op in &sc.ops {
            match op {
                Op::Append(l, m) => {
                    t.append_message(l, m);
                    out.push_str(&format!("        .{{ .append = .{{ .label = {}, .msg = {} }} }},\n", zstr(l), zstr(m)));
                }
                Op::AppendU64(l, v) => {
                    t.append_u64(l, *v);
                    out.push_str(&format!("        .{{ .append_u64 = .{{ .label = {}, .v = {} }} }},\n", zstr(l), v));
                }
                Op::Challenge(l, len) => {
                    let mut buf = vec![0u8; *len];
                    t.challenge_bytes(l, &mut buf);
                    out.push_str(&format!("        .{{ .challenge = .{{ .label = {}, .out = {} }} }},\n", zstr(l), zstr(&buf)));
                }
            }
        }
        out.push_str("    } },\n");
    }
    out.push_str("};\n\n");

    // B. Pedersen generators.
    let pc_gens = PedersenGens::default();
    out.push_str(&format!("/// `PedersenGens::default().B` (the Ristretto255 base point).\npub const pedersen_b = \"{}\";\n", hex::encode(pc_gens.B.compress().as_bytes())));
    out.push_str(&format!("/// `PedersenGens::default().B_blinding`.\npub const pedersen_b_blinding = \"{}\";\n\n", hex::encode(pc_gens.B_blinding.compress().as_bytes())));

    // C. dalek proofs.
    let bp_gens = BulletproofGens::new(64, 1);
    let mut rng = ChaCha20Rng::from_seed([7u8; 32]);
    out.push_str(&format!("/// The Merlin label both directions use (`Transcript::new`).\npub const label = {};\n\n", zstr(LABEL)));
    out.push_str("pub const Proof = struct { n: usize, v: []const u8, proof: []const u8 };\n\n");
    out.push_str("/// Made by dalek's `RangeProof::prove_single_with_rng`, accepted by its `verify_single`.\npub const dalek_proofs = [_]Proof{\n");
    let mut count_c = 0;
    for &(n, values) in &[
        (8usize, &[0u64, 1, 77, 255][..]),
        (16, &[0, 12345, 65535][..]),
        (32, &[0, 3_000_000_000, u32::MAX as u64][..]),
        (64, &[0, 1, 0x0123_4567_89ab_cdef, u64::MAX][..]),
    ] {
        for &v in values {
            let blinding = Scalar::random(&mut rng);
            let mut pt = Transcript::new(LABEL);
            let (proof, commitment) =
                RangeProof::prove_single_with_rng(&bp_gens, &pc_gens, &mut pt, v, &blinding, n, &mut rng)
                    .expect("dalek prove");
            let mut vt = Transcript::new(LABEL);
            proof
                .verify_single_with_rng(&bp_gens, &pc_gens, &mut vt, &commitment, n, &mut rng)
                .expect("dalek verifies its own proof");
            out.push_str(&format!(
                "    .{{ .n = {}, .v = \"{}\", .proof = \"{}\" }},\n",
                n,
                hex::encode(commitment.as_bytes()),
                hex::encode(proof.to_bytes())
            ));
            count_c += 1;
        }
    }
    out.push_str("};\n\n");

    // D. zig-libs proofs, verified by dalek.
    out.push_str("/// Made by this module (`tools/dalek/zig_proofs.txt`), each ACCEPTED by dalek's `verify_single` when this file was generated.\npub const zig_proofs_dalek_accepted = [_]Proof{\n");
    let mut count_d = 0;
    for line in std::io::stdin().lock().lines() {
        let line = line.expect("stdin");
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split(' ').collect();
        assert_eq!(f.len(), 4, "bad line: {line}");
        let n: usize = f[0].parse().expect("n");
        assert_eq!(hex::decode(f[1]).expect("label hex"), LABEL, "label");
        let v_bytes = hex::decode(f[2]).expect("V hex");
        let commitment = CompressedRistretto::from_slice(&v_bytes);
        let proof_bytes = hex::decode(f[3]).expect("proof hex");
        let proof = RangeProof::from_bytes(&proof_bytes).expect("dalek parses the zig-libs proof");
        let mut vt = Transcript::new(LABEL);
        proof
            .verify_single_with_rng(&bp_gens, &pc_gens, &mut vt, &commitment, n, &mut rng)
            .unwrap_or_else(|e| panic!("dalek REJECTS a zig-libs proof (n={n}): {e:?}"));
        out.push_str(&format!("    .{{ .n = {}, .v = \"{}\", .proof = \"{}\" }},\n", n, f[2], f[3]));
        count_d += 1;
    }
    out.push_str("};\n");
    assert!(count_c > 0 && count_d > 0, "empty corpus");
    print!("{out}");
}
