// SPDX-License-Identifier: MIT
//! tz — IANA time-zone offset lookup: zone name → UTC offset/DST at an instant
//! via committed transition table + POSIX-TZ footer rule. Composes datefmt.
//!
//! `tz_data.zig` (generated by the authors' `tz-gen` tool from a pinned IANA
//! tzdata release) holds each zone's UTC-offset transitions from 1970 onward plus
//! its POSIX-TZ footer rule. This module resolves a zone by name and reports
//! the UTC offset (and DST flag) at a given instant: a binary search over the
//! explicit transitions, then the POSIX rule for instants past the last one
//! (~2038+).

const std = @import("std");
const datefmt = @import("datefmt");
const tz_data = @import("tz_data.zig");

pub const meta = .{
    // The module catalog's one-line entry. This IS the source of truth:
    // README.md's table is rendered from it by `zig build gen-catalog`.
    .doc = "IANA time-zone offset lookup — zone name → UTC offset/DST at a given instant (598 zones + POSIX-TZ footer).",
    // The catalog's Platform cell. Prose, because it carries nuance the
    // `platform` enum below cannot -- "any (packer: linux)", "amd64 asm +
    // portable fallback". Rendered by `gen-catalog` alongside `doc`.
    .platform_note = "any",
    .targets = .{ .linux64, .windows },
    .platform = .any,
    .role = .util,
    .concurrency = .reentrant,
    .model_after = "IANA tzdata (zic) + POSIX TZ footer rule",
    .deps = .{"datefmt"},
};

pub const Zone = tz_data.Zone;
pub const Transition = tz_data.Transition;
pub const zones = tz_data.zones;

pub const Offset = struct {
    /// UTC offset in seconds (east of UTC positive: CEST = +7200).
    off: i32,
    dst: bool,
};

/// Resolve an IANA zone id (`"Europe/Prague"`, `"America/New_York"`, `"UTC"`).
/// Case-sensitive, matching the IANA database. Returns null for unknown names.
pub fn find(name: []const u8) ?*const tz_data.Zone {
    // zones are emitted sorted by name → binary search.
    var lo: usize = 0;
    var hi: usize = tz_data.zones.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, tz_data.zones[mid].name, name)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return &tz_data.zones[mid],
        }
    }
    return null;
}

/// UTC offset (+ DST flag) in `zone` at the given Unix instant.
pub fn offsetAt(zone: *const tz_data.Zone, unix: i64) Offset {
    const tr = zone.trans;
    if (tr.len == 0) {
        if (posixOffset(zone.posix, unix)) |o| return o;
        return .{ .off = zone.init_off, .dst = zone.init_dst };
    }
    if (unix < tr[0].ts) return .{ .off = zone.init_off, .dst = zone.init_dst };
    if (unix >= tr[tr.len - 1].ts) {
        // Past the last explicit transition — apply the POSIX-TZ footer rule.
        if (posixOffset(zone.posix, unix)) |o| return o;
        const last = tr[tr.len - 1];
        return .{ .off = last.off, .dst = last.dst };
    }
    // Rightmost transition with ts <= unix (unix is within [tr[0], tr[last])).
    var lo: usize = 0;
    var hi: usize = tr.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (tr[mid].ts <= unix) lo = mid + 1 else hi = mid;
    }
    const t = tr[lo - 1];
    return .{ .off = t.off, .dst = t.dst };
}

// ---------------------------------------------------------------------------
// POSIX-TZ footer evaluation (RFC 9636 §3.3 / the tzfile(5) footer)
//   stdoffset[dst[offset][,start[/time],end[/time]]]
// All three rule forms are evaluated: `Mm.w.d` (nth/last weekday of a month),
// `Jn` (1<=n<=365, Julian day not counting Feb 29 — day 60 is always March 1),
// and plain `n` (0<=n<=365, day of year counting Feb 29).
// ---------------------------------------------------------------------------

const DEFAULT_DST_TIME: i32 = 2 * 3600; // 02:00 local, POSIX default

/// A parsed POSIX-TZ footer: a constant offset, or standard + daylight
/// offsets with the two yearly rules.
const PosixRule = struct {
    utc_std: i32,
    dst: ?struct {
        utc_dst: i32,
        start: Rule,
        start_time: i32,
        end: Rule,
        end_time: i32,
    },

    /// The UTC instants DST starts and ends in `year` (the year `offsetAt`
    /// evaluates an instant in is its UTC year).
    fn transitionsIn(p: PosixRule, year: i32) ?[2]i64 {
        const d = p.dst orelse return null;
        const start_local = ruleDateUnix(year, d.start, d.start_time) orelse return null;
        const end_local = ruleDateUnix(year, d.end, d.end_time) orelse return null;
        // Transition instants: start is given in standard time, end in daylight time.
        return .{ start_local - p.utc_std, end_local - d.utc_dst };
    }
};

fn parsePosix(posix: []const u8) ?PosixRule {
    if (posix.len == 0) return null;
    var i: usize = 0;

    skipAbbrev(posix, &i);
    const std_written = parseOffsetSeconds(posix, &i) orelse return null;
    const utc_std: i32 = -std_written; // POSIX offset is add-to-local-for-UTC

    if (i >= posix.len) return .{ .utc_std = utc_std, .dst = null }; // no DST → constant

    skipAbbrev(posix, &i); // dst abbrev
    // Optional explicit DST offset; default is one hour east of standard.
    var utc_dst: i32 = utc_std + 3600;
    if (i < posix.len and posix[i] != ',') {
        const dst_written = parseOffsetSeconds(posix, &i) orelse return null;
        utc_dst = -dst_written;
    }

    if (i >= posix.len or posix[i] != ',') return null; // no rules → cannot place DST
    i += 1;
    const start = parseRule(posix, &i) orelse return null;
    const start_time = parseRuleTime(posix, &i);
    if (i >= posix.len or posix[i] != ',') return null;
    i += 1;
    const end = parseRule(posix, &i) orelse return null;
    const end_time = parseRuleTime(posix, &i);
    return .{ .utc_std = utc_std, .dst = .{
        .utc_dst = utc_dst,
        .start = start,
        .start_time = start_time,
        .end = end,
        .end_time = end_time,
    } };
}

fn posixOffset(posix: []const u8, unix: i64) ?Offset {
    const p = parsePosix(posix) orelse return null;
    const d = p.dst orelse return .{ .off = p.utc_std, .dst = false };
    const t = p.transitionsIn(datefmt.unixToParts(unix).year) orelse return null;
    const start_utc = t[0];
    const end_utc = t[1];

    const in_dst = if (start_utc <= end_utc)
        (unix >= start_utc and unix < end_utc) // northern hemisphere
    else
        (unix >= start_utc or unix < end_utc); // southern hemisphere (wraps year)

    return if (in_dst) .{ .off = d.utc_dst, .dst = true } else .{ .off = p.utc_std, .dst = false };
}

// ---------------------------------------------------------------------------
// Local wall-clock time → UTC
// ---------------------------------------------------------------------------

/// What a local wall-clock time names in a zone. `local` is the wall clock
/// read as if it were UTC (`datefmt.partsToUnix` of the local date and time).
pub const LocalTime = union(enum) {
    /// Exactly one instant shows this wall-clock time.
    unique: i64,
    /// A fold: the clocks were set back, so the wall clock showed this time
    /// twice. `earlier` is the first pass (the offset before the change),
    /// `later` the second.
    ambiguous: struct { earlier: i64, later: i64 },
    /// A gap: the clocks were set forward over this time, so no instant shows
    /// it. `earlier` reads it with the offset after the gap, `later` with the
    /// offset before it — the two instants the time is conventionally mapped
    /// to (both lie on either side of the jump, `later - earlier` = its size).
    nonexistent: struct { earlier: i64, later: i64 },
};

/// How `localToUtc` settles a local time that is not `unique`. The names are
/// Temporal's (`ZonedDateTime` `disambiguation`), and `compatible` is also
/// what java.time (`ZonedDateTime.ofLocal`) and Python (`fold=0`) do.
pub const Disambiguation = enum {
    /// Fold → earlier; gap → later (moved forward by the gap's size:
    /// 02:30 in a 02:00→03:00 jump becomes 03:30).
    compatible,
    /// Fold → earlier; gap → earlier (moved back: 02:30 becomes 01:30).
    earlier,
    /// Fold → later; gap → later.
    later,
    /// Fold → `error.AmbiguousLocalTime`; gap → `error.NonexistentLocalTime`.
    reject,
};

pub const LocalToUtcError = error{ AmbiguousLocalTime, NonexistentLocalTime };

/// The UTC instant a local wall-clock time names in `zone`, with `policy`
/// deciding folds and gaps. `local` as in `LocalTime`.
pub fn localToUtc(zone: *const tz_data.Zone, local: i64, policy: Disambiguation) LocalToUtcError!i64 {
    return switch (resolveLocal(zone, local)) {
        .unique => |u| u,
        .ambiguous => |a| switch (policy) {
            .compatible, .earlier => a.earlier,
            .later => a.later,
            .reject => error.AmbiguousLocalTime,
        },
        .nonexistent => |g| switch (policy) {
            .compatible, .later => g.later,
            .earlier => g.earlier,
            .reject => error.NonexistentLocalTime,
        },
    };
}

/// Every offset change a zone can have near an instant lies within this
/// distance: UTC offsets stay within ±26 h (POSIX's own bound is ±24:59:59),
/// and a change is found from both of its sides.
const local_window: i64 = 2 * 86400;

/// Classify a local wall-clock time in `zone`: the instants `u` with
/// `u + offsetAt(zone, u).off == local`, or the gap it falls into.
pub fn resolveLocal(zone: *const tz_data.Zone, local: i64) LocalTime {
    // Candidate offsets: the one in force at the window's start and the new
    // one at every change point inside it. A candidate `o` is real when the
    // instant it implies, `local - o`, carries `o` itself.
    var cands: Changes = .{};
    cands.collect(zone, local -| local_window, local +| local_window);

    var found: [max_changes + 1]i64 = undefined;
    var n: usize = 0;
    var offs: [max_changes + 1]i32 = undefined;
    var n_offs: usize = 0;
    offs[n_offs] = offsetAt(zone, local -| local_window).off;
    n_offs += 1;
    for (cands.at[0..cands.len]) |t| {
        const o = offsetAt(zone, t).off;
        if (std.mem.indexOfScalar(i32, offs[0..n_offs], o) == null) {
            offs[n_offs] = o;
            n_offs += 1;
        }
    }
    for (offs[0..n_offs]) |o| {
        const u = local -| @as(i64, o);
        if (offsetAt(zone, u).off != o) continue;
        if (std.mem.indexOfScalar(i64, found[0..n], u) == null) {
            found[n] = u;
            n += 1;
        }
    }
    if (n == 1) return .{ .unique = found[0] };
    if (n >= 2) {
        std.mem.sort(i64, found[0..n], {}, std.sort.asc(i64));
        return .{ .ambiguous = .{ .earlier = found[0], .later = found[n - 1] } };
    }
    // No instant shows `local`: find the forward jump that skipped it.
    for (cands.at[0..cands.len]) |t| {
        const before = offsetAt(zone, t -| 1).off;
        const after = offsetAt(zone, t).off;
        if (after > before and t +| @as(i64, before) <= local and local < t +| @as(i64, after))
            return .{ .nonexistent = .{ .earlier = local -| @as(i64, after), .later = local -| @as(i64, before) } };
    }
    // Unreachable for well-formed zone data (a wall-clock time either is
    // shown or was jumped over); answer with the offset in force, never a
    // panic on generated data.
    const o = offsetAt(zone, local).off;
    return .{ .unique = local -| @as(i64, o) };
}

/// Upper bound on the change points one window can hold: explicit transitions
/// are months apart in every real zone, and the POSIX rule adds two per year
/// over the three years a 4-day window can touch.
const max_changes = 16;

/// The instants in `[lo, hi]` at which `zone`'s offset may change: its
/// explicit transitions, and the POSIX-footer changes of the years around.
/// A superset is fine — `resolveLocal` checks every candidate.
const Changes = struct {
    at: [max_changes]i64 = undefined,
    len: usize = 0,

    fn add(c: *Changes, t: i64) void {
        if (c.len < max_changes) {
            c.at[c.len] = t;
            c.len += 1;
        }
    }

    fn collect(c: *Changes, zone: *const tz_data.Zone, lo: i64, hi: i64) void {
        const tr = zone.trans;
        // First transition with ts >= lo.
        var a: usize = 0;
        var b: usize = tr.len;
        while (a < b) {
            const mid = a + (b - a) / 2;
            if (tr[mid].ts < lo) a = mid + 1 else b = mid;
        }
        while (a < tr.len and tr[a].ts <= hi) : (a += 1) c.add(tr[a].ts);
        const p = parsePosix(zone.posix) orelse return;
        if (p.dst == null) return;
        const y_lo = datefmt.unixToParts(lo).year;
        const y_hi = datefmt.unixToParts(hi).year;
        var y = y_lo - 1;
        while (y <= y_hi + 1) : (y += 1) {
            const t = p.transitionsIn(y) orelse continue;
            for (t) |x| if (x >= lo and x <= hi) c.add(x);
        }
    }
};

const Rule = union(enum) {
    mwd: struct { month: i32, week: i32, day: i32 }, // Mm.w.d
    julian: i32, // Jn — 1..365, Feb 29 never counted (day 60 == March 1 always)
    yday: i32, // n — 0..365, Feb 29 counted in leap years
};

fn skipAbbrev(s: []const u8, i: *usize) void {
    if (i.* < s.len and s[i.*] == '<') {
        while (i.* < s.len and s[i.*] != '>') i.* += 1;
        if (i.* < s.len) i.* += 1; // consume '>'
    } else {
        while (i.* < s.len and std.ascii.isAlphabetic(s[i.*])) i.* += 1;
    }
}

fn readInt(s: []const u8, i: *usize) ?i32 {
    const start = i.*;
    while (i.* < s.len and s[i.*] >= '0' and s[i.*] <= '9') i.* += 1;
    if (i.* == start) return null;
    return std.fmt.parseInt(i32, s[start..i.*], 10) catch null;
}

/// `[+-]hh[:mm[:ss]]` → seconds (as written; POSIX west-positive sign).
fn parseOffsetSeconds(s: []const u8, i: *usize) ?i32 {
    var neg = false;
    if (i.* < s.len and (s[i.*] == '+' or s[i.*] == '-')) {
        neg = s[i.*] == '-';
        i.* += 1;
    }
    const h = readInt(s, i) orelse return null;
    var secs: i32 = h * 3600;
    if (i.* < s.len and s[i.*] == ':') {
        i.* += 1;
        const m = readInt(s, i) orelse return null;
        secs += m * 60;
        if (i.* < s.len and s[i.*] == ':') {
            i.* += 1;
            const sec = readInt(s, i) orelse return null;
            secs += sec;
        }
    }
    return if (neg) -secs else secs;
}

fn parseRule(s: []const u8, i: *usize) ?Rule {
    if (i.* >= s.len) return null;
    if (s[i.*] == 'M') {
        i.* += 1;
        const m = readInt(s, i) orelse return null;
        if (i.* >= s.len or s[i.*] != '.') return null;
        i.* += 1;
        const w = readInt(s, i) orelse return null;
        if (i.* >= s.len or s[i.*] != '.') return null;
        i.* += 1;
        const d = readInt(s, i) orelse return null;
        return .{ .mwd = .{ .month = m, .week = w, .day = d } };
    }
    if (s[i.*] == 'J') {
        i.* += 1;
        const n = readInt(s, i) orelse return null;
        if (n < 1 or n > 365) return null;
        return .{ .julian = n };
    }
    if (s[i.*] >= '0' and s[i.*] <= '9') {
        const n = readInt(s, i) orelse return null;
        if (n < 0 or n > 365) return null;
        return .{ .yday = n };
    }
    return null;
}

/// Optional `/time` after a rule; POSIX default is 02:00:00 local.
fn parseRuleTime(s: []const u8, i: *usize) i32 {
    if (i.* < s.len and s[i.*] == '/') {
        i.* += 1;
        return parseOffsetSeconds(s, i) orelse DEFAULT_DST_TIME;
    }
    return DEFAULT_DST_TIME;
}

/// Local pseudo-Unix (as if the wall-clock were UTC) for a POSIX rule in
/// `year` at `time_secs` past midnight. Null if the date doesn't exist
/// (e.g. an `Mm.w.d` weekday that isn't present that month).
fn ruleDateUnix(year: i32, r: Rule, time_secs: i32) ?i64 {
    switch (r) {
        .mwd => |mwd| {
            const iso_dow: i32 = if (mwd.day == 0) 7 else mwd.day; // POSIX 0=Sun → ISO 7
            const nth: i32 = if (mwd.week >= 5) -1 else mwd.week; // week 5 = last
            const parts = datefmt.nthWeekdayOfMonth(year, mwd.month, iso_dow, nth) orelse return null;
            return datefmt.partsToUnix(parts) + time_secs;
        },
        .julian => |n| {
            // Jn: 1==Jan 1, 60==March 1 in every year (Feb 29 is never
            // counted) — shift the zero-based day index by one once past
            // Feb 28 in a leap year so day 60 still lands on March 1.
            var idx: i64 = n - 1;
            if (datefmt.isLeapYear(year) and n >= 60) idx += 1;
            const epoch_day = datefmt.ymdToEpochDay(year, 1, 1) + idx;
            return epoch_day * 86400 + time_secs;
        },
        .yday => |n| {
            // n: 0==Jan 1 .. 365, zero-based day of year; Feb 29 counts
            // toward the index in leap years (no shift needed).
            const epoch_day = datefmt.ymdToEpochDay(year, 1, 1) + n;
            return epoch_day * 86400 + time_secs;
        },
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

// The zone count is written in this module's `meta.doc` (which renders the
// root README's catalog row), in its README and in its SPEC. `scripts/gen/tz-gen`
// can move it: dropping `localtime` and `posixrules` took it from 600 to 598
// and left three of those four places saying 600. Pin it here, so a
// regeneration that changes the count cannot land without someone walking past
// the number.
const local_kat = @import("local_kat.zig");

test "resolveLocal: every Python-zoneinfo vector (same pinned tzdata)" {
    try testing.expectEqualStrings(local_kat.release, tz_release);
    var seen = [_]usize{0} ** 3;
    for (local_kat.rows, 0..) |row, i| {
        const z = find(local_kat.zones[row.zone]).?;
        const got = resolveLocal(z, row.local);
        const ok = switch (row.kind) {
            .unique => got == .unique and got.unique == row.earlier,
            .ambiguous => got == .ambiguous and got.ambiguous.earlier == row.earlier and got.ambiguous.later == row.later,
            .nonexistent => got == .nonexistent and got.nonexistent.earlier == row.earlier and got.nonexistent.later == row.later,
        };
        if (!ok) {
            std.debug.print("local_kat row {d}: {s} local={d} want {t} {d}/{d}, got {any}\n", .{
                i, local_kat.zones[row.zone], row.local, row.kind, row.earlier, row.later, got,
            });
            return error.TestExpectedEqual;
        }
        seen[@intFromEnum(row.kind)] += 1;
    }
    // Teeth: the vectors cover all three answers in quantity.
    for (seen) |n| try testing.expect(n >= 100);
}

/// The release `tz_data.zig` is generated from, read from its header comment.
const tz_release = "2026a";

test "tz_release matches tz_data.zig's own header" {
    const src = @embedFile("tz_data.zig");
    try testing.expect(std.mem.indexOf(u8, src, "IANA tzdata " ++ tz_release ++ " ") != null);
}

test "localToUtc: Prague spring gap and autumn fold under every policy" {
    const z = find("Europe/Prague").?;
    // 2024-03-31: 02:00 CET -> 03:00 CEST. 02:30 does not exist.
    const gap = datefmt.partsToUnix(.{ .year = 2024, .month = 3, .day = 31, .hour = 2, .minute = 30 });
    const g_cet = gap - 3600; // read with the offset before the gap = 01:30Z = 03:30 CEST
    const g_cest = gap - 7200; // with the offset after = 00:30Z = 01:30 CET
    try testing.expectEqual(LocalTime{ .nonexistent = .{ .earlier = g_cest, .later = g_cet } }, resolveLocal(z, gap));
    try testing.expectEqual(g_cet, try localToUtc(z, gap, .compatible));
    try testing.expectEqual(g_cest, try localToUtc(z, gap, .earlier));
    try testing.expectEqual(g_cet, try localToUtc(z, gap, .later));
    try testing.expectError(error.NonexistentLocalTime, localToUtc(z, gap, .reject));

    // 2024-10-27: 03:00 CEST -> 02:00 CET. 02:30 happens twice.
    const fold = datefmt.partsToUnix(.{ .year = 2024, .month = 10, .day = 27, .hour = 2, .minute = 30 });
    const f1 = fold - 7200; // first pass, CEST
    const f2 = fold - 3600; // second pass, CET
    try testing.expectEqual(LocalTime{ .ambiguous = .{ .earlier = f1, .later = f2 } }, resolveLocal(z, fold));
    try testing.expectEqual(f1, try localToUtc(z, fold, .compatible));
    try testing.expectEqual(f1, try localToUtc(z, fold, .earlier));
    try testing.expectEqual(f2, try localToUtc(z, fold, .later));
    try testing.expectError(error.AmbiguousLocalTime, localToUtc(z, fold, .reject));

    // An ordinary time is the same under every policy.
    const noon = datefmt.partsToUnix(.{ .year = 2024, .month = 7, .day = 1, .hour = 12 });
    for ([_]Disambiguation{ .compatible, .earlier, .later, .reject }) |p|
        try testing.expectEqual(noon - 7200, try localToUtc(z, noon, p));
}

test "resolveLocal: the POSIX-footer era (2040) and a fixed zone" {
    const z = find("America/New_York").?;
    // 2040-03-11 02:30 does not exist (second Sunday of March), 2040-11-04 01:30 twice.
    const gap = datefmt.partsToUnix(.{ .year = 2040, .month = 3, .day = 11, .hour = 2, .minute = 30 });
    try testing.expect(resolveLocal(z, gap) == .nonexistent);
    const fold = datefmt.partsToUnix(.{ .year = 2040, .month = 11, .day = 4, .hour = 1, .minute = 30 });
    try testing.expect(resolveLocal(z, fold) == .ambiguous);
    const utc = find("UTC").?;
    try testing.expectEqual(LocalTime{ .unique = gap }, resolveLocal(utc, gap));
}

/// The defining property, checked by brute force: an answer's instants show
/// `local` (unique/ambiguous), a gap's do not, and nothing else shows it.
fn checkLocal(z: *const Zone, local: i64) !void {
    const shows = struct {
        fn f(zz: *const Zone, u: i64, l: i64) bool {
            return u + offsetAt(zz, u).off == l;
        }
    }.f;
    switch (resolveLocal(z, local)) {
        .unique => |u| try testing.expect(shows(z, u, local)),
        .ambiguous => |a| {
            try testing.expect(a.earlier < a.later);
            try testing.expect(shows(z, a.earlier, local));
            try testing.expect(shows(z, a.later, local));
        },
        .nonexistent => |g| {
            try testing.expect(g.earlier < g.later);
            try testing.expect(!shows(z, g.earlier, local));
            try testing.expect(!shows(z, g.later, local));
            // Nothing in between shows it either: the wall clock jumps from
            // below `local` straight to above it.
            const w0 = g.earlier + offsetAt(z, g.earlier).off;
            const w1 = g.later + offsetAt(z, g.later).off;
            try testing.expect(w0 < local and w1 > local);
        },
    }
}

test "resolveLocal: around EVERY explicit transition of EVERY zone, the defining property holds" {
    var checked: usize = 0;
    for (&tz_data.zones) |*z| {
        for (z.trans, 0..) |t, i| {
            const before: i32 = if (i == 0) z.init_off else z.trans[i - 1].off;
            const lo = t.ts + @min(before, t.off);
            const hi = t.ts + @max(before, t.off);
            for ([_]i64{ lo - 1, lo, lo + @divTrunc(hi - lo, 2), hi - 1, hi }) |l| {
                try checkLocal(z, l);
                checked += 1;
            }
        }
    }
    try testing.expect(checked > 10_000);
}

test "resolveLocal: random zones and local times 1900..2100" {
    var prng = std.Random.DefaultPrng.init(0x7a5eed);
    const r = prng.random();
    var i: usize = 0;
    while (i < 20_000) : (i += 1) {
        const z = &tz_data.zones[r.uintLessThan(usize, tz_data.zones.len)];
        const local = r.intRangeAtMost(i64, -2_208_988_800, 4_102_444_800);
        try checkLocal(z, local);
    }
}

test "zone count matches what the documentation states" {
    try testing.expectEqual(@as(usize, 598), tz_data.zones.len);
}

test "find: known + unknown zones" {
    try testing.expect(find("Europe/Prague") != null);
    try testing.expect(find("America/New_York") != null);
    try testing.expect(find("UTC") != null);
    try testing.expect(find("Not/AZone") == null);
}

test "offsetAt: Prague CET/CEST across a known transition" {
    const z = find("Europe/Prague").?;
    // 2024-01-15 12:00 UTC → CET (+3600, no DST)
    try testing.expectEqual(@as(i32, 3600), offsetAt(z, 1705320000).off);
    try testing.expect(!offsetAt(z, 1705320000).dst);
    // 2024-07-15 12:00 UTC → CEST (+7200, DST)
    try testing.expectEqual(@as(i32, 7200), offsetAt(z, 1721044800).off);
    try testing.expect(offsetAt(z, 1721044800).dst);
}

test "offsetAt: New York EST/EDT" {
    const z = find("America/New_York").?;
    // 2024-01-15 12:00 UTC → EST (-18000)
    try testing.expectEqual(@as(i32, -18000), offsetAt(z, 1705320000).off);
    // 2024-07-15 12:00 UTC → EDT (-14400)
    try testing.expectEqual(@as(i32, -14400), offsetAt(z, 1721044800).off);
}

test "offsetAt: half-hour zone (Kolkata, no DST)" {
    const z = find("Asia/Kolkata").?;
    try testing.expectEqual(@as(i32, 5 * 3600 + 1800), offsetAt(z, 1721044800).off);
}

test "offsetAt: POSIX footer applies far in the future (Prague 2040 summer)" {
    const z = find("Europe/Prague").?;
    // 2040-07-01 12:00 UTC — well past the last explicit transition → POSIX rule.
    const summer = datefmt.partsToUnix(.{ .year = 2040, .month = 7, .day = 1, .hour = 12 });
    try testing.expectEqual(@as(i32, 7200), offsetAt(z, summer).off);
    try testing.expect(offsetAt(z, summer).dst);
    // 2040-01-01 → standard CET.
    const winter = datefmt.partsToUnix(.{ .year = 2040, .month = 1, .day = 1, .hour = 12 });
    try testing.expectEqual(@as(i32, 3600), offsetAt(z, winter).off);
}

test "offsetAt: the exact transition instant already carries the NEW offset" {
    // Every other transition test in this file uses an arbitrary instant
    // well inside a transition period ("12:00 UTC"); none lands exactly ON
    // a transition's own timestamp, which is the one input that actually
    // exercises the binary search's `<=` boundary (an off-by-one there —
    // `<` instead of `<=` — would apply the OLD offset one second too
    // long and go undetected by every other test here). A transition's own
    // `ts` is defined as "the offset becomes X starting at this instant"
    // (tzfile semantics), so `ts` itself must read as the new offset and
    // `ts - 1` must still read as the old one.
    const z = find("Europe/Prague").?;
    const tr = z.trans;
    // Prague's first transition: 1970-05-31 22:00:00Z, CEST begins (+7200,
    // DST). Picking the very first entry keeps "old offset" unambiguous:
    // it is `z.init_off`/`z.init_dst`, not some earlier transition.
    const ts = tr[0].ts;
    try testing.expectEqual(z.init_off, offsetAt(z, ts - 1).off);
    try testing.expectEqual(z.init_dst, offsetAt(z, ts - 1).dst);
    try testing.expectEqual(tr[0].off, offsetAt(z, ts).off);
    try testing.expectEqual(tr[0].dst, offsetAt(z, ts).dst);
}

test "offsetAt: fixed UTC" {
    const z = find("UTC").?;
    try testing.expectEqual(@as(i32, 0), offsetAt(z, 1721044800).off);
}

// ---------------------------------------------------------------------------
// POSIX footer: Jn / n Julian-day rule forms
// ---------------------------------------------------------------------------
//
// These use synthetic zones (empty `trans`, so offsetAt always falls through
// to posixOffset) with a footer of the form `XST0XDT,<rule>/0,<rule2>/0` —
// standard offset UTC+0, DST +1h, transitions at 00:00:00 local so the rule's
// calendar date maps 1:1 onto a UTC instant.

test "posix footer: Jn Julian-day rule — day 59 is Feb 28 regardless of leap year" {
    // Jn (1<=n<=365) never counts Feb 29: day 59 is Feb 28 in every year,
    // leap or not.
    const z = Zone{
        .name = "Test/Jn",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = "XST0XDT,J59/0,J300/0",
    };
    // 2023 (non-leap): Feb 28 2023 00:00:00Z == 1677542400.
    try testing.expectEqual(@as(i32, 0), offsetAt(&z, 1677542400 - 1).off);
    try testing.expect(!offsetAt(&z, 1677542400 - 1).dst);
    try testing.expectEqual(@as(i32, 3600), offsetAt(&z, 1677542400).off);
    try testing.expect(offsetAt(&z, 1677542400).dst);
    // 2024 (leap): day 59 is *still* Feb 28 2024 00:00:00Z == 1709078400 —
    // same calendar date as the non-leap year above.
    try testing.expectEqual(@as(i32, 0), offsetAt(&z, 1709078400 - 1).off);
    try testing.expectEqual(@as(i32, 3600), offsetAt(&z, 1709078400).off);
    try testing.expect(offsetAt(&z, 1709078400).dst);
}

test "posix footer: n zero-based day-of-year rule — counts Feb 29 in leap years" {
    // Plain n (0<=n<=365) counts Feb 29: index 59 is March 1 in a non-leap
    // year but Feb 29 in a leap year (the index shifts once Feb 29 exists).
    const z = Zone{
        .name = "Test/n",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = "YST0YDT,59/0,300/0",
    };
    // 2023 (non-leap): index 59 == March 1 2023 00:00:00Z == 1677628800.
    try testing.expectEqual(@as(i32, 0), offsetAt(&z, 1677628800 - 1).off);
    try testing.expectEqual(@as(i32, 3600), offsetAt(&z, 1677628800).off);
    // 2024 (leap): index 59 == Feb 29 2024 00:00:00Z == 1709164800.
    try testing.expectEqual(@as(i32, 0), offsetAt(&z, 1709164800 - 1).off);
    try testing.expectEqual(@as(i32, 3600), offsetAt(&z, 1709164800).off);
}

test "posix footer: leap-year positive control — Jn and n resolve to different calendar days" {
    // Same nominal day-number (59) parsed via the two rule forms must NOT
    // land on the same instant in a leap year: J59 is Feb 29-blind (always
    // Feb 28), plain 59 is Feb 29-aware (lands on Feb 29 itself in 2024).
    // This is the whole point of having two separate rule forms rather than
    // aliasing one onto the other.
    const jn = Zone{
        .name = "Test/Jn2",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = "XST0XDT,J59/0,J300/0",
    };
    const yd = Zone{
        .name = "Test/n2",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = "YST0YDT,59/0,300/0",
    };
    const feb28_2024 = 1709078400; // 2024-02-28T00:00:00Z
    const feb29_2024 = 1709164800; // 2024-02-29T00:00:00Z
    try testing.expect(feb28_2024 != feb29_2024);
    // Jn already flipped to DST a full day before Feb 29 (it transitioned on
    // Feb 28, the last day it recognizes before March).
    try testing.expect(offsetAt(&jn, feb28_2024).dst);
    try testing.expect(offsetAt(&jn, feb29_2024).dst);
    // The zero-based form is still in STD at the start of Feb 28 and only
    // flips to DST exactly at Feb 29 00:00Z — a different UTC instant than Jn.
    try testing.expect(!offsetAt(&yd, feb28_2024).dst);
    try testing.expect(offsetAt(&yd, feb29_2024).dst);
}

// ---------------------------------------------------------------------------
// fuzz: find (zone-name lookup) and the POSIX-TZ footer grammar
// ---------------------------------------------------------------------------
//
// Two decode entry points take caller-supplied bytes: `find`'s zone-name
// binary search (what `check-fuzz`'s static scan actually flagged), and the
// module's real parsing logic — the POSIX-TZ footer grammar
// (`posixOffset`/`parseRule`/`ruleDateUnix`) reachable through the fully
// public `Zone.posix` field feeding the public `offsetAt`. A caller that
// reads a `TZ` environment variable or an untrusted footer string and builds
// its own `Zone` literal (exactly the pattern the synthetic-zone tests above
// use) hands this parser bytes it did not author.

/// `testkit.fuzz` — see that module for why a corpus entry is not the frame.
const tkfuzz = @import("testkit").fuzz;
const seed = tkfuzz.seed;

/// Zone names in the format `Smith.slice` reads (see `testkit.fuzz`). The
/// binary search's interesting inputs are the ends of the table, an exact hit
/// in the middle, and the near-misses on either side of one — none of which
/// arbitrary bytes ever produce.
const zone_name_seeds = [_][]const u8{
    seed("Africa/Abidjan"), // the first entry in the table
    seed("Zulu"), // the last entry
    seed("Europe/Prague"), // an exact hit in the middle
    seed("Europe/Pragu"), // one octet short of a hit
    seed("Europe/Praguf"), // the neighbour just above a hit
    seed("Europe/Pragud"), // the neighbour just below
    seed("UTC"),
    seed("Etc/UTC"),
    seed("Pacific/Kiritimati"), // the widest offset in the table
    seed("AAAAAAAA"), // sorts before every entry
    seed("zzzzzzzz"), // sorts after every entry
    seed(""), // the ONE input the collapsed harness ever ran
};

test "fuzz: find never panics, arbitrary or real zone-name bytes" {
    try std.testing.fuzz({}, fuzzFindNeverPanics, .{ .corpus = &zone_name_seeds });
}

fn fuzzFindNeverPanics(_: void, smith: *std.testing.Smith) !void {
    var buf: [64]u8 = undefined;
    // ⚠ One `smith.slice` call, and it is the FIRST draw. It used to go
    // through `buildZoneName`, which opened with
    // `smith.valueRangeAtMost(u8, 0, 2)` — a ranged draw, which reads eight
    // octets as a little-endian u64 and returns the range MINIMUM unless that
    // whole word lands inside the range. Outside `--fuzz` it was therefore
    // always 0, i.e. the "copy a real zone name" branch, and `smith.index`
    // right after it was 0 too, so `find` was called with
    // `"Africa/Abidjan"` — the FIRST table entry — and nothing else, ever.
    // The comment promising "one draw in three copies a real zone name"
    // described a distribution that never existed. Measured 2026-09-07 over
    // the corpus above: **1 distinct name and 1 table hit before; 11 of 12
    // seeds non-empty, 12 distinct names and 6 hits after.**
    const len: usize = smith.slice(&buf);
    _ = find(buf[0..len]);
}

test "corpus: every zone name reaches find, and the hit count is pinned" {
    // ⭐ The measurement, executable rather than written in a comment.
    //
    // ⚠ `find` returning null is not an error, so a "no crash" count would
    // read 100% on a corpus of one name. `hits` is the number the collapsed
    // harness could not move past 1, and `distinct` is the number it pinned
    // at 1 outright.
    var nonempty: usize = 0;
    var hits: usize = 0;
    var distinct: usize = 0;
    var seen: [zone_name_seeds.len][]const u8 = undefined;
    var store: [zone_name_seeds.len][64]u8 = undefined;
    for (zone_name_seeds, 0..) |sd, i| {
        var smith: std.testing.Smith = .{ .in = sd };
        const len: usize = smith.slice(&store[i]);
        if (len != 0) nonempty += 1;
        const name = store[i][0..len];
        if (find(name) != null) hits += 1;
        var already = false;
        for (seen[0..distinct]) |s| {
            if (std.mem.eql(u8, s, name)) already = true;
        }
        if (!already) {
            seen[distinct] = name;
            distinct += 1;
        }
    }
    // One seed IS the empty name, a legal member of a refusal corpus.
    try testing.expectEqual(zone_name_seeds.len - 1, nonempty);
    // Measured 2026-09-07: with the collapsing draws, exactly 1 distinct name
    // ("Africa/Abidjan", the first table entry) and 1 hit, twelve times over.
    try testing.expectEqual(@as(usize, 6), hits);
    try testing.expectEqual(zone_name_seeds.len, distinct);
}

/// POSIX-TZ footers in the format `Smith.slice` reads.
///
/// ⛔ These six strings were ALREADY here as a corpus — and none of them ever
/// reached the parser. The harness's first draw was
/// `smith.valueRangeAtMost(u8, 0, 5)` inside `buildPosixFooter`, which reads
/// eight octets as a little-endian u64: `"CET-1CES"` is not in `0..5`, so the
/// draw returned its minimum, took the arbitrary-bytes branch, and the ranged
/// length that followed it returned 0. Every one of these six real footers was
/// replayed as the empty string. A corpus is only as good as the draw that
/// reads it.
const posix_footer_corpus = [_][]const u8{
    seed("CET-1CEST,M3.5.0,M10.5.0/3"), // Europe/Prague's own footer: two M rules
    seed("EST5EDT,M3.2.0,M11.1.0"), // the US rules, no explicit times
    seed("UTC0"), // no DST at all: the short-circuit
    seed("<+05>-5"), // the bracketed-abbreviation form
    seed("XST0XDT,J59/0,J300/0"), // the Julian (J) rule form
    seed("YST0YDT,59/0,300/0"), // the zero-based day-of-year form
    seed("CET-1CEST,M3.5.0/2:30:15,M10.5.0/3:00"), // rule times with minutes and seconds
    seed("AAA+1BBB-2,M13.9.9,M0.0.0"), // out-of-range month/week/day fields
    seed("AAA"), // an abbreviation with no offset
    seed(",,,,"), // separators only
    seed("A" ** 128), // the full harness buffer
    seed(""), // the empty footer
};

test "fuzz: offsetAt's POSIX-TZ footer parser never panics, arbitrary or footer-shaped bytes" {
    try std.testing.fuzz({}, fuzzPosixFooterNeverPanics, .{ .corpus = &posix_footer_corpus });
}

fn zoneWithFooter(posix: []const u8) Zone {
    return .{
        .name = "Fuzz/Zone",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = posix,
    };
}

/// A wide but bounded instant, in whole years, derived from the drawn bytes.
/// Far enough past/before epoch to reach every rule form's year math without
/// courting unrelated `i64*86400` overflow in datefmt, which is not this
/// module's decode surface.
fn footerInstant(cur: *tkfuzz.Cursor) i64 {
    // ⚠ Two components, not one. A whole-year step alone lands every instant
    // within a few days of January, which is never DST in the northern
    // hemisphere — the day-of-year term is what makes the summer branch of a
    // `M3.5.0,M10.5.0` rule reachable at all.
    const years = @as(i64, cur.ranged(0, 200)) - 100;
    const days = @as(i64, cur.ranged(0, 364));
    return years * (365 * 86400) + days * 86400;
}

fn fuzzPosixFooterNeverPanics(_: void, smith: *std.testing.Smith) !void {
    var buf: [128]u8 = undefined;
    // ⚠ One `smith.slice` call, and it is the FIRST draw — see the corpus
    // comment above for what the old first draw did to the six real footers
    // that were already sitting there.
    const len: usize = smith.slice(&buf);
    const drawn = buf[0..len];
    var cur: tkfuzz.Cursor = .{ .bytes = drawn };

    // (a) The drawn bytes AS a footer, verbatim. This is what the corpus of
    // real POSIX-TZ strings is for, and it is the pass that never ran.
    const z = zoneWithFooter(drawn);
    _ = offsetAt(&z, footerInstant(&cur));

    // (b) The same bytes as a SCRIPT for the grammar generator, so the
    // structured shapes arbitrary bytes never spell still get built. ⚠ The
    // generator's choices come from the `Cursor`, not from draws after the
    // byte draw — every one of those was its range minimum on a replay, so
    // the generator emitted one fixed string when it ran at all.
    var gen_buf: [128]u8 = undefined;
    const gen = buildPosixFooter(&cur, &gen_buf);
    const gz = zoneWithFooter(gen);
    _ = offsetAt(&gz, footerInstant(&cur));
}

/// Assembles `stdoffset[dst[offset][,start[/time],end[/time]]]` — the grammar
/// `posixOffset` walks — with each optional piece independently present or
/// absent, so both the "no DST" short-circuit and the full two-rule path get
/// exercised, not just whichever one arbitrary bytes happen to stumble into.
fn buildPosixFooter(cur: *tkfuzz.Cursor, buf: []u8) []const u8 {
    var w: std.Io.Writer = .fixed(buf);
    writeAbbrev(cur, &w);
    writeFooterOffset(cur, &w);
    if (cur.byte() & 1 == 0) return w.buffered();
    writeAbbrev(cur, &w);
    if (cur.byte() & 1 == 1) writeFooterOffset(cur, &w);
    if (cur.byte() & 1 == 0) return w.buffered();
    w.writeByte(',') catch return w.buffered();
    writeRuleText(cur, &w);
    writeRuleTimeText(cur, &w);
    w.writeByte(',') catch return w.buffered();
    writeRuleText(cur, &w);
    writeRuleTimeText(cur, &w);
    return w.buffered();
}

fn writeAbbrev(cur: *tkfuzz.Cursor, w: *std.Io.Writer) void {
    const letters = "ABCXYZ";
    const len = cur.ranged(1, 4);
    var i: u32 = 0;
    while (i < len) : (i += 1) {
        w.writeByte(letters[cur.ranged(0, letters.len - 1)]) catch return;
    }
}

fn writeFooterOffset(cur: *tkfuzz.Cursor, w: *std.Io.Writer) void {
    if (cur.byte() & 1 == 1) w.writeByte(if (cur.byte() & 1 == 1) '+' else '-') catch return;
    w.print("{d}", .{cur.ranged(0, 23)}) catch return;
    if (cur.byte() & 1 == 0) return;
    w.print(":{d:0>2}", .{cur.ranged(0, 59)}) catch return;
    if (cur.byte() & 1 == 1) w.print(":{d:0>2}", .{cur.ranged(0, 59)}) catch return;
}

fn writeRuleText(cur: *tkfuzz.Cursor, w: *std.Io.Writer) void {
    switch (cur.ranged(0, 2)) {
        0 => w.print("M{d}.{d}.{d}", .{
            cur.ranged(1, 12),
            cur.ranged(1, 5),
            cur.ranged(0, 6),
        }) catch {},
        1 => w.print("J{d}", .{cur.ranged(1, 365)}) catch {},
        else => w.print("{d}", .{cur.ranged(0, 365)}) catch {},
    }
}

fn writeRuleTimeText(cur: *tkfuzz.Cursor, w: *std.Io.Writer) void {
    if (cur.byte() & 1 == 0) return;
    w.writeByte('/') catch return;
    writeFooterOffset(cur, w);
}

test "corpus: every footer reaches offsetAt, and the generator actually varies" {
    // ⭐ The measurement, executable rather than written in a comment.
    //
    // ⚠ `offsetAt` returns a value for ANY footer — a malformed one just
    // falls back to the zone's initial offset — so "no crash" and even "an
    // offset came back" are 100% on an empty corpus. The numbers that carry
    // information are how many footers produce a NON-DEFAULT result, and how
    // many distinct strings the grammar generator emits. Both were pinned at
    // their minimum by the collapsed draws.
    var nonempty: usize = 0;
    var dst_seen: usize = 0;
    var nonzero_offset: usize = 0;
    var distinct_generated: usize = 0;
    var seen: [posix_footer_corpus.len][128]u8 = undefined;
    var seen_len: [posix_footer_corpus.len]usize = undefined;
    for (posix_footer_corpus) |sd| {
        var smith: std.testing.Smith = .{ .in = sd };
        var buf: [128]u8 = undefined;
        const len: usize = smith.slice(&buf);
        if (len != 0) nonempty += 1;
        const drawn = buf[0..len];
        var cur: tkfuzz.Cursor = .{ .bytes = drawn };

        const z = zoneWithFooter(drawn);
        const off = offsetAt(&z, footerInstant(&cur));
        if (off.dst) dst_seen += 1;
        if (off.off != 0) nonzero_offset += 1;

        var gen_buf: [128]u8 = undefined;
        const gen = buildPosixFooter(&cur, &gen_buf);
        var already = false;
        for (seen[0..distinct_generated], seen_len[0..distinct_generated]) |s, l| {
            if (l == gen.len and std.mem.eql(u8, s[0..l], gen)) already = true;
        }
        if (!already) {
            @memcpy(seen[distinct_generated][0..gen.len], gen);
            seen_len[distinct_generated] = gen.len;
            distinct_generated += 1;
        }
        const gz = zoneWithFooter(gen);
        _ = offsetAt(&gz, footerInstant(&cur));
    }
    // One seed IS the empty footer, a legal member of the corpus.
    try testing.expectEqual(posix_footer_corpus.len - 1, nonempty);
    // Measured 2026-09-07: with the collapsing draws, all twelve footers
    // arrived as "" — 0 DST, 0 non-zero offsets — and the generator emitted
    // exactly 1 distinct string. After:
    try testing.expectEqual(@as(usize, 3), dst_seen);
    try testing.expectEqual(@as(usize, 6), nonzero_offset);
    try testing.expectEqual(@as(usize, 11), distinct_generated);
}

test {
    _ = @import("posix_test.zig");
}
