// SPDX-License-Identifier: MIT
//! tz — IANA time-zone offset lookup: zone name → UTC offset/DST at an instant
//! via committed transition table + POSIX-TZ footer rule. Composes datefmt.
//!
//! `tz_data.zig` (generated by the authors' `tz-gen` tool from a pinned IANA
//! tzdata release) holds each zone's UTC-offset transitions from 1970 onward plus
//! its POSIX-TZ footer rule. This module resolves a zone by name and reports
//! the UTC offset (and DST flag) at a given instant: a binary search over the
//! explicit transitions, then the POSIX rule for instants past the last one
//! (~2038+).

const std = @import("std");
const datefmt = @import("datefmt");
const tz_data = @import("tz_data.zig");

pub const meta = .{
    .targets = .{ .linux64, .windows },
    .platform = .any,
    .role = .util,
    .concurrency = .reentrant,
    .model_after = "IANA tzdata (zic) + POSIX TZ footer rule",
    .deps = .{"datefmt"},
};

pub const Zone = tz_data.Zone;
pub const Transition = tz_data.Transition;
pub const zones = tz_data.zones;

pub const Offset = struct {
    /// UTC offset in seconds (east of UTC positive: CEST = +7200).
    off: i32,
    dst: bool,
};

/// Resolve an IANA zone id (`"Europe/Prague"`, `"America/New_York"`, `"UTC"`).
/// Case-sensitive, matching the IANA database. Returns null for unknown names.
pub fn find(name: []const u8) ?*const tz_data.Zone {
    // zones are emitted sorted by name → binary search.
    var lo: usize = 0;
    var hi: usize = tz_data.zones.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        switch (std.mem.order(u8, tz_data.zones[mid].name, name)) {
            .lt => lo = mid + 1,
            .gt => hi = mid,
            .eq => return &tz_data.zones[mid],
        }
    }
    return null;
}

/// UTC offset (+ DST flag) in `zone` at the given Unix instant.
pub fn offsetAt(zone: *const tz_data.Zone, unix: i64) Offset {
    const tr = zone.trans;
    if (tr.len == 0) {
        if (posixOffset(zone.posix, unix)) |o| return o;
        return .{ .off = zone.init_off, .dst = zone.init_dst };
    }
    if (unix < tr[0].ts) return .{ .off = zone.init_off, .dst = zone.init_dst };
    if (unix >= tr[tr.len - 1].ts) {
        // Past the last explicit transition — apply the POSIX-TZ footer rule.
        if (posixOffset(zone.posix, unix)) |o| return o;
        const last = tr[tr.len - 1];
        return .{ .off = last.off, .dst = last.dst };
    }
    // Rightmost transition with ts <= unix (unix is within [tr[0], tr[last])).
    var lo: usize = 0;
    var hi: usize = tr.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        if (tr[mid].ts <= unix) lo = mid + 1 else hi = mid;
    }
    const t = tr[lo - 1];
    return .{ .off = t.off, .dst = t.dst };
}

// ---------------------------------------------------------------------------
// POSIX-TZ footer evaluation (RFC 9636 §3.3 / the tzfile(5) footer)
//   stdoffset[dst[offset][,start[/time],end[/time]]]
// All three rule forms are evaluated: `Mm.w.d` (nth/last weekday of a month),
// `Jn` (1<=n<=365, Julian day not counting Feb 29 — day 60 is always March 1),
// and plain `n` (0<=n<=365, day of year counting Feb 29).
// ---------------------------------------------------------------------------

const DEFAULT_DST_TIME: i32 = 2 * 3600; // 02:00 local, POSIX default

fn posixOffset(posix: []const u8, unix: i64) ?Offset {
    if (posix.len == 0) return null;
    var i: usize = 0;

    skipAbbrev(posix, &i);
    const std_written = parseOffsetSeconds(posix, &i) orelse return null;
    const utc_std: i32 = -std_written; // POSIX offset is add-to-local-for-UTC

    if (i >= posix.len) return .{ .off = utc_std, .dst = false }; // no DST → constant

    skipAbbrev(posix, &i); // dst abbrev
    // Optional explicit DST offset; default is one hour east of standard.
    var utc_dst: i32 = utc_std + 3600;
    if (i < posix.len and posix[i] != ',') {
        const dst_written = parseOffsetSeconds(posix, &i) orelse return null;
        utc_dst = -dst_written;
    }

    if (i >= posix.len or posix[i] != ',') return null; // no rules → cannot place DST
    i += 1;
    const start = parseRule(posix, &i) orelse return null;
    const start_time = parseRuleTime(posix, &i);
    if (i >= posix.len or posix[i] != ',') return null;
    i += 1;
    const end = parseRule(posix, &i) orelse return null;
    const end_time = parseRuleTime(posix, &i);

    const year = datefmt.unixToParts(unix).year;
    const start_local = ruleDateUnix(year, start, start_time) orelse return null;
    const end_local = ruleDateUnix(year, end, end_time) orelse return null;
    // Transition instants: start is given in standard time, end in daylight time.
    const start_utc = start_local - utc_std;
    const end_utc = end_local - utc_dst;

    const in_dst = if (start_utc <= end_utc)
        (unix >= start_utc and unix < end_utc) // northern hemisphere
    else
        (unix >= start_utc or unix < end_utc); // southern hemisphere (wraps year)

    return if (in_dst) .{ .off = utc_dst, .dst = true } else .{ .off = utc_std, .dst = false };
}

const Rule = union(enum) {
    mwd: struct { month: i32, week: i32, day: i32 }, // Mm.w.d
    julian: i32, // Jn — 1..365, Feb 29 never counted (day 60 == March 1 always)
    yday: i32, // n — 0..365, Feb 29 counted in leap years
};

fn skipAbbrev(s: []const u8, i: *usize) void {
    if (i.* < s.len and s[i.*] == '<') {
        while (i.* < s.len and s[i.*] != '>') i.* += 1;
        if (i.* < s.len) i.* += 1; // consume '>'
    } else {
        while (i.* < s.len and std.ascii.isAlphabetic(s[i.*])) i.* += 1;
    }
}

fn readInt(s: []const u8, i: *usize) ?i32 {
    const start = i.*;
    while (i.* < s.len and s[i.*] >= '0' and s[i.*] <= '9') i.* += 1;
    if (i.* == start) return null;
    return std.fmt.parseInt(i32, s[start..i.*], 10) catch null;
}

/// `[+-]hh[:mm[:ss]]` → seconds (as written; POSIX west-positive sign).
fn parseOffsetSeconds(s: []const u8, i: *usize) ?i32 {
    var neg = false;
    if (i.* < s.len and (s[i.*] == '+' or s[i.*] == '-')) {
        neg = s[i.*] == '-';
        i.* += 1;
    }
    const h = readInt(s, i) orelse return null;
    var secs: i32 = h * 3600;
    if (i.* < s.len and s[i.*] == ':') {
        i.* += 1;
        const m = readInt(s, i) orelse return null;
        secs += m * 60;
        if (i.* < s.len and s[i.*] == ':') {
            i.* += 1;
            const sec = readInt(s, i) orelse return null;
            secs += sec;
        }
    }
    return if (neg) -secs else secs;
}

fn parseRule(s: []const u8, i: *usize) ?Rule {
    if (i.* >= s.len) return null;
    if (s[i.*] == 'M') {
        i.* += 1;
        const m = readInt(s, i) orelse return null;
        if (i.* >= s.len or s[i.*] != '.') return null;
        i.* += 1;
        const w = readInt(s, i) orelse return null;
        if (i.* >= s.len or s[i.*] != '.') return null;
        i.* += 1;
        const d = readInt(s, i) orelse return null;
        return .{ .mwd = .{ .month = m, .week = w, .day = d } };
    }
    if (s[i.*] == 'J') {
        i.* += 1;
        const n = readInt(s, i) orelse return null;
        if (n < 1 or n > 365) return null;
        return .{ .julian = n };
    }
    if (s[i.*] >= '0' and s[i.*] <= '9') {
        const n = readInt(s, i) orelse return null;
        if (n < 0 or n > 365) return null;
        return .{ .yday = n };
    }
    return null;
}

/// Optional `/time` after a rule; POSIX default is 02:00:00 local.
fn parseRuleTime(s: []const u8, i: *usize) i32 {
    if (i.* < s.len and s[i.*] == '/') {
        i.* += 1;
        return parseOffsetSeconds(s, i) orelse DEFAULT_DST_TIME;
    }
    return DEFAULT_DST_TIME;
}

/// Local pseudo-Unix (as if the wall-clock were UTC) for a POSIX rule in
/// `year` at `time_secs` past midnight. Null if the date doesn't exist
/// (e.g. an `Mm.w.d` weekday that isn't present that month).
fn ruleDateUnix(year: i32, r: Rule, time_secs: i32) ?i64 {
    switch (r) {
        .mwd => |mwd| {
            const iso_dow: i32 = if (mwd.day == 0) 7 else mwd.day; // POSIX 0=Sun → ISO 7
            const nth: i32 = if (mwd.week >= 5) -1 else mwd.week; // week 5 = last
            const parts = datefmt.nthWeekdayOfMonth(year, mwd.month, iso_dow, nth) orelse return null;
            return datefmt.partsToUnix(parts) + time_secs;
        },
        .julian => |n| {
            // Jn: 1==Jan 1, 60==March 1 in every year (Feb 29 is never
            // counted) — shift the zero-based day index by one once past
            // Feb 28 in a leap year so day 60 still lands on March 1.
            var idx: i64 = n - 1;
            if (datefmt.isLeapYear(year) and n >= 60) idx += 1;
            const epoch_day = datefmt.ymdToEpochDay(year, 1, 1) + idx;
            return epoch_day * 86400 + time_secs;
        },
        .yday => |n| {
            // n: 0==Jan 1 .. 365, zero-based day of year; Feb 29 counts
            // toward the index in leap years (no shift needed).
            const epoch_day = datefmt.ymdToEpochDay(year, 1, 1) + n;
            return epoch_day * 86400 + time_secs;
        },
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

test "find: known + unknown zones" {
    try testing.expect(find("Europe/Prague") != null);
    try testing.expect(find("America/New_York") != null);
    try testing.expect(find("UTC") != null);
    try testing.expect(find("Not/AZone") == null);
}

test "offsetAt: Prague CET/CEST across a known transition" {
    const z = find("Europe/Prague").?;
    // 2024-01-15 12:00 UTC → CET (+3600, no DST)
    try testing.expectEqual(@as(i32, 3600), offsetAt(z, 1705320000).off);
    try testing.expect(!offsetAt(z, 1705320000).dst);
    // 2024-07-15 12:00 UTC → CEST (+7200, DST)
    try testing.expectEqual(@as(i32, 7200), offsetAt(z, 1721044800).off);
    try testing.expect(offsetAt(z, 1721044800).dst);
}

test "offsetAt: New York EST/EDT" {
    const z = find("America/New_York").?;
    // 2024-01-15 12:00 UTC → EST (-18000)
    try testing.expectEqual(@as(i32, -18000), offsetAt(z, 1705320000).off);
    // 2024-07-15 12:00 UTC → EDT (-14400)
    try testing.expectEqual(@as(i32, -14400), offsetAt(z, 1721044800).off);
}

test "offsetAt: half-hour zone (Kolkata, no DST)" {
    const z = find("Asia/Kolkata").?;
    try testing.expectEqual(@as(i32, 5 * 3600 + 1800), offsetAt(z, 1721044800).off);
}

test "offsetAt: POSIX footer applies far in the future (Prague 2040 summer)" {
    const z = find("Europe/Prague").?;
    // 2040-07-01 12:00 UTC — well past the last explicit transition → POSIX rule.
    const summer = datefmt.partsToUnix(.{ .year = 2040, .month = 7, .day = 1, .hour = 12 });
    try testing.expectEqual(@as(i32, 7200), offsetAt(z, summer).off);
    try testing.expect(offsetAt(z, summer).dst);
    // 2040-01-01 → standard CET.
    const winter = datefmt.partsToUnix(.{ .year = 2040, .month = 1, .day = 1, .hour = 12 });
    try testing.expectEqual(@as(i32, 3600), offsetAt(z, winter).off);
}

test "offsetAt: the exact transition instant already carries the NEW offset" {
    // Every other transition test in this file uses an arbitrary instant
    // well inside a transition period ("12:00 UTC"); none lands exactly ON
    // a transition's own timestamp, which is the one input that actually
    // exercises the binary search's `<=` boundary (an off-by-one there —
    // `<` instead of `<=` — would apply the OLD offset one second too
    // long and go undetected by every other test here). A transition's own
    // `ts` is defined as "the offset becomes X starting at this instant"
    // (tzfile semantics), so `ts` itself must read as the new offset and
    // `ts - 1` must still read as the old one.
    const z = find("Europe/Prague").?;
    const tr = z.trans;
    // Prague's first transition: 1970-05-31 22:00:00Z, CEST begins (+7200,
    // DST). Picking the very first entry keeps "old offset" unambiguous:
    // it is `z.init_off`/`z.init_dst`, not some earlier transition.
    const ts = tr[0].ts;
    try testing.expectEqual(z.init_off, offsetAt(z, ts - 1).off);
    try testing.expectEqual(z.init_dst, offsetAt(z, ts - 1).dst);
    try testing.expectEqual(tr[0].off, offsetAt(z, ts).off);
    try testing.expectEqual(tr[0].dst, offsetAt(z, ts).dst);
}

test "offsetAt: fixed UTC" {
    const z = find("UTC").?;
    try testing.expectEqual(@as(i32, 0), offsetAt(z, 1721044800).off);
}

// ---------------------------------------------------------------------------
// POSIX footer: Jn / n Julian-day rule forms
// ---------------------------------------------------------------------------
//
// These use synthetic zones (empty `trans`, so offsetAt always falls through
// to posixOffset) with a footer of the form `XST0XDT,<rule>/0,<rule2>/0` —
// standard offset UTC+0, DST +1h, transitions at 00:00:00 local so the rule's
// calendar date maps 1:1 onto a UTC instant.

test "posix footer: Jn Julian-day rule — day 59 is Feb 28 regardless of leap year" {
    // Jn (1<=n<=365) never counts Feb 29: day 59 is Feb 28 in every year,
    // leap or not.
    const z = Zone{
        .name = "Test/Jn",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = "XST0XDT,J59/0,J300/0",
    };
    // 2023 (non-leap): Feb 28 2023 00:00:00Z == 1677542400.
    try testing.expectEqual(@as(i32, 0), offsetAt(&z, 1677542400 - 1).off);
    try testing.expect(!offsetAt(&z, 1677542400 - 1).dst);
    try testing.expectEqual(@as(i32, 3600), offsetAt(&z, 1677542400).off);
    try testing.expect(offsetAt(&z, 1677542400).dst);
    // 2024 (leap): day 59 is *still* Feb 28 2024 00:00:00Z == 1709078400 —
    // same calendar date as the non-leap year above.
    try testing.expectEqual(@as(i32, 0), offsetAt(&z, 1709078400 - 1).off);
    try testing.expectEqual(@as(i32, 3600), offsetAt(&z, 1709078400).off);
    try testing.expect(offsetAt(&z, 1709078400).dst);
}

test "posix footer: n zero-based day-of-year rule — counts Feb 29 in leap years" {
    // Plain n (0<=n<=365) counts Feb 29: index 59 is March 1 in a non-leap
    // year but Feb 29 in a leap year (the index shifts once Feb 29 exists).
    const z = Zone{
        .name = "Test/n",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = "YST0YDT,59/0,300/0",
    };
    // 2023 (non-leap): index 59 == March 1 2023 00:00:00Z == 1677628800.
    try testing.expectEqual(@as(i32, 0), offsetAt(&z, 1677628800 - 1).off);
    try testing.expectEqual(@as(i32, 3600), offsetAt(&z, 1677628800).off);
    // 2024 (leap): index 59 == Feb 29 2024 00:00:00Z == 1709164800.
    try testing.expectEqual(@as(i32, 0), offsetAt(&z, 1709164800 - 1).off);
    try testing.expectEqual(@as(i32, 3600), offsetAt(&z, 1709164800).off);
}

test "posix footer: leap-year positive control — Jn and n resolve to different calendar days" {
    // Same nominal day-number (59) parsed via the two rule forms must NOT
    // land on the same instant in a leap year: J59 is Feb 29-blind (always
    // Feb 28), plain 59 is Feb 29-aware (lands on Feb 29 itself in 2024).
    // This is the whole point of having two separate rule forms rather than
    // aliasing one onto the other.
    const jn = Zone{
        .name = "Test/Jn2",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = "XST0XDT,J59/0,J300/0",
    };
    const yd = Zone{
        .name = "Test/n2",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = "YST0YDT,59/0,300/0",
    };
    const feb28_2024 = 1709078400; // 2024-02-28T00:00:00Z
    const feb29_2024 = 1709164800; // 2024-02-29T00:00:00Z
    try testing.expect(feb28_2024 != feb29_2024);
    // Jn already flipped to DST a full day before Feb 29 (it transitioned on
    // Feb 28, the last day it recognizes before March).
    try testing.expect(offsetAt(&jn, feb28_2024).dst);
    try testing.expect(offsetAt(&jn, feb29_2024).dst);
    // The zero-based form is still in STD at the start of Feb 28 and only
    // flips to DST exactly at Feb 29 00:00Z — a different UTC instant than Jn.
    try testing.expect(!offsetAt(&yd, feb28_2024).dst);
    try testing.expect(offsetAt(&yd, feb29_2024).dst);
}

// ---------------------------------------------------------------------------
// fuzz: find (zone-name lookup) and the POSIX-TZ footer grammar
// ---------------------------------------------------------------------------
//
// Two decode entry points take caller-supplied bytes: `find`'s zone-name
// binary search (what `check-fuzz`'s static scan actually flagged), and the
// module's real parsing logic — the POSIX-TZ footer grammar
// (`posixOffset`/`parseRule`/`ruleDateUnix`) reachable through the fully
// public `Zone.posix` field feeding the public `offsetAt`. A caller that
// reads a `TZ` environment variable or an untrusted footer string and builds
// its own `Zone` literal (exactly the pattern the synthetic-zone tests above
// use) hands this parser bytes it did not author.

test "fuzz: find never panics, arbitrary or real zone-name bytes" {
    try std.testing.fuzz({}, fuzzFindNeverPanics, .{});
}

fn fuzzFindNeverPanics(_: void, smith: *std.testing.Smith) !void {
    var buf: [64]u8 = undefined;
    const name = buildZoneName(smith, &buf);
    _ = find(name);
}

/// One draw in three copies a real zone name verbatim (or truncated) —
/// exercising exact-match hits and the binary search's boundary, which
/// arbitrary bytes essentially never do on their own; the rest is arbitrary
/// bytes.
fn buildZoneName(smith: *std.testing.Smith, buf: []u8) []const u8 {
    if (tz_data.zones.len != 0 and smith.valueRangeAtMost(u8, 0, 2) == 0) {
        const z = tz_data.zones[smith.index(tz_data.zones.len)];
        const len = @min(z.name.len, buf.len);
        @memcpy(buf[0..len], z.name[0..len]);
        return buf[0..len];
    }
    smith.bytes(buf);
    const len = smith.valueRangeAtMost(u8, 0, @intCast(buf.len));
    return buf[0..len];
}

const posix_footer_corpus = [_][]const u8{
    "CET-1CEST,M3.5.0,M10.5.0/3",
    "EST5EDT,M3.2.0,M11.1.0",
    "UTC0",
    "<+05>-5",
    "XST0XDT,J59/0,J300/0",
    "YST0YDT,59/0,300/0",
};

test "fuzz: offsetAt's POSIX-TZ footer parser never panics, arbitrary or footer-shaped bytes" {
    try std.testing.fuzz({}, fuzzPosixFooterNeverPanics, .{ .corpus = &posix_footer_corpus });
}

fn fuzzPosixFooterNeverPanics(_: void, smith: *std.testing.Smith) !void {
    var buf: [128]u8 = undefined;
    const posix = buildPosixFooter(smith, &buf);
    const z = Zone{
        .name = "Fuzz/Zone",
        .init_off = 0,
        .init_dst = false,
        .trans = &[_]Transition{},
        .posix = posix,
    };
    // A wide but bounded instant range — far enough past/before epoch to
    // reach every rule form's year math without courting unrelated i64*86400
    // overflow in datefmt, which is not this module's decode surface.
    const unix = smith.valueRangeAtMost(i64, -100 * 365 * 86400, 100 * 365 * 86400);
    _ = offsetAt(&z, unix);
}

/// One draw in six is pure arbitrary bytes; the rest assembles
/// `stdoffset[dst[offset][,start[/time],end[/time]]]` — the grammar
/// `posixOffset` walks — with each optional piece independently present or
/// absent, so both the "no DST" short-circuit and the full two-rule path get
/// exercised, not just whichever one arbitrary bytes happen to stumble into.
fn buildPosixFooter(smith: *std.testing.Smith, buf: []u8) []const u8 {
    if (smith.valueRangeAtMost(u8, 0, 5) == 0) {
        smith.bytes(buf);
        const len = smith.valueRangeAtMost(u8, 0, @intCast(buf.len));
        return buf[0..len];
    }
    var w: std.Io.Writer = .fixed(buf);
    writeAbbrev(smith, &w);
    writeFooterOffset(smith, &w);
    if (!smith.value(bool)) return w.buffered();
    writeAbbrev(smith, &w);
    if (smith.value(bool)) writeFooterOffset(smith, &w);
    if (!smith.value(bool)) return w.buffered();
    w.writeByte(',') catch return w.buffered();
    writeRuleText(smith, &w);
    writeRuleTimeText(smith, &w);
    w.writeByte(',') catch return w.buffered();
    writeRuleText(smith, &w);
    writeRuleTimeText(smith, &w);
    return w.buffered();
}

fn writeAbbrev(smith: *std.testing.Smith, w: *std.Io.Writer) void {
    const letters = "ABCXYZ";
    const len = smith.valueRangeAtMost(u8, 1, 4);
    var i: u8 = 0;
    while (i < len) : (i += 1) {
        w.writeByte(letters[smith.index(letters.len)]) catch return;
    }
}

fn writeFooterOffset(smith: *std.testing.Smith, w: *std.Io.Writer) void {
    if (smith.value(bool)) w.writeByte(if (smith.value(bool)) '+' else '-') catch return;
    w.print("{d}", .{smith.valueRangeAtMost(u8, 0, 23)}) catch return;
    if (!smith.value(bool)) return;
    w.print(":{d:0>2}", .{smith.valueRangeAtMost(u8, 0, 59)}) catch return;
    if (smith.value(bool)) w.print(":{d:0>2}", .{smith.valueRangeAtMost(u8, 0, 59)}) catch return;
}

fn writeRuleText(smith: *std.testing.Smith, w: *std.Io.Writer) void {
    switch (smith.valueRangeAtMost(u8, 0, 2)) {
        0 => w.print("M{d}.{d}.{d}", .{
            smith.valueRangeAtMost(u8, 1, 12),
            smith.valueRangeAtMost(u8, 1, 5),
            smith.valueRangeAtMost(u8, 0, 6),
        }) catch {},
        1 => w.print("J{d}", .{smith.valueRangeAtMost(u16, 1, 365)}) catch {},
        else => w.print("{d}", .{smith.valueRangeAtMost(u16, 0, 365)}) catch {},
    }
}

fn writeRuleTimeText(smith: *std.testing.Smith, w: *std.Io.Writer) void {
    if (!smith.value(bool)) return;
    w.writeByte('/') catch return;
    writeFooterOffset(smith, w);
}
