// SPDX-License-Identifier: MIT

//! The real `libuci` as a black-box oracle for this module's parser AND
//! serializer, and the recorder that freezes it into
//! `src/testdata/libuci_capture.zig`, replayed by `src/libuci_oracle_test.zig`
//! with no libuci.
//!
//!     python3 modules/uci/tools/libuci_corpus.py > .zig-cache/uci-differential/corpus.json
//!     zig build interop-uci                 # check that every input still captures
//!     zig build interop-uci -- --capture    # ...and rewrite the transcript
//!
//! Needs `oracle_dump` built against libuci (tools/README.md, "Building the
//! reference oracle") in `.zig-cache/uci-differential/out/`.
//!
//! For each corpus input: libuci's dump of it; and, when this module parses
//! it, this module's `serialize` output and libuci's dump of THAT -- whether
//! the real parser reads what this module writes as the model it wrote.

const std = @import("std");
const uci = @import("uci");

const base = ".zig-cache/uci-differential";
const oracle = base ++ "/out/oracle_dump";
const confdir = base ++ "/ref/root/etc/config";
const transcript_path = "modules/uci/src/testdata/libuci_capture.zig";

fn dumpWithLibuci(gpa: std.mem.Allocator, io: std.Io, text: []const u8) ![]u8 {
    var dir = try std.Io.Dir.cwd().openDir(io, confdir, .{});
    defer dir.close(io);
    try dir.writeFile(io, .{ .sub_path = "fz", .data = text });
    const r = try std.process.run(gpa, io, .{ .argv = &.{ oracle, confdir, "fz" } });
    defer gpa.free(r.stderr);
    return r.stdout;
}

fn zigString(gpa: std.mem.Allocator, out: *std.ArrayList(u8), s: []const u8) !void {
    try out.append(gpa, '"');
    for (s) |c| switch (c) {
        '"' => try out.appendSlice(gpa, "\\\""),
        '\\' => try out.appendSlice(gpa, "\\\\"),
        '\n' => try out.appendSlice(gpa, "\\n"),
        '\t' => try out.appendSlice(gpa, "\\t"),
        0x20...0x21, 0x23...0x5b, 0x5d...0x7e => try out.append(gpa, c),
        else => try out.print(gpa, "\\x{x:0>2}", .{c}),
    };
    try out.append(gpa, '"');
}

fn optString(gpa: std.mem.Allocator, out: *std.ArrayList(u8), s: ?[]const u8) !void {
    if (s) |v| try zigString(gpa, out, v) else try out.appendSlice(gpa, "null");
}

pub fn main(init: std.process.Init.Minimal) !u8 {
    var da: std.heap.DebugAllocator(.{}) = .init;
    defer _ = da.deinit();
    const gpa = da.allocator();
    var threaded: std.Io.Threaded = .init(gpa, .{ .environ = init.environ });
    defer threaded.deinit();
    const io = threaded.io();

    var capture = false;
    var args = init.args.iterate();
    _ = args.skip();
    while (args.next()) |a| {
        if (std.mem.eql(u8, a, "--capture")) capture = true else {
            std.debug.print("usage: zig build interop-uci [-- --capture]\n", .{});
            return 2;
        }
    }

    var arena_state = std.heap.ArenaAllocator.init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const corpus_text = try std.Io.Dir.cwd().readFileAlloc(io, base ++ "/corpus.json", arena, .limited(16 << 20));
    const corpus = try std.json.parseFromSliceLeaky([]const []const u8, arena, corpus_text, .{});

    var out: std.ArrayList(u8) = .empty;
    defer out.deinit(gpa);
    try out.appendSlice(gpa, "// SPDX-License-Identifier: MIT\n" ++
        "// Generated by `zig build interop-uci -- --capture` (modules/uci/tools/interop.zig): the\n" ++
        "// real libuci's dump of each input, and of this module's `serialize` of it. Replayed by\n" ++
        "// src/libuci_oracle_test.zig. Do not edit by hand.\n\n" ++
        "pub const Case = struct { input: []const u8, libuci: []const u8, serialized: ?[]const u8, libuci_serialized: ?[]const u8 };\n\n" ++
        "pub const cases = [_]Case{\n");

    var parsed: usize = 0;
    for (corpus) |hex| {
        const input = try arena.alloc(u8, hex.len / 2);
        _ = try std.fmt.hexToBytes(input, hex);
        const theirs = try dumpWithLibuci(arena, io, input);
        var ser: ?[]const u8 = null;
        var theirs_ser: ?[]const u8 = null;
        if (uci.parse(arena, input)) |pkg| {
            parsed += 1;
            if (uci.serialize(arena, &pkg)) |text| {
                ser = text;
                theirs_ser = try dumpWithLibuci(arena, io, text);
            } else |e| {
                // A value libuci itself would not write back (SerializeError):
                // recorded, and the replay requires the same refusal.
                theirs_ser = try std.fmt.allocPrint(arena, "SERIALIZE-ERROR {t}", .{e});
            }
        } else |_| {}
        try out.appendSlice(gpa, "    .{ .input = ");
        try zigString(gpa, &out, input);
        try out.appendSlice(gpa, ", .libuci = ");
        try zigString(gpa, &out, theirs);
        try out.appendSlice(gpa, ", .serialized = ");
        try optString(gpa, &out, ser);
        try out.appendSlice(gpa, ", .libuci_serialized = ");
        try optString(gpa, &out, theirs_ser);
        try out.appendSlice(gpa, " },\n");
    }
    try out.appendSlice(gpa, "};\n");
    std.debug.print("interop-uci: {d} inputs, {d} parsed by this module\n", .{ corpus.len, parsed });
    if (capture) {
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = transcript_path, .data = out.items });
        std.debug.print("interop-uci: transcript written to {s}\n", .{transcript_path});
    }
    return 0;
}
