#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for `src/diag_vectors.zig`: the RFC 8949 Appendix A table
(diagnostic notation <-> encoded hex), transcribed mechanically from the RFC
text, not typed by hand.

Run:  curl -sS -o rfc8949.txt https://www.rfc-editor.org/rfc/rfc8949.txt
      python3 gen_diag_vectors.py rfc8949.txt > ../src/diag_vectors.zig
      zig fmt ../src/diag_vectors.zig

Every row is emitted. `kind` says how the test uses it:
  .exact     -- `writeDiagnostic(decode(hex))` must equal the RFC's text;
  .bignum    -- the RFC shows the bignum's numeric value; this module prints
                the generic tag form (also valid diagnostic notation, RFC 8949
                section 8), so the test checks the hand-derived tag form;
  .indefinite -- the RFC's text carries `_` encoding indicators that a decoded
                `Value` does not keep (decode is lossless only for the data
                model); the test checks the text after dropping the indicators.
"""
import re, sys

def rows(path):
    lines = open(path, encoding="utf-8").read().splitlines()
    start = next(i for i, l in enumerate(lines) if l.startswith("Appendix A.  Examples"))
    out, diag, enc, inrow = [], [], [], False
    for l in lines[start:]:
        if l.startswith("Appendix B."):
            break
        m = re.match(r"^   \|(.*)\|(.*)\|\s*$", l)
        if m:
            inrow = True
            diag.append(m.group(1).rstrip())
            enc.append(m.group(2).strip())
        elif re.match(r"^   \+[-=+]+\+\s*$", l):
            if inrow and diag:
                d = " ".join(x.strip() for x in diag if x.strip())
                # A cell wrapped after ", " keeps one space; one wrapped mid-token
                # (long hex in the right column) is joined without one.
                d = d.replace("[ ", "[").replace("{ ", "{")
                e = "".join(enc)
                if d != "Diagnostic":
                    out.append((d, e))
            diag, enc, inrow = [], [], False
    return out

def zstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def main():
    rs = rows(sys.argv[1])
    print("// SPDX-License-Identifier: MIT")
    print("//! GENERATED by tools/gen_diag_vectors.py from the RFC 8949 text -- do not edit.")
    print("//! RFC 8949 Appendix A: diagnostic notation and the encoded item.")
    print("pub const Kind = enum { exact, bignum, indefinite };")
    print("pub const Row = struct { diag: []const u8, hex: []const u8, kind: Kind };")
    print("pub const rows = [_]Row{")
    for d, e in rs:
        assert e.startswith("0x"), (d, e)
        h = e[2:]
        if h.startswith("c249") or h.startswith("c349"):
            kind = "bignum"
        elif "_" in d:
            kind = "indefinite"
        else:
            kind = "exact"
        print(f"    .{{ .diag = {zstr(d)}, .hex = {zstr(h)}, .kind = .{kind} }},")
    print("};")
    print(f"// {len(rs)} rows")

main()
