#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for `src/cbor2_vectors.zig`: Python cbor2 (MIT) driven as a
BLACK-BOX oracle through its public `dumps`/`loads` only; no cbor2 source
was read.

Run (cbor2 6.1.5 in a throwaway venv):
    python3 -m venv venv && venv/bin/pip install cbor2==6.1.5
    venv/bin/python gen_cbor2_vectors.py > ../src/cbor2_vectors.zig
    zig fmt ../src/cbor2_vectors.zig

What is captured
  * floats   -- `dumps(x, canonical=True)` for edge values and random
                binary16/32/64 values: the shortest exact width (RFC 8949
                section 4.1), NaN as f97e00.
  * trees    -- random trees, encoded once with `canonical=True` and once
                plain. Keys are kept in insertion order by cbor2 only in the
                plain form; the canonical form sorts by (length, bytes) --
                RFC 7049 canonical, NOT the RFC 8949 bytewise order -- so the
                test compares bytes after a decode/re-encode WITHOUT key
                sorting: the wire order is kept, the float widths are what is
                checked.
  * verdicts -- for hand-made inputs, whether `loads(.., allow_duplicate_keys
                =False)` and `loads(.., allow_indefinite=False)` accept them.
                Only same-kind keys: Python's 1 == 1.0 would call an int and a
                float key equal, which the CBOR data model does not.
"""
import math, random, struct, cbor2

rng = random.Random(20261004)

def zhex(b):
    return '"' + b.hex() + '"'

floats = [0.0, -0.0, 1.0, -1.0, 1.5, 65504.0, 65505.0, 65519.0, 65520.0, 100000.0,
          1e300, 5.960464477539063e-08, 2.0 ** -25, 2.0 ** -24 * 3, 6.103515625e-05,
          6.097555160522461e-05, 3.4028234663852886e38, 3.4028235677973366e38,
          1.401298464324817e-45, 7e-46, 0.1, 1 / 3, -4.0, -4.1, math.inf, -math.inf,
          math.nan, 1363896240.5, 2.0 ** 24, 2.0 ** 24 + 1, 2.0 ** 11 + 1, 2.0 ** 11 + 2]
for _ in range(24):
    floats.append(struct.unpack(">e", rng.randbytes(2))[0])
for _ in range(24):
    floats.append(struct.unpack(">f", rng.randbytes(4))[0])
for _ in range(16):
    floats.append(struct.unpack(">d", rng.randbytes(8))[0])

def rand_tree(d):
    k = rng.randrange(9 if d < 3 else 6)
    if k == 0:
        return rng.choice([0, 1, 23, 24, 255, 256, 65535, 65536, 2 ** 32 - 1, 2 ** 32, 2 ** 64 - 1,
                           rng.randrange(2 ** rng.randrange(1, 64))])
    if k == 1:
        return -1 - rng.choice([0, 23, 24, 255, 256, 2 ** 32, 2 ** 64 - 1, rng.randrange(2 ** 40)])
    if k == 2:
        return rng.choice(floats)
    if k == 3:
        return "".join(rng.choice("abü水\U00010151\"\\\n") for _ in range(rng.randrange(6)))
    if k == 4:
        return rng.randbytes(rng.randrange(30))
    if k == 5:
        return rng.choice([True, False, None])
    if k == 6:
        return [rand_tree(d + 1) for _ in range(rng.randrange(5))]
    if k == 7:
        out = {}
        for _ in range(rng.randrange(5)):
            key = rng.choice([rng.randrange(-30, 3000), "k" * rng.randrange(1, 4) + str(rng.randrange(99))])
            out[key] = rand_tree(d + 1)
        return out
    return cbor2.CBORTag(rng.choice([1, 24, 32, 1000, 55799]), rand_tree(d + 1))

def verdict(hexs):
    b = bytes.fromhex(hexs)
    def ok(**kw):
        try:
            cbor2.loads(b, **kw)
            return "true"
        except Exception:
            return "false"
    assert ok() == "true", hexs
    return ok(allow_duplicate_keys=False), ok(allow_indefinite=False)

# built explicitly so every hex is checked by cbor2 itself
verdict_inputs = [
    ("a201010202", "distinct int keys"),
    ("a201010102", "int key 1 twice, same encoding"),
    ("a20101180102", "int key 1 as 01 and as 1801"),
    ("a2616101616202", "distinct text keys"),
    ("a2616101616102", "text key \"a\" twice"),
    ("a262616201" + "7f61616162ff" + "02", "\"ab\" definite and chunked"),
    ("a2420102014201020f", "byte string key twice"),
    ("a2f93c0001fb3ff000000000000002", "1.0 as binary16 and binary64"),
    ("a2f93c0001f9400002", "1.0 and 2.0"),
    ("a28201020182010202", "array key [1,2] twice"),
    ("a28201020182010302", "array keys [1,2] and [1,3]"),
    ("a3010102020103", "1 2 1: duplicate not adjacent"),
    ("bf01010102ff", "indefinite map, key 1 twice"),
    ("bf01010202ff", "indefinite map, distinct"),
    ("5f4101ff", "indefinite byte string"),
    ("7f6161ff", "indefinite text string"),
    ("9f01ff", "indefinite array"),
    ("8101", "definite array"),
    ("a1a1010201", "map key that is a map"),
    ("a2a10102 01 a10102 02".replace(" ", ""), "map key {1:2} twice"),
    ("a2c10101c10102", "tagged key 1(1) twice"),
    ("a2c10101d903e80102", "1(1) and 1000(1): distinct"),
]

print("// SPDX-License-Identifier: MIT")
print("//! GENERATED by tools/gen_cbor2_vectors.py (Python cbor2 6.1.5 as a black-box")
print("//! oracle) -- do not edit.")
print("pub const Float = struct { bits: u64, canonical_hex: []const u8 };")
print("pub const floats = [_]Float{")
for x in floats:
    print(f"    .{{ .bits = 0x{struct.unpack('>Q', struct.pack('>d', x))[0]:016x}, .canonical_hex = {zhex(cbor2.dumps(x, canonical=True))} }},")
print("};")
print("pub const Tree = struct { plain_hex: []const u8, canonical_hex: []const u8 };")
print("pub const trees = [_]Tree{")
for _ in range(80):
    t = rand_tree(0)
    print(f"    .{{ .plain_hex = {zhex(cbor2.dumps(t))}, .canonical_hex = {zhex(cbor2.dumps(t, canonical=True))} }},")
print("};")
print("pub const Verdict = struct { hex: []const u8, what: []const u8, unique_keys_ok: bool, definite_ok: bool };")
print("pub const verdicts = [_]Verdict{")
for h, what in verdict_inputs:
    d, i = verdict(h)
    w = what.replace('"', '\\"')
    print(f"    .{{ .hex = \"{h}\", .what = \"{w}\", .unique_keys_ok = {d}, .definite_ok = {i} }},")
print("};")
