#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for src/tree_vectors.zig: transcribes the `scriptPubKey` rows that
carry a `scriptTree` from BIP341's wallet-test-vectors.json.

  curl -sSL https://raw.githubusercontent.com/bitcoin/bips/master/bip-0341/wallet-test-vectors.json -o vectors.json
  python3 tools/gen_tree_vectors.py vectors.json > src/tree_vectors.zig

Per row it emits the tree twice: as the explicit nested shape (`tree`) and as
the depth-first (depth, version, script) list (`leaves`, the BIP371
PSBT_OUT_TAP_TREE order), plus every published intermediary / expected value.
JSON shape: a dict is a leaf, a 2-element list is a branch.
"""
import json
import sys

d = json.load(open(sys.argv[1]))


def leaf_list(t, depth, out):
    if isinstance(t, dict):
        out.append((depth, t["leafVersion"], t["script"]))
    else:
        assert len(t) == 2
        leaf_list(t[0], depth + 1, out)
        leaf_list(t[1], depth + 1, out)


def shape(t, ind):
    pad = "    " * ind
    if isinstance(t, dict):
        return '.{ .leaf = .{ .version = 0x%02x, .script = hx("%s") } }' % (t["leafVersion"], t["script"])
    a = shape(t[0], ind + 1)
    b = shape(t[1], ind + 1)
    return ".{ .branch = .{\n%s    &%s,\n%s    &%s,\n%s} }" % (pad, a, pad, b, pad)


def strs(xs, ind):
    pad = "    " * ind
    return "\n".join('%s"%s",' % (pad, x) for x in xs)


print("// SPDX-License-Identifier: MIT")
print("//! GENERATED by tools/gen_tree_vectors.py from BIP341's")
print("//! bip-0341/wallet-test-vectors.json (`scriptPubKey` rows with a `scriptTree`).")
print("//! Do not edit by hand; rerun the recipe.")
print()
print('const std = @import("std");')
print('const tree = @import("tree.zig");')
print()
print("/// Comptime hex literal -> bytes.")
print("fn hx(comptime s: []const u8) []const u8 {")
print("    @setEvalBranchQuota(100_000);")
print("    comptime {")
print("        var b: [s.len / 2]u8 = undefined;")
print("        _ = std.fmt.hexToBytes(&b, s) catch unreachable;")
print("        const f = b;")
print("        return &f;")
print("    }")
print("}")
print()
print("pub const Row = struct {")
print("    /// Index into the JSON's `scriptPubKey` array.")
print("    index: u8,")
print("    internal_pubkey: []const u8,")
print("    tree: tree.Node,")
print("    /// The same tree as a depth-first list (BIP371 order).")
print("    leaves: []const tree.DepthLeaf,")
print("    leaf_hashes: []const []const u8,")
print("    merkle_root: []const u8,")
print("    tweak: []const u8,")
print("    tweaked_pubkey: []const u8,")
print("    script_pub_key: []const u8,")
print("    control_blocks: []const []const u8,")
print("};")
print()
print("pub const rows = [_]Row{")
n = 0
for i, r in enumerate(d["scriptPubKey"]):
    t = r["given"]["scriptTree"]
    if t is None:
        continue
    ll = []
    leaf_list(t, 0, ll)
    im, ex = r["intermediary"], r["expected"]
    assert len(im["leafHashes"]) == len(ll) == len(ex["scriptPathControlBlocks"])
    n += len(ll)
    print("    .{")
    print("        .index = %d," % i)
    print('        .internal_pubkey = "%s",' % r["given"]["internalPubkey"])
    print("        .tree = %s," % shape(t, 2))
    print("        .leaves = &.{")
    for dep, ver, sc in ll:
        print('            .{ .depth = %d, .version = 0x%02x, .script = hx("%s") },' % (dep, ver, sc))
    print("        },")
    print("        .leaf_hashes = &.{")
    print(strs(im["leafHashes"], 3))
    print("        },")
    print('        .merkle_root = "%s",' % im["merkleRoot"])
    print('        .tweak = "%s",' % im["tweak"])
    print('        .tweaked_pubkey = "%s",' % im["tweakedPubkey"])
    print('        .script_pub_key = "%s",' % ex["scriptPubKey"])
    print("        .control_blocks = &.{")
    print(strs(ex["scriptPathControlBlocks"], 3))
    print("        },")
    print("    },")
print("};")
print()
print("/// Total `scriptPathControlBlocks` entries across `rows` (all asserted).")
print("pub const control_block_count = %d;" % n)
