#!/usr/bin/env bash
# Regenerate modules/zstd/src/testdata/goldens.zig from libzstd v1.5.7.
#
# Needs: git, make, a C compiler, sha256sum, zig. Writes only the goldens file;
# the libzstd checkout and the corpus files go to a disposable directory
# ($ZSTD_REF, default .zig-cache/zstd-ref under the repository root).
#
# Every (case, level, checksum) combination the golden test iterates must have
# a row, so LEVELS below must equal `corpus.levels`.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
mod=$(dirname "$here")
root=$(cd "$mod/../.." && pwd)
R=${ZSTD_REF:-$root/.zig-cache/zstd-ref}
pin=f8745da6ff1ad1e7bab384bd1f9d742439278e99 # tag v1.5.7
LEVELS="-5 -1 1 2 3"

if [ ! -d "$R/lib" ]; then
    git clone --quiet --depth 1 --branch v1.5.7 https://github.com/facebook/zstd.git "$R"
fi
got=$(git -C "$R" rev-parse HEAD)
if [ "$got" != "$pin" ]; then
    echo "libzstd checkout at $got, expected v1.5.7 ($pin)" >&2
    exit 1
fi
make -C "$R/lib" -j"$(nproc)" libzstd.a >/dev/null
cc -O2 -I "$R/lib" -o "$R/zref" "$here/zref.c" "$R/lib/libzstd.a"

work="$R/corpus"
mkdir -p "$work"
(cd "$root" && zig run --dep corpus -Mroot=modules/zstd/tools/dump_corpus.zig \
    -Mcorpus=modules/zstd/src/testdata/corpus.zig -- "$work")

out="$mod/src/testdata/goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin), ZSTD_compress2, one-shot."
    echo "//! Each row: compressed length and SHA-256 of the frame libzstd emits for"
    echo "//! corpus case \`case\` at \`level\`, with or without the content checksum."
    echo ""
    echo "pub const Golden = struct { case: []const u8, level: i32, checksum: bool, len: usize, sha256: *const [64]u8 };"
    echo ""
    echo "pub const rows = [_]Golden{"
    for f in $(cd "$work" && ls); do
        for l in $LEVELS; do
            for ck in 0 1; do
                "$R/zref" "$l" "$ck" "$work/$f" "$R/out.zst"
                len=$(stat -c %s "$R/out.zst")
                sum=$(sha256sum "$R/out.zst" | cut -d' ' -f1)
                b=$([ "$ck" = 1 ] && echo true || echo false)
                echo "    .{ .case = \"$f\", .level = $l, .checksum = $b, .len = $len, .sha256 = \"$sum\" },"
            done
        done
    done
    echo "};"
} >"$out"
echo "wrote $out ($(grep -c '\.case' "$out") rows)"
