#!/usr/bin/env bash
# Regenerate modules/zstd/src/testdata/mbs_kats.zig: libzstd 1.5.7's verdict
# on frames with blocks of various sizes decoded under ZSTD_d_maxBlockSize
# (`max_block_size`), which `dctx_test.zig` pins.
#
# The frames are libzstd's own (`zref` with ZSTD_c_maxBlockSize) over
# corpus inputs; the test makes them with this module's compressor and
# checks each frame's length and FNV-1a first. Each is decoded by `zdec`
# with every decoder maximum in three ways: one-shot (mode 0), streamed
# whole (mode 1: the single-pass shortcut where the content fits 128 KB of
# output) and streamed one byte at a time (mode 2) -- the verdict (0 for
# the input back, else the ZSTD_ErrorCode) and, streamed, the bytes of the
# stream's buffers at the end (`bufs:1`).
#
# Needs: git, make, a C compiler, zig, python3. Writes only the KAT file;
# the checkout and the frames go to $ZSTD_REF (default .zig-cache/zstd-ref
# under the repository root), as for gen-goldens.sh.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
mod=$(dirname "$here")
root=$(cd "$mod/../.." && pwd)
R=${ZSTD_REF:-$root/.zig-cache/zstd-ref}
pin=f8745da6ff1ad1e7bab384bd1f9d742439278e99 # tag v1.5.7

if [ ! -d "$R/lib" ]; then
    git clone --quiet --depth 1 --branch v1.5.7 https://github.com/facebook/zstd.git "$R"
fi
got=$(git -C "$R" rev-parse HEAD)
if [ "$got" != "$pin" ]; then
    echo "libzstd checkout at $got, expected v1.5.7 ($pin)" >&2
    exit 1
fi
make -C "$R/lib" -j"$(nproc)" libzstd.a >/dev/null
cc -O2 -I "$R/lib" -o "$R/zref-st" "$here/zref.c" "$R/lib/libzstd.a"
cc -O2 -I "$R/lib" -o "$R/zdec" "$here/zdec.c" "$R/lib/libzstd.a"

work="$R/mbs"
mkdir -p "$work/corpus"
(cd "$root" && zig run --dep corpus -Mroot=modules/zstd/tools/dump_corpus.zig \
    -Mcorpus=modules/zstd/src/testdata/corpus.zig -- "$work/corpus" "$work/m1" "$work/m2" "$work/m3")

fnv() { python3 -c 'import sys
h=0xcbf29ce484222325
for x in open(sys.argv[1],"rb").read(): h=((h^x)*0x100000001b3)&0xFFFFFFFFFFFFFFFF
print("0x%016x"%h)' "$1"; }
# "OK ..." -> 0, "ERR n" -> n; "BUF n" -> n
verdict() { sed -n 's/^OK .*/0/p; s/^ERR \([0-9]*\)/\1/p'; }
bufs() { sed -n 's/^BUF \([0-9]*\)/\1/p'; }

cases="words-16385 csv-131073 random-300000 zeros-300000 long-literals mix-1186"
levels="1 19"
frame_mbs="0 65536 4096 1024"
dec_mbs="1024 4096 65535 65536 131072"

out="$mod/src/testdata/mbs_kats.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-mbs-kats.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin): a frame \`zref\` makes of corpus case"
    echo "//! \`case\` at \`level\` with ZSTD_c_maxBlockSize \`frame_mbs\` (0: none),"
    echo "//! of \`len\` bytes and FNV-1a \`fnv\`, decoded by \`zdec\` with"
    echo "//! ZSTD_d_maxBlockSize \`mbs\`: one-shot, streamed whole, streamed one byte"
    echo "//! at a time -- 0 for the input back, else the ZSTD_ErrorCode -- and the"
    echo "//! stream's buffer bytes at the end of the two streamed runs."
    echo ""
    echo "pub const Kat = struct { case: []const u8, level: i32, frame_mbs: u32, len: usize, fnv: u64, mbs: u32, oneshot: u8, whole: u8, bytewise: u8, whole_buf: usize, bytewise_buf: usize };"
    echo ""
    echo "pub const kats = [_]Kat{"
    for c in $cases; do
        for l in $levels; do
            for f in $frame_mbs; do
                z="$work/$c-$l-$f.zst"
                if [ "$f" = 0 ]; then p=-; else p="maxBlockSize=$f"; fi
                "$R/zref-st" "$l" 0 "$work/corpus/$c" "$z" 0 0 0 "$p"
                len=$(stat -c %s "$z")
                h=$(fnv "$z")
                for m in $dec_mbs; do
                    o0=$("$R/zdec" "$z" - 0 0 "mbs:$m" || true)
                    o1=$("$R/zdec" "$z" - 1 0 "mbs:$m" bufs:1 || true)
                    o2=$("$R/zdec" "$z" - 2 0 "mbs:$m" bufs:1 || true)
                    echo "    .{ .case = \"$c\", .level = $l, .frame_mbs = $f, .len = $len, .fnv = $h, .mbs = $m, .oneshot = $(verdict <<<"$o0"), .whole = $(verdict <<<"$o1"), .bytewise = $(verdict <<<"$o2"), .whole_buf = $(bufs <<<"$o1"), .bytewise_buf = $(bufs <<<"$o2") },"
                done
            done
        done
    done
    echo "};"
} >"$out.tmp"
mv "$out.tmp" "$out"
echo "wrote $(grep -c '\.case =' "$out") rows to $out"
