#!/usr/bin/env bash
# Regenerate modules/zstd/src/testdata/seekable_goldens.zig from libzstd
# v1.5.7's contrib/seekable_format, driven by tools/zseekable.c.
#
# Needs: git, make, a C compiler, sha256sum, zig. Writes only the goldens file;
# the libzstd checkout and the corpus files go to a disposable directory
# ($ZSTD_REF, default .zig-cache/zstd-ref under the repository root), the same
# one tools/gen-goldens.sh uses.
#
# Each row: a corpus case compressed by ZSTD_seekable_CStream at a level, with
# or without frame checksums, a maxFrameSize, following a call schedule
# (see zseekable.c); the length and SHA-256 of everything it emits.
# `seekable_test.zig` drives `SeekableStream` by the same schedule and must
# match, then reads the result back through `Seekable`.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
mod=$(dirname "$here")
root=$(cd "$mod/../.." && pwd)
R=${ZSTD_REF:-$root/.zig-cache/zstd-ref}
pin=f8745da6ff1ad1e7bab384bd1f9d742439278e99 # tag v1.5.7

if [ ! -d "$R/lib" ]; then
    git clone --quiet --depth 1 --branch v1.5.7 https://github.com/facebook/zstd.git "$R"
fi
got=$(git -C "$R" rev-parse HEAD)
if [ "$got" != "$pin" ]; then
    echo "libzstd checkout at $got, expected v1.5.7 ($pin)" >&2
    exit 1
fi
make -C "$R/lib" -j"$(nproc)" libzstd.a >/dev/null
S="$R/contrib/seekable_format"
cc -O2 -I "$R/lib" -I "$R/lib/common" -I "$S" -o "$R/zseekable" "$here/zseekable.c" \
    "$S/zstdseek_compress.c" "$S/zstdseek_decompress.c" "$R/lib/libzstd.a"

work="$R/corpus"
mkdir -p "$work"
(cd "$root" && zig run --dep corpus -Mroot=modules/zstd/tools/dump_corpus.zig \
    -Mcorpus=modules/zstd/src/testdata/corpus.zig -- "$work" "$R/manifest.txt" "$R/stream-manifest.txt" \
    "$R/param-manifest.txt" "$R/dict-manifest.txt" "$mod/src/testdata" "$R/mt-manifest.txt" \
    "$R/seq-manifest.txt")

# case level checksum maxFrameSize schedule
rows() {
    cat <<'ROWS'
empty 3 0 0 e
empty 3 1 0 e
empty 3 1 1024 f,e
empty 3 0 1024 f,f,e
one 3 1 0 c*,e
seven 1 0 3 c*,e
words-1000 3 1 100 c*,e
words-1000 3 0 100 c1,c7,c500,c*,e
words-16385 3 1 4096 o7,c*,e
words-16385 3 0 4096 o1,c*,e
words-16385 3 1 4096 c*,o3,e
csv-131073 1 0 0 c*,e
csv-131073 3 1 0 c*,e
csv-131073 19 0 0 c*,e
words-262145 -5 0 65536 c*,e
words-262145 3 1 65536 c*,e
words-262145 9 0 65536 c*,e
csv-600000 3 1 262144 c*,e
csv-600000 3 0 262144 c100000,f,c*,e
csv-600000 6 1 100000 o4096,c*,e
random-300000 3 1 65536 c*,e
zeros-300000 3 0 1000 c*,e
mix-300000-9 12 1 131072 c50000,c50000,f,c*,e
mix-140000-1 16 0 70000 c*,e
words-1000 3 1 1 c*,e
far-repeat 3 1 0 c*,e
ROWS
}

out="$mod/src/testdata/seekable_goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-seekable-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin), contrib/seekable_format driven by tools/zseekable.c."
    echo "//! Each row: length and SHA-256 of everything ZSTD_seekable_CStream emits"
    echo "//! for corpus case \`case\` at \`level\`, with or without frame checksums, at"
    echo "//! \`max_frame_size\` (0: the 1 GiB default), following \`schedule\`."
    echo ""
    echo "pub const Golden = struct { case: []const u8, level: i32, checksum: bool, max_frame_size: u32, schedule: []const u8, len: usize, sha256: *const [64]u8 };"
    echo ""
    echo "pub const rows = [_]Golden{"
    rows | while read -r c l ck m sch; do
        "$R/zseekable" c "$l" "$ck" "$m" "$work/$c" "$R/seek.zst" "$sch" >/dev/null
        # every stream decodes back with the plain decoder too
        if [ "$c" != empty ] || [ -s "$R/seek.zst" ]; then
            "$R/programs/zstd" -q -d -c "$R/seek.zst" 2>/dev/null | cmp -s - "$work/$c" ||
                zstd -q -d -c "$R/seek.zst" | cmp -s - "$work/$c" || { echo "$c $sch: plain decode differs" >&2; exit 1; }
        fi
        len=$(stat -c %s "$R/seek.zst")
        sum=$(sha256sum "$R/seek.zst" | cut -d' ' -f1)
        b=$([ "$ck" = 1 ] && echo true || echo false)
        echo "    .{ .case = \"$c\", .level = $l, .checksum = $b, .max_frame_size = $m, .schedule = \"$sch\", .len = $len, .sha256 = \"$sum\" },"
    done
    echo "};"
} >"$out"
echo "wrote $out ($(grep -c '\.case' "$out") rows)"
