#!/usr/bin/env bash
# Regenerate modules/zstd/src/testdata/dict_goldens.zig: for every run in
# `dict_samples.runs`, what libzstd v1.5.7's cover / fastCover trainer puts in
# the dictionary buffer before finalization (length and SHA-256 of the
# content, and whether it warns of a small corpus), or the error it refuses
# with -- through tools/ztrain.c; and dict_final_goldens.zig: for every run
# in `dict_samples.final_runs`, the finished dictionary libzstd's
# finalizer, trainers, optimizers or COVER_selectDict give (length, SHA-256,
# header size, the optimizers' k and d or the selection's total), or the
# error -- through tools/zfinal.c.
#
# Needs: git, a C compiler, sha256sum, zig. Writes only the goldens file; the
# libzstd checkout, the two ztrain builds and the sample files go to a
# disposable directory ($ZSTD_REF, default .zig-cache/zstd-ref under the
# repository root).
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
mod=$(dirname "$here")
root=$(cd "$mod/../.." && pwd)
R=${ZSTD_REF:-$root/.zig-cache/zstd-ref}
pin=f8745da6ff1ad1e7bab384bd1f9d742439278e99 # tag v1.5.7

if [ ! -d "$R/lib" ]; then
    git clone --quiet --depth 1 --branch v1.5.7 https://github.com/facebook/zstd.git "$R"
fi
got=$(git -C "$R" rev-parse HEAD)
if [ "$got" != "$pin" ]; then
    echo "libzstd checkout at $got, expected v1.5.7 ($pin)" >&2
    exit 1
fi
L=("$R"/lib/common/*.c "$R"/lib/compress/*.c "$R/lib/dictBuilder/zdict.c" "$R/lib/dictBuilder/divsufsort.c")
# cover.h has no include guard: one build per trainer, the other linked.
cc -O2 -w -I "$R/lib" -I "$R/lib/dictBuilder" -o "$R/ztrain-cover" "$here/ztrain.c" \
    "${L[@]}" "$R/lib/dictBuilder/fastcover.c"
cc -O2 -w -DZTRAIN_FASTCOVER -I "$R/lib" -I "$R/lib/dictBuilder" -o "$R/ztrain-fastcover" "$here/ztrain.c" \
    "${L[@]}" "$R/lib/dictBuilder/cover.c"
make -C "$R/lib" -j"$(nproc)" libzstd.a >/dev/null
cc -O2 -w -I "$R/lib" -I "$R/lib/dictBuilder" -o "$R/zfinal" "$here/zfinal.c" "$R/lib/libzstd.a" -lpthread

work="$R/dict-samples"
mkdir -p "$work"
(cd "$root" && zig run --dep samples -Mroot=modules/zstd/tools/dump_samples.zig \
    -Msamples=modules/zstd/src/testdata/dict_samples.zig -- "$work" "$R/dict-manifest.txt" "$R/dict-final-manifest.txt")

out="$mod/src/testdata/dict_goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-dict-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin), cover.c / fastcover.c driven by tools/ztrain.c."
    echo "//! Each row: one \`dict_samples.runs\` entry, in order, and what libzstd's"
    echo "//! trainer did with it before finalization: the content's length and SHA-256"
    echo "//! and the small-corpus warning, or the error (\`ZSTD_ErrorCode\`) it refused with."
    echo ""
    echo "pub const Golden = struct { err: u32 = 0, len: usize = 0, small: bool = false, sha256: *const [64]u8 = \"-\" ** 64 };"
    echo ""
    echo "pub const rows = [_]Golden{"
    while read -r tr set cap k d f accel split; do
        res=$("$R/ztrain-$tr" "$tr" "$work/$set.bin" "$R/dict-out.bin" "$cap" "$k" "$d" "$f" "$accel" "$split")
        case "$res" in
        OK*)
            read -r _ len small <<<"$res"
            sum=$(sha256sum "$R/dict-out.bin" | cut -d' ' -f1)
            b=$([ "$small" = 1 ] && echo true || echo false)
            echo "    .{ .len = $len, .small = $b, .sha256 = \"$sum\" }, // $tr $set $cap k=$k d=$d f=$f accel=$accel split=$split"
            ;;
        ERR*)
            read -r _ code <<<"$res"
            echo "    .{ .err = $code }, // $tr $set $cap k=$k d=$d f=$f accel=$accel split=$split"
            ;;
        *) echo "unexpected ztrain output: $res" >&2; exit 1 ;;
        esac
    done <"$R/dict-manifest.txt"
    echo "};"
} >"$out"
echo "wrote $out ($(grep -c '^    \.{' "$out") rows)"

out="$mod/src/testdata/dict_final_goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-dict-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin), public dictBuilder API (and COVER_selectDict) driven"
    echo "//! by tools/zfinal.c. Each row: one \`dict_samples.final_runs\` entry, in order:"
    echo "//! the finished dictionary's length and SHA-256, ZDICT_getDictHeaderSize of it"
    echo "//! (negated error code if none), the optimizers' chosen k and d (a, b) or the"
    echo "//! selection's total compressed size (a) -- or the error (\`ZSTD_ErrorCode\`;"
    echo "//! 1000: COVER_selectDict gave no selection)."
    echo ""
    echo "pub const Golden = struct { err: u32 = 0, len: usize = 0, hdr: i64 = 0, a: u64 = 0, b: u64 = 0, sha256: *const [64]u8 = \"-\" ** 64 };"
    echo ""
    echo "pub const rows = [_]Golden{"
    while read -r op set cap off len nbfin nbtrain k d f accel steps split level dictid shrink maxreg; do
        s="$work/$set.bin"
        o="$R/dict-final-out.bin"
        case "$op" in
        finalize) res=$("$R/zfinal" finalize "$s" "$o" "$cap" "$off" "$len" "$nbfin" "$level" "$dictid") ;;
        addentropy) res=$("$R/zfinal" addentropy "$s" "$o" "$cap" "$off" "$len") ;;
        cover) res=$("$R/zfinal" cover "$s" "$o" "$cap" "$k" "$d" "$level" "$dictid") ;;
        fastcover) res=$("$R/zfinal" fastcover "$s" "$o" "$cap" "$k" "$d" "$f" "$accel" "$level" "$dictid") ;;
        optcover) res=$("$R/zfinal" optcover "$s" "$o" "$cap" "$k" "$d" "$steps" "$split" "$level" "$dictid") ;;
        optfast) res=$("$R/zfinal" optfast "$s" "$o" "$cap" "$k" "$d" "$steps" "$split" "$f" "$accel" "$level" "$dictid") ;;
        default) res=$("$R/zfinal" default "$s" "$o" "$cap") ;;
        select) res=$("$R/zfinal" select "$s" "$o" "$cap" "$off" "$len" "$nbfin" "$nbtrain" "$split" "$level" "$dictid" "$shrink" "$maxreg") ;;
        *) echo "unknown op $op" >&2; exit 1 ;;
        esac
        what="$op $set $cap off=$off len=$len fin=$nbfin train=$nbtrain k=$k d=$d f=$f accel=$accel steps=$steps split=$split level=$level id=$dictid shrink=$shrink/$maxreg"
        case "$res" in
        OK*)
            read -r _ size hdr a b <<<"$res"
            sum=$(sha256sum "$o" | cut -d' ' -f1)
            echo "    .{ .len = $size, .hdr = $hdr, .a = $a, .b = $b, .sha256 = \"$sum\" }, // $what"
            ;;
        ERR*)
            read -r _ code <<<"$res"
            echo "    .{ .err = $code }, // $what"
            ;;
        *) echo "unexpected zfinal output: $res" >&2; exit 1 ;;
        esac
    done <"$R/dict-final-manifest.txt"
    echo "};"
} >"$out"
echo "wrote $out ($(grep -c '^    \.{' "$out") rows)"
