#!/usr/bin/env bash
# Regenerate modules/zstd/src/testdata/copy_goldens.zig: libzstd v1.5.7's
# buffer-less compression (ZSTD_compressBegin*, ZSTD_compressContinue,
# ZSTD_compressEnd) and ZSTD_copyCCtx, through tools/zcopy.c, over corpus
# inputs and dictionaries. Each row runs one zcopy call plan and records the
# three frames it makes (two copies on one reused context, then the original)
# as length and SHA-256, or the error a call ended with (in the module's
# names), and what ZSTD_copyCCtx says about the used original.
#
# Needs: git, a C compiler, sha256sum, zig. Writes only copy_goldens.zig; the
# libzstd checkout and the corpus files go to a disposable directory
# ($ZSTD_REF, default .zig-cache/zstd-ref under the repository root).
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
mod=$(dirname "$here")
root=$(cd "$mod/../.." && pwd)
R=${ZSTD_REF:-$root/.zig-cache/zstd-ref}
pin=f8745da6ff1ad1e7bab384bd1f9d742439278e99 # tag v1.5.7

if [ ! -d "$R/lib" ]; then
    git clone --quiet --depth 1 --branch v1.5.7 https://github.com/facebook/zstd.git "$R"
fi
got=$(git -C "$R" rev-parse HEAD)
if [ "$got" != "$pin" ]; then
    echo "libzstd checkout at $got, expected v1.5.7 ($pin)" >&2
    exit 1
fi
# shellcheck disable=SC2086
cc -O2 -DZSTD_DISABLE_ASM -I "$R/lib" -I "$R/lib/common" -o "$R/zcopy" "$here/zcopy.c" \
    "$R"/lib/common/*.c "$R"/lib/compress/*.c "$R"/lib/decompress/*.c

# the corpus inputs and dictionaries (the trained ones from testdata)
work="$R/corpus"
mkdir -p "$work"
(cd "$root" && zig run --dep corpus -Mroot=modules/zstd/tools/dump_corpus.zig \
    -Mcorpus=modules/zstd/src/testdata/corpus.zig -- "$work" "$R/manifest.txt" "$R/stream-manifest.txt" \
    "$R/param-manifest.txt" "$R/dict-manifest.txt" "$mod/src/testdata" "$R/mt-manifest.txt" \
    "$R/seq-manifest.txt")

# case dict mode level pledged copy-pledged chunks flags capacity cparams
# ("-": none / unknown / default; see zcopy.c; for mode F the last column
# is the parameter list)
plans="
words-16384 zd-words L 1 - - 1 0 - -
words-16384 zd-words L 3 - 16384 3 0 - -
csv-131073 raw-csv-30000 L 5 - - 2 0 - -
csv-131073 zd-csv L 9 - - 1 0 - -
words-16384 raw-words-8000 L 13 - - 3 0 - -
mix-106 zd-words L 16 - 20000 2 0 - -
mix-106 raw-words-8000 L 19 - - 1 0 - -
words-1000 - L -5 - 0 1 0 - -
empty zd-words L 3 - - 1 0 - -
random-5000 raw-words-8000 L 7 - - 2 0 - -
words-16384 zd-words A 5 16384 16384 3 1 - -
csv-131073 raw-csv-30000 A 12 131073 - 2 2 - -
words-16384 - A 3 - 16384 1 0 - -
mix-106 zd-words A 11 20000 20000 1 4 - -
csv-131073 zd-csv A 4 131073 100 2 0 - -
csv-131073 zd-csv A 6 131073 131074 1 0 - -
csv-600000 raw-csv-30000 A 22 - - 3 0 - 27,16,16,3,3,256,9
csv-600000 raw-csv-30000 A 19 600000 600000 2 1 - 27,17,16,4,4,64,7
csv-131073 raw-csv-30000 A 5 131073 131073 2 0 2000 -
csv-131073 raw-csv-30000 A 1 131073 131073 1 0 60000 -
words-16384 zd-words C 3 16384 16384 1 0 - -
csv-131073 raw-csv-30000 C 5 131073 131073 2 1 - -
csv-600000 raw-csv-30000 C 7 600000 600000 3 0 - -
mix-106 raw-words-8000 C 19 - - 1 0 - -
words-16384 zd-words C 1 16384 - 2 3 - -
words-16384 zd-words c 3 - - 1 0 - -
csv-131073 raw-csv-30000 c 9 - 131073 2 0 - -
mix-106 raw-words-8000 c 16 - - 1 0 - -
csv-131073 raw-words-8000 C 5 100000 131073 2 0 - -
csv-131073 raw-words-8000 C 16 100000 131073 1 0 - -
words-16384 raw-words-8000 L 9 - - 2 8 - -
words-16384 raw-words-8000 A 13 16384 16384 1 8 - -
mix-106 raw-words-8000 L 16 - - 1 8 - -
csv-131073 - F 3 - 131073 2 0 - maxBlockSize=4096
csv-131073 - F 5 - - 1 0 - useRowMatchFinder=2
mix-200000-0 - F 16 - - 1 0 - splitAfterSequences=2
mix-10086 - F 3 - 300000 1 0 - enableLongDistanceMatching=1,ldmHashLog=15,ldmMinMatch=6,ldmBucketSizeLog=6,ldmHashRateLog=2
"

errname() {
    case "$1" in
    "Operation not authorized at current processing stage") echo StageWrong ;;
    "Src size is incorrect") echo SrcSizeWrong ;;
    "Destination buffer is too small") echo DstSizeTooSmall ;;
    "Parameter is out of bound") echo ParameterOutOfBound ;;
    *) echo "unknown libzstd error: $1" >&2; exit 1 ;;
    esac
}

out="$mod/src/testdata/copy_goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-copy-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin), buffer-less compression and ZSTD_copyCCtx"
    echo "//! (tools/zcopy.c): per call plan, the frames of two copies made on one"
    echo "//! reused context and of the original, each a length and SHA-256 or the"
    echo "//! error a call failed with; \`copy_after\` is ZSTD_copyCCtx of the used original."
    echo ""
    echo "pub const Frame = struct { len: usize = 0, sha256: *const [64]u8 = &@splat('-'), err: []const u8 = \"\" };"
    echo "pub const Row = struct { case: []const u8, dict: ?[]const u8, mode: u8, level: i32, pledged: ?u64, copy_pledged: ?u64, chunks: u32, flags: u32, capacity: ?usize, cparams: ?[7]u32, params: ?[]const u8, copy1: Frame, copy2: Frame, orig: Frame, copy_after: []const u8 };"
    echo ""
    echo "pub const rows = [_]Row{"
    echo "$plans" | while read -r c d m l p cp ch fl cap cps; do
        [ -z "$c" ] && continue
        dict=$([ "$d" = - ] && echo - || echo "$work/dict-$d")
        args=("$work/$c" "$dict" "$m" "$l" "$p" "$cp" "$ch" "$fl" "$R/cp")
        [ "$cap" != - ] || [ "$cps" != - ] && args+=("$cap")
        [ "$cps" != - ] && args+=("$cps")
        rm -f "$R/cp.copy1" "$R/cp.copy2" "$R/cp.orig"
        msgs=$("$R/zcopy" "${args[@]}")
        frame() {
            local e
            e=$(echo "$msgs" | sed -n "s/^$1 error //p")
            if [ -n "$e" ]; then
                echo ".{ .err = \"$(errname "$e")\" }"
            else
                echo ".{ .len = $(stat -c %s "$R/cp.$1"), .sha256 = \"$(sha256sum "$R/cp.$1" | cut -d' ' -f1)\" }"
            fi
        }
        after=$(echo "$msgs" | sed -n 's/^copy-after //p')
        [ "$after" = ok ] || after=$(errname "$after")
        opt() { [ "$1" = - ] && echo null || echo "$1"; }
        dq=$([ "$d" = - ] && echo null || echo "\"$d\"")
        if [ "$m" = F ]; then
            cpq=null
            pq="\"$cps\""
        else
            cpq=$([ "$cps" = - ] && echo null || echo ".{ $cps }")
            pq=null
        fi
        echo "    .{ .case = \"$c\", .dict = $dq, .mode = '$m', .level = $l, .pledged = $(opt "$p"), .copy_pledged = $(opt "$cp"), .chunks = $ch, .flags = $fl, .capacity = $(opt "$cap"), .cparams = $cpq, .params = $pq,"
        echo "       .copy1 = $(frame copy1), .copy2 = $(frame copy2), .orig = $(frame orig), .copy_after = \"$after\" },"
    done
    echo "};"
} >"$out"
zig fmt "$out" >/dev/null
echo "wrote $out"
