#!/usr/bin/env bash
# Regenerate modules/zstd/src/testdata/goldens.zig (one-shot),
# stream_goldens.zig (streaming), param_goldens.zig (one-shot with advanced
# parameters) and cdict_goldens.zig (with dictionaries, and the trained
# dictionaries zd-*.zdict they use) from libzstd v1.5.7.
#
# Needs: git, make, a C compiler, sha256sum, zig. Writes only the goldens files;
# the libzstd checkout and the corpus files go to a disposable directory
# ($ZSTD_REF, default .zig-cache/zstd-ref under the repository root).
#
# The rows are exactly the (case, level, checksum) set `corpus.covered`
# admits, which `dump_corpus.zig` writes to a manifest; the loop below reads it.
# A case marked `ldm` is compressed with long-distance matching switched on
# by hand (zref's last argument).
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
mod=$(dirname "$here")
root=$(cd "$mod/../.." && pwd)
R=${ZSTD_REF:-$root/.zig-cache/zstd-ref}
pin=f8745da6ff1ad1e7bab384bd1f9d742439278e99 # tag v1.5.7

if [ ! -d "$R/lib" ]; then
    git clone --quiet --depth 1 --branch v1.5.7 https://github.com/facebook/zstd.git "$R"
fi
got=$(git -C "$R" rev-parse HEAD)
if [ "$got" != "$pin" ]; then
    echo "libzstd checkout at $got, expected v1.5.7 ($pin)" >&2
    exit 1
fi
make -C "$R/lib" -j"$(nproc)" libzstd.a >/dev/null
cc -O2 -I "$R/lib" -o "$R/zref" "$here/zref.c" "$R/lib/libzstd.a"
cc -O2 -I "$R/lib" -o "$R/zstream" "$here/zstream.c" "$R/lib/libzstd.a"
cc -O2 -I "$R/lib" -o "$R/zdtrain" "$here/zdtrain.c" "$R/lib/libzstd.a"
# The same compressor with index overflow corrected whenever it safely can
# (libzstd's fuzzing mode), for the corpus cases marked `ocf`: that is how
# inputs of kilobytes reach the correction that otherwise waits for 3500 MiB.
# (the decoder too: the oracles decode dictionary frames back)
cc -O2 -DZSTD_WINDOW_OVERFLOW_CORRECT_FREQUENTLY=1 -DZSTD_DISABLE_ASM -I "$R/lib" -I "$R/lib/common" \
    -o "$R/zref-ocf" "$here/zref.c" "$R"/lib/common/*.c "$R"/lib/compress/*.c "$R"/lib/decompress/*.c
cc -O2 -DZSTD_WINDOW_OVERFLOW_CORRECT_FREQUENTLY=1 -DZSTD_DISABLE_ASM -I "$R/lib" -I "$R/lib/common" \
    -o "$R/zstream-ocf" "$here/zstream.c" "$R"/lib/common/*.c "$R"/lib/compress/*.c "$R"/lib/decompress/*.c

work="$R/corpus"
mkdir -p "$work"
dump() {
    (cd "$root" && zig run --dep corpus -Mroot=modules/zstd/tools/dump_corpus.zig \
        -Mcorpus=modules/zstd/src/testdata/corpus.zig -- "$work" "$R/manifest.txt" "$R/stream-manifest.txt" \
        "$R/param-manifest.txt" "$R/dict-manifest.txt" "$mod/src/testdata")
}
dump
# The trained dictionaries (committed: the tests embed them), from the
# samples the first dump wrote; the second dump builds the dictionaries
# derived from them.
for set in $(sed -n 's/^ *\.{ \.name = "\([^"]*\)", \.capacity = \([0-9]*\),.*/\1:\2/p' "$mod/src/testdata/corpus.zig"); do
    name=${set%%:*}
    "$R/zdtrain" "$mod/src/testdata/$name.zdict" "${set##*:}" "$work/train-$name"/*
done
dump

out="$mod/src/testdata/goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin), ZSTD_compress2, one-shot."
    echo "//! Each row: compressed length and SHA-256 of the frame libzstd emits for"
    echo "//! corpus case \`case\` at \`level\`, with or without the content checksum."
    echo ""
    echo "pub const Golden = struct { case: []const u8, level: i32, checksum: bool, len: usize, sha256: *const [64]u8 };"
    echo ""
    echo "pub const rows = [_]Golden{"
    while read -r f l ck ldm wl ocf; do
        z=$([ "$ocf" = 1 ] && echo "$R/zref-ocf" || echo "$R/zref")
        "$z" "$l" "$ck" "$work/$f" "$R/out.zst" 0 "$ldm" "$wl"
        len=$(stat -c %s "$R/out.zst")
        sum=$(sha256sum "$R/out.zst" | cut -d' ' -f1)
        b=$([ "$ck" = 1 ] && echo true || echo false)
        echo "    .{ .case = \"$f\", .level = $l, .checksum = $b, .len = $len, .sha256 = \"$sum\" },"
    done <"$R/manifest.txt"
    echo "};"
} >"$out"
echo "wrote $out ($(grep -c '\.case' "$out") rows)"

out="$mod/src/testdata/stream_goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin), ZSTD_compressStream2 driven by tools/zstream.c."
    echo "//! Each row: length and SHA-256 of everything libzstd emits for corpus case"
    echo "//! \`case\` at \`level\`, with or without the checksum, following \`schedule\`."
    echo ""
    echo "pub const Golden = struct { case: []const u8, level: i32, checksum: bool, schedule: []const u8, len: usize, sha256: *const [64]u8 };"
    echo ""
    echo "pub const rows = [_]Golden{"
    while read -r f l ck sch; do
        # a schedule with the token x wants the frequent-correction build
        z=$(case ",$sch," in *,x,*) echo "$R/zstream-ocf" ;; *) echo "$R/zstream" ;; esac)
        "$z" "$l" "$ck" "$work/$f" "$R/out.zst" "$sch"
        len=$(stat -c %s "$R/out.zst")
        sum=$(sha256sum "$R/out.zst" | cut -d' ' -f1)
        b=$([ "$ck" = 1 ] && echo true || echo false)
        echo "    .{ .case = \"$f\", .level = $l, .checksum = $b, .schedule = \"$sch\", .len = $len, .sha256 = \"$sum\" },"
    done <"$R/stream-manifest.txt"
    echo "};"
} >"$out"
echo "wrote $out ($(grep -c '\.case' "$out") rows)"

out="$mod/src/testdata/param_goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin), ZSTD_compress2 with advanced parameters (tools/zref.c)."
    echo "//! Each row: compressed length and SHA-256 of the frame libzstd emits for"
    echo "//! corpus case \`case\` at \`level\` with \`params\` set, with or without the checksum."
    echo ""
    echo "pub const Golden = struct { case: []const u8, level: i32, checksum: bool, params: []const u8, len: usize, sha256: *const [64]u8 };"
    echo ""
    echo "pub const rows = [_]Golden{"
    while read -r f l ck prm; do
        "$R/zref" "$l" "$ck" "$work/$f" "$R/out.zst" 0 0 0 "$prm"
        len=$(stat -c %s "$R/out.zst")
        sum=$(sha256sum "$R/out.zst" | cut -d' ' -f1)
        b=$([ "$ck" = 1 ] && echo true || echo false)
        echo "    .{ .case = \"$f\", .level = $l, .checksum = $b, .params = \"$prm\", .len = $len, .sha256 = \"$sum\" },"
    done <"$R/param-manifest.txt"
    echo "};"
} >"$out"
echo "wrote $out ($(grep -c '\.case' "$out") rows)"

out="$mod/src/testdata/cdict_goldens.zig"
{
    echo "// SPDX-License-Identifier: MIT"
    echo "//! GENERATED by modules/zstd/tools/gen-goldens.sh -- do not edit."
    echo "//! libzstd v1.5.7 ($pin) with a dictionary: tools/zref.c (one-shot) or"
    echo "//! tools/zstream.c (a case with a schedule), each frame decoded back with"
    echo "//! the dictionary by libzstd. Each row: length and SHA-256 of the output"
    echo "//! for dictionary case \`case\` (\`corpus.dict_cases\`) at \`level\`."
    echo ""
    echo "pub const Golden = struct { case: []const u8, level: i32, checksum: bool, len: usize, sha256: *const [64]u8 };"
    echo ""
    echo "pub const rows = [_]Golden{"
    while read -r c d p t l ck prm sch ocf; do
        if [ "$sch" = - ]; then
            z=$([ "$ocf" = 1 ] && echo "$R/zref-ocf" || echo "$R/zref")
            "$z" "$l" "$ck" "$work/dict-in-$c" "$R/out.zst" 0 0 0 "$prm" "$p:$t:$work/dict-$d"
        else
            "$R/zstream" "$l" "$ck" "$work/dict-in-$c" "$R/out.zst" "$sch" "$p:$t:$work/dict-$d"
        fi
        len=$(stat -c %s "$R/out.zst")
        sum=$(sha256sum "$R/out.zst" | cut -d' ' -f1)
        b=$([ "$ck" = 1 ] && echo true || echo false)
        echo "    .{ .case = \"$c\", .level = $l, .checksum = $b, .len = $len, .sha256 = \"$sum\" },"
    done <"$R/dict-manifest.txt"
    echo "};"
} >"$out"
echo "wrote $out ($(grep -c '\.case' "$out") rows)"
