#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate src/local_kat.zig: local wall-clock time -> UTC vectors for
tz.resolveLocal, from Python's zoneinfo used as a black-box oracle.

Python must read the SAME tzdata release the committed table was generated
from, never the host's /usr/share/zoneinfo:

    scripts/gen/tz-gen/fetch-and-build.sh --check     # builds .zig-cache/tz-gen/<release>/zoneinfo
    python3 modules/tz/tools/gen_local_kat.py .zig-cache/tz-gen/2026a/zoneinfo > modules/tz/src/local_kat.zig

For every offset change of the listed zones in the listed years, five local
times are classified: the last second before the gap/fold, its first second,
its middle, its last second and the first second after it. Python's `fold`
gives the two candidate instants; a candidate is real when converting it
back shows the same wall-clock time.
"""
import os
import sys
import zoneinfo
from datetime import datetime, timedelta, timezone

ZONES = [
    "Europe/Prague",       # the common case, northern hemisphere
    "America/New_York",
    "Australia/Sydney",    # southern hemisphere: DST wraps the year
    "Australia/Lord_Howe", # 30-minute DST
    "America/St_Johns",    # half-hour standard offset
    "Europe/Dublin",       # "negative DST" in tzdata (winter is the DST period)
    "Pacific/Apia",        # skipped 2011-12-30 entirely (24 h gap), DST until 2021
    "Africa/Casablanca",   # Ramadan changes: many transitions a month apart
    "America/Santiago",
    "Antarctica/Troll",    # 2-hour DST
    "America/Sao_Paulo",   # DST abolished 2019
    "Europe/Moscow",       # permanent offset changes 2011 and 2014
]
YEARS = list(range(2008, 2013)) + list(range(2020, 2027)) + list(range(2036, 2042))
EPOCH = datetime(1970, 1, 1)


def off(z, u):
    return int(datetime.fromtimestamp(u, z).utcoffset().total_seconds())


def transitions(z, year):
    lo = int(datetime(year, 1, 1, tzinfo=timezone.utc).timestamp())
    hi = int(datetime(year + 1, 1, 1, tzinfo=timezone.utc).timestamp())
    step = 3 * 3600
    out = []
    u = lo
    o = off(z, u)
    while u < hi:
        v = min(u + step, hi)
        p = off(z, v)
        if p != o:
            a, b = u, v  # off(a) == o, off(b) == p: bisect to the first second of p
            while b - a > 1:
                m = (a + b) // 2
                if off(z, m) == o:
                    a = m
                else:
                    b = m
            out.append((b, o, off(z, b)))
            o = off(z, b)
        u = v
    return out


def classify(z, local):
    naive = EPOCH + timedelta(seconds=local)
    us = sorted({int(naive.replace(tzinfo=z, fold=f).timestamp()) for f in (0, 1)})
    shown = [datetime.fromtimestamp(u, z).replace(tzinfo=None) == naive for u in us]
    if len(us) == 1:
        assert shown[0], (z, local)
        return ("unique", us[0], us[0])
    if all(shown):
        return ("ambiguous", us[0], us[1])
    assert not any(shown), (z, local)
    return ("nonexistent", us[0], us[1])


def main():
    zoneinfo.reset_tzpath([os.path.abspath(sys.argv[1])])
    with open(sys.argv[1] + "/+VERSION") as f:
        release = f.read().strip()
    rows = []
    for zi, name in enumerate(ZONES):
        z = zoneinfo.ZoneInfo(name)
        for y in YEARS:
            for t, a, b in transitions(z, y):
                lo, hi = t + min(a, b), t + max(a, b)
                for local in sorted({lo - 1, lo, (lo + hi) // 2, hi - 1, hi}):
                    kind, e, l = classify(z, local)
                    rows.append((zi, local, kind, e, l))
    w = sys.stdout.write
    w("// SPDX-License-Identifier: MIT\n")
    w("// GENERATED by modules/tz/tools/gen_local_kat.py from Python zoneinfo over\n")
    w(f"// IANA tzdata {release} (the release tz_data.zig is pinned to). Do not edit.\n")
    w("//! Local wall-clock time -> UTC vectors: (zone, local, kind, earlier, later).\n\n")
    w("pub const Kind = enum { unique, ambiguous, nonexistent };\n")
    w("pub const Row = struct { zone: u8, local: i64, kind: Kind, earlier: i64, later: i64 };\n\n")
    w(f'pub const release = "{release}";\n\n')
    w("pub const zones = [_][]const u8{\n")
    for n in ZONES:
        w(f'    "{n}",\n')
    w("};\n\n")
    w("pub const rows = [_]Row{\n")
    for zi, local, kind, e, l in rows:
        w(f"    .{{ .zone = {zi}, .local = {local}, .kind = .{kind}, .earlier = {e}, .later = {l} }},\n")
    w("};\n")


main()
