#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate src/posix_kat.zig: UTC offset/DST vectors for tz.offsetAt from two
black-box oracles, never from this module.

  - zones: every zone of the committed table, 2037..2050 (the POSIX-footer era
    past the explicit transitions), from Python's zoneinfo -- which parses the
    TZif footer with its own implementation -- over the SAME tzdata release the
    table was generated from:

        scripts/gen/tz-gen/fetch-and-build.sh --check   # .zig-cache/tz-gen/<release>/zoneinfo
        python3 modules/tz/tools/gen_posix_kat.py .zig-cache/tz-gen/2026a/zoneinfo > modules/tz/src/posix_kat.zig

  - rules: POSIX TZ strings no IANA release ships (Jn and n day forms, rule
    times past 24 h or negative, offsets with minutes, rules that cross the UTC
    year), 2024..2030, asked of THREE implementations: glibc (TZ= + tzset, via
    Python's time module), Python's zoneinfo (a footer-only TZif) and Go's time
    package (`tools/go_posix`, the same TZif through LoadLocationFromTZData;
    needs `go` on PATH). A string at least two of them agree on is emitted with
    the majority answer, and the dissenter is named in `dissent`; a string all
    three answer differently is listed there too and not tested.

Each table lists, per zone or string, the offset in effect at the range start
and then every change: (instant, new offset, new DST flag).
"""
import io
import json
import os
import re
import struct
import subprocess
import sys
import time
import zoneinfo
from datetime import datetime, timezone

RULES = [
    # day forms
    "XXX3YYY,J60,J300",
    "XXX3YYY,J1,J365",
    "XXX3YYY,59,299",
    "XXX3YYY,0,365",
    "XXX3YYY,J59,J61",
    "XXX3YYY,58,60",
    "XXX3YYY,M2.5.0,M5.5.6",
    "XXX3YYY,M1.1.0,M12.5.6",
    # rule times
    "XXX3YYY,M3.2.0/26,M11.1.0/-1",
    "XXX3YYY,M3.2.0/167,M11.1.0/-167",
    "XXX3YYY,M3.2.0/1:30,M11.1.0/0:59:59",
    "XXX3YYY,M3.2.0/24:00:01,M11.1.0/23:59:59",
    "IST-2IDT,M3.4.4/26,M10.5.0",
    "<-02>2<-01>,M3.5.0/-1,M10.5.0/0",
    # offsets
    "<+0545>-5:45<+0645>,M3.5.0,M10.5.0",
    "<-0330>3:30<-0230>,M3.2.0,M11.1.0",
    "AAA3BBB4,M3.2.0,M11.1.0",
    "AAA-1BBB-0:30,M3.5.0,M10.5.0",
    "AAA-1BBB-3,M3.5.0,M10.5.0",
    "XXX-14YYY,M3.2.0,M11.1.0",
    "XXX12YYY,M3.2.0,M11.1.0",
    # southern hemisphere and the UTC year boundary
    "<+11>-11<+12>,M10.1.0,M4.1.0/3",
    "AEST-10AEDT,M10.1.0,M4.1.0/3",
    "XXX10YYY,M12.5.0/23,M3.2.0",
    "XXX-13YYY,M1.1.0/1,M10.1.0",
    "XXX-14YYY,J1/0,J100",
    "XXX11YYY,J365/23,J100",
    "XXX-12YYY,J1/1,J200",
    # all-year DST (RFC 9636 3.3.1 example)
    "EST5EDT,0/0,J365/25",
    # no DST
    "XXX3",
    "<+0545>-5:45",
]

RULE_YEARS = (2024, 2031)
ZONE_YEARS = (2037, 2051)
STEP = 3600


def ts(year):
    return int(datetime(year, 1, 1, tzinfo=timezone.utc).timestamp())


def changes(off, lo, hi):
    """The offset at lo, then every (instant, offset) where off() changes."""
    first = off(lo)
    out = []
    u, o = lo, first
    while u < hi:
        v = min(u + STEP, hi)
        p = off(v)
        if p != o:
            a, b = u, v
            while b - a > 1:
                m = (a + b) // 2
                if off(m) == o:
                    a = m
                else:
                    b = m
            out.append((b, off(b)))
            # A change and its reversal inside one step: rescan from b.
            u, o = b, off(b)
            continue
        u, o = v, p
    return first, out


def zone_off(z):
    def f(u):
        d = datetime.fromtimestamp(u, z)
        return (int(d.utcoffset().total_seconds()), d.dst().total_seconds() != 0)
    return f


def footer_only_tzif(posix):
    def block():
        hdr = b"TZif2" + b"\0" * 15 + struct.pack(">6l", 0, 0, 0, 0, 1, 4)
        return hdr + struct.pack(">lBB", 0, 0, 0) + b"UTC\0"
    return block() + block() + b"\n" + posix.encode() + b"\n"


def glibc_off(posix):
    def f(u):
        lt = time.localtime(u)
        return (lt.tm_gmtoff, lt.tm_isdst > 0)
    os.environ["TZ"] = posix
    time.tzset()
    return f


def row(i, u, o):
    return f"    .{{ .i = {i}, .ts = {u}, .off = {o[0]}, .dst = {'true' if o[1] else 'false'} }},"


def main():
    zdir = sys.argv[1]
    table = open(os.path.join(os.path.dirname(__file__), "..", "src", "tz_data.zig")).read()
    names = re.findall(r'\.name = "([^"]+)"', table)
    release = re.search(r"IANA tzdata (\w+)", table).group(1)

    out = []
    out.append("// SPDX-License-Identifier: MIT")
    out.append(f"// GENERATED by modules/tz/tools/gen_posix_kat.py from Python zoneinfo over IANA tzdata {release}")
    out.append(f"// and glibc ({os.confstr('CS_GNU_LIBC_VERSION')}). Do not edit; see the script's docstring.")
    out.append("//! UTC offset vectors for tz.offsetAt: per zone or POSIX string, the offset at the range")
    out.append("//! start (a row at `start`), then every change.")
    out.append("")
    out.append("pub const Row = struct { i: u16, ts: i64, off: i32, dst: bool };")
    out.append(f'pub const release = "{release}";')
    out.append(f"pub const zone_range = [2]i64{{ {ts(ZONE_YEARS[0])}, {ts(ZONE_YEARS[1])} }};")
    out.append(f"pub const rule_range = [2]i64{{ {ts(RULE_YEARS[0])}, {ts(RULE_YEARS[1])} }};")
    out.append("")

    out.append("pub const zone_names = [_][]const u8{")
    out += [f'    "{n}",' for n in names]
    out.append("};")
    out.append("")
    out.append("/// Python zoneinfo, every zone, the footer era.")
    out.append("pub const zone_rows = [_]Row{")
    lo, hi = ts(ZONE_YEARS[0]), ts(ZONE_YEARS[1])
    for i, n in enumerate(names):
        with open(os.path.join(zdir, n), "rb") as fh:
            z = zoneinfo.ZoneInfo.from_file(fh, key=n)
        first, ch = changes(zone_off(z), lo, hi)
        out.append(row(i, lo, first))
        out += [row(i, u, o) for u, o in ch]
    out.append("};")
    out.append("")

    agreed, dissent = [], []
    lo, hi = ts(RULE_YEARS[0]), ts(RULE_YEARS[1])
    here = os.path.dirname(os.path.abspath(__file__))
    go_out = subprocess.run(["go", "run", ".", "-lo", str(lo), "-hi", str(hi)], cwd=os.path.join(here, "go_posix"),
                            input="\n".join(RULES) + "\n", capture_output=True, text=True, check=True).stdout
    go = {}
    for line in go_out.splitlines():
        j = json.loads(line)
        go[j["s"]] = ((j["first"]["off"], j["first"]["dst"]), [(c[0], (c[1], c[2])) for c in (j["changes"] or [])])
    for s in RULES:
        z = zoneinfo.ZoneInfo.from_file(io.BytesIO(footer_only_tzif(s)), key=s)
        votes = {
            "glibc": changes(glibc_off(s), lo, hi),
            "python": changes(zone_off(z), lo, hi),
            "go": go[s],
        }
        names = list(votes)
        winner = next((votes[a] for a in names for b in names if a < b and votes[a] == votes[b]), None)
        if winner is None:
            dissent.append((s, "all three differ; not tested"))
            continue
        agreed.append((s, winner))
        odd = [n for n in names if votes[n] != winner]
        if odd:
            dissent.append((s, f"{odd[0]} differs from the other two"))
    out.append("/// POSIX strings glibc and Python zoneinfo agree on.")
    out.append("pub const rule_strings = [_][]const u8{")
    out += [f'    "{s}",' for s, _ in agreed]
    out.append("};")
    out.append("")
    out.append("pub const rule_rows = [_]Row{")
    for i, (s, (first, ch)) in enumerate(agreed):
        out.append(row(i, lo, first))
        out += [row(i, u, o) for u, o in ch]
    out.append("};")
    out.append("")
    out.append("/// Strings one oracle answers differently from the other two (the majority is in")
    out.append("/// `rule_rows`), or all three do (not tested).")
    out.append("pub const dissent = [_][2][]const u8{")
    for s, why in dissent:
        out.append(f'    .{{ "{s}", "{why}" }},')
    out.append("};")
    print("\n".join(out))


main()
