// SPDX-License-Identifier: MIT

// Differential oracle for modules/zipstream: Go's standard library
// archive/zip as an independent implementation. The read-area inputs are
// OURS -- archives built record by record in read.go, plus archives Go's own
// Writer produced for entry tables in read.go -- and Go only answers them.
// The write area reads archives THIS module's ArchiveWriter produced
// (tools/interop.zig writes them into scratch) and records what Go makes of
// them. The answers are written out as a Zig file that the module's own
// tests replay hermetically -- no Go at test time.
//
//	zig build interop-zipstream -- --regen   (writes our archives, then runs this)
//	cd modules/zipstream/tools/go_oracle && go run . -write DIR -out ../../src/go_oracle_vectors.zig
//	go run . -dump DIR                        (every read case as DIR/<id>.zip, to ask unzip)
//
// Stdlib only, no network.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"runtime"
)

func main() {
	out := flag.String("out", "", "write the Zig vectors file here (default stdout)")
	writeDir := flag.String("write", "", "directory holding this module's ArchiveWriter output (<id>.zip)")
	dump := flag.String("dump", "", "write every read-area case to <dir>/<id>.zip and exit")
	flag.Parse()
	if *dump != "" {
		for _, c := range append(goWritten(), crafted()...) {
			if err := os.WriteFile(*dump+"/"+c.id+".zip", c.data, 0o644); err != nil {
				fmt.Fprintln(os.Stderr, err)
				os.Exit(1)
			}
		}
		return
	}
	if *writeDir == "" {
		fmt.Fprintln(os.Stderr, "-write <dir> is required (see the header of main.go)")
		os.Exit(2)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// SPDX-License-Identifier: MIT\n")
	fmt.Fprintf(&b, "// GENERATED by modules/zipstream/tools/go_oracle (%s) -- do not hand-edit.\n", runtime.Version())
	fmt.Fprintf(&b, "//! Go archive/zip verdicts on this module's own case tables, replayed\n")
	fmt.Fprintf(&b, "//! by `go_oracle.zig`. Regenerate with the command in tools/go_oracle/main.go.\n\n")
	fmt.Fprintf(&b, "pub const go_version = %s;\n\n", zigStr(runtime.Version()))
	emitTypes(&b)
	emitCases(&b, "go_written", "/// Archives Go's own Writer produced for entry tables in read.go.", goWritten())
	emitCases(&b, "crafted", "/// Archives built record by record in read.go.", crafted())
	if err := emitWrite(&b, *writeDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	b.Truncate(b.Len() - 1)

	if *out == "" {
		os.Stdout.Write(b.Bytes())
		return
	}
	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func emitTypes(b *bytes.Buffer) {
	b.WriteString(`/// One member of Go's zip.Reader.File list (central-directory order).
pub const Entry = struct {
    name: []const u8,
    method: u16,
    crc32: u32,
    compressed_size: u64,
    uncompressed_size: u64,
    /// FileHeader.Modified as Unix seconds; null when Go left it zero.
    mtime: ?i64,
    /// Permission bits incl. setuid/setgid/sticky, only for an entry made on
    /// a Unix host with non-zero attributes (what this module reports).
    mode: ?u16,
    /// FileHeader.NonUTF8: the UTF-8 flag (bit 11) is clear and the name is
    /// not plain ASCII... as Go decides it.
    non_utf8: bool,
    /// The content Go's File.Open yielded, or the error it stopped with.
    content: []const u8,
    open_err: ?[]const u8,
};

/// An archive as runs of non-zero bytes: ` + "`len`" + ` bytes, zero except at each run.
pub const Run = struct { off: u32, bytes: []const u8 };
pub const Archive = struct { len: u32, runs: []const Run };

pub const Case = struct {
    id: []const u8,
    archive: Archive,
    /// zip.NewReader refused the archive (the text is Go's); entries empty.
    err: ?[]const u8,
    entries: []const Entry,
};

`)
}
