#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for `src/testdata/libubox_oracle.zig`: OpenWRT libubox's own blobmsg
JSON codec as a black box, replayed by `src/libubox_oracle_test.zig`.

    B=.zig-cache/blobmsg-oracle; mkdir -p $B && cd $B
    git clone --depth 1 https://git.openwrt.org/project/libubox.git libubox
    git clone --depth 1 https://github.com/json-c/json-c.git json-c
    cmake -S json-c -B json-c-build -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DDISABLE_WERROR=ON
    cmake --build json-c-build
    gcc -O1 -std=gnu99 -Ilibubox -Ijson-c -Ijson-c-build -o oracle_blobmsg \\
        ../../modules/blobmsg/tools/oracle_blobmsg.c libubox/blob.c libubox/blobmsg.c \\
        libubox/blobmsg_json.c json-c-build/libjson-c.a -lm
    cd ../.. && python3 modules/blobmsg/tools/libubox_oracle.py | zig fmt --stdin > modules/blobmsg/src/testdata/libubox_oracle.zig

For each JSON object below: the blobmsg children libubox's
`blobmsg_add_json_from_string` builds from it (what `ubus call` sends), and
what `blobmsg_format_json` reads back out of those bytes (what `ubus` prints).
libubox (ISC/LGPL) and json-c (MIT) are run, never read or copied; their
sources live only in the droppable cache.
"""
import os
import subprocess
import sys

ORACLE = os.path.join(os.path.dirname(__file__), "../../../.zig-cache/blobmsg-oracle/oracle_blobmsg")
ORACLE = os.environ.get("ORACLE", ORACLE)

CASES = [
    '{}',
    '{"a":1}',
    '{"zero":0,"neg":-1,"i32max":2147483647,"i32min":-2147483648}',
    '{"over":2147483648,"under":-2147483649,"big":9007199254740993,"i64max":9223372036854775807,"i64min":-9223372036854775808}',
    '{"t":true,"f":false}',
    '{"s":"x","empty":"","esc":"a\\"b\\\\c\\n\\t","uni":"\\u00e9\\u4e2d\\ud83d\\ude00","ctl":"\\u0001"}',
    '{"d":1.5,"neg":-0.25,"tiny":1e-300,"huge":1e300,"third":0.3333333333333333,"whole":2.0}',
    '{"arr":[1,"two",true,1.5,[3],{"k":"v"}],"empty_arr":[],"empty_obj":{}}',
    '{"nested":{"a":{"b":{"c":{"d":[[[[1]]]]}}}}}',
    '{"":"empty key","key with spaces":1,"k\\u00e9y":2}',
    '{"n":null}',
    '{"arr_of_null":[null,1]}',
    '{"dup":1,"dup":2}',
    '{"long":"' + "x" * 300 + '"}',
    '{"name3":"abc","name4":"abcd","name5":"abcde"}',
]


def run(mode, lines):
    r = subprocess.run([ORACLE, mode], input="\n".join(lines) + "\n", capture_output=True, text=True, check=True)
    out = r.stdout.split("\n")[:-1]
    assert len(out) == len(lines), (mode, len(out), len(lines))
    return out


def z(s):
    out = '"'
    for ch in s:
        o = ord(ch)
        if ch == '"':
            out += '\\"'
        elif ch == "\\":
            out += "\\\\"
        elif ch == "\n":
            out += "\\n"
        elif 0x20 <= o < 0x7F:
            out += ch
        else:
            out += "".join(f"\\x{b:02x}" for b in ch.encode())
    return out + '"'


def main():
    enc = run("enc", CASES)
    dec = run("dec", [h if h != "ERR" else "" for h in enc])
    o = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by modules/blobmsg/tools/libubox_oracle.py: OpenWRT libubox's blobmsg JSON codec",
        "// (blobmsg_add_json_from_string / blobmsg_format_json) on these objects. Replayed by",
        "// src/libubox_oracle_test.zig. Do not edit by hand.",
        "",
        "/// `bytes` is null where libubox refused the JSON.",
        "pub const Case = struct { json: []const u8, bytes: ?[]const u8, formatted: []const u8 };",
        "",
        "pub const cases = [_]Case{",
    ]
    for js, h, f in zip(CASES, enc, dec):
        b = "null" if h == "ERR" else z(h)
        o.append(f"    .{{ .json = {z(js)}, .bytes = {b}, .formatted = {z(f)} }},")
    o.append("};")
    sys.stdout.write("\n".join(o) + "\n")


if __name__ == "__main__":
    main()
