#!/usr/bin/env Rscript
# SPDX-License-Identifier: MIT
#
# Recipe for `src/testdata/cf_vectors.zig`: the Cornish-Fisher VaR/CVaR of the
# five seeded series in tools/oracle.py, from R PerformanceAnalytics (the
# reference implementation of "modified" VaR), replayed by src/oracle_test.zig.
#
# R is a ONE-SHOT tool here (user, 2026-10-07): installed for one run, then
# removed; the committed vectors are what every lane checks. One way, no root:
#
#   R1=~/.cache/zig-libs-r-oneshot   # micromamba from micro.mamba.pm, then
#   micromamba create -p $R1/env -c conda-forge r-base r-performanceanalytics
#   V=~/.local/share/zig-libs/oracle-venvs/finstats/bin/python
#   $V modules/finstats/tools/oracle.py --series-csv > /tmp/series.csv
#   $R1/env/bin/Rscript modules/finstats/tools/cf_oracle.R /tmp/series.csv \
#     | zig fmt --stdin > modules/finstats/src/testdata/cf_vectors.zig
#
# What answers for what (black box; no PerformanceAnalytics source read):
#   var  -- VaR(r, p = conf, method = "modified"), the Cornish-Fisher quantile
#           with sample sd and moment skewness / excess kurtosis — this module's
#           `cornishFisherVaR` convention;
#   cvar -- -(1/alpha) * integrate(q, 0, alpha), q(p) the same PerformanceAnalytics
#           modified-VaR quantile at level p: the tail mean of the CF quantile,
#           which is what `cornishFisherCVaR` defines. NOT ES(method = "modified"):
#           that is Boudt, Peterson & Croux's Edgeworth expansion, a different
#           estimator; its value is emitted as `pa_es` for the record and is not
#           asserted against.
suppressMessages(library(PerformanceAnalytics))
args <- commandArgs(trailingOnly = TRUE)
d <- read.csv(args[1], header = FALSE, col.names = c("name", "r"))
f <- function(x) sprintf("%.17g", x)
# PerformanceAnalytics' modified VaR as a positive loss at confidence `conf`.
pav <- function(r, conf) as.numeric(VaR(r, p = conf, method = "modified", invert = FALSE))
cat("// SPDX-License-Identifier: MIT\n")
cat("// Generated by modules/finstats/tools/cf_oracle.R from R", as.character(getRversion()),
    "and PerformanceAnalytics", as.character(packageVersion("PerformanceAnalytics")), "\n")
cat("// over tools/oracle.py's seeded series. Replayed by src/oracle_test.zig. Do not edit by hand.\n\n")
cat("/// `sd` is the POPULATION standard deviation: PerformanceAnalytics' modified VaR\n")
cat("/// uses it (measured: its quantile is the CF formula with sqrt(m2), 2.0e-3 off with\n")
cat("/// the sample sd at n = 250). `cornishFisherVaR` takes sd as a parameter, so the\n")
cat("/// replay passes this one; `parametricRisk`'s documented choice is the sample sd.\n")
cat("pub const Cf = struct { series: []const u8, conf: f64, mean: f64, sd: f64, skew: f64, kurt: f64, var_: f64, cvar: f64, cvar_p: f64, pa_es: f64 };\n")
cat("pub const cases = [_]Cf{\n")
for (nm in unique(d$name)) {
  r <- d$r[d$name == nm]
  m <- mean(r)
  sdp <- sqrt(mean((r - m)^2))
  s <- as.numeric(skewness(r, method = "moment"))
  k <- as.numeric(kurtosis(r, method = "excess"))
  for (conf in c(0.95, 0.99)) {
    alpha <- 1 - conf
    v <- suppressWarnings(pav(r, conf))
    # Tail mean of the PA quantile over p in (0, alpha], by R's adaptive
    # quadrature, TWICE: in z (p = pnorm(z), dp = dnorm(z) dz — smooth) and
    # in p (steep as p -> 0). R's own error estimate proved unreliable here
    # (7e-8 reported where the two agree to 1e-11), so the two answers'
    # disagreement is the uncertainty the replay checks. Lower bounds: z = -8
    # (PA takes the level as 1 - p, and below about -8.3 `1 - pnorm(z)` rounds
    # to 1, an infinite quantile; the area beyond is ~1e-14) and p = 1e-15.
    iz <- integrate(function(zs) sapply(zs, function(z) suppressWarnings(pav(r, 1 - pnorm(z))) * dnorm(z)),
                    -8, qnorm(alpha), rel.tol = 1e-12, subdivisions = 2000L, stop.on.error = FALSE)
    ip <- integrate(function(ps) sapply(ps, function(p) suppressWarnings(pav(r, 1 - p))),
                    1e-15, alpha, rel.tol = 1e-12, subdivisions = 2000L, stop.on.error = FALSE)
    cv <- iz$value / alpha
    cv_p <- ip$value / alpha
    es <- suppressWarnings(as.numeric(ES(r, p = conf, method = "modified", invert = FALSE)))
    cat(sprintf('    .{ .series = "%s", .conf = %s, .mean = %s, .sd = %s, .skew = %s, .kurt = %s, .var_ = %s, .cvar = %s, .cvar_p = %s, .pa_es = %s },\n',
                nm, conf, f(m), f(sdp), f(s), f(k), f(v), f(cv), f(cv_p), f(es)))
  }
}
cat("};\n")
