#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for `src/testdata/oracle_vectors.zig`: reference values from foreign
implementations, over seeded synthetic inputs, replayed by
`src/oracle_test.zig`.

    V=~/.local/share/zig-libs/oracle-venvs/finstats
    python3 -m venv $V && $V/bin/pip install pyxirr scipy numpy pandas empyrical-reloaded
    $V/bin/python modules/finstats/tools/oracle.py | zig fmt --stdin > modules/finstats/src/testdata/oracle_vectors.zig

Every expected number comes from a library this module did not write, used as
a black box (none of their source is read or copied):

  - xirr / xirrPrecise  -- pyxirr `xirr` with `DayCount.ACT_365_25` (this
    module's day count), on the cash flows `opening` describes;
  - skewness / excessKurtosis -- `scipy.stats.skew` / `kurtosis` (population,
    `bias=True`, Fisher);
  - invNormCdf / normalPdf -- `scipy.stats.norm.ppf` / `pdf`;
  - gaussianVaR / gaussianCVaR -- `norm.ppf`, and the tail mean by numerical
    integration (`norm.expect(..., conditional=True)`), not the closed form;
  - quantile -- `numpy.quantile(method="linear")`;
  - riskMetrics ann_vol / downside / var95 / cvar95 / mdd -- empyrical-reloaded
    `annual_volatility`, `downside_risk`, `value_at_risk`,
    `conditional_value_at_risk`, `max_drawdown` (daily, 252 periods);
  - omegaRatio -- empyrical `omega_ratio(annualization=1)`;
  - betaAlpha beta / r2 -- `scipy.stats.linregress` slope and rvalue^2;
  - rollingMean / rollingVolatility -- pandas `rolling(w).mean()` / `.std()`.

Not here, because no foreign implementation was found to anchor them on:
twrDaily (Modified Dietz), brinsonAttribution, the Cornish-Fisher pair.
"""
import datetime as dt
import sys

import empyrical as ep
import numpy as np
import pandas as pd
import pyxirr
from scipy import stats

rng = np.random.default_rng(20261006)
N = 250
WINDOW = 20


def series():
    t = rng.standard_t(4, N) * 0.008 + 0.0004
    crash = rng.normal(0.0006, 0.006, N)
    crash[rng.choice(N, 6, replace=False)] -= rng.uniform(0.03, 0.08, 6)  # negative skew
    calm = rng.normal(0.0002, 0.004, N)
    bench = rng.normal(0.0003, 0.009, N)
    port = 1.2 * bench + rng.normal(0.0001, 0.004, N)
    return {"fat_tails": t, "crashes": crash, "calm": calm, "bench": bench, "port": port}


def f(x):
    return repr(float(x))


def floats(xs):
    return "&.{" + ", ".join(f(x) for x in xs) + "}"


def main():
    S = series()
    o = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by modules/finstats/tools/oracle.py: reference values from pyxirr, scipy,",
        "// numpy, pandas and empyrical-reloaded over seeded inputs. Replayed by src/oracle_test.zig.",
        "// Do not edit by hand.",
        "",
        f"pub const window = {WINDOW};",
        "pub const Pair = struct { f64, f64 };",
        "pub const Gauss = struct { mean: f64, sd: f64, conf: f64, var_: f64, cvar: f64 };",
        "pub const Series = struct { name: []const u8, values: []const f64, skew: f64, kurt: f64, quantiles: []const Pair,"
        " ann_vol: f64, downside: f64, var95: f64, cvar95: f64, mdd: f64, omega: []const Pair, gauss: []const Gauss,"
        " roll_mean: []const f64, roll_std: []const f64 };",
        "",
        "pub const series = [_]Series{",
    ]
    for name, r in S.items():
        qs = [0.0, 0.01, 0.05, 0.25, 0.5, 0.75, 0.95, 0.99, 1.0]
        quant = ", ".join(f".{{ {q}, {f(np.quantile(r, q, method='linear'))} }}" for q in qs)
        om = ", ".join(f".{{ {t}, {f(ep.omega_ratio(r, required_return=t, annualization=1))} }}" for t in (0.0, 0.001, -0.002))
        g = []
        mu, sd = float(np.mean(r)), float(np.std(r, ddof=1))
        for c in (0.95, 0.99):
            q = stats.norm.ppf(1 - c, mu, sd)
            tail = stats.norm.expect(lambda x: x, loc=mu, scale=sd, ub=q, conditional=True)
            g.append(f".{{ .mean = {f(mu)}, .sd = {f(sd)}, .conf = {c}, .var_ = {f(-q)}, .cvar = {f(-tail)} }}")
        roll = pd.Series(r).rolling(WINDOW)
        o.append(
            f'    .{{ .name = "{name}", .values = {floats(r)}, .skew = {f(stats.skew(r, bias=True))},'
            f" .kurt = {f(stats.kurtosis(r, fisher=True, bias=True))}, .quantiles = &.{{{quant}}},"
            f" .ann_vol = {f(ep.annual_volatility(r))}, .downside = {f(ep.downside_risk(r, required_return=0))},"
            f" .var95 = {f(-ep.value_at_risk(r, cutoff=0.05))}, .cvar95 = {f(-ep.conditional_value_at_risk(r, cutoff=0.05))},"
            f" .mdd = {f(ep.max_drawdown(r))}, .omega = &.{{{om}}}, .gauss = &.{{{', '.join(g)}}},"
            f" .roll_mean = {floats(roll.mean().dropna())}, .roll_std = {floats(roll.std().dropna())} }},"
        )
    o.append("};")

    lr = stats.linregress(S["bench"], S["port"])
    o.append("")
    o.append(f"/// `port` regressed on `bench` (scipy.stats.linregress).")
    o.append(f"pub const beta = {f(lr.slope)};")
    o.append(f"pub const r2 = {f(lr.rvalue ** 2)};")

    ps = [1e-12, 1e-6, 0.001, 0.02, 0.02425, 0.05, 0.3, 0.5, 0.7, 0.95, 0.97575, 0.999, 1 - 1e-9]
    o.append("")
    o.append("/// p -> scipy.stats.norm.ppf(p)")
    o.append("pub const ppf = [_]Pair{" + ", ".join(f".{{ {p!r}, {f(stats.norm.ppf(p))} }}" for p in ps) + "};")
    zs = [-6.0, -2.5, -1.0, 0.0, 0.3, 1.6448536269514722, 4.0]
    o.append("/// z -> scipy.stats.norm.pdf(z)")
    o.append("pub const pdf = [_]Pair{" + ", ".join(f".{{ {z!r}, {f(stats.norm.pdf(z))} }}" for z in zs) + "};")

    # Cash-flow schedules: rows of (date, flow, value). `flow` is money put in
    # (+) or taken out (-); `value` the position after it.
    o.append("")
    o.append("pub const Row = struct { date: []const u8, flow: f64, value: f64 };")
    o.append("pub const Opening = enum { none, value_includes_flow };")
    o.append("pub const Schedule = struct { rows: []const Row, opening: Opening, xirr: f64 };")
    o.append("pub const schedules = [_]Schedule{")
    for k in range(10):
        start = dt.date(2019, 1, 1) + dt.timedelta(days=int(rng.integers(0, 900)))
        n = int(rng.integers(3, 14))
        days = sorted(rng.choice(np.arange(1, 365 * int(rng.integers(1, 6))), n - 1, replace=False))
        dates = [start] + [start + dt.timedelta(days=int(d)) for d in days]
        rate = float(rng.uniform(-0.35, 0.6))
        flows = [float(rng.uniform(1000, 50000))] + [float(rng.choice([0.0, rng.uniform(-3000, 8000)])) for _ in dates[1:]]
        # Values grow at `rate` between rows, noisily, plus the flow.
        values, v = [], 0.0
        for i, d in enumerate(dates):
            if i:
                v *= (1 + rate) ** ((d - dates[i - 1]).days / 365.25) * float(rng.uniform(0.97, 1.03))
            v += flows[i]
            values.append(v)
        opening = "none" if k % 3 else "value_includes_flow"
        if opening == "none":
            cf = [(d, -fl) for d, fl in zip(dates, flows) if abs(fl) > 1e-6]
        else:  # seed = -value[0] on day 0; row 0's flow is inside it
            cf = [(dates[0], -values[0])] + [(d, -fl) for d, fl in zip(dates[1:], flows[1:]) if abs(fl) > 1e-6]
        cf.append((dates[-1], values[-1]))
        x = pyxirr.xirr([c[0] for c in cf], [c[1] for c in cf], day_count=pyxirr.DayCount.ACT_365_25)
        rows = ", ".join(f'.{{ .date = "{d.isoformat()}", .flow = {f(fl)}, .value = {f(v)} }}' for d, fl, v in zip(dates, flows, values))
        o.append(f"    .{{ .rows = &.{{{rows}}}, .opening = .{opening}, .xirr = {f(x)} }},")
    o.append("};")
    sys.stdout.write("\n".join(o) + "\n")


if __name__ == "__main__":
    main()
