#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""gen_kat_vectors — regenerate `src/kat_vectors.zig` from the text of
draft-irtf-cfrg-bbs-signatures-12 (BLS12-381-SHA-256 vectors: §8.2, §8.4,
Appendix D.2).

The recipe that produced the committed KATs (CONVENTIONS §9). Usage:

    curl -fsSL -o draft-12.txt \
        https://www.ietf.org/archive/id/draft-irtf-cfrg-bbs-signatures-12.txt
    python3 -I modules/bbs/tools/gen_kat_vectors.py draft-12.txt > modules/bbs/src/kat_vectors.zig
    zig fmt modules/bbs/src/kat_vectors.zig

Values are copied verbatim (hex, lowercased); nothing is computed here.
"""
import re
import sys


def sections(path):
    lines = open(path, encoding="utf-8").read().split("\n")
    keep = [l for l in lines
            if not re.match(r"^(Looker, et al\.|Internet-Draft  )", l) and not l.startswith("\x0c")]
    txt = "\n".join(keep)
    parts = re.split(r"\n((?:8|D)\.[0-9.]+)  ([^\n]+)\n", txt)
    out = {}
    for k in range(1, len(parts), 3):
        num, title, body = parts[k].rstrip("."), parts[k + 1], parts[k + 2]
        vals = {}
        order = []
        for m in re.finditer(r"([A-Za-z_~^0-9]+)\s*=\s*(?:h|0x)'([0-9a-fA-F\s]*)'", body):
            vals[m.group(1)] = re.sub(r"\s+", "", m.group(2)).lower()
            order.append(m.group(1))
        idx = re.search(r"revealed_indexes = \[([0-9 ,]*)\]", body)
        valid = re.search(r"(?m)^valid: (true|false)", body)
        out[num] = {
            "title": title.strip(),
            "vals": vals,
            "order": order,
            "revealed": [int(x) for x in idx.group(1).split(",") if x.strip()] if idx else None,
            "valid": (valid.group(1) == "true") if valid else True,
        }
    return out


def zstr(s):
    return '"' + s + '"'


def msgs_of(sec):
    return [sec["vals"][k] for k in sec["order"] if re.fullmatch(r"m_\d+", k)]


def main():
    s = sections(sys.argv[1])
    w = sys.stdout.write
    w("// SPDX-License-Identifier: MIT\n")
    w("//! GENERATED by `tools/gen_kat_vectors.py` from the text of\n")
    w("//! draft-irtf-cfrg-bbs-signatures-12 (BLS12-381-SHA-256: §8.2, §8.4,\n")
    w("//! Appendix D.2) — do not edit by hand. Hex as published, lowercased.\n")
    w("//! The draft's code components are under the Revised BSD License (IETF\n")
    w("//! Trust Legal Provisions); see `../NOTICE`.\n\n")
    w('pub const draft = "draft-irtf-cfrg-bbs-signatures-12";\n\n')

    kp = s["8.4.1"]["vals"]
    w("pub const keypair = struct {\n")
    for k in ("key_material", "key_info", "key_dst"):
        w(f"    pub const {k} = {zstr(kp[k])};\n")
    w(f"    pub const sk = {zstr(kp['SK'])};\n")
    w(f"    pub const pk = {zstr(kp['PK'])};\n")
    w("};\n\n")

    w("/// §8.2 — the ten messages every multi-message fixture signs.\n")
    w("pub const messages = [_][]const u8{\n")
    for m in msgs_of(s["8.2"]):
        w(f"    {zstr(m)},\n")
    w("};\n\n")

    ms = s["8.4.2"]
    w("pub const map_messages_to_scalar = struct {\n")
    w(f"    pub const dst = {zstr(ms['vals']['dst'])};\n")
    w("    pub const scalars = [_][]const u8{\n")
    for k in ms["order"]:
        if k.startswith("msg_scalar_"):
            w(f"        {zstr(ms['vals'][k])},\n")
    w("    };\n};\n\n")

    g = s["8.4.3"]
    w("pub const generators = struct {\n")
    w(f"    pub const q1 = {zstr(g['vals']['Q_1'])};\n")
    w("    pub const msg_generators = [_][]const u8{\n")
    for k in g["order"]:
        if k.startswith("H_"):
            w(f"        {zstr(g['vals'][k])},\n")
    w("    };\n};\n\n")

    r = s["8.4.5"]
    w("/// §8.1 / §8.4.5 — `seeded_random_scalars(SEED, api_id ||\n")
    w("/// \"MOCK_RANDOM_SCALARS_DST_\", 10)`.\n")
    w("pub const mocked_rng = struct {\n")
    w(f"    pub const seed = {zstr(r['vals']['SEED'])};\n")
    w("    pub const scalars = [_][]const u8{\n")
    for k in r["order"]:
        if k.startswith("random_scalar_"):
            w(f"        {zstr(r['vals'][k])},\n")
    w("    };\n};\n\n")

    h = s["D.2.3"]["vals"]
    w("/// Appendix D.2.3.\n")
    w("pub const h2s = struct {\n")
    for k in ("msg", "dst", "scalar"):
        w(f"    pub const {k} = {zstr(h[k])};\n")
    w("};\n\n")

    w("pub const SignatureCase = struct {\n")
    w("    name: []const u8,\n    messages: []const []const u8,\n    sk: []const u8,\n    pk: []const u8,\n")
    w("    header: []const u8,\n    signature: []const u8,\n    valid: bool,\n};\n\n")
    w("pub const signature_cases = [_]SignatureCase{\n")
    for num in ("8.4.4.1", "8.4.4.2", "D.2.1.1", "D.2.1.2", "D.2.1.3", "D.2.1.4", "D.2.1.5", "D.2.1.6", "D.2.1.7"):
        c = s[num]
        v = c["vals"]
        w("    .{\n")
        w(f"        .name = {zstr(num + ' ' + c['title'])},\n")
        w("        .messages = &.{" + ", ".join(zstr(m) for m in msgs_of(c)) + "},\n")
        w(f"        .sk = {zstr(v['SK'])},\n        .pk = {zstr(v['PK'])},\n")
        w(f"        .header = {zstr(v['header'])},\n        .signature = {zstr(v['signature'])},\n")
        w(f"        .valid = {'true' if c['valid'] else 'false'},\n")
        w("    },\n")
    w("};\n\n")

    w("pub const ProofCase = struct {\n")
    w("    name: []const u8,\n    /// Every signed message, in signing order.\n    messages: []const []const u8,\n")
    w("    pk: []const u8,\n    signature: []const u8,\n    header: []const u8,\n    presentation_header: []const u8,\n")
    w("    disclosed_indexes: []const usize,\n    proof: []const u8,\n};\n\n")
    w("/// Proofs under `mocked_rng.seed` (5 + U scalars each).\n")
    w("pub const proof_cases = [_]ProofCase{\n")
    for num in ("8.4.5.1", "8.4.5.2", "8.4.5.3", "D.2.2.1", "D.2.2.2"):
        c = s[num]
        v = c["vals"]
        msgs = [v[k] for k in c["order"] if re.fullmatch(r"m_\d+", k)]
        w("    .{\n")
        w(f"        .name = {zstr(num + ' ' + c['title'])},\n")
        w("        .messages = &.{" + ", ".join(zstr(m) for m in msgs) + "},\n")
        w(f"        .pk = {zstr(v['public_key'])},\n        .signature = {zstr(v['signature'])},\n")
        w(f"        .header = {zstr(v['header'])},\n        .presentation_header = {zstr(v['presentation_header'])},\n")
        w("        .disclosed_indexes = &.{" + ", ".join(str(i) for i in c["revealed"]) + "},\n")
        w(f"        .proof = {zstr(v['proof'])},\n")
        w("    },\n")
    w("};\n")


if __name__ == "__main__":
    main()
