// SPDX-License-Identifier: MIT
//! openssh — Blowfish + the OpenBSD `bcrypt_pbkdf` KDF, the two primitives
//! the OpenSSH `PROTOCOL.key` private-key format needs for
//! passphrase-protected keys. Support code for `rsa.fromOpenSSH` (P4b), not
//! a general-purpose cipher offering: Blowfish is a 1993 64-bit-block
//! cipher — do not reach for it for anything but bcrypt compatibility.
//!
//! Provenance (clean-room, no OpenSSH/OpenBSD C source consulted):
//! * Blowfish: implemented from B. Schneier, "Description of a New
//!   Variable-Length Key, 64-Bit Block Cipher (Blowfish)", Fast Software
//!   Encryption '93 — 16-round Feistel network; P-array/S-boxes seeded from
//!   the fractional hexadecimal digits of pi ("nothing up my sleeve"
//!   constants, recomputed independently for this file from a
//!   Machin-formula evaluation rather than copied from any implementation;
//!   see `pi_hex`).
//! * bcrypt-pbkdf: implemented from the published description of OpenBSD's
//!   `bcrypt_pbkdf(3)` algorithm (Ted Unangst) — SHA-512 pre-hashing, the
//!   EksBlowfish expensive key schedule at fixed cost 6, the
//!   "OxychromaticBlowfishSwatDynamite" magic block, little-endian word
//!   emission, and the output-stride byte permutation.
//!
//! Test-vector provenance:
//! * Blowfish ECB known answers: Eric Young's classic vectors as published
//!   at schneier.com (vectors-2.txt, "Test vectors by Eric Young").
//! * bcrypt_hash + bcrypt_pbkdf golden vectors: golang.org/x/crypto
//!   `ssh/internal/bcrypt_pbkdf/bcrypt_pbkdf_test.go` ("Test vectors
//!   generated by the reference implementation from OpenBSD").
//! * `std.crypto.pwhash.bcrypt.pbkdf` doubles as an independent oracle.

const std = @import("std");

// The fractional hexadecimal digits of pi: 1042 32-bit words = 18 P-array
// subkeys + 4x256 S-box entries, exactly as the Blowfish spec prescribes.
// Recomputed for this file with a high-precision Machin-formula evaluation
// (pi = 16*atan(1/5) - 4*atan(1/239), integer arithmetic); corner words
// cross-checked against the values printed in the published spec
// (P[0] = 0x243f6a88, S4[255] = 0x3ac372e6).
const pi_hex =
    "243f6a8885a308d313198a2e03707344a4093822299f31d0082efa98ec4e6c89" ++
    "452821e638d01377be5466cf34e90c6cc0ac29b7c97c50dd3f84d5b5b5470917" ++
    "9216d5d98979fb1bd1310ba698dfb5ac2ffd72dbd01adfb7b8e1afed6a267e96" ++
    "ba7c9045f12c7f9924a19947b3916cf70801f2e2858efc16636920d871574e69" ++
    "a458fea3f4933d7e0d95748f728eb658718bcd5882154aee7b54a41dc25a59b5" ++
    "9c30d5392af26013c5d1b023286085f0ca417918b8db38ef8e79dcb0603a180e" ++
    "6c9e0e8bb01e8a3ed71577c1bd314b2778af2fda55605c60e65525f3aa55ab94" ++
    "5748986263e8144055ca396a2aab10b6b4cc5c341141e8cea15486af7c72e993" ++
    "b3ee1411636fbc2a2ba9c55d741831f6ce5c3e169b87931eafd6ba336c24cf5c" ++
    "7a325381289586773b8f48986b4bb9afc4bfe81b6628219361d809ccfb21a991" ++
    "487cac605dec8032ef845d5de98575b1dc262302eb651b8823893e81d396acc5" ++
    "0f6d6ff383f442392e0b4482a484200469c8f04a9e1f9b5e21c66842f6e96c9a" ++
    "670c9c61abd388f06a51a0d2d8542f68960fa728ab5133a36eef0b6c137a3be4" ++
    "ba3bf0507efb2a98a1f1651d39af017666ca593e82430e888cee8619456f9fb4" ++
    "7d84a5c33b8b5ebee06f75d885c12073401a449f56c16aa64ed3aa62363f7706" ++
    "1bfedf72429b023d37d0d724d00a1248db0fead349f1c09b075372c980991b7b" ++
    "25d479d8f6e8def7e3fe501ab6794c3b976ce0bd04c006bac1a94fb6409f60c4" ++
    "5e5c9ec2196a246368fb6faf3e6c53b51339b2eb3b52ec6f6dfc511f9b30952c" ++
    "cc814544af5ebd09bee3d004de334afd660f2807192e4bb3c0cba85745c8740f" ++
    "d20b5f39b9d3fbdb5579c0bd1a60320ad6a100c6402c7279679f25fefb1fa3cc" ++
    "8ea5e9f8db3222f83c7516dffd616b152f501ec8ad0552ab323db5fafd238760" ++
    "53317b483e00df829e5c57bbca6f8ca01a87562edf1769dbd542a8f6287effc3" ++
    "ac6732c68c4f5573695b27b0bbca58c8e1ffa35db8f011a010fa3d98fd2183b8" ++
    "4afcb56c2dd1d35b9a53e479b6f84565d28e49bc4bfb9790e1ddf2daa4cb7e33" ++
    "62fb1341cee4c6e8ef20cada36774c01d07e9efe2bf11fb495dbda4dae909198" ++
    "eaad8e716b93d5a0d08ed1d0afc725e08e3c5b2f8e7594b78ff6e2fbf2122b64" ++
    "8888b812900df01c4fad5ea0688fc31cd1cff191b3a8c1ad2f2f2218be0e1777" ++
    "ea752dfe8b021fa1e5a0cc0fb56f74e818acf3d6ce89e299b4a84fe0fd13e0b7" ++
    "7cc43b81d2ada8d9165fa2668095770593cc7314211a1477e6ad206577b5fa86" ++
    "c75442f5fb9d35cfebcdaf0c7b3e89a0d6411bd3ae1e7e4900250e2d2071b35e" ++
    "226800bb57b8e0af2464369bf009b91e5563911d59dfa6aa78c14389d95a537f" ++
    "207d5ba202e5b9c5832603766295cfa911c819684e734a41b3472dca7b14a94a" ++
    "1b5100529a532915d60f573fbc9bc6e42b60a47681e6740008ba6fb5571be91f" ++
    "f296ec6b2a0dd915b6636521e7b9f9b6ff34052ec585566453b02d5da99f8fa1" ++
    "08ba47996e85076a4b7a70e9b5b32944db75092ec4192623ad6ea6b049a7df7d" ++
    "9cee60b88fedb266ecaa8c71699a17ff5664526cc2b19ee1193602a575094c29" ++
    "a0591340e4183a3e3f54989a5b429d656b8fe4d699f73fd6a1d29c07efe830f5" ++
    "4d2d38e6f0255dc14cdd20868470eb266382e9c6021ecc5e09686b3f3ebaefc9" ++
    "3c9718146b6a70a1687f358452a0e286b79c5305aa5007373e07841c7fdeae5c" ++
    "8e7d44ec5716f2b8b03ada37f0500c0df01c1f040200b3ffae0cf51a3cb574b2" ++
    "25837a58dc0921bdd19113f97ca92ff69432477322f547013ae5e58137c2dadc" ++
    "c8b576349af3dda7a94461460fd0030eecc8c73ea4751e41e238cd993bea0e2f" ++
    "3280bba1183eb3314e548b384f6db9086f420d03f60a04bf2cb8129024977c79" ++
    "5679b072bcaf89afde9a771fd9930810b38bae12dccf3f2e5512721f2e6b7124" ++
    "501adde69f84cd877a5847187408da17bc9f9abce94b7d8cec7aec3adb851dfa" ++
    "63094366c464c3d2ef1c18473215d908dd433b3724c2ba1612a14d432a65c451" ++
    "50940002133ae4dd71dff89e10314e5581ac77d65f11199b043556f1d7a3c76b" ++
    "3c11183b5924a509f28fe6ed97f1fbfa9ebabf2c1e153c6e86e34570eae96fb1" ++
    "860e5e0a5a3e2ab3771fe71c4e3d06fa2965dcb999e71d0f803e89d65266c825" ++
    "2e4cc9789c10b36ac6150eba94e2ea78a5fc3c531e0a2df4f2f74ea7361d2b3d" ++
    "1939260f19c279605223a708f71312b6ebadfe6eeac31f66e3bc4595a67bc883" ++
    "b17f37d1018cff28c332ddefbe6c5aa56558218568ab9802eecea50fdb2f953b" ++
    "2aef7dad5b6e2f841521b62829076170ecdd4775619f151013cca830eb61bd96" ++
    "0334fe1eaa0363cfb5735c904c70a239d59e9e0bcbaade14eecc86bc60622ca7" ++
    "9cab5cabb2f3846e648b1eaf19bdf0caa02369b9655abb5040685a323c2ab4b3" ++
    "319ee9d5c021b8f79b540b19875fa09995f7997e623d7da8f837889a97e32d77" ++
    "11ed935f166812810e358829c7e61fd696dedfa17858ba9957f584a51b227263" ++
    "9b83c3ff1ac24696cdb30aeb532e30548fd948e46dbc312858ebf2ef34c6ffea" ++
    "fe28ed61ee7c3c735d4a14d9e864b7e342105d14203e13e045eee2b6a3aaabea" ++
    "db6c4f15facb4fd0c742f442ef6abbb5654f3b1d41cd2105d81e799e86854dc7" ++
    "e44b476a3d816250cf62a1f25b8d2646fc8883a0c1c7b6a37f1524c369cb7492" ++
    "47848a0b5692b285095bbf00ad19489d1462b17423820e0058428d2a0c55f5ea" ++
    "1dadf43e233f70613372f0928d937e41d65fecf16c223bdb7cde3759cbee7460" ++
    "4085f2a7ce77326ea607808419f8509ee8efd85561d99735a969a7aac50c06c2" ++
    "5a04abfc800bcadc9e447a2ec3453484fdd567050e1e9ec9db73dbd3105588cd" ++
    "675fda79e3674340c5c43465713e38d83d28f89ef16dff20153e21e78fb03d4a" ++
    "e6e39f2bdb83adf7e93d5a68948140f7f64c261c94692934411520f77602d4f7" ++
    "bcf46b2ed4a20068d40824713320f46a43b7d4b7500061af1e39f62e97244546" ++
    "14214f74bf8b88404d95fc1d96b591af70f4ddd366a02f45bfbc09ec03bd9785" ++
    "7fac6dd031cb850496eb27b355fd3941da2547e6abca0a9a28507825530429f4" ++
    "0a2c86dae9b66dfb68dc1462d7486900680ec0a427a18dee4f3ffea2e887ad8c" ++
    "b58ce0067af4d6b6aace1e7cd3375fecce78a399406b2a4220fe9e35d9f385b9" ++
    "ee39d7ab3b124e8b1dc9faf74b6d185626a36631eae397b23a6efa74dd5b4332" ++
    "6841e7f7ca7820fbfb0af54ed8feb397454056acba48952755533a3a20838d87" ++
    "fe6ba9b7d096954b55a867bca1159a58cca9296399e1db33a62a4a563f3125f9" ++
    "5ef47e1c9029317cfdf8e80204272f7080bb155c05282ce395c11548e4c66d22" ++
    "48c1133fc70f86dc07f9c9ee41041f0f404779a45d886e17325f51ebd59bc0d1" ++
    "f2bcc18f41113564257b7834602a9c60dff8e8a31f636c1b0e12b4c202e1329e" ++
    "af664fd1cad181156b2395e0333e92e13b240b62eebeb92285b2a20ee6ba0d99" ++
    "de720c8c2da2f728d012784595b794fd647d0862e7ccf5f05449a36f877d48fa" ++
    "c39dfd27f33e8d1e0a476341992eff743a6f6eabf4f8fd37a812dc60a1ebddf8" ++
    "991be14cdb6e6b0dc67b55106d672c372765d43bdcd0e804f1290dc7cc00ffa3" ++
    "b5390f92690fed0b667b9ffbcedb7d9ca091cf0bd9155ea3bb132f88515bad24" ++
    "7b9479bf763bd6eb37392eb3cc1159798026e297f42e312d6842ada7c66a2b3b" ++
    "12754ccc782ef11c6a124237b79251e706a1bbe64bfb63501a6b101811caedfa" ++
    "3d25bdd8e2e1c3c9444216590a121386d90cec6ed5abea2a64af674eda86a85f" ++
    "bebfe98864e4c3fe9dbc8057f0f7c08660787bf86003604dd1fd8346f6381fb0" ++
    "7745ae04d736fccc83426b33f01eab71b08041873c005e5f77a057bebde8ae24" ++
    "55464299bf582e614e58f48ff2ddfda2f474ef388789bdc25366f9c3c8b38e74" ++
    "b475f25546fcd9b97aeb26618b1ddf84846a0e79915f95e2466e598e20b45770" ++
    "8cd55591c902de4cb90bace1bb8205d011a862487574a99eb77f19b6e0a9dc09" ++
    "662d09a1c4324633e85a1f0209f0be8c4a99a0251d6efe101ab93d1d0ba5a4df" ++
    "a186f20f2868f169dcb7da83573906fea1e2ce9b4fcd7f5250115e01a70683fa" ++
    "a002b5c40de6d0279af88c27773f8641c3604c0661a806b5f0177a28c0f586e0" ++
    "006058aa30dc7d6211e69ed72338ea6353c2dd94c2c21634bbcbee5690bcb6de" ++
    "ebfc7da1ce591d766f05e4094b7c018839720a3d7c927c2486e3725f724d9db9" ++
    "1ac15bb4d39eb8fced54557808fca5b5d83d7cd34dad0fc41e50ef5eb161e6f8" ++
    "a28514d96c51133c6fd5c7e756e14ec4362abfceddc6c837d79a323492638212" ++
    "670efa8e406000e03a39ce37d3faf5cfabc277375ac52d1b5cb0679e4fa33742" ++
    "d382274099bc9bbed5118e9dbf0f7315d62d1c7ec700c47bb78c1b6b21a19045" ++
    "b26eb1be6a366eb45748ab2fbc946e79c6a376d26549c2c8530ff8ee468dde7d" ++
    "d5730a1d4cd04dc62939bbdba9ba4650ac9526e8be5ee304a1fad5f06a2d519a" ++
    "63ef8ce29a86ee22c089c2b843242ef6a51e03aa9cf2d0a483c061ba9be96a4d" ++
    "8fe51550ba645bd62826a2f9a73a3ae14ba99586ef5562e9c72fefd3f752f7da" ++
    "3f046f6977fa0a5980e4a91587b086019b09e6ad3b3ee593e990fd5a9e34d797" ++
    "2cf0b7d9022b8b5196d5ac3a017da67dd1cf3ed67c7d2d281f9f25cfadf2b89b" ++
    "5ad6b4725a88f54ce029ac71e019a5e647b0acfded93fa9be8d3c48d283b57cc" ++
    "f8d5662979132e28785f0191ed756055f7960e44e3d35e8c15056dd488f46dba" ++
    "03a161250564f0bdc3eb9e153c9057a297271aeca93a072a1b3f6d9b1e6321f5" ++
    "f59c66fb26dcf3197533d928b155fdf5035634828aba3cbb28517711c20ad9f8" ++
    "abcc5167ccad925f4de817513830dc8e379d58629320f991ea7a90c2fb3e7bce" ++
    "5121ce64774fbe32a8b6e37ec3293d4648de53696413e680a2ae0810dd6db224" ++
    "69852dfd09072166b39a460a6445c0dd586cdecf1c20c8ae5bbef7dd1b588d40" ++
    "ccd2017f6bb4e3bbdda26a7e3a59ff453e350a44bcb4cdd572eacea8fa6484bb" ++
    "8d6612aebf3c6f47d29be463542f5d9eaec2771bf64e6370740e0d8de75b1357" ++
    "f8721671af537d5d4040cb084eb4e2cc34d2466a0115af84e1b0042895983a1d" ++
    "06b89fb4ce6ea0486f3f3b823520ab82011a1d4b277227f8611560b1e7933fdc" ++
    "bb3a792b344525bda08839e151ce794b2f32c9b7a01fbac9e01cc87ebcc7d1f6" ++
    "cf0111c3a1e8aac71a908749d44fbd9ad0dadecbd50ada380339c32ac6913667" ++
    "8df9317ce0b12b4ff79e59b743f5bb3af2d519ff27d9459cbf97222c15e6fc2a" ++
    "0f91fc719b941525fae59361ceb69cebc2a8645912baa8d1b6c1075ee3056a0c" ++
    "10d25065cb03a442e0ec6e0e1698db3b4c98a0be3278e9649f1f9532e0d392df" ++
    "d3a0342b8971f21e1b0a74414ba3348cc5be7120c37632d8df359f8d9b992f2e" ++
    "e60b6f470fe3f11de54cda541edad891ce6279cfcd3e7e6f1618b166fd2c1d05" ++
    "848fd2c5f6fb2299f523f357a632762393a8353156cccd02acf081625a75ebb5" ++
    "6e16369788d273ccde96629281b949d04c50901b71c65614e6c6c7bd327a140a" ++
    "45e1d006c3f27b9ac9aa53fd62a80f00bb25bfe235bdd2f671126905b2040222" ++
    "b6cbcf7ccd769c2b53113ec01640e3d338abbd602547adf0ba38209cf746ce76" ++
    "77afa1c52075606085cbfe4e8ae88dd87aaaf9b04cf9aa7e1948c25c02fb8a8c" ++
    "01c36ae4d6ebe1f990d4f869a65cdea03f09252dc208e69fb74e6132ce77e25b" ++
    "578fdfe33ac372e6";

/// Blowfish block cipher (Schneier, FSE '93): 64-bit blocks, 16-round
/// Feistel network, variable-length key folded into an 18-word P-array and
/// four 256-entry S-boxes. Includes the bcrypt key-schedule variants
/// (`expandState`/`expand0State`) that make the "expensive key setup"
/// possible. Table-based S-box lookups are inherently cache-timing
/// sensitive; acceptable here because bcrypt's schedule is
/// password-randomized, and this module is only used for key-file KDF work.
pub const Blowfish = struct {
    p: [subkey_count]u32,
    s: [4][256]u32,

    const feistel_rounds = 16;
    const subkey_count = feistel_rounds + 2;

    /// The spec's initial state: P-array and S-boxes filled with the
    /// fractional hex digits of pi, in order.
    pub const initial: Blowfish = blk: {
        @setEvalBranchQuota(600_000);
        var st: Blowfish = undefined;
        var idx: usize = 0;
        for (&st.p) |*w| {
            w.* = piWord(idx);
            idx += 1;
        }
        for (&st.s) |*box| {
            for (box) |*w| {
                w.* = piWord(idx);
                idx += 1;
            }
        }
        break :blk st;
    };

    fn piWord(i: usize) u32 {
        var v: u32 = 0;
        for (pi_hex[i * 8 ..][0..8]) |c| {
            const digit: u32 = switch (c) {
                '0'...'9' => c - '0',
                'a'...'f' => c - 'a' + 10,
                else => unreachable,
            };
            v = (v << 4) | digit;
        }
        return v;
    }

    /// Standard Blowfish key schedule: XOR the (cyclically repeated) key
    /// into P, then regenerate P and all S-boxes by chain-encrypting the
    /// all-zero block (spec steps 1-7). Key must be 1..72 bytes (the spec
    /// recommends at most 56 = 448 bits; bcrypt feeds 64-byte SHA-512s).
    pub fn init(key: []const u8) Blowfish {
        var st = initial;
        st.expand0State(key);
        return st;
    }

    /// The Feistel F-function: split x into 4 bytes a,b,c,d, then
    /// F = ((S1[a] + S2[b]) ^ S3[c]) + S4[d], addition mod 2^32.
    fn f(self: *const Blowfish, x: u32) u32 {
        const a: u8 = @truncate(x >> 24);
        const b: u8 = @truncate(x >> 16);
        const c: u8 = @truncate(x >> 8);
        const d: u8 = @truncate(x);
        return ((self.s[0][a] +% self.s[1][b]) ^ self.s[2][c]) +% self.s[3][d];
    }

    /// Encrypt one 64-bit block held as two 32-bit halves, in place.
    /// Two spec rounds per loop iteration so the per-round halve swap
    /// cancels out; the trailing lines are the spec's final un-swap plus
    /// P17/P18 whitening.
    pub fn encryptWords(self: *const Blowfish, xl: *u32, xr: *u32) void {
        var l = xl.*;
        var r = xr.*;
        var i: usize = 0;
        while (i < feistel_rounds) : (i += 2) {
            l ^= self.p[i];
            r ^= self.f(l);
            r ^= self.p[i + 1];
            l ^= self.f(r);
        }
        xl.* = r ^ self.p[feistel_rounds + 1];
        xr.* = l ^ self.p[feistel_rounds];
    }

    /// Decrypt one 64-bit block: identical network with the P-array
    /// traversed in reverse (spec: "decryption is the same as encryption,
    /// except that P1..P18 are used in the reverse order").
    pub fn decryptWords(self: *const Blowfish, xl: *u32, xr: *u32) void {
        var l = xl.*;
        var r = xr.*;
        var i: usize = 0;
        while (i < feistel_rounds) : (i += 2) {
            l ^= self.p[subkey_count - 1 - i];
            r ^= self.f(l);
            r ^= self.p[subkey_count - 2 - i];
            l ^= self.f(r);
        }
        xl.* = r ^ self.p[0];
        xr.* = l ^ self.p[1];
    }

    /// ECB-encrypt one 8-byte block (big-endian halves, the conventional
    /// byte order used by the published test vectors).
    pub fn encryptBlock(self: *const Blowfish, block: [8]u8) [8]u8 {
        var l = std.mem.readInt(u32, block[0..4], .big);
        var r = std.mem.readInt(u32, block[4..8], .big);
        self.encryptWords(&l, &r);
        var out: [8]u8 = undefined;
        std.mem.writeInt(u32, out[0..4], l, .big);
        std.mem.writeInt(u32, out[4..8], r, .big);
        return out;
    }

    /// ECB-decrypt one 8-byte block.
    pub fn decryptBlock(self: *const Blowfish, block: [8]u8) [8]u8 {
        var l = std.mem.readInt(u32, block[0..4], .big);
        var r = std.mem.readInt(u32, block[4..8], .big);
        self.decryptWords(&l, &r);
        var out: [8]u8 = undefined;
        std.mem.writeInt(u32, out[0..4], l, .big);
        std.mem.writeInt(u32, out[4..8], r, .big);
        return out;
    }

    /// Next big-endian 32-bit word from `data`, cycling from the start when
    /// the end is reached (bcrypt's "stream2word"; also exactly how the
    /// standard schedule repeats the key over the P-array).
    fn stream2word(data: []const u8, j: *usize) u32 {
        std.debug.assert(data.len > 0);
        var w: u32 = 0;
        var k: usize = 0;
        while (k < 4) : (k += 1) {
            w = (w << 8) | data[j.*];
            j.* += 1;
            if (j.* >= data.len) j.* = 0;
        }
        return w;
    }

    /// bcrypt's salted key-schedule step, ExpandKey(state, data, key):
    /// XOR `key` into P, then rebuild P and the S-boxes by encrypting a
    /// chaining block that is XORed with successive (cyclic) words of
    /// `data` before every encryption. With `data` all-absent this
    /// degenerates to the standard schedule (`expand0State`).
    pub fn expandState(self: *Blowfish, data: []const u8, key: []const u8) void {
        var j: usize = 0;
        for (&self.p) |*pe| pe.* ^= stream2word(key, &j);
        var l: u32 = 0;
        var r: u32 = 0;
        j = 0;
        var i: usize = 0;
        while (i < subkey_count) : (i += 2) {
            l ^= stream2word(data, &j);
            r ^= stream2word(data, &j);
            self.encryptWords(&l, &r);
            self.p[i] = l;
            self.p[i + 1] = r;
        }
        for (&self.s) |*box| {
            i = 0;
            while (i < 256) : (i += 2) {
                l ^= stream2word(data, &j);
                r ^= stream2word(data, &j);
                self.encryptWords(&l, &r);
                box[i] = l;
                box[i + 1] = r;
            }
        }
    }

    /// bcrypt's plain key-schedule step, ExpandKey(state, 0, key): the
    /// standard Blowfish key schedule (no data-XOR into the chaining
    /// block). `initial` + one `expand0State(key)` == the classic schedule
    /// the ECB test vectors exercise.
    pub fn expand0State(self: *Blowfish, key: []const u8) void {
        var j: usize = 0;
        for (&self.p) |*pe| pe.* ^= stream2word(key, &j);
        var l: u32 = 0;
        var r: u32 = 0;
        var i: usize = 0;
        while (i < subkey_count) : (i += 2) {
            self.encryptWords(&l, &r);
            self.p[i] = l;
            self.p[i + 1] = r;
        }
        for (&self.s) |*box| {
            i = 0;
            while (i < 256) : (i += 2) {
                self.encryptWords(&l, &r);
                box[i] = l;
                box[i + 1] = r;
            }
        }
    }
};

// ── bcrypt_pbkdf (OpenBSD) ───────────────────────────────────────────────────

/// EksBlowfishSetup — bcrypt's "expensive key schedule": one salted
/// expansion, then 2^cost alternating plain re-expansions keyed by salt and
/// password. NOTE: this is the *bcrypt_pbkdf* ordering (salt first, then
/// password, and the salted expansion takes the salt as chaining data);
/// the classic bcrypt password hash alternates in the opposite order.
pub fn eksBlowfishSetup(cost: u6, salt: []const u8, key: []const u8) Blowfish {
    var st = Blowfish.initial;
    st.expandState(salt, key);
    const n = @as(usize, 1) << cost;
    var i: usize = 0;
    while (i < n) : (i += 1) {
        st.expand0State(salt);
        st.expand0State(key);
    }
    return st;
}

/// bcrypt_pbkdf's inner hash: EksBlowfish at fixed cost 6 (= 64 expensive
/// iterations) keyed by the SHA-512s of passphrase and salt, then the
/// 32-byte magic "OxychromaticBlowfishSwatDynamite" (8 big-endian words, 4
/// Blowfish blocks) ECB-encrypted 64 times; the 8 result words are emitted
/// LITTLE-endian — the deliberate byte swap the OpenBSD algorithm
/// documents, kept so outputs stay incompatible with raw bcrypt.
pub fn bcryptHash(sha2_pass: [64]u8, sha2_salt: [64]u8) [32]u8 {
    const magic = "OxychromaticBlowfishSwatDynamite"; // 32 bytes, 8 words
    var st = eksBlowfishSetup(6, &sha2_salt, &sha2_pass);
    defer std.crypto.secureZero(u8, std.mem.asBytes(&st));

    var cdata: [8]u32 = undefined;
    for (&cdata, 0..) |*w, i| w.* = std.mem.readInt(u32, magic[i * 4 ..][0..4], .big);
    var round: usize = 0;
    while (round < 64) : (round += 1) {
        var b: usize = 0;
        while (b < 8) : (b += 2) st.encryptWords(&cdata[b], &cdata[b + 1]);
    }

    var out: [32]u8 = undefined;
    for (cdata, 0..) |w, i| std.mem.writeInt(u32, out[i * 4 ..][0..4], w, .little);
    std.crypto.secureZero(u32, &cdata);
    return out;
}

pub const PbkdfError = error{InvalidParameters};

/// OpenBSD `bcrypt_pbkdf(3)`: derive `out.len` key bytes from a passphrase
/// and salt. Per 32-byte output block: sha2salt = SHA-512(salt ||
/// be32(block_index)), then `rounds` XOR-accumulated `bcryptHash`
/// invocations, each rekeyed with the SHA-512 of the previous raw hash.
/// Output bytes are laid out with the OpenBSD stride permutation — byte i
/// of block c lands at out[i*stride + c], stride = ceil(out.len/32) — so
/// truncating the output never yields a prefix of a longer derivation.
/// `rounds` >= 1; pass/salt non-empty; out 1..1024 bytes (OpenBSD's bounds).
pub fn bcryptPbkdf(pass: []const u8, salt: []const u8, rounds: u32, out: []u8) PbkdfError!void {
    const Sha512 = std.crypto.hash.sha2.Sha512;
    if (rounds < 1 or pass.len == 0 or salt.len == 0) return error.InvalidParameters;
    if (out.len == 0 or out.len > 1024) return error.InvalidParameters;

    var sha2_pass: [64]u8 = undefined;
    defer std.crypto.secureZero(u8, &sha2_pass);
    Sha512.hash(pass, &sha2_pass, .{});

    const stride = (out.len + 32 - 1) / 32;
    const amt = (out.len + stride - 1) / stride;

    var remaining = out.len;
    var count: u32 = 1;
    while (remaining > 0) : (count += 1) {
        var count_be: [4]u8 = undefined;
        std.mem.writeInt(u32, &count_be, count, .big);
        var sha2_salt: [64]u8 = undefined;
        defer std.crypto.secureZero(u8, &sha2_salt);
        var h = Sha512.init(.{});
        h.update(salt);
        h.update(&count_be);
        h.final(&sha2_salt);

        var tmp = bcryptHash(sha2_pass, sha2_salt);
        var acc = tmp;
        var r: u32 = 1;
        while (r < rounds) : (r += 1) {
            Sha512.hash(&tmp, &sha2_salt, .{});
            tmp = bcryptHash(sha2_pass, sha2_salt);
            for (&acc, tmp) |*a, t| a.* ^= t;
        }
        std.crypto.secureZero(u8, &tmp);

        // Stride permutation: block c contributes at positions c-1, c-1 +
        // stride, c-1 + 2*stride, ...
        const n = @min(amt, remaining);
        var taken: usize = 0;
        var i: usize = 0;
        while (i < n) : (i += 1) {
            const dest = i * stride + (count - 1);
            if (dest >= out.len) break;
            out[dest] = acc[i];
            taken += 1;
        }
        std.crypto.secureZero(u8, &acc);
        remaining -= taken;
    }
}

// ── tests ────────────────────────────────────────────────────────────────────
//
// Vector sources are listed in the module doc comment ("Test-vector
// provenance"). All hex is transcribed verbatim from the cited files.

const testing = std.testing;

fn hexArr(comptime hex: []const u8) [hex.len / 2]u8 {
    var out: [hex.len / 2]u8 = undefined;
    _ = std.fmt.hexToBytes(&out, hex) catch unreachable;
    return out;
}

test "blowfish initial state matches the published pi constants" {
    // Corner words as printed in the Blowfish spec's constant listings.
    const st = Blowfish.initial;
    try testing.expectEqual(@as(u32, 0x243f6a88), st.p[0]);
    try testing.expectEqual(@as(u32, 0x85a308d3), st.p[1]);
    try testing.expectEqual(@as(u32, 0x8979fb1b), st.p[17]);
    try testing.expectEqual(@as(u32, 0xd1310ba6), st.s[0][0]);
    try testing.expectEqual(@as(u32, 0x3ac372e6), st.s[3][255]);
}

test "blowfish ECB known answers (Eric Young vectors) + decrypt round-trip" {
    // schneier.com vectors-2.txt, "ecb test data" (key / clear / cipher).
    const vectors = [_][3][]const u8{
        .{ "0000000000000000", "0000000000000000", "4EF997456198DD78" },
        .{ "FFFFFFFFFFFFFFFF", "FFFFFFFFFFFFFFFF", "51866FD5B85ECB8A" },
        .{ "3000000000000000", "1000000000000001", "7D856F9A613063F2" },
        .{ "1111111111111111", "1111111111111111", "2466DD878B963C9D" },
        .{ "0123456789ABCDEF", "1111111111111111", "61F9C3802281B096" },
        .{ "1111111111111111", "0123456789ABCDEF", "7D0CC630AFDA1EC7" },
        .{ "FEDCBA9876543210", "0123456789ABCDEF", "0ACEAB0FC6A0A28D" },
        .{ "7CA110454A1A6E57", "01A1D6D039776742", "59C68245EB05282B" },
        .{ "0131D9619DC1376E", "5CD54CA83DEF57DA", "B1B8CC0B250F09A0" },
        .{ "0170F175468FB5E6", "0756D8E0774761D2", "432193B78951FC98" },
        .{ "0101010101010101", "0123456789ABCDEF", "FA34EC4847B268B2" },
        .{ "0000000000000000", "FFFFFFFFFFFFFFFF", "014933E0CDAFF6E4" },
        .{ "FFFFFFFFFFFFFFFF", "0000000000000000", "F21E9A77B71C49BC" },
        .{ "0123456789ABCDEF", "0000000000000000", "245946885754369A" },
        .{ "FEDCBA9876543210", "FFFFFFFFFFFFFFFF", "6B5C5A9C5D9E0A5A" },
    };
    inline for (vectors) |v| {
        const key = hexArr(v[0]);
        const clear = hexArr(v[1]);
        const cipher = hexArr(v[2]);
        const bf = Blowfish.init(&key);
        try testing.expectEqualSlices(u8, &cipher, &bf.encryptBlock(clear));
        try testing.expectEqualSlices(u8, &clear, &bf.decryptBlock(cipher));
    }
}

test "bcrypt_hash golden vector (x/crypto bcrypt_pbkdf_test.go TestBcryptHash)" {
    // pass[i] = i, salt[i] = 64 + i, i in 0..64.
    var pass: [64]u8 = undefined;
    var salt: [64]u8 = undefined;
    for (&pass, &salt, 0..) |*p, *s, i| {
        p.* = @intCast(i);
        s.* = @intCast(i + 64);
    }
    const expected = hexArr("87904870eef9deddf8e7611a140106e6aaf1a363d9a2c504db356443721eb555");
    try testing.expectEqualSlices(u8, &expected, &bcryptHash(pass, salt));
}

test "bcrypt_pbkdf golden vectors (x/crypto, OpenBSD reference implementation)" {
    // Vector 1: rounds 12, "password", "salt", 32 bytes.
    {
        var out: [32]u8 = undefined;
        try bcryptPbkdf("password", "salt", 12, &out);
        const expected = hexArr("1ae42c05d487bc02f64921a4ebe4ea93bcacfe135fda99974c06b7b01fae149a");
        try testing.expectEqualSlices(u8, &expected, &out);
    }
    // Vector 2: rounds 3, embedded NULs.
    {
        var out: [32]u8 = undefined;
        try bcryptPbkdf("passwordy\x00PASSWORD\x00", "salty\x00SALT\x00", 3, &out);
        const expected = hexArr("7f310bd3e78c3280c59ce4595211a2928e8d4ec744c1ed2efc9f764e3388e0ad");
        try testing.expectEqualSlices(u8, &expected, &out);
    }
    // Vector 3: rounds 8, UTF-8 pass/salt, 88-byte output — exercises the
    // stride permutation with a non-multiple-of-32 length (stride 3).
    {
        var out: [88]u8 = undefined;
        try bcryptPbkdf("секретное слово", "посолить немножко", 8, &out);
        const expected = hexArr("8df43fc6fe131fc47f0c9e39224bd94c70b6fcc8ee8135faddf61156e6cb2733" ++
            "ea765f315a3e1e4afc35bf8687d189254c1e05a6fe80c0617f9183d67260d6a1" ++
            "15c6c94e3603e2303fbb43a76a64523ffda686b1d4518543");
        try testing.expectEqualSlices(u8, &expected, &out);
    }
}

test "bcrypt_pbkdf agrees with std.crypto's bcrypt.opensshKdf (independent oracle)" {
    // std's OpenBSD-compatible function is `opensshKdf` (its `pbkdf` is a
    // generic PBKDF2-with-bcrypt-PRF that only coincides for outputs of a
    // single 32-byte block). Same parameter shape OpenSSH uses for key
    // files (48 = 32-byte key + 16-byte IV), plus a non-block-aligned
    // length for the stride path.
    var mine: [48]u8 = undefined;
    var theirs: [48]u8 = undefined;
    try bcryptPbkdf("hunter2", "0123456789abcdef", 4, &mine);
    try std.crypto.pwhash.bcrypt.opensshKdf("hunter2", "0123456789abcdef", &theirs, 4);
    try testing.expectEqualSlices(u8, &mine, &theirs);

    var mine2: [17]u8 = undefined;
    var theirs2: [17]u8 = undefined;
    try bcryptPbkdf("p", "s", 2, &mine2);
    try std.crypto.pwhash.bcrypt.opensshKdf("p", "s", &theirs2, 2);
    try testing.expectEqualSlices(u8, &mine2, &theirs2);
}

test "bcrypt_pbkdf rejects invalid parameters" {
    var out: [32]u8 = undefined;
    try testing.expectError(error.InvalidParameters, bcryptPbkdf("p", "s", 0, &out));
    try testing.expectError(error.InvalidParameters, bcryptPbkdf("", "s", 1, &out));
    try testing.expectError(error.InvalidParameters, bcryptPbkdf("p", "", 1, &out));
    try testing.expectError(error.InvalidParameters, bcryptPbkdf("p", "s", 1, out[0..0]));
    var huge: [1025]u8 = undefined;
    try testing.expectError(error.InvalidParameters, bcryptPbkdf("p", "s", 1, &huge));
}
