// SPDX-License-Identifier: MIT
// Generated by modules/finstats/tools/cf_oracle.R from R 4.5.3 and PerformanceAnalytics 2.1.0
// over tools/oracle.py's seeded series. Replayed by src/oracle_test.zig. Do not edit by hand.

/// `sd` is the POPULATION standard deviation: PerformanceAnalytics' modified VaR
/// uses it (measured: its quantile is the CF formula with sqrt(m2), 2.0e-3 off with
/// the sample sd at n = 250). `cornishFisherVaR` takes sd as a parameter, so the
/// replay passes this one; `parametricRisk`'s documented choice is the sample sd.
pub const Cf = struct { series: []const u8, conf: f64, mean: f64, sd: f64, skew: f64, kurt: f64, var_: f64, cvar: f64, cvar_p: f64, pa_es: f64 };
pub const cases = [_]Cf{
    .{ .series = "fat_tails", .conf = 0.95, .mean = 0.00045174359644783025, .sd = 0.011294073426817817, .skew = -0.10486135091377612, .kurt = 1.7428803293061019, .var_ = 0.018062428427039333, .cvar = 0.026368415487906888, .cvar_p = 0.026368415487508377, .pa_es = 0.026248538574762868 },
    .{ .series = "fat_tails", .conf = 0.99, .mean = 0.00045174359644783025, .sd = 0.011294073426817817, .skew = -0.10486135091377612, .kurt = 1.7428803293061019, .var_ = 0.031248235088160135, .cvar = 0.040427046274900208, .cvar_p = 0.04042704627484018, .pa_es = 0.040574979531319284 },
    .{ .series = "crashes", .conf = 0.95, .mean = -0.00060497539903460462, .sd = 0.0099044170556549307, .skew = -3.0986860705437755, .kurt = 14.917299347808061, .var_ = 0.020852440685002784, .cvar = 0.036011156839940044, .cvar_p = 0.036011156839979706, .pa_es = 0.045964361925324458 },
    .{ .series = "crashes", .conf = 0.99, .mean = -0.00060497539903460462, .sd = 0.0099044170556549307, .skew = -3.0986860705437755, .kurt = 14.917299347808061, .var_ = 0.044964892758580517, .cvar = 0.061938919278949844, .cvar_p = 0.061938919279044165, .pa_es = 0.044964892758580517 },
    .{ .series = "calm", .conf = 0.95, .mean = 0.00048667296386926213, .sd = 0.0042490367453338739, .skew = 0.058357447219092001, .kurt = -0.20378007626887262, .var_ = 0.0064490873653904723, .cvar = 0.008007071291372795, .cvar_p = 0.0080070712913712441, .pa_es = 0.0080152383333804041 },
    .{ .series = "calm", .conf = 0.99, .mean = 0.00048667296386926213, .sd = 0.0042490367453338739, .skew = 0.058357447219092001, .kurt = -0.20378007626887262, .var_ = 0.0090078582413269971, .cvar = 0.01014693176118792, .cvar_p = 0.010146931761159796, .pa_es = 0.010273440442115209 },
    .{ .series = "bench", .conf = 0.95, .mean = -0.00024545359750270136, .sd = 0.0085819481424528488, .skew = -0.18239893071075425, .kurt = -0.097161624512930089, .var_ = 0.014817925503186629, .cvar = 0.018638319618304294, .cvar_p = 0.018638319617164688, .pa_es = 0.018587139370829574 },
    .{ .series = "bench", .conf = 0.99, .mean = -0.00024545359750270136, .sd = 0.0085819481424528488, .skew = -0.18239893071075425, .kurt = -0.097161624512930089, .var_ = 0.021058677122111139, .cvar = 0.024119570174592802, .cvar_p = 0.024119570174449441, .pa_es = 0.024138806551782788 },
    .{ .series = "port", .conf = 0.95, .mean = 0.00013827129444079624, .sd = 0.011205740229852896, .skew = -0.17235860562094044, .kurt = -0.32718109849089583, .var_ = 0.018910283379822396, .cvar = 0.023446553942451476, .cvar_p = 0.023446553942451841, .pa_es = 0.023275207331535222 },
    .{ .series = "port", .conf = 0.99, .mean = 0.00013827129444079624, .sd = 0.011205740229852896, .skew = -0.17235860562094044, .kurt = -0.32718109849089583, .var_ = 0.026367953545944931, .cvar = 0.029684887920877367, .cvar_p = 0.029684887920795738, .pa_es = 0.029772498673463255 },
};
