// SPDX-License-Identifier: MIT

//! **Byte-exact goldens produced by an independent BACnet stack.**
//!
//! Every datagram in `wire` was emitted by Python **bacpypes3 0.0.106**
//! (Joel Bender; the reference open-source BACnet implementation), driven as a
//! black box: build the service object, let it encode through its own APDU →
//! NPDU → BVLC layers, print the octets. Nothing in this module was derived
//! from those octets — they are the oracle, checked against afterwards.
//!
//! Three assertions run over the whole table, and they are what makes it a
//! test rather than a data dump:
//!
//! 1. **Every datagram decodes** — BVLC, NPDU, APDU, and the service body.
//! 2. **Every datagram re-encodes to the identical octets**, rebuilt from the
//!    *decoded* fields through this module's own writers. So it is the
//!    encoder being checked, not a memcpy.
//! 3. **A representative subset is asserted field by field** against what the
//!    frame is supposed to mean.
//!
//! See SPEC.md for what is third-party-validated versus self-derived, and for
//! the live-interop story.

const std = @import("std");
const types = @import("types.zig");
const tag = @import("tag.zig");
const bvll = @import("bvll.zig");
const npdu = @import("npdu.zig");
const apdu = @import("apdu.zig");
const service = @import("service.zig");

pub const Golden = struct {
    name: []const u8,
    /// The complete BACnet/IP datagram, BVLC header included.
    hex: []const u8,
};

/// 42 datagrams generated by bacpypes3. Names describe the frame, not a real
/// site: instance 599 and the `192.0.2.0/24` documentation range are used
/// throughout, and no real device identifier or site name appears.
pub const wire = [_]Golden{
    .{ .name = "whois_unbounded", .hex = "810b000801001008" },
    .{ .name = "whois_range_1_100", .hex = "810b000c0100100809011964" },
    .{ .name = "whois_single_599", .hex = "810b000e010010080a02571a0257" },
    .{ .name = "whois_wide", .hex = "810b000e0100100809001b3fffff" },
    .{ .name = "iam_599", .hex = "810b001501001000c4020002572205c491032203e7" },
    .{ .name = "iam_segmented", .hex = "810b001401001000c4023fffff2201e09100210f" },
    .{ .name = "whohas_by_name", .hex = "810b0014010010073d0a005a4f4e452d54454d50" },
    .{ .name = "whohas_by_id", .hex = "810b001101001007090119642c00000003" },
    .{ .name = "ihave", .hex = "810b001e01001001c402000257c400000003750a005a4f4e452d54454d50" },
    .{ .name = "readproperty_req", .hex = "810a001101000005010c0c000000051955" },
    .{ .name = "readproperty_req_arrayindex", .hex = "810a0013010000052a0c0c02000257194c2902" },
    .{ .name = "readproperty_req_proprietary_prop", .hex = "810a001201000005070c0c008000011a0200" },
    .{ .name = "readproperty_ack_real", .hex = "810a0017010030010c0c0000000519553e44429100003f" },
    .{ .name = "readproperty_ack_string", .hex = "810a0020010030020c0c00000005194d3e750c005a4f4e452d312d54454d503f" },
    .{ .name = "readproperty_ack_enum", .hex = "810a0014010030030c0c00c0000219553e91013f" },
    .{ .name = "readproperty_ack_statusflags", .hex = "810a0015010030040c0c00000005196f3e8204003f" },
    .{ .name = "readproperty_ack_arrayindex", .hex = "810a0016010030050c0c02000257194c29003e21043f" },
    .{ .name = "writeproperty_req", .hex = "810a0018010000050a0f0c0080000119553e4441a800003f" },
    .{ .name = "writeproperty_req_priority", .hex = "810a001a010000050b0f0c0040000119553e4441a800003f4908" },
    .{ .name = "writeproperty_relinquish", .hex = "810a0016010000050c0f0c0040000119553e003f4908" },
    .{ .name = "writeproperty_string", .hex = "810a0020010000050d0f0c02000257194d3e750b004255494c44494e472d413f" },
    .{ .name = "writeproperty_arrayindex", .hex = "810a001a010000050e0f0c02000257194c29033ec4000000093f" },
    .{ .name = "simpleack_writeproperty", .hex = "810a00090100200a0f" },
    .{ .name = "simpleack_subscribecov", .hex = "810a00090100201405" },
    .{ .name = "reject_unrecognized", .hex = "810a00090100600309" },
    .{ .name = "reject_invalid_tag", .hex = "810a00090100600404" },
    .{ .name = "abort_segmentation", .hex = "810a00090100710504" },
    .{ .name = "abort_other_client", .hex = "810a00090100700600" },
    .{ .name = "error_unknown_property", .hex = "810a000d010050010c91019120" },
    .{ .name = "error_write_access_denied", .hex = "810a000d010050020f91029128" },
    .{ .name = "rpm_req_two_props", .hex = "810a0015010000051e0e0c000000051e0955096f1f" },
    .{ .name = "rpm_req_all_required_optional", .hex = "810a001e010000051f0e0c000000051e09081f0c020002571e096909501f" },
    .{ .name = "rpm_req_array_index", .hex = "810a001501000005200e0c020002571e094c19011f" },
    .{ .name = "rpm_ack_two_props", .hex = "810a00200100301e0e0c000000051e29554e44429100004f296f4e8204004f1f" },
    .{ .name = "rpm_ack_with_error", .hex = "810a0018010030210e0c000000091e29555e9101911f5f1f" },
    .{ .name = "subscribecov_req", .hex = "810a001601000005140509071c0000000529013a012c" },
    .{ .name = "subscribecov_cancel", .hex = "810a001101000005150509071c00000005" },
    .{ .name = "subscribecov_unconfirmed_indefinite", .hex = "810a001501000005160509071c0000000529003900" },
    .{ .name = "unconfirmed_cov_notification", .hex = "810b00290100100209071c020002572c000000053a01184e09552e44429100002f096f2e8204002f4f" },
    .{ .name = "confirmed_cov_notification", .hex = "810a002401000005280109071c020002572c000000053a01184e09552e44429100002f4f" },
    .{ .name = "readrange_req_byposition", .hex = "810a001701000005321a0c0500000119833e2101310a3f" },
    .{ .name = "readrange_req_all", .hex = "810a001101000005331a0c050000011983" },
};

/// Primitive tag encodings, also from bacpypes3, kept as their own table
/// because clause 20.2 is where implementations disagree and a failure here
/// localises instantly.
pub const primitives = [_]Golden{
    .{ .name = "null", .hex = "00" },
    .{ .name = "boolean_true", .hex = "11" },
    .{ .name = "boolean_false", .hex = "10" },
    .{ .name = "unsigned_0", .hex = "2100" },
    .{ .name = "unsigned_255", .hex = "21ff" },
    .{ .name = "unsigned_256", .hex = "220100" },
    .{ .name = "unsigned_65535", .hex = "22ffff" },
    .{ .name = "unsigned_65536", .hex = "23010000" },
    .{ .name = "unsigned_max_u32", .hex = "24ffffffff" },
    .{ .name = "signed_minus1", .hex = "31ff" },
    .{ .name = "signed_minus128", .hex = "3180" },
    .{ .name = "signed_minus129", .hex = "32ff7f" },
    .{ .name = "signed_0", .hex = "3100" },
    .{ .name = "signed_127", .hex = "317f" },
    .{ .name = "signed_128", .hex = "320080" },
    .{ .name = "signed_minus32768", .hex = "328000" },
    .{ .name = "signed_minus32769", .hex = "33ff7fff" },
    .{ .name = "signed_max_i32", .hex = "347fffffff" },
    .{ .name = "signed_min_i32", .hex = "3480000000" },
    .{ .name = "real_3_14", .hex = "444048f5c3" },
    .{ .name = "real_0", .hex = "4400000000" },
    .{ .name = "double_3_14", .hex = "550840091eb851eb851f" },
    .{ .name = "octets_0", .hex = "60" },
    .{ .name = "octets_1", .hex = "61ab" },
    .{ .name = "octets_4", .hex = "64abababab" },
    .{ .name = "octets_5", .hex = "6505ababababab" },
    .{ .name = "octets_6", .hex = "6506abababababab" },
    .{ .name = "string_hello", .hex = "75060068656c6c6f" },
    .{ .name = "string_empty", .hex = "7100" },
    .{ .name = "string_latin1_abc", .hex = "7400616263" },
    .{ .name = "bitstring_101", .hex = "8205a0" },
    .{ .name = "bitstring_empty", .hex = "8100" },
    .{ .name = "bitstring_8_set", .hex = "8200ff" },
    .{ .name = "enumerated_3", .hex = "9103" },
    .{ .name = "date", .hex = "a47c071702" },
    .{ .name = "time", .hex = "b40d2d1e32" },
    .{ .name = "objectid_device_max", .hex = "c4023fffff" },
    .{ .name = "objectid_analog_value_12", .hex = "c40080000c" },
    .{ .name = "context0_unsigned_1", .hex = "0901" },
    .{ .name = "opening_tag_3", .hex = "3e" },
    .{ .name = "closing_tag_3", .hex = "3f" },
    .{ .name = "context15_unsigned_1", .hex = "f90f01" },
    .{ .name = "context254_unsigned_1", .hex = "f9fe01" },
    .{ .name = "context5_len6", .hex = "5d06aaaaaaaaaaaa" },
    .{ .name = "opening_tag_15", .hex = "fe0f" },
    .{ .name = "closing_tag_99", .hex = "ff63" },
    .{ .name = "context0_len0", .hex = "08" },
};

// ── tests ───────────────────────────────────────────────────────────────────

const testing = std.testing;

fn bytesOf(g: Golden, buf: []u8) ![]u8 {
    return std.fmt.hexToBytes(buf, g.hex);
}

/// Decodes a golden datagram down to the APDU, returning the layers.
const Decoded = struct {
    bvlc: bvll.Message,
    npdu: npdu.Npdu,
    apdu: apdu.Apdu,
};

fn decodeAll(dgram: []const u8) !Decoded {
    const b = try bvll.decode(dgram);
    const n = try npdu.decode(b.npdu().?);
    const a = try apdu.decode(n.payload.apdu);
    return .{ .bvlc = b, .npdu = n, .apdu = a };
}

test "goldens: every third-party datagram decodes at all four layers" {
    var buf: [256]u8 = undefined;
    for (wire) |g| {
        const dgram = try bytesOf(g, &buf);
        const d = decodeAll(dgram) catch |e| {
            std.debug.print("golden '{s}' failed to decode: {t}\n", .{ g.name, e });
            return e;
        };
        // Every one of them is a plain NPDU with no routing fields and
        // protocol version 1 — that is what a same-subnet exchange looks like.
        try testing.expectEqual(@as(usize, 2), d.npdu.header_len);
        // And every APDU's service body is reachable (i.e. nothing is
        // segmented in this table).
        try testing.expect(!d.apdu.isSegmented());
        _ = try d.apdu.serviceData();
    }
}

test "goldens: every datagram re-encodes to the identical octets" {
    var buf: [256]u8 = undefined;
    var out: [256]u8 = undefined;
    for (wire) |g| {
        const dgram = try bytesOf(g, &buf);
        const d = try decodeAll(dgram);

        // Rebuild from the decoded APDU, not from the input slice.
        var a_buf: [256]u8 = undefined;
        const a = try apdu.encode(d.apdu, &a_buf);
        var n_buf: [256]u8 = undefined;
        const n = try npdu.encode(d.npdu.npci, a, &n_buf);
        const again = try bvll.encode(switch (d.bvlc.function()) {
            .original_unicast_npdu => .{ .original_unicast_npdu = n },
            .original_broadcast_npdu => .{ .original_broadcast_npdu = n },
            else => unreachable,
        }, &out);
        testing.expectEqualSlices(u8, dgram, again) catch |e| {
            std.debug.print("golden '{s}' did not round-trip\n", .{g.name});
            return e;
        };
    }
}

test "goldens: every primitive tag decodes and re-encodes identically" {
    var buf: [32]u8 = undefined;
    var out: [32]u8 = undefined;
    for (primitives) |g| {
        const bytes = try bytesOf(g, &buf);
        const t = tag.decodeHeader(bytes) catch |e| {
            std.debug.print("primitive '{s}' header failed: {t}\n", .{ g.name, e });
            return e;
        };
        const n = try tag.encodeHeader(t, &out);
        testing.expectEqualSlices(u8, bytes[0..n], out[0..n]) catch |e| {
            std.debug.print("primitive '{s}' header not canonical\n", .{g.name});
            return e;
        };

        // Application-tagged ones must also survive a value round trip.
        if (t.class == .application and t.form == .primitive) {
            var r = tag.Reader.init(bytes);
            const v = try r.appValue();
            try testing.expect(r.atEnd());
            var w = tag.Writer.init(&out);
            w.appValue(v) catch |e| {
                std.debug.print("primitive '{s}' value re-encode failed: {t}\n", .{ g.name, e });
                return e;
            };
            testing.expectEqualSlices(u8, bytes, w.written()) catch |e| {
                std.debug.print("primitive '{s}' value not byte-identical\n", .{g.name});
                return e;
            };
        }
    }
}

fn find(name: []const u8) Golden {
    for (wire) |g| {
        if (std.mem.eql(u8, g.name, name)) return g;
    }
    unreachable;
}

test "goldens field by field: discovery" {
    var buf: [256]u8 = undefined;

    {
        const d = try decodeAll(try bytesOf(find("whois_unbounded"), &buf));
        try testing.expectEqual(bvll.Function.original_broadcast_npdu, d.bvlc.function());
        const u = d.apdu.unconfirmed_request;
        try testing.expectEqual(types.UnconfirmedService.who_is, u.service);
        const wi = try service.WhoIs.decode(u.data);
        try testing.expectEqual(@as(?u32, null), wi.low);
        try testing.expect(wi.matches(0) and wi.matches(4194303));
    }
    {
        const d = try decodeAll(try bytesOf(find("whois_range_1_100"), &buf));
        const wi = try service.WhoIs.decode(d.apdu.unconfirmed_request.data);
        try testing.expectEqual(@as(?u32, 1), wi.low);
        try testing.expectEqual(@as(?u32, 100), wi.high);
    }
    {
        // The wide form: high limit is the 22-bit maximum, encoded in 3
        // octets (`1b 3f ff ff`), which is the boundary an implementation that
        // hardcodes 4-octet unsigneds gets wrong.
        const d = try decodeAll(try bytesOf(find("whois_wide"), &buf));
        const wi = try service.WhoIs.decode(d.apdu.unconfirmed_request.data);
        try testing.expectEqual(@as(?u32, 0), wi.low);
        try testing.expectEqual(@as(?u32, 4194303), wi.high);
    }
    {
        const d = try decodeAll(try bytesOf(find("iam_599"), &buf));
        const iam = try service.IAm.decode(d.apdu.unconfirmed_request.data);
        try testing.expect(iam.device.eql(.{ .type = .device, .instance = 599 }));
        try testing.expectEqual(@as(u32, 1476), iam.max_apdu_accepted);
        try testing.expectEqual(types.Segmentation.none, iam.segmentation);
        try testing.expectEqual(@as(u16, 999), iam.vendor_id);
    }
    {
        const d = try decodeAll(try bytesOf(find("iam_segmented"), &buf));
        const iam = try service.IAm.decode(d.apdu.unconfirmed_request.data);
        try testing.expectEqual(tag.ObjectId.unconfigured_instance, iam.device.instance);
        try testing.expectEqual(@as(u32, 480), iam.max_apdu_accepted);
        try testing.expectEqual(types.Segmentation.both, iam.segmentation);
    }
    {
        const d = try decodeAll(try bytesOf(find("whohas_by_name"), &buf));
        const wh = try service.WhoHas.decode(d.apdu.unconfirmed_request.data);
        try testing.expectEqualStrings("ZONE-TEMP", wh.target.object_name);
        try testing.expectEqual(@as(?u32, null), wh.low);
    }
    {
        const d = try decodeAll(try bytesOf(find("whohas_by_id"), &buf));
        const wh = try service.WhoHas.decode(d.apdu.unconfirmed_request.data);
        try testing.expect(wh.target.object_id.eql(.{ .type = .analog_input, .instance = 3 }));
        try testing.expectEqual(@as(?u32, 1), wh.low);
        try testing.expectEqual(@as(?u32, 100), wh.high);
    }
    {
        const d = try decodeAll(try bytesOf(find("ihave"), &buf));
        const ih = try service.IHave.decode(d.apdu.unconfirmed_request.data);
        try testing.expect(ih.device.eql(.{ .type = .device, .instance = 599 }));
        try testing.expect(ih.object.eql(.{ .type = .analog_input, .instance = 3 }));
        try testing.expectEqualStrings("ZONE-TEMP", ih.object_name);
    }
}

test "goldens field by field: ReadProperty and its ACKs" {
    var buf: [256]u8 = undefined;
    {
        const d = try decodeAll(try bytesOf(find("readproperty_req"), &buf));
        const r = d.apdu.confirmed_request;
        try testing.expectEqual(@as(u8, 1), r.invoke_id);
        try testing.expectEqual(types.ConfirmedService.read_property, r.service);
        try testing.expectEqual(apdu.MaxApdu.up_to_1476, r.max_apdu);
        try testing.expectEqual(apdu.MaxSegments.unspecified, r.max_segments);
        try testing.expectEqual(@as(?apdu.SegmentInfo, null), r.segment);
        const rp = try service.ReadProperty.decode(r.data);
        try testing.expect(rp.object.eql(.{ .type = .analog_input, .instance = 5 }));
        try testing.expectEqual(types.PropertyIdentifier.present_value, rp.property);
        try testing.expectEqual(@as(?u32, null), rp.array_index);
    }
    {
        const d = try decodeAll(try bytesOf(find("readproperty_req_arrayindex"), &buf));
        const rp = try service.ReadProperty.decode(d.apdu.confirmed_request.data);
        try testing.expectEqual(types.PropertyIdentifier.object_list, rp.property);
        try testing.expectEqual(@as(?u32, 2), rp.array_index);
        try testing.expectEqual(@as(u8, 42), d.apdu.confirmed_request.invoke_id);
    }
    {
        // Property identifier 512 — the first vendor-proprietary value. It
        // needs two octets, which is where a 1-octet assumption breaks.
        const d = try decodeAll(try bytesOf(find("readproperty_req_proprietary_prop"), &buf));
        const rp = try service.ReadProperty.decode(d.apdu.confirmed_request.data);
        try testing.expectEqual(@as(u32, 512), @intFromEnum(rp.property));
        try testing.expect(rp.property.isProprietary());
    }
    {
        const d = try decodeAll(try bytesOf(find("readproperty_ack_real"), &buf));
        const c = d.apdu.complex_ack;
        try testing.expectEqual(@as(u8, 1), c.invoke_id);
        const ack = try service.ReadPropertyAck.decode(c.data);
        try testing.expectEqual(@as(f32, 72.5), (try ack.scalar()).real);
    }
    {
        const d = try decodeAll(try bytesOf(find("readproperty_ack_string"), &buf));
        const ack = try service.ReadPropertyAck.decode(d.apdu.complex_ack.data);
        try testing.expectEqual(types.PropertyIdentifier.object_name, ack.property);
        const cs = (try ack.scalar()).character_string;
        try testing.expectEqual(tag.StringEncoding.utf8, cs.encoding);
        try testing.expectEqualStrings("ZONE-1-TEMP", cs.asUtf8().?);
    }
    {
        const d = try decodeAll(try bytesOf(find("readproperty_ack_enum"), &buf));
        const ack = try service.ReadPropertyAck.decode(d.apdu.complex_ack.data);
        try testing.expect(ack.object.eql(.{ .type = .binary_input, .instance = 2 }));
        try testing.expectEqual(@as(u32, 1), (try ack.scalar()).enumerated);
        try testing.expectEqual(
            types.BinaryPV.active,
            @as(types.BinaryPV, @enumFromInt((try ack.scalar()).enumerated)),
        );
    }
    {
        // statusFlags is a 4-bit BitString: `82 04 00` = 1 unused-bit octet
        // saying 4, then one data octet.
        const d = try decodeAll(try bytesOf(find("readproperty_ack_statusflags"), &buf));
        const ack = try service.ReadPropertyAck.decode(d.apdu.complex_ack.data);
        const bs = (try ack.scalar()).bit_string;
        try testing.expectEqual(@as(u3, 4), bs.unused_bits);
        try testing.expectEqual(@as(usize, 4), bs.bitCount());
        const flags = types.StatusFlags.fromOctet(bs.bytes[0]);
        try testing.expect(!flags.in_alarm and !flags.fault and
            !flags.overridden and !flags.out_of_service);
    }
    {
        // Array index 0 asks for the array's *length*, and the answer is an
        // Unsigned, not an element.
        const d = try decodeAll(try bytesOf(find("readproperty_ack_arrayindex"), &buf));
        const ack = try service.ReadPropertyAck.decode(d.apdu.complex_ack.data);
        try testing.expectEqual(@as(?u32, 0), ack.array_index);
        try testing.expectEqual(@as(u64, 4), (try ack.scalar()).unsigned);
    }
}

test "goldens field by field: WriteProperty, priority and relinquish" {
    var buf: [256]u8 = undefined;
    {
        const d = try decodeAll(try bytesOf(find("writeproperty_req"), &buf));
        const wp = try service.WriteProperty.decode(d.apdu.confirmed_request.data);
        try testing.expect(wp.object.eql(.{ .type = .analog_value, .instance = 1 }));
        try testing.expectEqual(@as(?u8, null), wp.priority);
        try testing.expect(!wp.isRelinquish());
        var r = tag.Reader.init(wp.value);
        try testing.expectEqual(@as(f32, 21.0), (try r.appValue()).real);
    }
    {
        const d = try decodeAll(try bytesOf(find("writeproperty_req_priority"), &buf));
        const wp = try service.WriteProperty.decode(d.apdu.confirmed_request.data);
        try testing.expectEqual(@as(?u8, 8), wp.priority);
        try testing.expect(!wp.isRelinquish());
    }
    {
        // The relinquish: an application Null in the value block, at priority
        // 8. Byte for byte it is a write; semantically it hands the slot back.
        const d = try decodeAll(try bytesOf(find("writeproperty_relinquish"), &buf));
        const wp = try service.WriteProperty.decode(d.apdu.confirmed_request.data);
        try testing.expectEqual(@as(?u8, 8), wp.priority);
        try testing.expect(wp.isRelinquish());
        var r = tag.Reader.init(wp.value);
        try testing.expectEqual(tag.Value.null, try r.appValue());
    }
    {
        const d = try decodeAll(try bytesOf(find("writeproperty_string"), &buf));
        const wp = try service.WriteProperty.decode(d.apdu.confirmed_request.data);
        var r = tag.Reader.init(wp.value);
        try testing.expectEqualStrings(
            "BUILDING-A",
            (try r.appValue()).character_string.asUtf8().?,
        );
    }
    {
        const d = try decodeAll(try bytesOf(find("writeproperty_arrayindex"), &buf));
        const wp = try service.WriteProperty.decode(d.apdu.confirmed_request.data);
        try testing.expectEqual(@as(?u32, 3), wp.array_index);
        var r = tag.Reader.init(wp.value);
        try testing.expect((try r.appValue()).object_identifier.eql(
            .{ .type = .analog_input, .instance = 9 },
        ));
    }
}

test "goldens field by field: acks, errors, rejects and aborts" {
    var buf: [256]u8 = undefined;
    {
        const d = try decodeAll(try bytesOf(find("simpleack_writeproperty"), &buf));
        try testing.expectEqual(@as(u8, 10), d.apdu.simple_ack.invoke_id);
        try testing.expectEqual(types.ConfirmedService.write_property, d.apdu.simple_ack.service);
    }
    {
        const d = try decodeAll(try bytesOf(find("error_unknown_property"), &buf));
        const e = d.apdu.err;
        try testing.expectEqual(types.ConfirmedService.read_property, e.service);
        try testing.expectEqual(types.ErrorClass.object, e.class);
        try testing.expectEqual(types.ErrorCode.unknown_property, e.code);
    }
    {
        const d = try decodeAll(try bytesOf(find("error_write_access_denied"), &buf));
        const e = d.apdu.err;
        try testing.expectEqual(types.ErrorClass.property, e.class);
        try testing.expectEqual(types.ErrorCode.write_access_denied, e.code);
    }
    {
        const d = try decodeAll(try bytesOf(find("reject_unrecognized"), &buf));
        try testing.expectEqual(types.RejectReason.unrecognized_service, d.apdu.reject.reason);
    }
    {
        const d = try decodeAll(try bytesOf(find("reject_invalid_tag"), &buf));
        try testing.expectEqual(types.RejectReason.invalid_tag, d.apdu.reject.reason);
    }
    {
        // The Abort this module itself emits when a peer offers segmentation.
        const d = try decodeAll(try bytesOf(find("abort_segmentation"), &buf));
        try testing.expectEqual(types.AbortReason.segmentation_not_supported, d.apdu.abort.reason);
        try testing.expectEqual(true, d.apdu.abort.server);
        var out: [8]u8 = undefined;
        const mine = try apdu.encode(apdu.segmentationNotSupported(5, true), &out);
        var theirs: [8]u8 = undefined;
        const t = try std.fmt.hexToBytes(&theirs, "710504");
        try testing.expectEqualSlices(u8, t, mine);
    }
    {
        const d = try decodeAll(try bytesOf(find("abort_other_client"), &buf));
        try testing.expectEqual(false, d.apdu.abort.server);
        try testing.expectEqual(types.AbortReason.other, d.apdu.abort.reason);
    }
}

test "goldens field by field: ReadPropertyMultiple" {
    var buf: [256]u8 = undefined;
    {
        const d = try decodeAll(try bytesOf(find("rpm_req_two_props"), &buf));
        var it = service.RpmRequestIterator.init(d.apdu.confirmed_request.data);
        const spec = (try it.next()).?;
        try testing.expect(spec.object.eql(.{ .type = .analog_input, .instance = 5 }));
        var props = spec.properties();
        try testing.expectEqual(
            types.PropertyIdentifier.present_value,
            (try props.next()).?.property,
        );
        try testing.expectEqual(
            types.PropertyIdentifier.status_flags,
            (try props.next()).?.property,
        );
        try testing.expectEqual(@as(?service.PropertyReference, null), try props.next());
        try testing.expectEqual(@as(?service.RpmRequestIterator.Spec, null), try it.next());
    }
    {
        const d = try decodeAll(try bytesOf(find("rpm_req_all_required_optional"), &buf));
        var it = service.RpmRequestIterator.init(d.apdu.confirmed_request.data);
        var p1 = (try it.next()).?.properties();
        try testing.expectEqual(types.PropertyIdentifier.all, (try p1.next()).?.property);
        const second = (try it.next()).?;
        try testing.expect(second.object.eql(.{ .type = .device, .instance = 599 }));
        var p2 = second.properties();
        try testing.expectEqual(types.PropertyIdentifier.required, (try p2.next()).?.property);
        try testing.expectEqual(types.PropertyIdentifier.optional, (try p2.next()).?.property);
    }
    {
        const d = try decodeAll(try bytesOf(find("rpm_req_array_index"), &buf));
        var it = service.RpmRequestIterator.init(d.apdu.confirmed_request.data);
        var props = (try it.next()).?.properties();
        const ref = (try props.next()).?;
        try testing.expectEqual(types.PropertyIdentifier.object_list, ref.property);
        try testing.expectEqual(@as(?u32, 1), ref.array_index);
    }
    {
        const d = try decodeAll(try bytesOf(find("rpm_ack_two_props"), &buf));
        var it = service.RpmAckIterator.init(d.apdu.complex_ack.data);
        var els = (try it.next()).?.results();
        const e1 = (try els.next()).?;
        var r = tag.Reader.init(e1.outcome.value);
        try testing.expectEqual(@as(f32, 72.5), (try r.appValue()).real);
        const e2 = (try els.next()).?;
        try testing.expectEqual(types.PropertyIdentifier.status_flags, e2.property);
        var r2 = tag.Reader.init(e2.outcome.value);
        try testing.expectEqual(@as(u3, 4), (try r2.appValue()).bit_string.unused_bits);
    }
    {
        // The whole point of RPM: a failing property is reported *inside* the
        // ACK, not as a failure of the whole request.
        const d = try decodeAll(try bytesOf(find("rpm_ack_with_error"), &buf));
        var it = service.RpmAckIterator.init(d.apdu.complex_ack.data);
        const res = (try it.next()).?;
        try testing.expect(res.object.eql(.{ .type = .analog_input, .instance = 9 }));
        var els = res.results();
        const e = (try els.next()).?;
        try testing.expectEqual(types.ErrorClass.object, e.outcome.access_error.class);
        try testing.expectEqual(types.ErrorCode.unknown_object, e.outcome.access_error.code);
    }
}

test "goldens field by field: COV and ReadRange" {
    var buf: [256]u8 = undefined;
    {
        const d = try decodeAll(try bytesOf(find("subscribecov_req"), &buf));
        const s = try service.SubscribeCov.decode(d.apdu.confirmed_request.data);
        try testing.expectEqual(@as(u32, 7), s.process_id);
        try testing.expect(s.object.eql(.{ .type = .analog_input, .instance = 5 }));
        try testing.expectEqual(@as(?bool, true), s.confirmed);
        try testing.expectEqual(@as(?u32, 300), s.lifetime);
        try testing.expect(!s.isCancellation());
    }
    {
        const d = try decodeAll(try bytesOf(find("subscribecov_cancel"), &buf));
        const s = try service.SubscribeCov.decode(d.apdu.confirmed_request.data);
        try testing.expect(s.isCancellation());
        try testing.expectEqual(@as(?bool, null), s.confirmed);
    }
    {
        const d = try decodeAll(try bytesOf(find("subscribecov_unconfirmed_indefinite"), &buf));
        const s = try service.SubscribeCov.decode(d.apdu.confirmed_request.data);
        try testing.expectEqual(@as(?bool, false), s.confirmed);
        try testing.expectEqual(@as(?u32, 0), s.lifetime);
        try testing.expect(!s.isCancellation());
    }
    {
        const d = try decodeAll(try bytesOf(find("unconfirmed_cov_notification"), &buf));
        try testing.expectEqual(
            types.UnconfirmedService.unconfirmed_cov_notification,
            d.apdu.unconfirmed_request.service,
        );
        const n = try service.CovNotification.decode(d.apdu.unconfirmed_request.data);
        try testing.expectEqual(@as(u32, 7), n.process_id);
        try testing.expect(n.initiating_device.eql(.{ .type = .device, .instance = 599 }));
        try testing.expect(n.monitored_object.eql(.{ .type = .analog_input, .instance = 5 }));
        try testing.expectEqual(@as(u32, 280), n.time_remaining);
        var vals = n.values();
        const v1 = (try vals.next()).?;
        try testing.expectEqual(types.PropertyIdentifier.present_value, v1.property);
        var r = tag.Reader.init(v1.value);
        try testing.expectEqual(@as(f32, 72.5), (try r.appValue()).real);
        const v2 = (try vals.next()).?;
        try testing.expectEqual(types.PropertyIdentifier.status_flags, v2.property);
        try testing.expectEqual(@as(?service.CovValue, null), try vals.next());
    }
    {
        // The confirmed form has identical parameters — only the APDU type
        // and service choice differ.
        const d = try decodeAll(try bytesOf(find("confirmed_cov_notification"), &buf));
        const r = d.apdu.confirmed_request;
        try testing.expectEqual(types.ConfirmedService.confirmed_cov_notification, r.service);
        try testing.expectEqual(@as(u8, 40), r.invoke_id);
        const n = try service.CovNotification.decode(r.data);
        try testing.expectEqual(@as(u32, 280), n.time_remaining);
    }
    {
        const d = try decodeAll(try bytesOf(find("readrange_req_byposition"), &buf));
        const rr = try service.ReadRange.decode(d.apdu.confirmed_request.data);
        try testing.expect(rr.object.eql(.{ .type = .trend_log, .instance = 1 }));
        try testing.expectEqual(types.PropertyIdentifier.log_buffer, rr.property);
        try testing.expectEqual(@as(u32, 1), rr.range.?.by_position.reference_index);
        try testing.expectEqual(@as(i32, 10), rr.range.?.by_position.count);
    }
    {
        const d = try decodeAll(try bytesOf(find("readrange_req_all"), &buf));
        const rr = try service.ReadRange.decode(d.apdu.confirmed_request.data);
        try testing.expectEqual(@as(?service.ReadRange.Range, null), rr.range);
    }
}

test "goldens: our own encoders reproduce the third-party service bodies" {
    // The round-trip test above rebuilds the APDU from decoded *fields*; this
    // one rebuilds the service *body* from scratch, so the service encoders
    // are checked too rather than being carried along as opaque bytes.
    var buf: [256]u8 = undefined;
    var out: [256]u8 = undefined;

    {
        const d = try decodeAll(try bytesOf(find("whois_range_1_100"), &buf));
        var w = tag.Writer.init(&out);
        try (service.WhoIs{ .low = 1, .high = 100 }).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.unconfirmed_request.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("iam_599"), &buf));
        var w = tag.Writer.init(&out);
        try (service.IAm{
            .device = .{ .type = .device, .instance = 599 },
            .max_apdu_accepted = 1476,
            .segmentation = .none,
            .vendor_id = 999,
        }).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.unconfirmed_request.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("whohas_by_name"), &buf));
        var w = tag.Writer.init(&out);
        try (service.WhoHas{ .target = .{ .object_name = "ZONE-TEMP" } }).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.unconfirmed_request.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("readproperty_req"), &buf));
        var w = tag.Writer.init(&out);
        try (service.ReadProperty{
            .object = .{ .type = .analog_input, .instance = 5 },
            .property = .present_value,
        }).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.confirmed_request.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("readproperty_ack_real"), &buf));
        var vbuf: [8]u8 = undefined;
        var vw = tag.Writer.init(&vbuf);
        try vw.appReal(72.5);
        var w = tag.Writer.init(&out);
        try (service.ReadPropertyAck{
            .object = .{ .type = .analog_input, .instance = 5 },
            .property = .present_value,
            .value = vw.written(),
        }).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.complex_ack.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("writeproperty_relinquish"), &buf));
        var w = tag.Writer.init(&out);
        try service.WriteProperty.relinquish(
            .{ .type = .analog_output, .instance = 1 },
            .present_value,
            8,
        ).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.confirmed_request.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("rpm_req_all_required_optional"), &buf));
        var w = tag.Writer.init(&out);
        var b = service.RpmRequestBuilder.init(&w);
        try b.object(.{ .type = .analog_input, .instance = 5 });
        try b.property(.{ .property = .all });
        try b.object(.{ .type = .device, .instance = 599 });
        try b.property(.{ .property = .required });
        try b.property(.{ .property = .optional });
        try b.finish();
        try testing.expectEqualSlices(u8, d.apdu.confirmed_request.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("rpm_ack_with_error"), &buf));
        var w = tag.Writer.init(&out);
        var b = service.RpmAckBuilder.init(&w);
        try b.object(.{ .type = .analog_input, .instance = 9 });
        try b.accessError(.present_value, null, .object, .unknown_object);
        try b.finish();
        try testing.expectEqualSlices(u8, d.apdu.complex_ack.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("subscribecov_req"), &buf));
        var w = tag.Writer.init(&out);
        try (service.SubscribeCov{
            .process_id = 7,
            .object = .{ .type = .analog_input, .instance = 5 },
            .confirmed = true,
            .lifetime = 300,
        }).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.confirmed_request.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("unconfirmed_cov_notification"), &buf));
        var vbuf: [64]u8 = undefined;
        var vw = tag.Writer.init(&vbuf);
        var pv_buf: [8]u8 = undefined;
        var iw1 = tag.Writer.init(&pv_buf);
        try iw1.appReal(72.5);
        try service.writeCovValue(&vw, .{ .property = .present_value, .value = iw1.written() });
        var sf_buf: [8]u8 = undefined;
        var iw2 = tag.Writer.init(&sf_buf);
        try iw2.appBitString(.{ .unused_bits = 4, .bytes = &.{0x00} });
        try service.writeCovValue(&vw, .{ .property = .status_flags, .value = iw2.written() });

        var w = tag.Writer.init(&out);
        try (service.CovNotification{
            .process_id = 7,
            .initiating_device = .{ .type = .device, .instance = 599 },
            .monitored_object = .{ .type = .analog_input, .instance = 5 },
            .time_remaining = 280,
            .values_block = vw.written(),
        }).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.unconfirmed_request.data, w.written());
    }
    {
        const d = try decodeAll(try bytesOf(find("readrange_req_byposition"), &buf));
        var w = tag.Writer.init(&out);
        try (service.ReadRange{
            .object = .{ .type = .trend_log, .instance = 1 },
            .property = .log_buffer,
            .range = .{ .by_position = .{ .reference_index = 1, .count = 10 } },
        }).encode(&w);
        try testing.expectEqualSlices(u8, d.apdu.confirmed_request.data, w.written());
    }
}

test "goldens: the table covers every PDU type and every modelled service" {
    var buf: [256]u8 = undefined;
    var seen_pdu = std.EnumSet(apdu.PduType).initEmpty();
    var seen_confirmed = std.AutoHashMap(types.ConfirmedService, void).init(testing.allocator);
    defer seen_confirmed.deinit();
    var seen_unconfirmed = std.AutoHashMap(types.UnconfirmedService, void).init(testing.allocator);
    defer seen_unconfirmed.deinit();

    for (wire) |g| {
        const d = try decodeAll(try bytesOf(g, &buf));
        seen_pdu.insert(d.apdu.pduType());
        switch (d.apdu) {
            .confirmed_request => |r| try seen_confirmed.put(r.service, {}),
            .unconfirmed_request => |u| try seen_unconfirmed.put(u.service, {}),
            .complex_ack => |c| try seen_confirmed.put(c.service, {}),
            .simple_ack => |s| try seen_confirmed.put(s.service, {}),
            else => {},
        }
    }

    // Seven of the eight PDU types are here; SegmentACK is not, because
    // nothing in this module produces or consumes a segmented transfer (see
    // SPEC.md's deferred list) and a golden for it would be self-derived.
    for ([_]apdu.PduType{
        .confirmed_request, .unconfirmed_request, .simple_ack,
        .complex_ack,       .err,                 .reject,
        .abort,
    }) |t| {
        try testing.expect(seen_pdu.contains(t));
    }
    try testing.expect(!seen_pdu.contains(.segment_ack));

    for ([_]types.ConfirmedService{
        .read_property, .read_property_multiple,     .write_property,
        .subscribe_cov, .confirmed_cov_notification, .read_range,
    }) |s| {
        try testing.expect(seen_confirmed.contains(s));
    }
    for ([_]types.UnconfirmedService{
        .who_is, .i_am, .who_has, .i_have, .unconfirmed_cov_notification,
    }) |s| {
        try testing.expect(seen_unconfirmed.contains(s));
    }
}
