// SPDX-License-Identifier: MIT

//! **Byte-exact BACnet/SC goldens, and the byte-order question they settled.**
//!
//! Every frame in `wire` was emitted by Python **bacpypes3 0.0.106**'s
//! `bacpypes3.sc.bvll` encoders, driven as a black box: construct the LPDU,
//! set its header fields, call `encode()`, print the octets. Nothing in
//! `sc.zig` was derived from them — they are the oracle, checked against
//! afterwards.
//!
//! Three assertions run over the whole table:
//!
//! 1. **Every frame decodes**, header and body.
//! 2. **Every frame re-encodes to the identical octets** from its *decoded*
//!    fields, through this module's own writer. So it is the encoder under
//!    test, not a memcpy.
//! 3. **A representative subset is asserted field by field**, and a coverage
//!    test asserts the table really does contain all thirteen BVLC functions
//!    so it cannot silently rot.
//!
//! ## The byte-order finding
//!
//! A **second** independent implementation was compiled and driven as an
//! oracle: `bvlc-sc.c` from the **bacnet-stack** project (C, GPL-2.0 with
//! linking exception; nothing was copied — it was compiled and run through its
//! published prototypes). The two stacks agree on **every structural
//! question** — field order, field widths, which control bit means what, the
//! option marker's bit layout, that the option Header Length is two octets,
//! that destination options precede data options which precede the payload,
//! and that a `BVLC-Result` NAK is marker/class/code/details with no
//! terminator on the details string.
//!
//! They disagree on exactly one thing: bacnet-stack writes every 16-bit field
//! (message id, option header length, the connect maxima, the error class and
//! code, the proprietary vendor id) **little-endian**; bacpypes3 writes them
//! **big-endian**. Wireshark 4.6.4's `packet-bvlc.c` BACnet/SC dissector — a
//! third, independent reading of Annex AB — dissects all of them with
//! `ENC_BIG_ENDIAN`, and big-endian is BACnet's convention everywhere else
//! (Annex J's BVLC length, the NPDU's DNET/SNET, every clause 20.2 multi-octet
//! value). **This module is big-endian.** `bacnet_stack_divergence` below
//! records the disagreement as a live test rather than a comment, so the
//! decision stays visible.
//!
//! See SPEC.md for what is third-party-validated versus self-derived.

const std = @import("std");
const types = @import("types.zig");
const sc = @import("sc.zig");

pub const Golden = struct {
    name: []const u8,
    /// One complete BACnet/SC BVLC message — what would ride in one binary
    /// WebSocket frame.
    hex: []const u8,
};

/// 29 frames generated by bacpypes3. The VMACs, the UUID and the URIs are
/// synthetic: `01:02:03:04:05:06` / `0a:0b:0c:0d:0e:0f`, the all-counting-up
/// UUID, and the `192.0.2.0/24` documentation range. No real device identity
/// or certificate appears anywhere.
pub const wire = [_]Golden{
    // ── the four-octet minimum, one per empty-body function ────────────────
    .{ .name = "heartbeat_request_min", .hex = "0a000001" },
    .{ .name = "heartbeat_ack_min", .hex = "0b000001" },
    .{ .name = "disconnect_request_min", .hex = "08001234" },
    .{ .name = "disconnect_ack_min", .hex = "09001234" },
    .{ .name = "address_resolution_min", .hex = "02000007" },
    .{ .name = "advertisement_solicitation", .hex = "05000008" },

    // ── every combination of the two VMAC control bits ─────────────────────
    .{ .name = "heartbeat_request_src", .hex = "0a080002010203040506" },
    .{ .name = "heartbeat_request_dst", .hex = "0a0400030a0b0c0d0e0f" },
    .{ .name = "heartbeat_request_both", .hex = "0a0cffff0102030405060a0b0c0d0e0f" },

    // ── connect negotiation ────────────────────────────────────────────────
    .{
        .name = "connect_request",
        .hex = "0600000101020304050600112233445566778899aabbccddeeff05780514",
    },
    .{
        .name = "connect_accept",
        .hex = "070000010a0b0c0d0e0f00112233445566778899aabbccddeeff05780514",
    },
    .{
        .name = "connect_request_max",
        .hex = "0608abcd0a0b0c0d0e0f0a0b0c0d0e0f00112233445566778899aabbccddeeffffffffff",
    },

    // ── advertisement, all three hub-connection states ─────────────────────
    .{ .name = "advertisement", .hex = "04000005010105780514" },
    .{ .name = "advertisement_nohub", .hex = "04000006000005d905c4" },
    .{ .name = "advertisement_failover", .hex = "04080006010203040506020005d905c4" },

    // ── address resolution ─────────────────────────────────────────────────
    .{ .name = "address_resolution_ack_empty", .hex = "03000009" },
    .{
        .name = "address_resolution_ack_uris",
        .hex = "030c000a0102030405060a0b0c0d0e0f" ++
            "7773733a2f2f3139322e302e322e312f207773733a2f2f3139322e302e322e323a383434332f",
    },

    // ── BVLC-Result, ACK and both NAK spellings ────────────────────────────
    .{ .name = "result_ack", .hex = "000000010600" },
    .{ .name = "result_nak", .hex = "00000001060100000700976475706c6963617465" },
    .{ .name = "result_nak_no_details", .hex = "0000020301011f00070092" },

    // ── encapsulated NPDU ──────────────────────────────────────────────────
    .{
        .name = "encapsulated_npdu",
        .hex = "010c00110102030405060a0b0c0d0e0f0120ffff00ff1008",
    },
    .{ .name = "encapsulated_npdu_bare", .hex = "0100000101040275010c0c000000051955" },

    // ── proprietary message ────────────────────────────────────────────────
    .{ .name = "proprietary_message", .hex = "0c0000aa03e72adeadbeef" },

    // ── header options, which is where the fiddly encoding lives ───────────
    .{ .name = "encapsulated_secure_path_dest", .hex = "01020100410100" },
    .{ .name = "encapsulated_secure_path_data", .hex = "01010101410100" },
    .{ .name = "encapsulated_proprietary_option", .hex = "010201023f000503e70301020100" },
    .{ .name = "encapsulated_two_options", .hex = "01020103c13f00030001000100" },
    .{ .name = "encapsulated_all_fields", .hex = "010f01040102030405060a0b0c0d0e0f41410100" },
    .{
        .name = "connect_request_secure_path",
        .hex = "060201054101020304050600112233445566778899aabbccddeeff05780514",
    },
};

fn bytes(g: Golden, buf: []u8) []u8 {
    return std.fmt.hexToBytes(buf, g.hex) catch unreachable;
}

/// Looks a golden up by name. Indices into `wire` would silently point at the
/// wrong frame the moment a vector is inserted; a name cannot.
fn named(comptime name: []const u8) Golden {
    const index = comptime blk: {
        for (wire, 0..) |g, i| {
            if (std.mem.eql(u8, g.name, name)) break :blk i;
        }
        @compileError("no golden named " ++ name);
    };
    return wire[index];
}

// ── tests ──────────────────────────────────────────────────────────────────

const testing = std.testing;

test "every third-party frame decodes" {
    var buf: [256]u8 = undefined;
    for (wire) |g| {
        const frame = bytes(g, &buf);
        _ = sc.decode(frame) catch |e| {
            std.debug.print("golden {s} failed to decode: {t}\n", .{ g.name, e });
            return e;
        };
    }
}

test "every third-party frame re-encodes to the identical octets" {
    // Rebuilt from the *decoded* fields through this module's own writer, so a
    // regression in the encoder cannot hide behind a memcpy of the input.
    var buf: [256]u8 = undefined;
    var out: [256]u8 = undefined;
    for (wire) |g| {
        const frame = bytes(g, &buf);
        const msg = try sc.decode(frame);
        const again = try sc.encode(msg, &out);
        testing.expectEqualSlices(u8, frame, again) catch |e| {
            std.debug.print("golden {s} did not round-trip\n", .{g.name});
            return e;
        };
    }
}

test "the golden table covers all thirteen BVLC functions" {
    var seen = [_]bool{false} ** 13;
    var buf: [256]u8 = undefined;
    for (wire) |g| {
        const msg = try sc.decode(bytes(g, &buf));
        seen[@intFromEnum(msg.function())] = true;
    }
    for (seen, 0..) |ok, i| {
        if (!ok) {
            std.debug.print("no golden for BVLC function 0x{x:0>2}\n", .{i});
            return error.MissingCoverage;
        }
    }
}

test "field by field: connect_request" {
    var buf: [64]u8 = undefined;
    const msg = try sc.decode(bytes(named("connect_request"), &buf));
    try testing.expectEqual(@as(u16, 1), msg.header.message_id);
    try testing.expectEqual(@as(?sc.Vmac, null), msg.header.source);
    const c = msg.payload.connect_request;
    try testing.expectEqualSlices(u8, &.{ 1, 2, 3, 4, 5, 6 }, &c.vmac.octets);
    var text: [40]u8 = undefined;
    try testing.expectEqualStrings(
        "00112233-4455-6677-8899-aabbccddeeff",
        try std.fmt.bufPrint(&text, "{f}", .{c.uuid}),
    );
    try testing.expectEqual(@as(u16, 1400), c.max_bvlc_length);
    try testing.expectEqual(@as(u16, 1300), c.max_npdu_length);
}

test "field by field: the maximum connect proposal" {
    var buf: [64]u8 = undefined;
    const msg = try sc.decode(bytes(named("connect_request_max"), &buf));
    try testing.expectEqual(@as(u16, 0xABCD), msg.header.message_id);
    try testing.expect(msg.header.source != null);
    try testing.expectEqual(@as(u16, 65535), msg.payload.connect_request.max_bvlc_length);
    try testing.expectEqual(@as(u16, 65535), msg.payload.connect_request.max_npdu_length);
}

test "field by field: advertisement, all three hub states" {
    var buf: [64]u8 = undefined;
    const primary = try sc.decode(bytes(named("advertisement"), &buf));
    try testing.expectEqual(sc.HubConnectionStatus.connected_to_primary, primary.payload.advertisement.hub_status);
    try testing.expectEqual(sc.DirectConnectionSupport.supported, primary.payload.advertisement.direct_connections);
    try testing.expectEqual(@as(u16, 1400), primary.payload.advertisement.max_bvlc_length);

    const none = try sc.decode(bytes(named("advertisement_nohub"), &buf));
    try testing.expectEqual(sc.HubConnectionStatus.no_hub_connection, none.payload.advertisement.hub_status);
    try testing.expectEqual(sc.DirectConnectionSupport.unsupported, none.payload.advertisement.direct_connections);
    try testing.expectEqual(@as(u16, 1497), none.payload.advertisement.max_bvlc_length);
    try testing.expectEqual(@as(u16, 1476), none.payload.advertisement.max_npdu_length);

    const failover = try sc.decode(bytes(named("advertisement_failover"), &buf));
    try testing.expectEqual(sc.HubConnectionStatus.connected_to_failover, failover.payload.advertisement.hub_status);
    try testing.expectEqualSlices(u8, &.{ 1, 2, 3, 4, 5, 6 }, &failover.header.source.?.octets);
}

test "field by field: the NAK's error block" {
    var buf: [64]u8 = undefined;
    const msg = try sc.decode(bytes(named("result_nak"), &buf));
    const r = msg.payload.result;
    try testing.expectEqual(sc.Function.connect_request, r.function);
    try testing.expectEqual(sc.ResultCode.nak, r.code);
    try testing.expectEqual(types.ErrorClass.communication, r.err.?.class);
    try testing.expectEqual(types.ErrorCode.node_duplicate_vmac, r.err.?.code);
    try testing.expectEqualStrings("duplicate", r.err.?.details);
}

test "field by field: an option list of two, with the more bit chaining them" {
    var buf: [64]u8 = undefined;
    const msg = try sc.decode(bytes(named("encapsulated_two_options"), &buf));
    var it = sc.optionIterator(msg.header.destination_options);
    const first = (try it.next()).?;
    try testing.expectEqual(sc.OptionType.secure_path, first.type);
    try testing.expect(first.must_understand);
    try testing.expectEqual(@as(?[]const u8, null), first.data);
    const second = (try it.next()).?;
    const p = try second.asProprietary();
    try testing.expectEqual(@as(u16, 1), p.vendor_id);
    try testing.expectEqual(@as(u8, 0), p.option_type);
    try testing.expectEqual(@as(usize, 0), p.data.len);
    try testing.expectEqual(@as(?sc.Option, null), try it.next());
    try testing.expectEqualSlices(u8, &.{ 0x01, 0x00 }, msg.payload.encapsulated_npdu);
}

test "field by field: both option lists and both VMACs at once" {
    var buf: [64]u8 = undefined;
    const msg = try sc.decode(bytes(named("encapsulated_all_fields"), &buf));
    try testing.expectEqual(@as(u8, 0x0F), msg.header.controlOctet());
    try testing.expectEqual(@as(usize, 1), msg.header.destination_options.len);
    try testing.expectEqual(@as(usize, 1), msg.header.data_options.len);
    try testing.expect(msg.header.hasSecurePath());
    try testing.expectEqual(@as(?sc.Option, null), try msg.header.unsupportedOption());
}

test "the bodies are rebuilt from scratch, not carried along as opaque octets" {
    // Encoding from freshly-constructed values, with no decode in the loop,
    // is what proves the *encoder* agrees with the oracle rather than the
    // decoder agreeing with itself.
    var out: [64]u8 = undefined;

    const cr: sc.Message = .{
        .header = .{ .message_id = 1 },
        .payload = .{ .connect_request = .{
            .vmac = .{ .octets = .{ 1, 2, 3, 4, 5, 6 } },
            .uuid = sc.Uuid.parse("00112233-4455-6677-8899-aabbccddeeff").?,
            .max_bvlc_length = 1400,
            .max_npdu_length = 1300,
        } },
    };
    var expect: [64]u8 = undefined;
    try testing.expectEqualSlices(
        u8,
        bytes(named("connect_request"), &expect),
        try sc.encode(cr, &out),
    );

    const adv: sc.Message = .{
        .header = .{ .message_id = 5 },
        .payload = .{ .advertisement = .{
            .hub_status = .connected_to_primary,
            .direct_connections = .supported,
            .max_bvlc_length = 1400,
            .max_npdu_length = 1300,
        } },
    };
    try testing.expectEqualSlices(
        u8,
        bytes(named("advertisement"), &expect),
        try sc.encode(adv, &out),
    );

    const bad = sc.nak(.connect_request, 1, null, null, .{
        .header_marker = 0,
        .class = .communication,
        .code = .node_duplicate_vmac,
        .details = "duplicate",
    });
    try testing.expectEqualSlices(
        u8,
        bytes(named("result_nak"), &expect),
        try sc.encode(bad, &out),
    );

    const pm: sc.Message = .{
        .header = .{ .message_id = 0x00AA },
        .payload = .{ .proprietary_message = .{
            .vendor_id = 999,
            .function = 42,
            .data = &.{ 0xDE, 0xAD, 0xBE, 0xEF },
        } },
    };
    try testing.expectEqualSlices(
        u8,
        bytes(named("proprietary_message"), &expect),
        try sc.encode(pm, &out),
    );
}

test "the header option list is rebuilt from scratch too" {
    var data: [8]u8 = undefined;
    const pd = try sc.encodeProprietaryOptionData(
        .{ .vendor_id = 1, .option_type = 0, .data = &.{} },
        &data,
    );
    var list: [16]u8 = undefined;
    const opts = try sc.encodeOptions(&.{
        sc.Option.secure_path,
        .{ .type = .proprietary, .must_understand = false, .data = pd },
    }, &list);

    const msg: sc.Message = .{
        .header = .{ .message_id = 0x0103, .destination_options = opts },
        .payload = .{ .encapsulated_npdu = &.{ 0x01, 0x00 } },
    };
    var out: [64]u8 = undefined;
    var expect: [64]u8 = undefined;
    try testing.expectEqualSlices(
        u8,
        bytes(named("encapsulated_two_options"), &expect),
        try sc.encode(msg, &out),
    );
}

test "bacnet_stack_divergence: a second oracle disagrees on byte order only" {
    // These four frames came from bacnet-stack's `bvlc-sc.c`, compiled and run
    // as a black box for exactly the same inputs as the bacpypes3 goldens
    // above. Every structural decision matches; every 16-bit field is byte
    // swapped. The test states that as fact so the decision to follow
    // bacpypes3 and Wireshark (big-endian) stays visible and reviewable rather
    // than living in a comment.
    var buf: [64]u8 = undefined;

    // bacnet-stack's Heartbeat-Request with message id 1.
    const hb = try sc.decode(std.fmt.hexToBytes(&buf, "0a000100") catch unreachable);
    try testing.expectEqual(sc.Function.heartbeat_request, hb.function());
    // Big-endian reading: 0x0100. Little-endian would have been 1.
    try testing.expectEqual(@as(u16, 0x0100), hb.header.message_id);

    // ... and its Connect-Request, whose maxima come out byte-swapped.
    const cr = try sc.decode(std.fmt.hexToBytes(
        &buf,
        "0600010001020304050600112233445566778899aabbccddeeff78051405",
    ) catch unreachable);
    try testing.expectEqual(@as(u16, 0x7805), cr.payload.connect_request.max_bvlc_length);
    try testing.expectEqual(@as(u16, 0x1405), cr.payload.connect_request.max_npdu_length);

    // The two stacks *do* agree octet for octet whenever every 16-bit field is
    // a palindrome — message id 0x0101 here — which isolates the disagreement
    // to byte order and nothing else.
    const both_agree = "01010101410100";
    const decoded = try sc.decode(std.fmt.hexToBytes(&buf, both_agree) catch unreachable);
    try testing.expectEqual(@as(u16, 0x0101), decoded.header.message_id);
    try testing.expect(decoded.header.hasSecurePath());
    var out: [32]u8 = undefined;
    try testing.expectEqualSlices(
        u8,
        std.fmt.hexToBytes(buf[32..], both_agree) catch unreachable,
        try sc.encode(decoded, &out),
    );
}
