// SPDX-License-Identifier: MIT

//! kat_test -- byte-exact known-answer tests against an INDEPENDENT re-derivation.
//!
//! `kat_vectors.zig` is generated by `tools/rederive.py`, a stdlib-only Python
//! implementation of the two-server DPF PIR written from the SPECs (BGI16 Gen and
//! Eval over the SHA-256 PRG, the server's ring inner product, the client's
//! word-wise sum). Before emitting anything the script reproduces every `fss`
//! KAT byte-exact, so the DPF underneath is the already-anchored one.
//!
//! The vectors are stated over `fss.prg.Sha256Prg` for the reason `fss` states
//! its own: one body of correction-word code serves every PRG, and only the
//! SHA-256 instantiation can be re-derived from a standard library alone.
//!
//! Label: DERIVED (an in-house re-derivation by a different route, in a
//! different language). It catches implementation typos in `query`, the
//! record-to-word decomposition, the inner product and the codecs; it does NOT
//! catch a misreading of the construction that the script shares with the
//! module. There is no EXTERNAL vector for this composition (SPEC.md).

const std = @import("std");
const fss = @import("fss");
const pir = @import("pir.zig");
const db_mod = @import("db.zig");
const kat_vectors = @import("kat_vectors.zig");

fn KatPir(comptime v: anytype) type {
    return pir.PirWith(fss.prg.Sha256Prg, v.domain_bits, v.word_bytes);
}

test "DERIVED: query shares are byte-exact against the Python re-derivation" {
    inline for (kat_vectors.all) |v| {
        const P = KatPir(v);
        const shares = try P.query(v.index, v.seed0, v.seed1);
        var b0: [P.share_len]u8 = undefined;
        var b1: [P.share_len]u8 = undefined;
        P.shareToBytes(shares[0], &b0);
        P.shareToBytes(shares[1], &b1);
        try std.testing.expectEqualSlices(u8, v.share0, &b0);
        try std.testing.expectEqualSlices(u8, v.share1, &b1);
    }
}

test "DERIVED: server answers are byte-exact, computed from the recorded shares" {
    inline for (kat_vectors.all) |v| {
        const P = KatPir(v);
        const database = try db_mod.Database.init(v.db, v.record_len);
        try std.testing.expectEqual(v.count, database.count());
        const n_words = comptime P.answerWords(v.record_len);
        const shares = [2]P.Share{
            try P.shareFromBytes(v.share0),
            try P.shareFromBytes(v.share1),
        };
        var w0: [n_words]P.Word = undefined;
        var w1: [n_words]P.Word = undefined;
        try P.answer(0, shares[0], database, &w0);
        try P.answer(1, shares[1], database, &w1);
        var a0: [n_words * v.word_bytes]u8 = undefined;
        var a1: [n_words * v.word_bytes]u8 = undefined;
        try P.answerToBytes(&w0, &a0);
        try P.answerToBytes(&w1, &a1);
        try std.testing.expectEqualSlices(u8, v.answer0, &a0);
        try std.testing.expectEqualSlices(u8, v.answer1, &a1);
    }
}

test "DERIVED: the recorded answers reconstruct the recorded record" {
    inline for (kat_vectors.all) |v| {
        const P = KatPir(v);
        var rec: [v.record_len]u8 = undefined;
        try P.reconstructFromBytes(v.answer0, v.answer1, &rec);
        try std.testing.expectEqualSlices(u8, v.record, &rec);
        if (v.index < v.count) {
            const at = v.index * v.record_len;
            try std.testing.expectEqualSlices(u8, v.db[at..][0..v.record_len], &rec);
        } else {
            // in-domain but unpopulated index: the base layer reconstructs zeros
            try std.testing.expectEqualSlices(u8, &[_]u8{0} ** v.record_len, &rec);
        }
    }
}
