#!/usr/bin/env python3
"""Differential oracle for `numparse.parse`: Babel (BSD-3-Clause) as a black box.

Two jobs, both through Babel's public API only:

1. `--check-table`: compare the CLDR symbols hard-coded in `numparse.locale`
   (group, decimal, grouping) with what Babel's CLDR data says. Exit 1 on any
   mismatch.
2. default: write `src/testdata/babel_golden.txt` — one line per case,
   `locale<TAB>input<TAB>expected`, where `expected` is what
   `babel.numbers.parse_decimal(input, locale, strict=True)` returns as a
   plain decimal string, or `-` when it refuses. Inputs are Babel's own
   formatting of random values (must parse) plus systematic corruptions of
   them (wrong group widths, swapped or mixed separators, a leading-zero
   group, a dangling separator), so both acceptance and refusal are covered.

Babel's strict mode has a few behaviours `numparse` deliberately does not copy
(listed in SPEC.md "Verification"); those input shapes are simply not
generated here: a leading '+' or U+2212, a trailing decimal separator, an
exponent, an empty integer part before the decimal separator, and leading
zeros on an UNGROUPED integer (Babel's strict re-format check refuses
`0123`; numparse reads it as 123, like Decimal.parse).

    modules/numparse/tools/babel-oracle.py --check-table
    modules/numparse/tools/babel-oracle.py > modules/numparse/src/testdata/babel_golden.txt
"""
import random
import sys
from decimal import Decimal

from babel import Locale
from babel.numbers import NumberFormatError, format_decimal, parse_decimal

# Mirror of the table in src/root.zig `locale` (name, group, decimal, grouping).
TABLE = [
    ("en", ",", ".", "western"), ("en_US", ",", ".", "western"),
    ("en_GB", ",", ".", "western"), ("en_IN", ",", ".", "indian"),
    ("hi", ",", ".", "indian"), ("ja", ",", ".", "western"),
    ("zh", ",", ".", "western"), ("de", ".", ",", "western"),
    ("de_AT", ".", ",", "western"), ("de_CH", "’", ".", "western"),
    ("it", ".", ",", "western"), ("es", ".", ",", "western"),
    ("pt_BR", ".", ",", "western"), ("nl", ".", ",", "western"),
    ("da", ".", ",", "western"), ("fr", " ", ",", "western"),
    ("cs", " ", ",", "western"), ("sk", " ", ",", "western"),
    ("pl", " ", ",", "western"), ("ru", " ", ",", "western"),
    ("uk", " ", ",", "western"), ("sv", " ", ",", "western"),
    ("fi", " ", ",", "western"), ("hu", " ", ",", "western"),
    ("nb", " ", ",", "western"),
]


def check_table():
    bad = 0
    for name, group, dec, grouping in TABLE:
        loc = Locale.parse(name)
        sym = loc.number_symbols["latn"]
        pattern = loc.decimal_formats[None].pattern
        want_grouping = "indian" if "#,##,##0" in pattern else "western"
        got = (sym["group"], sym["decimal"], want_grouping)
        if got != (group, dec, grouping):
            print(f"MISMATCH {name}: table {(group, dec, grouping)!r} CLDR {got!r}")
            bad += 1
    print(f"table: {len(TABLE)} locales, {bad} mismatches")
    return bad == 0


def plain(d):
    s = format(d, "f")
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    if s in ("-0", ""):
        s = "0"
    return s


def oracle(text, name):
    try:
        return plain(parse_decimal(text, locale=name, strict=True))
    except (NumberFormatError, ValueError):
        return "-"


def corruptions(text, group, dec):
    out = []
    if group in text:
        i = text.index(group)
        out.append(text[:i] + text[i + len(group):])          # drop one separator
        out.append(text[: i + len(group) + 1] + group + text[i + len(group) + 1:])  # split a group
        out.append(text.replace(group, dec, 1))                 # swap the first separator
        out.append("0" + text)                                  # leading-zero first group
        out.append(text + group)                                # dangling separator
        if group != " ":
            out.append(text.replace(group, " ", 1))             # mixed spelling
    if dec in text:
        i = text.index(dec)
        out.append(text[:i] + group + text[i + len(dec):])      # decimal → group
        out.append(text + dec + "5")                            # second decimal separator
    return out


def main():
    rng = random.Random(20261004)
    print("# numparse golden: babel.numbers.parse_decimal(strict=True), Babel "
          + __import__("babel").__version__ + "; generated by tools/babel-oracle.py")
    seen = set()
    for name, group, dec, _ in TABLE:
        for _ in range(40):
            mag = rng.choice([1, 2, 3, 4, 5, 6, 7, 9, 12])
            v = Decimal(rng.randrange(10 ** (mag - 1), 10 ** mag))
            if rng.random() < 0.6:
                v = v / (Decimal(10) ** rng.randrange(1, 4))
            if rng.random() < 0.3:
                v = -v
            text = format_decimal(v, locale=name, decimal_quantization=False)
            for t in [text] + corruptions(text, group, dec):
                if not t or (name, t) in seen:
                    continue
                seen.add((name, t))
                print(f"{name}\t{t}\t{oracle(t, name)}")


if __name__ == "__main__":
    if "--check-table" in sys.argv:
        sys.exit(0 if check_table() else 1)
    main()
