#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Regenerates src/kat_rfc9180_a6.zig — RFC 9180 Appendix A.6
(DHKEM(P-521, HKDF-SHA512), HKDF-SHA512, AES-256-GCM), all four modes, every
published field — from the RFC's own text.

    curl -sSfLO https://www.rfc-editor.org/rfc/rfc9180.txt
    sha256sum rfc9180.txt
      f45a8b7c30231b26d668b1e8168074e5ab514b174d656b67e859895117f1f8f6  (fetched 2026-10-10)
    python3 -I modules/hpke/tools/gen_rfc9180_a6.py rfc9180.txt > modules/hpke/src/kat_rfc9180_a6.zig

The RFC wraps long hex values over several lines and inserts page headers and
footers inside sections; both are undone here (a continuation is a line of
bare hex after a `name:` line; header/footer lines are dropped).
"""
import re
import sys

lines = open(sys.argv[1], encoding="utf-8-sig").read().splitlines()

SECTIONS = [("a6", "A.6.1."), ("a6_psk", "A.6.2."), ("a6_auth", "A.6.3."), ("a6_auth_psk", "A.6.4.")]
HEX = re.compile(r"^[0-9a-f]+$")


def section_lines(prefix):
    start = next(i for i, l in enumerate(lines) if l.startswith(prefix + "  "))
    out = []
    for l in lines[start + 1:]:
        if re.match(r"^A\.6\.\d\.  ", l) or l.startswith("A.7."):
            break
        if l.startswith("Barnes & Wood") or l.startswith("RFC 9180 ") or l.startswith("\f"):
            continue
        out.append(l.strip())
    return out


def records(ls):
    """Split into (kind, [dict]) blocks: setup / encryptions / exports."""
    blocks, kind, cur, last = [], "setup", {}, None
    recs = []
    for l in ls:
        if re.match(r"^A\.6\.\d\.1\.  Encryptions", l):
            if cur:
                recs.append(cur)
            blocks.append((kind, recs))
            kind, recs, cur, last = "enc", [], {}, None
            continue
        if re.match(r"^A\.6\.\d\.2\.  Exported Values", l):
            if cur:
                recs.append(cur)
            blocks.append((kind, recs))
            kind, recs, cur, last = "exp", [], {}, None
            continue
        if not l:
            if kind != "setup" and cur:
                recs.append(cur)
                cur, last = {}, None
            continue
        m = re.match(r"^([A-Za-z_ ]+):\s*(\S*)$", l)
        if m:
            last = m.group(1)
            cur[last] = m.group(2)
        elif HEX.match(l) and last is not None:
            cur[last] += l
        else:
            raise SystemExit("unparsed line: %r" % l)
    if cur:
        recs.append(cur)
    blocks.append((kind, recs))
    return blocks


def hx(v):
    assert len(v) % 2 == 0, v
    return 'hexTo(%d, "%s")' % (len(v) // 2, v)


out = sys.stdout
out.write("// SPDX-License-Identifier: MIT\n")
out.write("// GENERATED by modules/hpke/tools/gen_rfc9180_a6.py from RFC 9180's text -- do not edit.\n")
out.write("//! RFC 9180 Appendix A.6: DHKEM(P-521, HKDF-SHA512), HKDF-SHA512, AES-256-GCM,\n")
out.write("//! all four modes (A.6.1 base, A.6.2 psk, A.6.3 auth, A.6.4 auth_psk), every field.\n\n")
out.write('const kat = @import("kat_rfc9180.zig");\nconst hexTo = kat.hexTo;\nconst Encryption = kat.Encryption;\nconst Export = kat.Export;\n')
for name, prefix in SECTIONS:
    blocks = dict((k, v) for k, v in records(section_lines(prefix)))
    setup = blocks["setup"][0]
    out.write("\npub const %s = struct {\n" % name)
    for k in ("mode", "kem_id", "kdf_id", "aead_id"):
        out.write("    pub const %s: %s = %s;\n" % (k, "u8" if k == "mode" else "u16", int(setup[k])))
    for k in ("info", "ikmE", "pkEm", "skEm", "ikmR", "pkRm", "skRm", "ikmS", "pkSm", "skSm", "psk", "psk_id",
              "enc", "shared_secret", "key_schedule_context", "secret", "key", "base_nonce", "exporter_secret"):
        if k in setup:
            out.write("    pub const %s = %s;\n" % (k, hx(setup[k])))
    out.write("\n    pub const encryptions = [_]Encryption{\n")
    for e in blocks["enc"]:
        out.write("        .{ .seq = %s, .pt = &%s, .aad = &%s, .nonce = %s, .ct = &%s },\n" % (
            e["sequence number"], hx(e["pt"]), hx(e["aad"]), hx(e["nonce"]), hx(e["ct"])))
    out.write("    };\n\n    pub const exports = [_]Export{\n")
    for e in blocks["exp"]:
        ctx = e["exporter_context"]
        ctx_s = '""' if ctx == "" else "&" + hx(ctx)
        assert e["L"] == "32"
        out.write("        .{ .exporter_context = %s, .l = 32, .exported_value = %s },\n" % (ctx_s, hx(e["exported_value"])))
    out.write("    };\n};\n")
