#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Turn what `fetch.py` captured into the Zig literals this module pins.

WHY THIS EXISTS. See `README.md` here: `modules/drand` keeps its vectors as
inline string literals, not as a generated file, and that is deliberate — a
vector that changes without a human reading the diff is a vector nobody checked.
So this prints the literals and a person pastes what they want, rather than
overwriting a tracked file.

WHAT IT NEEDS. The four JSON files `fetch.py` wrote.

    python3 fetch.py live/
    python3 gen_vectors.py live/ > /tmp/vectors.zig     # then paste by hand

WHAT IT PRODUCES. On stdout: `quicknet_info`, `quicknet_t_info` and the two
round arrays, each as a compact JSON string escaped for Zig, with a banner
naming THIS file and the capture date so the next reader knows how to re-obtain
them.

⚠ The banner used to name `~/CML/.../A1/repro/drand/gen_vectors.py` — a path
outside the repository, so anyone who read it had no way to re-run the
generator. That is the defect this whole directory exists to fix; the banner now
names a path that ships.
"""
import json, os, sys, datetime

src = sys.argv[1] if len(sys.argv) > 1 else "live"


def load(name):
    p = os.path.join(src, name)
    if not os.path.exists(p):
        print(f"⛔ missing {p} — run `python3 fetch.py {src}` first", file=sys.stderr)
        sys.exit(1)
    return json.load(open(p))


qn_info = load("quicknet_info.json")
tn_info = load("quicknet_t_info.json")
qn = load("quicknet_rounds.json")
tn = load("quicknet_t_rounds.json")

if not qn or not tn:
    print("⛔ a round array is empty — nothing to pin", file=sys.stderr)
    sys.exit(1)


def zstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def compact(d):
    return json.dumps(d, separators=(',', ':'))


stamp = datetime.date.today().isoformat()
L = []
L.append("// GENERATED by modules/drand/tools/gen_vectors.py from live drand endpoints.")
L.append(f"// api.drand.sh (quicknet) + pl-us.testnet.drand.sh (quicknet-t), fetched {stamp}.")
L.append("pub const quicknet_info = " + zstr(compact(qn_info)) + ";")
L.append("pub const quicknet_t_info = " + zstr(compact(tn_info)) + ";")
L.append("pub const quicknet_rounds = [_][]const u8{")
for r in qn:
    L.append("    " + zstr(compact(r)) + ",")
L.append("};")
L.append("pub const quicknet_t_rounds = [_][]const u8{")
for r in tn:
    L.append("    " + zstr(compact(r)) + ",")
L.append("};")
print("\n".join(L))
print(f"// {len(qn)} quicknet + {len(tn)} quicknet-t rounds", file=sys.stderr)
