// SPDX-License-Identifier: MIT
//! Poseidon over the **BN254 (alt-bn128) scalar field** with circomlib's
//! parameter set — the instance the overwhelming majority of deployed circuits
//! use (circom/snarkjs, Semaphore, Tornado-style mixers, iden3, Dark Forest).
//!
//! Parameters, all sourced rather than remembered:
//!
//!   - field: `bn254.Fr`, `r = 0x30644e72…f0000001` (254 bits) — the sibling
//!     `bn254` module's scalar field, reused as-is;
//!   - `alpha = 5`, `R_F = 8`;
//!   - `R_P` per width from `N_ROUNDS_P` below;
//!   - Grain seed width `n = 254`.
//!
//! `n = 254` is a *seed* input, so it is part of the instance identity. The
//! header comment on circomlib's `circuits/poseidon_constants.circom` records
//! the exact invocation:
//! `sage generate_parameters_grain.sage 1 0 254 <t> 8 <R_P>
//! 0x30644e72e131a029b85045b68181585d2833e84879b9709143e1f593f0000001`.
//!
//! ## Usage
//!
//! ```zig
//! const p = poseidon.bn254.Perm(3).init();   // once, at startup
//! const node = p.compress(left, right);      // Merkle node
//! ```

const std = @import("std");
const bn254 = @import("bn254");
const perm = @import("perm.zig");

pub const Fr = bn254.Fr;

/// Number of partial rounds per state width, indexed by `t - 2` (so `t` runs
/// 2..17, i.e. 1..16 hash inputs).
///
/// Source: the identical literal appears in **both** circomlib's
/// `circuits/poseidon.circom` (`var N_ROUNDS_P[16] = …`) and circomlibjs'
/// `src/poseidon_reference.js` (`const N_ROUNDS_P = …`), each carrying the
/// comment "Using recommended parameters from whitepaper
/// <https://eprint.iacr.org/2019/458.pdf> (table 2, table 8) / Generated by
/// …/calc_round_numbers.py / And rounded up to nearest integer that divides
/// by t".
///
/// It is **not** monotonic in `t` (t=3 → 57 but t=4 → 56) — that is what the
/// round-up-to-a-multiple-of-`t` step does. A "looks like a typo, let me
/// smooth it" edit here silently changes every digest.
pub const N_ROUNDS_P = [16]u10{ 56, 57, 56, 60, 60, 63, 64, 63, 60, 66, 60, 65, 70, 60, 64, 68 };

/// Full rounds — 8 for every width in this parameter set.
pub const N_ROUNDS_F: u10 = 8;

/// The Poseidon permutation over BN254 at state width `t` (2..17). Call
/// `.init()` on the returned type to build an instance.
pub fn Perm(comptime t: u12) type {
    if (t < 2 or t > 17) @compileError("poseidon/bn254: t must be in 2..17 (circomlib's published parameter range)");
    return perm.Permutation(.{
        .Fr = Fr,
        .modulus_be = bn254.scalar.r_bytes,
        .n = 254,
        .t = t,
        .r_f = N_ROUNDS_F,
        .r_p = N_ROUNDS_P[t - 2],
    });
}

/// The type of the 2-to-1 compression instance — `circomlib.Poseidon(2)`,
/// the Merkle-tree node function. Named because it is the common case.
pub const Compress2 = Perm(3);

/// Small-integer literal to `Fr`. For tests, domain tags and indices; real
/// inputs come from the caller's witness.
pub fn fromU64(v: u64) Fr {
    var be: [32]u8 = @splat(0);
    std.mem.writeInt(u64, be[24..32], v, .big);
    return Fr.fromBytes(be) catch unreachable;
}
