#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Regenerates p521's embedded known-answer vectors from their upstream files.

Recipe (the sha256 sums are the files the committed vectors were built from,
fetched 2026-10-10; a different sum means upstream changed and the committed
counts in `src/kat_test.zig` will say so):

  mkdir dl && cd dl
  W=https://raw.githubusercontent.com/C2SP/wycheproof/main/testvectors_v1
  curl -sSfLO $W/ecdh_secp521r1_test.json
  curl -sSfLO $W/ecdsa_secp521r1_sha512_test.json
  curl -sSfLO $W/ecdsa_secp521r1_sha512_p1363_test.json
  C=https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents
  curl -sSfLO $C/dss/186-4ecdsatestvectors.zip
  curl -sSfLO $C/components/ecccdhtestvectors.zip
  mkdir cavp && (cd cavp && unzip -q ../186-4ecdsatestvectors.zip && unzip -q ../ecccdhtestvectors.zip)
  sha256sum *
    b5e379919833afa94ef6cb7e085367408a5ea63cf486ad008ad36ef9be4bebf0  ecdh_secp521r1_test.json
    0fa3bb09a2319242253028b53d555fb8ec2081d891271321205cdaeabb3eef3e  ecdsa_secp521r1_sha512_test.json
    d294cbe0485dff0a2c53f6b363103ddb81c444e7e5ee44df56549ea92b873840  ecdsa_secp521r1_sha512_p1363_test.json
    fe47cc92b4cee418236125c9ffbcd9bb01c8c34e74a4ba195d954bcb72824752  186-4ecdsatestvectors.zip
    5fff092551f2d72e89a3d9362711878708f9a14b502f0dfae819649105b0ea39  ecccdhtestvectors.zip
  cd ..
  python3 -I modules/p521/tools/gen_vectors.py dl modules/p521/src

Writes src/cavp_vectors.zig, src/wycheproof_ecdsa_vectors.zig and
src/wycheproof_ecdh_vectors.zig. Every dropped row is counted in the header of
the file it would have gone to, with the reason, so an omission reads as one.

What is dropped and why:
  * Wycheproof ECDH rows whose public key is not a well-formed
    SubjectPublicKeyInfo naming secp521r1 (id-ecPublicKey + the named-curve
    OID 1.3.132.0.35, strict DER). Those rows test an ASN.1 parser (invalid
    DER, explicit/modified curve parameters, other curves); p521 takes a SEC1
    point, not an SPKI, so there is nothing of ours for them to exercise.
  * Wycheproof P1363 rows whose signature is not 132 bytes: the API takes
    `[132]u8`, so the length is enforced by the type, not by the code.
  * CAVP SigVer/SigGen rows for SHA-1 (no FIPS 186-4 SigGen for it; SigVer
    keeps it, `Ecdsa` is generic over the hash) are KEPT; the truncated
    SHA-512/224 and /256 files are not read.
"""
import json
import os
import sys

dl, out = sys.argv[1], sys.argv[2]

SECP521R1_OID = bytes.fromhex("2b81040023")
EC_PUBKEY_OID = bytes.fromhex("2a8648ce3d0201")


def der_tlv(b, i):
    """One strict-DER TLV at b[i]: (tag, value, next index) or raise."""
    if i + 2 > len(b):
        raise ValueError("short")
    tag = b[i]
    ln = b[i + 1]
    i += 2
    if ln & 0x80:
        n = ln & 0x7F
        if n == 0 or n > 2 or i + n > len(b):
            raise ValueError("length form")
        ln = int.from_bytes(b[i : i + n], "big")
        if ln < 0x80 or b[i] == 0:
            raise ValueError("non-minimal length")
        i += n
    if i + ln > len(b):
        raise ValueError("overrun")
    return tag, b[i : i + ln], i + ln


def spki_point(hexstr):
    """The SEC1 point of an SPKI naming secp521r1, or None."""
    try:
        b = bytes.fromhex(hexstr)
        tag, body, end = der_tlv(b, 0)
        if tag != 0x30 or end != len(b):
            return None
        tag, alg, j = der_tlv(body, 0)
        if tag != 0x30:
            return None
        t1, oid1, k = der_tlv(alg, 0)
        t2, oid2, k = der_tlv(alg, k)
        if t1 != 6 or oid1 != EC_PUBKEY_OID or t2 != 6 or oid2 != SECP521R1_OID or k != len(alg):
            return None
        tag, bits, j = der_tlv(body, j)
        if tag != 3 or j != len(body) or len(bits) < 1 or bits[0] != 0:
            return None
        return bits[1:].hex()
    except ValueError:
        return None


def zstr(s):
    return '"' + s + '"'


def header(f, what):
    f.write("// SPDX-License-Identifier: Apache-2.0\n" if "wycheproof" in what else "// SPDX-License-Identifier: MIT\n")
    f.write("// GENERATED by modules/p521/tools/gen_vectors.py -- do not edit by hand.\n")
    f.write("// " + what + "\n")


# ── Wycheproof ECDSA (DER + P1363) ────────────────────────────────────────
def ecdsa_groups(path, p1363):
    data = json.load(open(path))
    groups, dropped, kept = [], 0, 0
    for g in data["testGroups"]:
        assert g["sha"] == "SHA-512", g["sha"]
        key = g["publicKey"]["uncompressed"]
        rows = []
        for t in g["tests"]:
            if p1363 and len(t["sig"]) != 264:
                dropped += 1
                continue
            rows.append((t["tcId"], t["msg"], t["sig"], t["result"]))
            kept += 1
        groups.append((key, rows))
    return groups, kept, dropped


with open(os.path.join(out, "wycheproof_ecdsa_vectors.zig"), "w") as f:
    header(f, "wycheproof ECDSA secp521r1/SHA-512 vectors (C2SP/wycheproof testvectors_v1, Apache-2.0; see ../NOTICE).")
    f.write("\npub const Result = enum { valid, invalid, acceptable };\n")
    f.write("pub const Case = struct { id: u32, msg: []const u8, sig: []const u8, result: Result };\n")
    f.write("pub const Group = struct { key: []const u8, cases: []const Case };\n")
    for name, fn, p1363 in (("der", "ecdsa_secp521r1_sha512_test.json", False), ("p1363", "ecdsa_secp521r1_sha512_p1363_test.json", True)):
        groups, kept, dropped = ecdsa_groups(os.path.join(dl, fn), p1363)
        f.write("\n// %s: %d rows kept, %d dropped (signature not 132 bytes: the type enforces it).\n" % (fn, kept, dropped))
        f.write("pub const %s_count = %d;\n" % (name, kept))
        f.write("pub const %s_groups = [_]Group{\n" % name)
        for key, rows in groups:
            f.write("    .{ .key = %s, .cases = &.{\n" % zstr(key))
            for (i, m, s, r) in rows:
                f.write("        .{ .id = %d, .msg = %s, .sig = %s, .result = .%s },\n" % (i, zstr(m), zstr(s), r))
            f.write("    } },\n")
        f.write("};\n")

# ── Wycheproof ECDH ───────────────────────────────────────────────────────
data = json.load(open(os.path.join(dl, "ecdh_secp521r1_test.json")))
rows, dropped = [], 0
for g in data["testGroups"]:
    assert g["curve"] == "secp521r1" and g["encoding"] == "asn"
    for t in g["tests"]:
        pt = spki_point(t["public"])
        if pt is None:
            dropped += 1
            continue
        priv = t["private"]
        assert len(priv) <= 132, t["tcId"]
        rows.append((t["tcId"], pt, priv.rjust(132, "0"), t["shared"], t["result"]))

with open(os.path.join(out, "wycheproof_ecdh_vectors.zig"), "w") as f:
    header(f, "wycheproof ECDH secp521r1 vectors (C2SP/wycheproof testvectors_v1, Apache-2.0; see ../NOTICE).")
    f.write("// ecdh_secp521r1_test.json: %d rows kept, %d dropped (public key not a strict-DER\n" % (len(rows), dropped))
    f.write("// SPKI naming secp521r1: those rows test an ASN.1 parser, p521 takes a SEC1 point).\n")
    f.write("// `public` is the SEC1 point taken out of the SPKI; `private` is left-padded to 66 bytes.\n\n")
    f.write("pub const Result = enum { valid, invalid, acceptable };\n")
    f.write("pub const Case = struct { id: u32, public: []const u8, private: []const u8, shared: []const u8, result: Result };\n")
    f.write("pub const count = %d;\n" % len(rows))
    f.write("pub const cases = [_]Case{\n")
    for (i, p, d, s, r) in rows:
        f.write("    .{ .id = %d, .public = %s, .private = %s, .shared = %s, .result = .%s },\n" % (i, zstr(p), zstr(d), zstr(s), r))
    f.write("};\n")


# ── NIST CAVP ─────────────────────────────────────────────────────────────
def sections(path):
    """Yield (section header, [record dict]) for every [..] section."""
    sec, recs, cur = None, [], {}
    for line in open(path, encoding="latin-1"):
        line = line.strip()
        if line.startswith("[") and line.endswith("]"):
            if cur:
                recs.append(cur)
                cur = {}
            if sec is not None:
                yield sec, recs
            sec, recs = line[1:-1], []
            continue
        if not line or line.startswith("#"):
            if cur:
                recs.append(cur)
                cur = {}
            continue
        if " = " in line:
            k, v = line.split(" = ", 1)
            if k in cur:  # a new record started without a blank line
                recs.append(cur)
                cur = {}
            cur[k] = v
    if cur:
        recs.append(cur)
    if sec is not None:
        yield sec, recs


def h66(v):
    v = v.strip()
    assert len(v) <= 132, v
    return v.rjust(132, "0")


cavp = os.path.join(dl, "cavp", "186-4ecdsatestvectors")
HASHES = {"SHA-1": "sha1", "SHA-224": "sha224", "SHA-256": "sha256", "SHA-384": "sha384", "SHA-512": "sha512"}

sigver = []
for sec, recs in sections(os.path.join(cavp, "SigVer.rsp")):
    if not sec.startswith("P-521,"):
        continue
    hname = HASHES[sec.split(",")[1]]
    for r in recs:
        if "Msg" not in r:
            continue
        sigver.append((hname, r["Msg"], h66(r["Qx"]), h66(r["Qy"]), h66(r["R"]), h66(r["S"]), r["Result"].startswith("P")))

siggen = []
for sec, recs in sections(os.path.join(cavp, "SigGen.txt")):
    if not sec.startswith("P-521,"):
        continue
    hname = HASHES[sec.split(",")[1]]
    for r in recs:
        if "Msg" not in r:
            continue
        siggen.append((hname, r["Msg"], h66(r["d"]), h66(r["Qx"]), h66(r["Qy"]), h66(r["k"]), h66(r["R"]), h66(r["S"])))

keypair = []
in521 = False
for sec, recs in sections(os.path.join(cavp, "KeyPair.rsp")):
    if sec == "P-521":
        in521 = True
    elif not sec.startswith("B.4.2"):
        in521 = False
    if not in521:
        continue
    for r in recs:
        if "d" in r:
            keypair.append((h66(r["d"]), h66(r["Qx"]), h66(r["Qy"])))

pkv = []
for sec, recs in sections(os.path.join(cavp, "PKV.rsp")):
    if sec != "P-521":
        continue
    for r in recs:
        if "Qx" in r:
            pkv.append((r["Qx"].rjust(132, "0"), r["Qy"].rjust(132, "0"), r["Result"].startswith("P")))

cdh = []
for sec, recs in sections(os.path.join(dl, "cavp", "KAS_ECC_CDH_PrimitiveTest.txt")):
    if sec != "P-521":
        continue
    for r in recs:
        if "QCAVSx" in r:
            cdh.append((h66(r["QCAVSx"][-132:]), h66(r["QCAVSy"][-132:]), h66(r["dIUT"][-132:]), h66(r["QIUTx"][-132:]), h66(r["QIUTy"][-132:]), h66(r["ZIUT"])))

with open(os.path.join(out, "cavp_vectors.zig"), "w") as f:
    header(f, "NIST CAVP P-521 vectors (US Government work, public domain): 186-4ecdsatestvectors.zip + ecccdhtestvectors.zip.")
    f.write("// Hex values are left-padded to 66 bytes (CAVP drops a leading zero nibble).\n")
    f.write("// PKV coordinates are NOT padded beyond 66 bytes' worth: an over-long one is a test row.\n\n")
    f.write("pub const Hash = enum { sha1, sha224, sha256, sha384, sha512 };\n")
    f.write("pub const SigVer = struct { hash: Hash, msg: []const u8, qx: []const u8, qy: []const u8, r: []const u8, s: []const u8, ok: bool };\n")
    f.write("pub const SigGen = struct { hash: Hash, msg: []const u8, d: []const u8, qx: []const u8, qy: []const u8, k: []const u8, r: []const u8, s: []const u8 };\n")
    f.write("pub const KeyPair = struct { d: []const u8, qx: []const u8, qy: []const u8 };\n")
    f.write("pub const Pkv = struct { qx: []const u8, qy: []const u8, ok: bool };\n")
    f.write("pub const Cdh = struct { qx: []const u8, qy: []const u8, d: []const u8, qiut_x: []const u8, qiut_y: []const u8, z: []const u8 };\n\n")
    f.write("pub const sigver = [_]SigVer{\n")
    for (h, m, x, y, r, s, ok) in sigver:
        f.write("    .{ .hash = .%s, .msg = %s, .qx = %s, .qy = %s, .r = %s, .s = %s, .ok = %s },\n" % (h, zstr(m), zstr(x), zstr(y), zstr(r), zstr(s), "true" if ok else "false"))
    f.write("};\n\npub const siggen = [_]SigGen{\n")
    for (h, m, d, x, y, k, r, s) in siggen:
        f.write("    .{ .hash = .%s, .msg = %s, .d = %s, .qx = %s, .qy = %s, .k = %s, .r = %s, .s = %s },\n" % (h, zstr(m), zstr(d), zstr(x), zstr(y), zstr(k), zstr(r), zstr(s)))
    f.write("};\n\npub const keypair = [_]KeyPair{\n")
    for (d, x, y) in keypair:
        f.write("    .{ .d = %s, .qx = %s, .qy = %s },\n" % (zstr(d), zstr(x), zstr(y)))
    f.write("};\n\npub const pkv = [_]Pkv{\n")
    for (x, y, ok) in pkv:
        f.write("    .{ .qx = %s, .qy = %s, .ok = %s },\n" % (zstr(x), zstr(y), "true" if ok else "false"))
    f.write("};\n\npub const cdh = [_]Cdh{\n")
    for (x, y, d, ux, uy, z) in cdh:
        f.write("    .{ .qx = %s, .qy = %s, .d = %s, .qiut_x = %s, .qiut_y = %s, .z = %s },\n" % (zstr(x), zstr(y), zstr(d), zstr(ux), zstr(uy), zstr(z)))
    f.write("};\n")

print("ecdsa der/p1363, ecdh=%d (dropped %d), sigver=%d siggen=%d keypair=%d pkv=%d cdh=%d" % (len(rows), dropped, len(sigver), len(siggen), len(keypair), len(pkv), len(cdh)))
