#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Differential oracle: OpenSSL produces P-521 keys, ECDSA-SHA512 signatures
(RFC 6979 deterministic and random-nonce) and ECDH shared secrets; the results
are embedded in src/oracle_vectors.zig and checked byte for byte by
src/oracle_test.zig.

  python3 -I modules/p521/tools/openssl_oracle.py <workdir> modules/p521/src/oracle_vectors.zig [cases]

Needs `openssl` >= 3.2 (deterministic ECDSA, `-pkeyopt nonce-type:1`).
Generated 2026-10-10 with OpenSSL 3.5.5. The workdir receives throwaway PEM
files; use an empty scratch directory.

What each row pins:
  * `d`, `pub`, `pub_c`: OpenSSL's key; ours must derive `pub` from `d`
    (uncompressed and compressed SEC1 byte-exact).
  * `sig_det`: OpenSSL's RFC 6979 signature over `msg`; ours must be
    byte-identical (r||s) — a check of the nonce derivation, not just of the
    curve arithmetic.
  * `sig_rnd`: a random-nonce OpenSSL signature; ours must verify it.
  * `peer`, `shared`: OpenSSL's ECDH(d, peer); ours must agree.
Our signatures are checked by OpenSSL in the other direction implicitly: a
byte-identical deterministic signature is one OpenSSL itself produced.
"""
import os
import subprocess
import sys

work, out = sys.argv[1], sys.argv[2]
n = int(sys.argv[3]) if len(sys.argv) > 3 else 24


def run(*args, inp=None):
    return subprocess.run(["openssl", *args], input=inp, capture_output=True, check=True).stdout


def text_hex(txt, label):
    """Concatenate the hex block after `label:` in `openssl ... -text`."""
    lines = txt.decode().splitlines()
    out, on = [], False
    for ln in lines:
        if ln.strip().startswith(label + ":"):
            on = True
            continue
        if on:
            s = ln.strip()
            if ":" in s and all(c in "0123456789abcdef:" for c in s):
                out.append(s.replace(":", ""))
            else:
                break
    return "".join(out)


def der_rs(der):
    """r||s, 66 bytes each, from a DER ECDSA signature."""
    assert der[0] == 0x30
    i = 2 if der[1] < 0x80 else 3
    vals = []
    for _ in range(2):
        assert der[i] == 2
        ln = der[i + 1]
        v = int.from_bytes(der[i + 2 : i + 2 + ln], "big")
        vals.append(v.to_bytes(66, "big").hex())
        i += 2 + ln
    return vals[0] + vals[1]


def keygen(name):
    path = os.path.join(work, name + ".pem")
    run("genpkey", "-algorithm", "EC", "-pkeyopt", "ec_paramgen_curve:P-521", "-out", path)
    txt = run("pkey", "-in", path, "-text", "-noout")
    d = text_hex(txt, "priv").rjust(132, "0")[-132:]
    pub = text_hex(txt, "pub")
    pubpath = os.path.join(work, name + ".pub.pem")
    run("pkey", "-in", path, "-pubout", "-out", pubpath)
    ctxt = run("ec", "-in", path, "-conv_form", "compressed", "-text", "-noout")
    pub_c = text_hex(ctxt, "pub")
    assert len(pub) == 266 and len(pub_c) == 134, (len(pub), len(pub_c))
    return path, pubpath, d, pub, pub_c


rows = []
for i in range(n):
    a, _, d, pub, pub_c = keygen("a%d" % i)
    _, bpub, _, peer, _ = keygen("b%d" % i)
    msg = os.urandom(i * 7 % 97)
    mpath = os.path.join(work, "m%d" % i)
    open(mpath, "wb").write(msg)
    sig_det = der_rs(run("pkeyutl", "-sign", "-inkey", a, "-rawin", "-digest", "sha512", "-pkeyopt", "nonce-type:1", "-in", mpath))
    sig_rnd = der_rs(run("pkeyutl", "-sign", "-inkey", a, "-rawin", "-digest", "sha512", "-in", mpath))
    shared = run("pkeyutl", "-derive", "-inkey", a, "-peerkey", bpub).hex()
    assert len(shared) == 132
    rows.append((d, pub, pub_c, msg.hex(), sig_det, sig_rnd, peer, shared))
    for p in (a, bpub, mpath, os.path.join(work, "b%d.pem" % i), os.path.join(work, "a%d.pub.pem" % i)):
        os.remove(p)

ver = run("version").decode().strip()
with open(out, "w") as f:
    f.write("// SPDX-License-Identifier: MIT\n")
    f.write("// GENERATED by modules/p521/tools/openssl_oracle.py -- do not edit by hand.\n")
    f.write("// Oracle: %s, 2026-10-10. %d rows.\n\n" % (ver, len(rows)))
    f.write("pub const Row = struct { d: []const u8, pub_u: []const u8, pub_c: []const u8, msg: []const u8, sig_det: []const u8, sig_rnd: []const u8, peer: []const u8, shared: []const u8 };\n")
    f.write("pub const count = %d;\n" % len(rows))
    f.write("pub const rows = [_]Row{\n")
    for r in rows:
        f.write('    .{ .d = "%s", .pub_u = "%s", .pub_c = "%s", .msg = "%s", .sig_det = "%s", .sig_rnd = "%s", .peer = "%s", .shared = "%s" },\n' % r)
    f.write("};\n")
print("rows", len(rows))
