// SPDX-License-Identifier: MIT

// Generates `src/casefold.zig`: the simple case-folding orbits `(?i)` matches
// by, as Go's `unicode.SimpleFold` (the module's reference, run as a black box
// through its public API) answers them for every code point. The data are
// Unicode's (CaseFolding.txt, as Go's tables carry it); the run encoding and
// the code below are ours. No Go source was read.
//
//	cd modules/regex/tools/go_casefold
//	GOTOOLCHAIN=go1.26.0 GOPROXY=off go run . -out ../../src/casefold.zig
//	GOTOOLCHAIN=go1.26.0 GOPROXY=off go run . -check ../../src/casefold.zig
//
// Standard library only; needs `zig` on PATH (the output goes through
// `zig fmt --stdin`).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"unicode"
)

// A run of consecutive code points whose orbit successor is cp+delta, or,
// for an alternating run, cp+1 at an even offset from lo and cp-1 at an odd
// one (upper/lower pairs side by side). Every pair of an alternating run is a
// whole orbit of two.
type run struct {
	lo, hi rune
	delta  int32
	alt    bool
}

func (r run) next(c rune) rune {
	if r.alt {
		if (c-r.lo)%2 == 0 {
			return c + 1
		}
		return c - 1
	}
	return c + rune(r.delta)
}

func twoOrbit(c rune) bool {
	return unicode.SimpleFold(unicode.SimpleFold(c)) == c
}

func build() (runs []run, orbit int) {
	for c := rune(0); c <= unicode.MaxRune; c++ {
		f := unicode.SimpleFold(c)
		if f == c {
			continue
		}
		k := 1
		for x := f; x != c; x = unicode.SimpleFold(x) {
			k++
		}
		orbit = max(orbit, k)
		d := int32(f - c)
		if n := len(runs); n > 0 && runs[n-1].hi+1 == c {
			l := &runs[n-1]
			if !l.alt && l.delta == d && !(l.lo == l.hi && d == -1) {
				l.hi = c
				continue
			}
			off := c - l.lo
			pairStart := (l.alt || (l.lo == l.hi && l.delta == 1 && twoOrbit(l.lo))) && off%2 == 1
			if pairStart && d == -1 && twoOrbit(c) {
				l.alt, l.delta = true, 0
				l.hi = c
				continue
			}
			if l.alt && off%2 == 0 && d == 1 && twoOrbit(c) && c+1 <= unicode.MaxRune && unicode.SimpleFold(c+1) == c {
				l.hi = c
				continue
			}
		}
		runs = append(runs, run{lo: c, hi: c, delta: d})
	}
	// An alternating run is whole pairs; a single entry left as "alt" is not.
	for i := range runs {
		if runs[i].alt && (runs[i].hi-runs[i].lo)%2 == 0 {
			panic(fmt.Sprintf("odd alternating run %x-%x", runs[i].lo, runs[i].hi))
		}
	}
	return runs, orbit
}

// verify that the runs give SimpleFold's answer for every code point.
func verify(runs []run) {
	i := 0
	for c := rune(0); c <= unicode.MaxRune; c++ {
		for i < len(runs) && runs[i].hi < c {
			i++
		}
		got := c
		if i < len(runs) && runs[i].lo <= c {
			got = runs[i].next(c)
		}
		if got != unicode.SimpleFold(c) {
			panic(fmt.Sprintf("U+%04X: runs give U+%04X, SimpleFold U+%04X", c, got, unicode.SimpleFold(c)))
		}
	}
}

func main() {
	out := flag.String("out", "", "write the Zig file here (default stdout)")
	check := flag.String("check", "", "re-take and compare with this committed file")
	flag.Parse()

	runs, orbit := build()
	verify(runs)

	var b bytes.Buffer
	b.WriteString("// SPDX-License-Identifier: MIT\n")
	fmt.Fprintf(&b, "// GENERATED by modules/regex/tools/go_casefold (%s, Unicode %s) -- do not hand-edit.\n", runtime.Version(), unicode.Version)
	b.WriteString(`//! Simple case-folding orbits: the code points ` + "`(?i)`" + ` treats as one letter
//! (Unicode CaseFolding.txt, C + S entries, as Go's ` + "`unicode.SimpleFold`" + ` walks
//! them). ` + "`next`" + ` is the orbit successor; following it from any code point comes
//! back to it within ` + "`max_orbit`" + ` steps. Regenerate with the command in
//! tools/go_casefold/main.go.

/// A run of consecutive code points: the successor of ` + "`cp`" + ` is ` + "`cp + delta`" + `, or
/// for an alternating run (` + "`alt`" + `, upper/lower pairs side by side) ` + "`cp + 1`" + ` at an
/// even offset from ` + "`lo`" + ` and ` + "`cp - 1`" + ` at an odd one; each such pair is a whole orbit.
pub const Run = struct { lo: u21, hi: u21, delta: i32 = 0, alt: bool = false };

`)
	fmt.Fprintf(&b, "pub const unicode_version = %q;\n", unicode.Version)
	fmt.Fprintf(&b, "pub const max_orbit = %d;\n", orbit)
	fmt.Fprintf(&b, "/// The lowest and highest code point with a fold.\npub const min_fold: u21 = 0x%X;\npub const max_fold: u21 = 0x%X;\n\n", runs[0].lo, runs[len(runs)-1].hi)
	b.WriteString("pub const runs = [_]Run{\n")
	for _, r := range runs {
		if r.alt {
			fmt.Fprintf(&b, ".{ .lo = 0x%X, .hi = 0x%X, .alt = true },\n", r.lo, r.hi)
		} else {
			fmt.Fprintf(&b, ".{ .lo = 0x%X, .hi = 0x%X, .delta = %d },\n", r.lo, r.hi, r.delta)
		}
	}
	b.WriteString("};\n")

	fmtCmd := exec.Command("zig", "fmt", "--stdin")
	fmtCmd.Stdin = bytes.NewReader(b.Bytes())
	fmtCmd.Stderr = os.Stderr
	formatted, err := fmtCmd.Output()
	if err != nil {
		fmt.Fprintln(os.Stderr, "zig fmt --stdin:", err)
		os.Exit(2)
	}

	switch {
	case *check != "":
		old, err := os.ReadFile(*check)
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(2)
		}
		if !bytes.Equal(dropVersionLine(old), dropVersionLine(formatted)) {
			fmt.Fprintln(os.Stderr, "casefold: DRIFT — committed table differs from a fresh re-take")
			os.Exit(1)
		}
		fmt.Fprintln(os.Stderr, "casefold: committed table matches a fresh re-take")
	case *out != "":
		if err := os.WriteFile(*out, formatted, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(2)
		}
	default:
		os.Stdout.Write(formatted)
	}
}

func dropVersionLine(b []byte) []byte {
	var keep [][]byte
	for _, l := range bytes.Split(b, []byte("\n")) {
		if !bytes.HasPrefix(l, []byte("// GENERATED ")) {
			keep = append(keep, l)
		}
	}
	return bytes.Join(keep, []byte("\n"))
}
