// SPDX-License-Identifier: MIT
//! The radix-2 FFT evaluation domain over `Fr`: the multiplicative subgroup
//! of order `n` (a power of two) generated by a primitive `n`-th root of
//! unity `ω`. QAP interpolation and the quotient-polynomial computation both
//! happen over this domain. REAL and ungated.
//!
//! ## Where `ω` comes from (and why it exists)
//!
//! `Fr`'s multiplicative group has order `r − 1`, which is divisible by
//! `2^28` (BN254's scalar-field 2-adicity — see `bn254/src/scalar.zig`). So
//! a primitive `n`-th root of unity exists for every `n = 2^k`, `k ≤ 28`.
//! With `g = 5` a known multiplicative generator of `Fr` (`g^((r−1)/2) ≠ 1`,
//! i.e. `g` has full 2-adic order — the same generator arkworks/gnark use
//! for BN254), `ω = g^((r−1)/n)` is a primitive `n`-th root. Both facts are
//! asserted by this module's own tests (`ω^n == 1`, `ω^{n/2} ≠ 1`), so a
//! wrong constant fails loudly rather than silently.

const std = @import("std");
const bn254 = @import("bn254");
const field = @import("field.zig");
const Fr = field.Fr;

/// A known multiplicative generator of `Fr` with full 2-adic order.
pub const generator: u64 = 5;

/// `r − 1` as a `comptime_int`, derived from the sibling module's verified
/// modulus bytes — never hand-transcribed.
const r_minus_1: comptime_int = blk: {
    var x: comptime_int = 0;
    for (bn254.scalar.r_bytes) |byte| x = x * 256 + @as(comptime_int, byte);
    break :blk x - 1;
};

/// `(r − 1) / n` as a 32-byte big-endian exponent, exact because `n | r−1`
/// for every power-of-two `n ≤ 2^28`.
fn rootExponent(comptime n: usize) [32]u8 {
    comptime {
        if (n == 0 or (n & (n - 1)) != 0) @compileError("groth16/domain: n must be a power of two");
        const n_int: comptime_int = n;
        if (r_minus_1 % n_int != 0) @compileError("groth16/domain: n does not divide r-1 (n > 2^28?)");
        var e: comptime_int = r_minus_1 / n_int;
        var out: [32]u8 = undefined;
        var i: usize = 32;
        while (i > 0) {
            i -= 1;
            out[i] = e % 256;
            e = e / 256;
        }
        return out;
    }
}

/// An evaluation domain of size `n` (a power of two, `n ≤ 2^28`). All the
/// roots-of-unity constants are computed once from `bn254.Fr`'s verified
/// modulus; nothing here re-implements field arithmetic.
pub fn Domain(comptime n: usize) type {
    return struct {
        pub const size: usize = n;

        /// The `(r−1)/n` exponent, comptime-derived (pure integer math, no
        /// field ops — the actual `Fr` powers below are computed at runtime,
        /// since `std.crypto.ff`'s Montgomery path is a runtime path).
        const root_exp = rootExponent(n);

        /// A primitive `n`-th root of unity `ω = 5^{(r−1)/n}`.
        pub fn root() Fr {
            return field.frFromU64(generator).pow(root_exp);
        }

        /// `ω^{−1}` — the inverse root used by the inverse FFT.
        pub fn rootInv() Fr {
            return root().inv() catch unreachable;
        }

        /// `n^{−1} (mod r)` — the inverse-FFT normalisation factor.
        pub fn nInv() Fr {
            return field.frFromU64(n).inv() catch unreachable;
        }

        /// The `n` domain points `ω^0, ω^1, …, ω^{n−1}`, in order.
        pub fn points() [n]Fr {
            const w = root();
            var out: [n]Fr = undefined;
            var cur = Fr.one;
            for (&out) |*p| {
                p.* = cur;
                cur = cur.mul(w);
            }
            return out;
        }

        /// Evaluates the vanishing polynomial `Z(x) = x^n − 1` at `x`. Zero
        /// exactly on the domain points.
        pub fn vanishingEval(x: Fr) Fr {
            return field.frPowU64(x, n).sub(Fr.one);
        }
    };
}

// ── tests ────────────────────────────────────────────────────────────────

test "root of unity is primitive: ω^n == 1 and ω^{n/2} != 1" {
    inline for (.{ 2, 4, 8, 16, 256 }) |n| {
        const D = Domain(n);
        try std.testing.expect(field.frPowU64(D.root(), n).eql(Fr.one));
        try std.testing.expect(!field.frPowU64(D.root(), n / 2).eql(Fr.one));
    }
}

test "domain points are distinct and vanish under Z" {
    const D = Domain(8);
    const pts = D.points();
    for (pts) |p| {
        try std.testing.expect(D.vanishingEval(p).isZero());
    }
    // distinctness: ω^i are all different for i in 0..n
    for (pts, 0..) |a, i| {
        for (pts[i + 1 ..]) |b| {
            try std.testing.expect(!a.eql(b));
        }
    }
}

test "n_inv * n == 1" {
    const D = Domain(16);
    try std.testing.expect(D.nInv().mul(field.frFromU64(16)).eql(Fr.one));
}

test "root_inv * root == 1" {
    const D = Domain(32);
    try std.testing.expect(D.rootInv().mul(D.root()).eql(Fr.one));
}
