// SPDX-License-Identifier: MIT

//! What an application that wants "encrypt now, readable only after a known
//! future drand round" actually does with `tlock`: encrypt offline to a
//! round identified only by number, show the ciphertext stays opaque under
//! the wrong signature (the temporal secret nobody has yet), then decrypt it
//! with the genuine beacon signature for that round. A second, independent
//! round repeats the whole thing against a ciphertext this example never
//! produced itself — a real `tle`-encrypted fixture from drand's own Go
//! implementation — to prove actual byte-level interop, not just internal
//! self-consistency.
//!
//! `tlock`'s own `encrypt`/`decrypt` allocate NOTHING (both operate on fixed-
//! size stack arrays and `bls12_381` value types; grep confirms no
//! `Allocator` reaches `tlock.zig`/`ciphersuite.zig` at all). The one place
//! this example allocates is `std.Io.Threaded`'s own bookkeeping, needed only
//! to hand `ciphersuite.randomSigma` a real `std.Io` for round A's random
//! draw — checked under the leak-checking allocator below regardless.
//!
//! ⚠ WHAT COULD NOT BE EXERCISED HERE, AND WHY: a genuine drand network
//! round. This machine has no internet access, so no round's signature can
//! be *fetched* live. What it CAN do, and does below, is use REAL published
//! drand data captured in advance:
//!
//!   - Round A uses quicknet mainnet's real master public key `P_pub` and
//!     the real published signature for round 1000 (chain hash
//!     `52db9ba7...c84e971`) — fetched live from `https://api.drand.sh/`
//!     2026-07-16, the same data `tlock`'s own `kat_test.zig` pins. The
//!     CIPHERTEXT itself is produced by THIS example calling `tlock.encrypt`
//!     — self-generated, but decrypted against a real external key.
//!   - Round B is the strongest anchor available offline: a genuine
//!     ciphertext produced by drand's OWN Go `tle` CLI (`github.com/
//!     drand/tlock` commit `7ceb44a598293f10c43d2291df9e669c4251fe24`,
//!     `testdata/lorem-tle-testnet-quicknet-t-2024-01-17-15-28.tle`,
//!     testnet chain `cc9c3984...41a9a5`, round 5423142) together with that
//!     round's real published signature (fetched live from
//!     `https://pl-us.testnet.drand.sh/`, 2026-07-16). This example never
//!     ran `encrypt` to produce these bytes; decrypting them byte-exactly is
//!     a genuine foreign-implementation interop check, not a round trip.
//!     Full chain of custody for both fixtures: `../SPEC.md`'s "KAT plan"
//!     and `../src/kat_test.zig`'s section 3 comment (same commit, same
//!     live endpoints, same values reproduced here).
//!
//! What CANNOT be shown at all in this environment: a round that has not
//! yet happened becoming decryptable the moment the beacon publishes it —
//! that requires a live, running beacon network advancing in real time.
//! The "wrong signature" checks below are the offline substitute: they
//! prove the ciphertext is opaque under any signature except the one
//! genuine private key for its exact round, which is the entire security
//! property scheduled disclosure relies on.
//!
//! Built against the PUBLISHED module (`@import("tlock")` plus its two
//! declared deps `bls12_381`/`entropy`) — no `test_deps`, no reaching into
//! `src/`.

const std = @import("std");
const tlock = @import("tlock");
const bls12_381 = @import("bls12_381");
const entropy = @import("entropy");

const g1 = bls12_381.g1;
const g2 = bls12_381.g2;

fn hexBytes(comptime n: usize, comptime hex: *const [2 * n:0]u8) [n]u8 {
    @setEvalBranchQuota(100_000);
    var out: [n]u8 = undefined;
    _ = std.fmt.hexToBytes(&out, hex) catch unreachable;
    return out;
}

// ── Round A: quicknet mainnet, published key + published round-1000 sig ──
// (published by the League of Entropy, captured from https://api.drand.sh/
// 2026-07-16 — same values `tlock`'s own kat_test.zig pins). The
// ciphertext itself is generated by this example, not drand.

const quicknet_pubkey_hex =
    "83cf0f2896adee7eb8b5f01fcad3912212c437e0073e911fb90022d3e760183" ++
    "c8c4b450b6a0a6c3ac6a5776a2d1064510d1fec758c921cc22b0e17e63aaf4b" ++
    "cb5ed66304de9cf809bd274ca73bab4af5a6e9c76a4bc09e76eae8991ef5ece" ++
    "45a";

const round_1000_sig_hex =
    "b44679b9a59af2ec876b1a6b1ad52ea9b1615fc3982b19576350f93447cb112" ++
    "5e342b73a8dd2bacbe47e4b6b63ed5e39";

fn quicknetPubkey() g2.Affine {
    return g2.fromBytesCompressed(hexBytes(96, quicknet_pubkey_hex)) catch unreachable;
}

fn round1000Signature() g1.Affine {
    return g1.fromBytesCompressed(hexBytes(48, round_1000_sig_hex)) catch unreachable;
}

fn roundA(gpa: std.mem.Allocator) !void {
    var threaded: std.Io.Threaded = .init(gpa, .{});
    defer threaded.deinit();
    const io = threaded.io();

    const p_pub = quicknetPubkey();
    const round: u64 = 1000;
    const message = [_]u8{0x5a} ** tlock.block_bytes;

    // A production caller draws sigma from real entropy rather than a fixed
    // constant -- exercising the `entropy` dep this module declares.
    const sigma = tlock.ciphersuite.randomSigma(io);
    const ct = tlock.encrypt(p_pub, round, message, sigma);

    // Wrong signature first: nobody has round 1000's genuine private key
    // (its beacon signature) except by fetching it from the network -- the
    // temporal secret this scheme sells. Standing in for "not reached yet",
    // a signature for a NEIGHBORING round is offered instead and rejected
    // by the Fiat-Shamir-Okamoto consistency check, by name.
    const ct_wrong_round = tlock.encrypt(p_pub, round + 1, message, sigma);
    if (tlock.decrypt(round1000Signature(), ct_wrong_round)) |_| {
        return error.UnexpectedAccept;
    } else |err| switch (err) {
        error.FoCheckFailed => std.debug.print(
            "round A: ciphertext for round {d} does not open under round {d}'s signature: FoCheckFailed (expected)\n",
            .{ round + 1, round },
        ),
    }

    // A tampered copy of the REAL round-1000 ciphertext is rejected the
    // same way -- a bit-flip in V, not a wrong round.
    var tampered = ct;
    tampered.v[0] ^= 0xff;
    if (tlock.decrypt(round1000Signature(), tampered)) |_| {
        return error.UnexpectedAccept;
    } else |err| switch (err) {
        error.FoCheckFailed => std.debug.print("round A: tampered ciphertext (V flipped): FoCheckFailed (expected)\n", .{}),
    }

    // Now the genuine round-1000 signature: this is "the round has been
    // reached and the beacon published" -- the ciphertext opens.
    const recovered = try tlock.decrypt(round1000Signature(), ct);
    if (!std.mem.eql(u8, &message, &recovered)) return error.WrongPlaintext;
    std.debug.print("round A: decrypted under the genuine published round-1000 signature -- plaintext matches\n", .{});
}

// ── Round B: a genuine Go-`tle`-produced ciphertext (real external anchor) ──
// Published by drand/tlock (Go), captured from `github.com/drand/tlock`
// commit `7ceb44a598293f10c43d2291df9e669c4251fe24`,
// `testdata/lorem-tle-testnet-quicknet-t-2024-01-17-15-28.tle`, plus the
// round's real signature fetched live from https://pl-us.testnet.drand.sh/
// 2026-07-16. This example never calls `encrypt` to produce these bytes.

const quicknet_t_pubkey_hex =
    "b15b65b46fb29104f6a4b5d1e11a8da6344463973d423661bb0804846a0ecd1" ++
    "ef93c25057f1c0baab2ac53e56c662b66072f6d84ee791a3382bfb055afab1e" ++
    "6a375538d8ffc451104ac971d2dc9b168e2d3246b0be2015969cbaac298f650" ++
    "2da";

const interop_round: u64 = 5423142;

const interop_round_sig_hex =
    "96fce8e2f70e2784577c8f2d8bd36af7a4b0dfd73dd91469d8556b36d2973a4" ++
    "f84681a45b1af2ce0511e5a32dd72508f";

const interop_ct_hex =
    "87333e1baaf45ffafbaac29e472ae0974986e9d6028fb4b15cc470fdc7d4121" ++
    "31733f6c867c7bc56ed52b6ae85196b4b0d156e65ba0038b3c6521017b3aed0" ++
    "c45f31011db4a326cc75f4f4a8d78ded24715853d25d7acee2ee98a8a01d8b0" ++
    "d20868992a49bbb8dfa7756f8a804930fe58c997398f72fe8c72da3aab6984f" ++
    "2c9c";

const interop_filekey_hex = "2088b21b7778175ecb9349dd98737373";

fn interopRoundSignature() g1.Affine {
    return g1.fromBytesCompressed(hexBytes(48, interop_round_sig_hex)) catch unreachable;
}

fn roundB() !void {
    const ct = try tlock.Ciphertext.fromBytes(hexBytes(128, interop_ct_hex));

    // The mainnet quicknet round-1000 signature is a perfectly valid G1
    // point -- but it is not this ciphertext's round's private key, so it
    // must be rejected, never silently emit a wrong file key.
    if (tlock.decrypt(round1000Signature(), ct)) |_| {
        return error.UnexpectedAccept;
    } else |err| switch (err) {
        error.FoCheckFailed => std.debug.print(
            "round B: genuine Go-tle ciphertext rejects the mainnet round-1000 signature (wrong beacon entirely): FoCheckFailed (expected)\n",
            .{},
        ),
    }

    // The genuine testnet round-5423142 signature: decrypts a ciphertext
    // this example never produced, byte-exactly, to drand's own recorded
    // plaintext.
    const filekey = try tlock.decrypt(interopRoundSignature(), ct);
    const expected = hexBytes(16, interop_filekey_hex);
    if (!std.mem.eql(u8, &expected, &filekey)) return error.WrongPlaintext;
    std.debug.print("round B: genuine drand-Go-tle ciphertext decrypted byte-exactly to the published file key\n", .{});

    // Malformed input is reported by name too -- `Ciphertext.fromBytes`
    // never panics on a hostile 128 bytes; it decodes the G2 point once and
    // rejects a broken compression flag.
    var broken = hexBytes(128, interop_ct_hex);
    broken[0] = 0xff;
    if (tlock.Ciphertext.fromBytes(broken)) |_| {
        return error.UnexpectedAccept;
    } else |err| switch (err) {
        error.InvalidEncoding => std.debug.print("round B: corrupted U-point flag byte: InvalidEncoding (expected)\n", .{}),
        else => return err,
    }
    _ = quicknet_t_pubkey_hex; // recorded for provenance; not needed once the round signature is pinned to the ciphertext's identity by decrypt's own FO check
}

pub fn main() !void {
    var gpa_state: std.heap.DebugAllocator(.{}) = .init;
    defer if (gpa_state.deinit() == .leak) @panic("leak");
    const gpa = gpa_state.allocator();

    try roundA(gpa);
    try roundB();

    std.debug.print("OK: all tlock example checks passed\n", .{});
}
