#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for `src/testdata/wycheproof.zig`: the Wycheproof ChaCha20-Poly1305
vectors this module's API can take (Apache-2.0 test data -- see ../NOTICE).

    curl -sSfLO https://raw.githubusercontent.com/C2SP/wycheproof/main/testvectors_v1/chacha20_poly1305_test.json
    python3 modules/chachapoly/tools/wycheproof.py chacha20_poly1305_test.json > modules/chachapoly/src/testdata/wycheproof.zig

Kept: every test of a group with a 256-bit key, a 96-bit nonce and a 128-bit
tag -- the only shape `ChaCha20Poly1305` has (`[32]u8` key, `[12]u8` nonce,
`[16]u8` tag), so any other is refused by the type, not by the code under
test. The dropped count is printed into the output header. Per test: `tcId`,
key, nonce, AD, plaintext, ciphertext, tag and whether the result is `valid`;
comments, flags and notes are not reproduced.
"""
import json
import sys

data = json.load(open(sys.argv[1]))
rows, dropped = [], 0
for g in data["testGroups"]:
    for t in g["tests"]:
        if g["keySize"] != 256 or g["ivSize"] != 96 or g["tagSize"] != 128:
            dropped += 1
            continue
        assert t["result"] in ("valid", "invalid"), t["result"]
        rows.append((t["tcId"], t["key"], t["iv"], t["aad"], t["msg"], t["ct"], t["tag"], t["result"] == "valid"))

o = []
o.append("// SPDX-License-Identifier: MIT")
o.append("// Generated by modules/chachapoly/tools/wycheproof.py from C2SP/wycheproof")
o.append(f"// testvectors_v1/chacha20_poly1305_test.json ({data['numberOfTests']} tests; {len(rows)} kept, {dropped} dropped: a key")
o.append("// other than 256 bits, a nonce other than 96 bits or a tag other than 128 bits). Do not edit by hand.")
o.append("// The vector data is Wycheproof's, Apache-2.0: see modules/chachapoly/NOTICE.")
o.append("")
o.append("pub const Vector = struct { tc_id: u32, key: []const u8, iv: []const u8, aad: []const u8, msg: []const u8, ct: []const u8, tag: []const u8, valid: bool };")
o.append("")
o.append("pub const vectors = [_]Vector{")
for tc, key, iv, aad, msg, ct, tag, valid in rows:
    o.append(f'    .{{ .tc_id = {tc}, .key = "{key}", .iv = "{iv}", .aad = "{aad}", .msg = "{msg}", .ct = "{ct}", .tag = "{tag}", .valid = {"true" if valid else "false"} }},')
o.append("};")
sys.stdout.write("\n".join(o) + "\n")
