// SPDX-License-Identifier: MIT
//! Map creation + rule-population helpers for `xdp-classifier`'s two kernel
//! maps (the `BPF_MAP_TYPE_LPM_TRIE` ruleset map and the single-slot
//! `BPF_MAP_TYPE_PERCPU_ARRAY` scratch/output map — see `classifier.zig`'s
//! `ClassifierOptions` doc comment). Everything here runs at setup time on
//! the CONTROL side (creating maps, loading rules) — none of it is part of
//! the generated bytecode itself (`classifier.zig` owns that).

const std = @import("std");
const linux = std.os.linux;
const BPF = linux.BPF;
const rules = @import("rules.zig");

/// `BPF_MAP_TYPE_LPM_TRIE` key layout: native-endian `u32` prefixlen + a
/// 4-byte IPv4 address — see `rules.LpmKey`.
pub const lpm_key_size: u32 = 8;
/// A `u32` class handle.
pub const lpm_value_size: u32 = 4;
pub const scratch_key_size: u32 = 4;
pub const scratch_value_size: u32 = 4;
/// The scratch map is always exactly one slot (key `0`) — see
/// `classifier.ClassifierOptions.scratch_map_fd`'s doc comment.
pub const scratch_max_entries: u32 = 1;

/// `BPF_MAP_TYPE_CPUMAP` key layout: a native-endian `u32` CPU index. See
/// `createCpuMap`.
pub const cpumap_key_size: u32 = 4;
/// `BPF_MAP_TYPE_CPUMAP` value layout: `struct bpf_cpumap_val` — 8 bytes, see
/// `CpumapVal`. The kernel accepts a CPUMAP `value_size` of either 4 (bare
/// `qsize`) or 8 (`qsize` + the optional per-CPU program) — this module always
/// uses 8 so `populateCpu` can carry a per-CPU XDP program when asked.
pub const cpumap_value_size: u32 = @sizeOf(CpumapVal);

/// `struct bpf_cpumap_val` (linux UAPI `include/uapi/linux/bpf.h`, added in
/// kernel 5.9 alongside CPUMAP's optional per-CPU XDP program support): an
/// 8-byte value written into a `BPF_MAP_TYPE_CPUMAP` slot.
///
///   struct bpf_cpumap_val {
///       __u32 qsize;            // queue size to remote target CPU
///       union {
///           int   fd;           // program fd on map write
///           __u32 id;           // program id on map read
///       } bpf_prog;
///   };
///
/// `extern struct` (not `packed`) so the field layout is the C ABI the kernel
/// copies in/out verbatim: `qsize` at offset 0, the union at offset 4, total
/// size 8 — asserted by this file's `smoke` test, the same
/// non-privilege-needed layout anchor `rules.LpmKey` has for its own key.
pub const CpumapVal = extern struct {
    /// Per-CPU backlog queue length — the number of packets that may sit
    /// queued for the remote CPU's `cpu_map_kthread` before drops start.
    /// LibreQoS uses 192; document your own choice at the `populateCpu` call.
    qsize: u32,
    /// Optional per-CPU XDP program run on the remote CPU after redirect. A
    /// union because the kernel takes an fd on write and hands back an id on
    /// read (see the struct doc above); pass `null` to `populateCpu` for the
    /// common "no per-CPU program" case, which writes `fd = 0`.
    bpf_prog: extern union {
        fd: i32,
        id: u32,
    },
};

pub const CreateMapError = error{
    PermissionDenied,
    Unexpected,
};

/// Create the `BPF_MAP_TYPE_LPM_TRIE` ruleset map. `max_entries` should be
/// at least as large as the rule table's `RuleSet.rules.len` (see
/// `rules.RuleSet.validate`, which is validated against this same bound).
///
/// `BPF_MAP_TYPE_LPM_TRIE` mandates `BPF_F_NO_PREALLOC` (map_flags bit 0) at
/// creation time — the kernel rejects `map_create` for this map type without
/// it (`kernel/bpf/lpm_trie.c`'s `trie_alloc`). `std.os.linux.BPF.map_create`
/// (see `../../ebpf/README.md`'s std-inventory section) does not expose a
/// `map_flags` parameter — it always zeroes `MapCreateAttr` and never sets
/// `.map_flags` — so an LPM_TRIE map cannot be created through it. This
/// function fills the same `Attr` struct directly: every field/type/flag
/// involved (`Cmd.map_create`, `MapCreateAttr`, `BPF_F_NO_PREALLOC`) is
/// already public in `std`, only the flags-aware wrapper FUNCTION is missing
/// — the same shape of gap `ebpf`'s `attach.zig` documents for
/// `BPF_PROG_ATTACH` (types exist, the convenience wrapper doesn't). This
/// stays local to `xdp-classifier` rather than being added to `ebpf` itself:
/// it is a single-purpose, single-caller convenience specific to this
/// module's one map type, not a general primitive worth growing `ebpf`'s
/// public surface for.
pub fn createLpmTrieMap(max_entries: u32) CreateMapError!linux.fd_t {
    var attr = BPF.Attr{ .map_create = std.mem.zeroes(BPF.MapCreateAttr) };
    attr.map_create.map_type = @intFromEnum(BPF.MapType.lpm_trie);
    attr.map_create.key_size = lpm_key_size;
    attr.map_create.value_size = lpm_value_size;
    attr.map_create.max_entries = max_entries;
    attr.map_create.map_flags = BPF.BPF_F_NO_PREALLOC;
    const rc = linux.bpf(.map_create, &attr, @sizeOf(BPF.MapCreateAttr));
    return switch (linux.errno(rc)) {
        .SUCCESS => @intCast(rc),
        .PERM => CreateMapError.PermissionDenied,
        else => CreateMapError.Unexpected,
    };
}

/// Create the single-slot `BPF_MAP_TYPE_PERCPU_ARRAY` scratch/output map.
/// No flags gap here — `std.os.linux.BPF.map_create`'s ordinary wrapper is
/// sufficient (PERCPU_ARRAY needs no creation-time flags).
pub fn createScratchMap() !linux.fd_t {
    return BPF.map_create(.percpu_array, scratch_key_size, scratch_value_size, scratch_max_entries);
}

pub const PopulateError = error{
    BadFd,
    NotFound,
    PermissionDenied,
    Unexpected,
};

fn mapPopulateError(err: anyerror) PopulateError {
    return switch (err) {
        error.BadFd => PopulateError.BadFd,
        error.NotFound => PopulateError.NotFound,
        error.PermissionDenied => PopulateError.PermissionDenied,
        else => PopulateError.Unexpected,
    };
}

/// Load one rule into an already-created LPM trie map (`lpm_map_fd`, see
/// `createLpmTrieMap`). Uses `rules.LpmKey`'s encoding — the SAME byte
/// layout `classifier.buildClassifierProgram`'s generated bytecode
/// constructs at runtime from a live packet (see that function's doc
/// comment point 4 and `rules.zig`'s module doc for why the two must agree
/// byte-for-byte).
pub fn populateRule(lpm_map_fd: linux.fd_t, rule: rules.ClassifierRule) PopulateError!void {
    const key = rules.LpmKey.fromPrefix(rule.prefix).toBytes();
    var value: [4]u8 = undefined;
    std.mem.writeInt(u32, &value, rule.class, @import("builtin").cpu.arch.endian());
    BPF.map_update_elem(lpm_map_fd, &key, &value, 0) catch |e| return mapPopulateError(e);
}

/// Load an entire validated `RuleSet` (see `rules.RuleSet.validate` — call
/// it first; this function does not re-validate). Rules are loaded in
/// order; a caller that already checked `RuleSet.validate` for
/// `DuplicatePrefix` has no ordering-dependent surprises left, but this
/// function does not itself re-check that invariant (single-responsibility:
/// validation is `rules.zig`'s job, population is this file's).
pub fn populateRuleSet(lpm_map_fd: linux.fd_t, rule_set: rules.RuleSet) PopulateError!void {
    for (rule_set.rules) |rule| try populateRule(lpm_map_fd, rule);
}

/// Read back the scratch map's current classification (CPU 0's slot on a
/// PERCPU_ARRAY — see `createScratchMap`'s doc; a full per-CPU read needs
/// `bpf_map_lookup_elem` with a `num_possible_cpus()`-sized buffer, which
/// `std.os.linux.BPF.map_lookup_elem` already handles via its plain
/// `value: []u8` parameter sized appropriately by the caller — this helper
/// covers only the common single-CPU-slot case).
pub fn readScratchClass(scratch_map_fd: linux.fd_t) !u32 {
    var key: [4]u8 = .{ 0, 0, 0, 0 };
    var value: [4]u8 = undefined;
    try BPF.map_lookup_elem(scratch_map_fd, &key, &value);
    return std.mem.readInt(u32, &value, @import("builtin").cpu.arch.endian());
}

// ── CPUMAP steering (see classifier.buildCpumapSteerProgram) ────────────────
//
// The redirect-to-cpumap XDP program (`classifier.buildCpumapSteerProgram`)
// steers a matched flow onto a chosen CPU via `bpf_redirect_map(&cpumap, cpu,
// flags)`; these two helpers create and populate that `BPF_MAP_TYPE_CPUMAP` on
// the control side, the same setup-time role `createLpmTrieMap`/`populateRule`
// play for the classifier. The per-CPU HTB/MQ tree a downstream `tc`/`tcplan`
// stage builds is what actually shapes each CPU's redirected traffic — the
// flow->CPU decision here and the per-CPU queue there are two halves of one
// invariant (a subscriber's packets must land on exactly one CPU's queue),
// see this module's SPEC.

/// Create a `BPF_MAP_TYPE_CPUMAP` (map type 16). `max_entries` = the number of
/// CPUs the steer program may target; a redirect to an index `>= max_entries`
/// (or to an unpopulated slot) is a runtime miss, not a creation error. Unlike
/// `createLpmTrieMap`, CPUMAP needs no creation-time `map_flags`, so
/// `std.os.linux.BPF.map_create`'s ordinary wrapper is sufficient (same as
/// `createScratchMap`). Key = native-endian `u32` CPU index
/// (`cpumap_key_size`), value = `CpumapVal` (`cpumap_value_size`).
pub fn createCpuMap(max_entries: u32) !linux.fd_t {
    return BPF.map_create(.cpumap, cpumap_key_size, cpumap_value_size, max_entries);
}

/// Populate one CPUMAP slot: at key `cpu`, write a `CpumapVal{ .qsize, .fd =
/// prog_fd orelse 0 }`. `qsize` is the per-CPU backlog queue length (LibreQoS
/// uses 192 — big enough to absorb bursts without inflating latency); a
/// non-null `prog_fd` attaches an optional per-CPU XDP program run after the
/// redirect. The value is written in native `CpumapVal` (C-ABI) layout, which
/// is exactly what the kernel copies into `struct bpf_cpumap_val`.
pub fn populateCpu(map_fd: linux.fd_t, cpu: u32, qsize: u32, prog_fd: ?linux.fd_t) PopulateError!void {
    var key: [4]u8 = undefined;
    std.mem.writeInt(u32, &key, cpu, @import("builtin").cpu.arch.endian());
    var value: CpumapVal = .{ .qsize = qsize, .bpf_prog = .{ .fd = prog_fd orelse 0 } };
    BPF.map_update_elem(map_fd, &key, std.mem.asBytes(&value), 0) catch |e| return mapPopulateError(e);
}

// ── tests ────────────────────────────────────────────────────────────────────

const testing = std.testing;
const builtin = @import("builtin");

fn hasBpfCapability() bool {
    return linux.geteuid() == 0;
}

test "smoke: map size/entry constants have the shape the LPM trie key layout expects" {
    try testing.expectEqual(@as(u32, 8), lpm_key_size);
    try testing.expectEqual(@as(u32, 4), lpm_value_size);
    try testing.expectEqual(@as(u32, 1), scratch_max_entries);
}

test "createLpmTrieMap + populateRule + real lookup round-trip (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    if (!hasBpfCapability()) return error.SkipZigTest;

    const lpm_fd = createLpmTrieMap(16) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(lpm_fd);

    const rule: rules.ClassifierRule = .{
        .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 },
        .class = 7,
    };
    try populateRule(lpm_fd, rule);

    // Look up an address inside 10.0.0.0/8 with an exact-/32 key, the same
    // shape the generated program constructs at runtime.
    const lookup_key = rules.LpmKey.exact(.{ 10, 1, 2, 3 }).toBytes();
    var value: [4]u8 = undefined;
    try BPF.map_lookup_elem(lpm_fd, &lookup_key, &value);
    try testing.expectEqual(@as(u32, 7), std.mem.readInt(u32, &value, builtin.cpu.arch.endian()));
}

test "smoke: CpumapVal has the exact 8-byte struct bpf_cpumap_val layout" {
    // Non-privileged layout anchor for the CPUMAP steering path — the same
    // role the LPM key-size constants play above. If the kernel UAPI layout
    // and this struct ever disagree, populateCpu would write mis-aligned
    // bytes the kernel silently reinterprets, so pin size AND offsets.
    try testing.expectEqual(@as(usize, 8), @sizeOf(CpumapVal));
    try testing.expectEqual(@as(usize, 0), @offsetOf(CpumapVal, "qsize"));
    try testing.expectEqual(@as(usize, 4), @offsetOf(CpumapVal, "bpf_prog"));
    try testing.expectEqual(@as(u32, 4), cpumap_key_size);
    try testing.expectEqual(@as(u32, 8), cpumap_value_size);
}

test "createCpuMap + populateCpu + real lookup round-trip (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    if (!hasBpfCapability()) return error.SkipZigTest;

    const cpumap_fd = createCpuMap(4) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(cpumap_fd);

    // qsize 192 (LibreQoS's per-CPU backlog), no per-CPU program.
    populateCpu(cpumap_fd, 0, 192, null) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };

    var key: [4]u8 = undefined;
    std.mem.writeInt(u32, &key, 0, builtin.cpu.arch.endian());
    var value: [cpumap_value_size]u8 = undefined;
    try BPF.map_lookup_elem(cpumap_fd, &key, &value);
    const got: CpumapVal = std.mem.bytesToValue(CpumapVal, &value);
    try testing.expectEqual(@as(u32, 192), got.qsize);
    // No per-CPU program was written, so the read-back program id is 0.
    try testing.expectEqual(@as(u32, 0), got.bpf_prog.id);
}

test "createScratchMap + readScratchClass round-trip (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    if (!hasBpfCapability()) return error.SkipZigTest;

    const scratch_fd = createScratchMap() catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(scratch_fd);

    var key: [4]u8 = .{ 0, 0, 0, 0 };
    var value: [4]u8 = undefined;
    std.mem.writeInt(u32, &value, 42, builtin.cpu.arch.endian());
    try BPF.map_update_elem(scratch_fd, &key, &value, 0);

    try testing.expectEqual(@as(u32, 42), try readScratchClass(scratch_fd));
}

test "populateRuleSet loads every rule in a small ruleset (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    if (!hasBpfCapability()) return error.SkipZigTest;

    const lpm_fd = createLpmTrieMap(16) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(lpm_fd);

    const rule_list = [_]rules.ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = 0 }, .class = 9 },
    };
    const rule_set: rules.RuleSet = .{ .rules = &rule_list };
    try rule_set.validate(16);
    try populateRuleSet(lpm_fd, rule_set);

    // 10.1.2.3 should resolve to the more specific /16's class (2), matching
    // rules.lookupReference's userspace prediction for the same ruleset.
    const key = rules.LpmKey.exact(.{ 10, 1, 2, 3 }).toBytes();
    var value: [4]u8 = undefined;
    try BPF.map_lookup_elem(lpm_fd, &key, &value);
    const found_class = std.mem.readInt(u32, &value, builtin.cpu.arch.endian());
    try testing.expectEqual(@as(u32, 2), found_class);
    try testing.expectEqual(found_class, rules.lookupReference(&rule_list, .{ 10, 1, 2, 3 }, 0));
}
