// SPDX-License-Identifier: MIT
//! Map creation + rule-population helpers for `xdp-classifier`'s two kernel
//! maps (the `BPF_MAP_TYPE_LPM_TRIE` ruleset map and the single-slot
//! `BPF_MAP_TYPE_PERCPU_ARRAY` scratch/output map — see `classifier.zig`'s
//! `ClassifierOptions` doc comment). Everything here runs at setup time on
//! the CONTROL side (creating maps, loading rules) — none of it is part of
//! the generated bytecode itself (`classifier.zig` owns that).

const std = @import("std");
const linux = std.os.linux;
const BPF = linux.BPF;
const rules = @import("rules.zig");

/// `BPF_MAP_TYPE_LPM_TRIE` key layout: native-endian `u32` prefixlen + a
/// 4-byte IPv4 address — see `rules.LpmKey`.
pub const lpm_key_size: u32 = 8;
/// A `u32` class handle.
pub const lpm_value_size: u32 = 4;
pub const scratch_key_size: u32 = 4;
pub const scratch_value_size: u32 = 4;
/// The scratch map is always exactly one slot (key `0`) — see
/// `classifier.ClassifierOptions.scratch_map_fd`'s doc comment.
pub const scratch_max_entries: u32 = 1;

pub const CreateMapError = error{
    PermissionDenied,
    Unexpected,
};

/// Create the `BPF_MAP_TYPE_LPM_TRIE` ruleset map. `max_entries` should be
/// at least as large as the rule table's `RuleSet.rules.len` (see
/// `rules.RuleSet.validate`, which is validated against this same bound).
///
/// `BPF_MAP_TYPE_LPM_TRIE` mandates `BPF_F_NO_PREALLOC` (map_flags bit 0) at
/// creation time — the kernel rejects `map_create` for this map type without
/// it (`kernel/bpf/lpm_trie.c`'s `trie_alloc`). `std.os.linux.BPF.map_create`
/// (see `../../ebpf/README.md`'s std-inventory section) does not expose a
/// `map_flags` parameter — it always zeroes `MapCreateAttr` and never sets
/// `.map_flags` — so an LPM_TRIE map cannot be created through it. This
/// function fills the same `Attr` struct directly: every field/type/flag
/// involved (`Cmd.map_create`, `MapCreateAttr`, `BPF_F_NO_PREALLOC`) is
/// already public in `std`, only the flags-aware wrapper FUNCTION is missing
/// — the same shape of gap `ebpf`'s `attach.zig` documents for
/// `BPF_PROG_ATTACH` (types exist, the convenience wrapper doesn't). This
/// stays local to `xdp-classifier` rather than being added to `ebpf` itself:
/// it is a single-purpose, single-caller convenience specific to this
/// module's one map type, not a general primitive worth growing `ebpf`'s
/// public surface for.
pub fn createLpmTrieMap(max_entries: u32) CreateMapError!linux.fd_t {
    var attr = BPF.Attr{ .map_create = std.mem.zeroes(BPF.MapCreateAttr) };
    attr.map_create.map_type = @intFromEnum(BPF.MapType.lpm_trie);
    attr.map_create.key_size = lpm_key_size;
    attr.map_create.value_size = lpm_value_size;
    attr.map_create.max_entries = max_entries;
    attr.map_create.map_flags = BPF.BPF_F_NO_PREALLOC;
    const rc = linux.bpf(.map_create, &attr, @sizeOf(BPF.MapCreateAttr));
    return switch (linux.errno(rc)) {
        .SUCCESS => @intCast(rc),
        .PERM => CreateMapError.PermissionDenied,
        else => CreateMapError.Unexpected,
    };
}

/// Create the single-slot `BPF_MAP_TYPE_PERCPU_ARRAY` scratch/output map.
/// No flags gap here — `std.os.linux.BPF.map_create`'s ordinary wrapper is
/// sufficient (PERCPU_ARRAY needs no creation-time flags).
pub fn createScratchMap() !linux.fd_t {
    return BPF.map_create(.percpu_array, scratch_key_size, scratch_value_size, scratch_max_entries);
}

pub const PopulateError = error{
    BadFd,
    NotFound,
    PermissionDenied,
    Unexpected,
};

fn mapPopulateError(err: anyerror) PopulateError {
    return switch (err) {
        error.BadFd => PopulateError.BadFd,
        error.NotFound => PopulateError.NotFound,
        error.PermissionDenied => PopulateError.PermissionDenied,
        else => PopulateError.Unexpected,
    };
}

/// Load one rule into an already-created LPM trie map (`lpm_map_fd`, see
/// `createLpmTrieMap`). Uses `rules.LpmKey`'s encoding — the SAME byte
/// layout `classifier.buildClassifierProgram`'s generated bytecode
/// constructs at runtime from a live packet (see that function's doc
/// comment point 4 and `rules.zig`'s module doc for why the two must agree
/// byte-for-byte).
pub fn populateRule(lpm_map_fd: linux.fd_t, rule: rules.ClassifierRule) PopulateError!void {
    const key = rules.LpmKey.fromPrefix(rule.prefix).toBytes();
    var value: [4]u8 = undefined;
    std.mem.writeInt(u32, &value, rule.class, @import("builtin").cpu.arch.endian());
    BPF.map_update_elem(lpm_map_fd, &key, &value, 0) catch |e| return mapPopulateError(e);
}

/// Load an entire validated `RuleSet` (see `rules.RuleSet.validate` — call
/// it first; this function does not re-validate). Rules are loaded in
/// order; a caller that already checked `RuleSet.validate` for
/// `DuplicatePrefix` has no ordering-dependent surprises left, but this
/// function does not itself re-check that invariant (single-responsibility:
/// validation is `rules.zig`'s job, population is this file's).
pub fn populateRuleSet(lpm_map_fd: linux.fd_t, rule_set: rules.RuleSet) PopulateError!void {
    for (rule_set.rules) |rule| try populateRule(lpm_map_fd, rule);
}

/// Read back the scratch map's current classification (CPU 0's slot on a
/// PERCPU_ARRAY — see `createScratchMap`'s doc; a full per-CPU read needs
/// `bpf_map_lookup_elem` with a `num_possible_cpus()`-sized buffer, which
/// `std.os.linux.BPF.map_lookup_elem` already handles via its plain
/// `value: []u8` parameter sized appropriately by the caller — this helper
/// covers only the common single-CPU-slot case).
pub fn readScratchClass(scratch_map_fd: linux.fd_t) !u32 {
    var key: [4]u8 = .{ 0, 0, 0, 0 };
    var value: [4]u8 = undefined;
    try BPF.map_lookup_elem(scratch_map_fd, &key, &value);
    return std.mem.readInt(u32, &value, @import("builtin").cpu.arch.endian());
}

// ── tests ────────────────────────────────────────────────────────────────────

const testing = std.testing;
const builtin = @import("builtin");

fn hasBpfCapability() bool {
    return linux.geteuid() == 0;
}

test "smoke: map size/entry constants have the shape the LPM trie key layout expects" {
    try testing.expectEqual(@as(u32, 8), lpm_key_size);
    try testing.expectEqual(@as(u32, 4), lpm_value_size);
    try testing.expectEqual(@as(u32, 1), scratch_max_entries);
}

test "createLpmTrieMap + populateRule + real lookup round-trip (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    if (!hasBpfCapability()) return error.SkipZigTest;

    const lpm_fd = createLpmTrieMap(16) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(lpm_fd);

    const rule: rules.ClassifierRule = .{
        .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 },
        .class = 7,
    };
    try populateRule(lpm_fd, rule);

    // Look up an address inside 10.0.0.0/8 with an exact-/32 key, the same
    // shape the generated program constructs at runtime.
    const lookup_key = rules.LpmKey.exact(.{ 10, 1, 2, 3 }).toBytes();
    var value: [4]u8 = undefined;
    try BPF.map_lookup_elem(lpm_fd, &lookup_key, &value);
    try testing.expectEqual(@as(u32, 7), std.mem.readInt(u32, &value, builtin.cpu.arch.endian()));
}

test "createScratchMap + readScratchClass round-trip (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    if (!hasBpfCapability()) return error.SkipZigTest;

    const scratch_fd = createScratchMap() catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(scratch_fd);

    var key: [4]u8 = .{ 0, 0, 0, 0 };
    var value: [4]u8 = undefined;
    std.mem.writeInt(u32, &value, 42, builtin.cpu.arch.endian());
    try BPF.map_update_elem(scratch_fd, &key, &value, 0);

    try testing.expectEqual(@as(u32, 42), try readScratchClass(scratch_fd));
}

test "populateRuleSet loads every rule in a small ruleset (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    if (!hasBpfCapability()) return error.SkipZigTest;

    const lpm_fd = createLpmTrieMap(16) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(lpm_fd);

    const rule_list = [_]rules.ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = 0 }, .class = 9 },
    };
    const rule_set: rules.RuleSet = .{ .rules = &rule_list };
    try rule_set.validate(16);
    try populateRuleSet(lpm_fd, rule_set);

    // 10.1.2.3 should resolve to the more specific /16's class (2), matching
    // rules.lookupReference's userspace prediction for the same ruleset.
    const key = rules.LpmKey.exact(.{ 10, 1, 2, 3 }).toBytes();
    var value: [4]u8 = undefined;
    try BPF.map_lookup_elem(lpm_fd, &key, &value);
    const found_class = std.mem.readInt(u32, &value, builtin.cpu.arch.endian());
    try testing.expectEqual(@as(u32, 2), found_class);
    try testing.expectEqual(found_class, rules.lookupReference(&rule_list, .{ 10, 1, 2, 3 }, 0));
}
