// SPDX-License-Identifier: MIT
//! Map creation + rule-population helpers for `xdp-classifier`'s two kernel
//! maps (the `BPF_MAP_TYPE_LPM_TRIE` ruleset map and the single-slot
//! `BPF_MAP_TYPE_PERCPU_ARRAY` scratch/output map — see `classifier.zig`'s
//! `ClassifierOptions` doc comment). Everything here runs at setup time on
//! the CONTROL side (creating maps, loading rules) — none of it is part of
//! the generated bytecode itself (`classifier.zig` owns that).

const std = @import("std");
const linux = std.os.linux;
const BPF = linux.BPF;
const rules = @import("rules.zig");
const ebpf = @import("ebpf");

/// `BPF_MAP_TYPE_LPM_TRIE` key layout: native-endian `u32` prefixlen + a
/// 4-byte IPv4 address — see `rules.LpmKey`.
pub const lpm_key_size: u32 = 8;
/// A `u32` class handle.
pub const lpm_value_size: u32 = 4;
pub const scratch_key_size: u32 = 4;
pub const scratch_value_size: u32 = 4;
/// The scratch map is always exactly one slot (key `0`) — see
/// `classifier.ClassifierOptions.scratch_map_fd`'s doc comment.
pub const scratch_max_entries: u32 = 1;

/// The scratch map's one and only key, native-endian `u32` 0. Every
/// read/write helper below shares this ONE literal (F5: a mutation changing
/// just one of three independent `.{0,0,0,0}` copies to a nonzero key would
/// silently read/write the wrong slot on any map with `max_entries > 1`, and
/// nothing but a CAP_BPF-gated round-trip — one of the module's root-gated
/// skips — would ever have seen it).
pub const scratch_key_bytes: [scratch_key_size]u8 = .{ 0, 0, 0, 0 };

/// Bytes the kernel transfers PER CPU for the scratch map: the value size
/// rounded up to 8. A `PERCPU_*` map's `bpf(2)` lookup/update always moves
/// `round_up(value_size, 8) * num_possible_cpus()` bytes — there is no
/// single-slot form of the syscall, and the caller does not get to ask for one.
pub const scratch_percpu_stride: u32 = (scratch_value_size + 7) & ~@as(u32, 7);

/// Most CPUs `readScratchClass` will size a stack buffer for. Above this it
/// returns `error.TooManyCpus` rather than reading into a buffer it cannot
/// prove is big enough; `readScratchClassAll` has no such bound.
/// 1024 × 8 B = 8 KiB of stack, which covers every machine this module has a
/// plausible deployment on.
pub const scratch_max_stack_cpus: u32 = 1024;

/// `BPF_MAP_TYPE_CPUMAP` key layout: a native-endian `u32` CPU index. See
/// `createCpuMap`.
pub const cpumap_key_size: u32 = 4;
/// `BPF_MAP_TYPE_CPUMAP` value layout: `struct bpf_cpumap_val` — 8 bytes, see
/// `CpumapVal`. The kernel accepts a CPUMAP `value_size` of either 4 (bare
/// `qsize`) or 8 (`qsize` + the optional per-CPU program) — this module always
/// uses 8 so `populateCpu` can carry a per-CPU XDP program when asked.
pub const cpumap_value_size: u32 = @sizeOf(CpumapVal);

/// `struct bpf_cpumap_val` (linux UAPI `include/uapi/linux/bpf.h`, added in
/// kernel 5.9 alongside CPUMAP's optional per-CPU XDP program support): an
/// 8-byte value written into a `BPF_MAP_TYPE_CPUMAP` slot.
///
///   struct bpf_cpumap_val {
///       __u32 qsize;            // queue size to remote target CPU
///       union {
///           int   fd;           // program fd on map write
///           __u32 id;           // program id on map read
///       } bpf_prog;
///   };
///
/// `extern struct` (not `packed`) so the field layout is the C ABI the kernel
/// copies in/out verbatim: `qsize` at offset 0, the union at offset 4, total
/// size 8 — asserted by this file's `smoke` test, the same
/// non-privilege-needed layout anchor `rules.LpmKey` has for its own key.
pub const CpumapVal = extern struct {
    /// Per-CPU backlog queue length — the number of packets that may sit
    /// queued for the remote CPU's `cpu_map_kthread` before drops start.
    /// LibreQoS uses 192; document your own choice at the `populateCpu` call.
    qsize: u32,
    /// Optional per-CPU XDP program run on the remote CPU after redirect. A
    /// union because the kernel takes an fd on write and hands back an id on
    /// read (see the struct doc above); pass `null` to `populateCpu` for the
    /// common "no per-CPU program" case, which writes `fd = 0`.
    bpf_prog: extern union {
        fd: i32,
        id: u32,
    },
};

pub const CreateMapError = error{
    PermissionDenied,
    Unexpected,
};

/// Create the `BPF_MAP_TYPE_LPM_TRIE` ruleset map. `max_entries` should be
/// at least as large as the rule table's `RuleSet.rules.len` (see
/// `rules.RuleSet.validate`, which is validated against this same bound).
///
/// `BPF_MAP_TYPE_LPM_TRIE` mandates `BPF_F_NO_PREALLOC` (map_flags bit 0) at
/// creation time — the kernel rejects `map_create` for this map type without
/// it (`kernel/bpf/lpm_trie.c`'s `trie_alloc`). `std.os.linux.BPF.map_create`
/// (see `../../ebpf/README.md`'s std-inventory section) does not expose a
/// `map_flags` parameter — it always zeroes `MapCreateAttr` and never sets
/// `.map_flags` — so an LPM_TRIE map cannot be created through it. This
/// function fills the same `Attr` struct directly: every field/type/flag
/// involved (`Cmd.map_create`, `MapCreateAttr`, `BPF_F_NO_PREALLOC`) is
/// already public in `std`, only the flags-aware wrapper FUNCTION is missing
/// — the same shape of gap `ebpf`'s `attach.zig` documents for
/// `BPF_PROG_ATTACH` (types exist, the convenience wrapper doesn't). This
/// stays local to `xdp-classifier` rather than being added to `ebpf` itself:
/// it is a single-purpose, single-caller convenience specific to this
/// module's one map type, not a general primitive worth growing `ebpf`'s
/// public surface for.
/// Pure builder for `createLpmTrieMap`'s `BPF_MAP_CREATE` attr — split out so
/// the map_type/map_flags this function commits to are testable WITHOUT
/// `CAP_BPF` (see the `smoke` test below). F5: a mutation dropping
/// `BPF_F_NO_PREALLOC` or swapping the map type is otherwise invisible to
/// every test in this file except the two CAP_BPF-gated round-trips.
fn lpmTrieCreateAttr(max_entries: u32) BPF.MapCreateAttr {
    var attr = std.mem.zeroes(BPF.MapCreateAttr);
    attr.map_type = @intFromEnum(BPF.MapType.lpm_trie);
    attr.key_size = lpm_key_size;
    attr.value_size = lpm_value_size;
    attr.max_entries = max_entries;
    attr.map_flags = BPF.BPF_F_NO_PREALLOC;
    return attr;
}

pub fn createLpmTrieMap(max_entries: u32) CreateMapError!linux.fd_t {
    var attr = BPF.Attr{ .map_create = lpmTrieCreateAttr(max_entries) };
    const rc = linux.bpf(.map_create, &attr, @sizeOf(BPF.MapCreateAttr));
    return switch (linux.errno(rc)) {
        .SUCCESS => @intCast(rc),
        .PERM => CreateMapError.PermissionDenied,
        else => CreateMapError.Unexpected,
    };
}

/// The scratch map's kernel map type. MUST stay `.percpu_array` — a plain
/// `.array` would race every packet classified concurrently on different
/// CPUs onto the same shared slot (see `classifier.ClassifierOptions`'s doc
/// comment on `scratch_map_fd`). Named so `createScratchMap` and its
/// `smoke` test (F5) share one source of truth instead of two independent
/// literals that a mutation could desync unnoticed.
pub const scratch_map_type: BPF.MapType = .percpu_array;

/// Create the single-slot `BPF_MAP_TYPE_PERCPU_ARRAY` scratch/output map.
/// No flags gap here — `std.os.linux.BPF.map_create`'s ordinary wrapper is
/// sufficient (PERCPU_ARRAY needs no creation-time flags).
pub fn createScratchMap() !linux.fd_t {
    return BPF.map_create(scratch_map_type, scratch_key_size, scratch_value_size, scratch_max_entries);
}

pub const PopulateError = error{
    BadFd,
    NotFound,
    PermissionDenied,
    Unexpected,
};

fn mapPopulateError(err: anyerror) PopulateError {
    return switch (err) {
        error.BadFd => PopulateError.BadFd,
        error.NotFound => PopulateError.NotFound,
        error.PermissionDenied => PopulateError.PermissionDenied,
        else => PopulateError.Unexpected,
    };
}

/// Load one rule into an already-created LPM trie map (`lpm_map_fd`, see
/// `createLpmTrieMap`). Uses `rules.LpmKey`'s encoding — the SAME byte
/// layout `classifier.buildClassifierProgram`'s generated bytecode
/// constructs at runtime from a live packet (see that function's doc
/// comment point 4 and `rules.zig`'s module doc for why the two must agree
/// byte-for-byte).
/// Pure LPM-trie VALUE encoding: a `u32` class handle in the host's native
/// byte order (there is no wire-order convention for it — unlike the key's
/// IPv4 address bytes, see `rules.LpmKey`'s doc comment). Split out so the
/// byte order `populateRule` commits to is unit-testable WITHOUT `CAP_BPF`
/// (see the `smoke` test below) — the kernel-round-trip test that used to be
/// the only check of this is one of the module's root-gated skips (F5).
pub fn ruleValueBytes(class: u32) [4]u8 {
    var value: [4]u8 = undefined;
    std.mem.writeInt(u32, &value, class, @import("builtin").cpu.arch.endian());
    return value;
}

pub fn populateRule(lpm_map_fd: linux.fd_t, rule: rules.ClassifierRule) PopulateError!void {
    const key = rules.LpmKey.fromPrefix(rule.prefix).toBytes();
    const value = ruleValueBytes(rule.class);
    BPF.map_update_elem(lpm_map_fd, &key, &value, 0) catch |e| return mapPopulateError(e);
}

/// Load an entire validated `RuleSet` (see `rules.RuleSet.validate` — call
/// it first; this function does not re-validate). Rules are loaded in
/// order; a caller that already checked `RuleSet.validate` for
/// `DuplicatePrefix` has no ordering-dependent surprises left, but this
/// function does not itself re-check that invariant (single-responsibility:
/// validation is `rules.zig`'s job, population is this file's).
pub fn populateRuleSet(lpm_map_fd: linux.fd_t, rule_set: rules.RuleSet) PopulateError!void {
    for (rule_set.rules) |rule| try populateRule(lpm_map_fd, rule);
}

pub const ScratchReadError = error{
    /// `/sys/devices/system/cpu/possible` could not be read or parsed, so the
    /// required buffer size is unknown. Refusing is the only safe answer: a
    /// guess that is too small is a kernel write past the end of it.
    CpuEnumerationFailed,
    /// This machine has more possible CPUs than `scratch_max_stack_cpus`. Use
    /// `readScratchClassAll`, which sizes from the heap.
    TooManyCpus,
};

/// Bytes `bpf(2)` will transfer for one scratch-map lookup or update on this
/// machine. ⛔ Read it fresh rather than caching: CPUs are hot-pluggable and
/// `possible` is what the kernel sizes by.
pub fn scratchTransferLen() ScratchReadError!usize {
    const ncpu = ebpf.possibleCpuCount() catch return error.CpuEnumerationFailed;
    return @as(usize, scratch_percpu_stride) * ncpu;
}

/// Read back the scratch map's current classification — CPU 0's slot.
///
/// ⛔⛔ **This function used to hand the kernel a 4-byte stack buffer, and that
/// was a stack overflow, not a documentation nit.** A `PERCPU_ARRAY` lookup
/// moves `round_up(value_size, 8) * num_possible_cpus()` bytes and
/// `std.os.linux.BPF.map_lookup_elem` passes only `value.ptr` — the slice
/// length never reaches `bpf(2)`, so nothing clamps the write. Measured as real
/// root under QEMU on 2026-09-09: the kernel wrote **8 bytes at 1 vCPU and 32 at
/// 4**, into four bytes. It scales linearly, so an ordinary 8-CPU desktop
/// overflows by 60.
///
/// ⛔ The previous doc comment claimed `map_lookup_elem` "already handles" the
/// sizing "via its plain `value: []u8` parameter", and that this helper covered
/// "the common single-CPU-slot case". Both halves were false: the length is
/// never transferred, and there IS no single-CPU-slot case — the syscall path
/// for per-CPU maps always works across all of them. That comment is why the
/// bug survived review, so it is recorded here rather than deleted.
///
/// Returns CPU 0's slot, which is what the single-`u32` return can express. Use
/// `readScratchClassAll` for every CPU's value — on a live classifier the
/// packet's own CPU wrote its slot, and that is usually not CPU 0.
pub fn readScratchClass(scratch_map_fd: linux.fd_t) !u32 {
    const ncpu = ebpf.possibleCpuCount() catch return error.CpuEnumerationFailed;
    if (ncpu > scratch_max_stack_cpus) return error.TooManyCpus;

    var value: [scratch_max_stack_cpus * scratch_percpu_stride]u8 = undefined;
    const need = @as(usize, scratch_percpu_stride) * ncpu;
    try BPF.map_lookup_elem(scratch_map_fd, &scratch_key_bytes, value[0..need]);
    return std.mem.readInt(u32, value[0..4], @import("builtin").cpu.arch.endian());
}

/// Every possible CPU's scratch slot, in CPU order. The value the classifier
/// wrote lives in the slot of the CPU that handled the packet, so a
/// control-plane poller that wants "what did we classify" wants this, not
/// `readScratchClass`.
///
/// Caller owns the returned slice.
pub fn readScratchClassAll(gpa: std.mem.Allocator, scratch_map_fd: linux.fd_t) ![]u32 {
    const ncpu = ebpf.possibleCpuCount() catch return error.CpuEnumerationFailed;

    const raw = try gpa.alloc(u8, @as(usize, scratch_percpu_stride) * ncpu);
    defer gpa.free(raw);

    try BPF.map_lookup_elem(scratch_map_fd, &scratch_key_bytes, raw);

    const out = try gpa.alloc(u32, ncpu);
    errdefer gpa.free(out);
    const endian = @import("builtin").cpu.arch.endian();
    for (out, 0..) |*slot, i| {
        const at = i * scratch_percpu_stride;
        slot.* = std.mem.readInt(u32, raw[at..][0..4], endian);
    }
    return out;
}

/// Write `class` into EVERY CPU's scratch slot. ⛔ The mirror image of the read
/// bug: a per-CPU update READS `round_up(value_size, 8) * num_possible_cpus()`
/// bytes out of the caller's buffer, so handing it four bytes over-reads the
/// caller's stack just as surely. This module's own round-trip test did exactly
/// that until 2026-09-09.
pub fn writeScratchClassAll(gpa: std.mem.Allocator, scratch_map_fd: linux.fd_t, class: u32) !void {
    const ncpu = ebpf.possibleCpuCount() catch return error.CpuEnumerationFailed;

    const raw = try gpa.alloc(u8, @as(usize, scratch_percpu_stride) * ncpu);
    defer gpa.free(raw);
    @memset(raw, 0);

    const endian = @import("builtin").cpu.arch.endian();
    var i: usize = 0;
    while (i < ncpu) : (i += 1) {
        std.mem.writeInt(u32, raw[i * scratch_percpu_stride ..][0..4], class, endian);
    }

    try BPF.map_update_elem(scratch_map_fd, &scratch_key_bytes, raw, 0);
}

// ── CPUMAP steering (see classifier.buildCpumapSteerProgram) ────────────────
//
// The redirect-to-cpumap XDP program (`classifier.buildCpumapSteerProgram`)
// steers a matched flow onto a chosen CPU via `bpf_redirect_map(&cpumap, cpu,
// flags)`; these two helpers create and populate that `BPF_MAP_TYPE_CPUMAP` on
// the control side, the same setup-time role `createLpmTrieMap`/`populateRule`
// play for the classifier. The per-CPU HTB/MQ tree a downstream `tc`/`tcplan`
// stage builds is what actually shapes each CPU's redirected traffic — the
// flow->CPU decision here and the per-CPU queue there are two halves of one
// invariant (a subscriber's packets must land on exactly one CPU's queue),
// see this module's SPEC.

/// Create a `BPF_MAP_TYPE_CPUMAP` (map type 16). `max_entries` = the number of
/// CPUs the steer program may target; a redirect to an index `>= max_entries`
/// (or to an unpopulated slot) is a runtime miss, not a creation error. Unlike
/// `createLpmTrieMap`, CPUMAP needs no creation-time `map_flags`, so
/// `std.os.linux.BPF.map_create`'s ordinary wrapper is sufficient (same as
/// `createScratchMap`). Key = native-endian `u32` CPU index
/// (`cpumap_key_size`), value = `CpumapVal` (`cpumap_value_size`).
pub fn createCpuMap(max_entries: u32) !linux.fd_t {
    return BPF.map_create(.cpumap, cpumap_key_size, cpumap_value_size, max_entries);
}

/// Populate one CPUMAP slot: at key `cpu`, write a `CpumapVal{ .qsize, .fd =
/// prog_fd orelse 0 }`. `qsize` is the per-CPU backlog queue length (LibreQoS
/// uses 192 — big enough to absorb bursts without inflating latency); a
/// non-null `prog_fd` attaches an optional per-CPU XDP program run after the
/// redirect. The value is written in native `CpumapVal` (C-ABI) layout, which
/// is exactly what the kernel copies into `struct bpf_cpumap_val`.
pub fn populateCpu(map_fd: linux.fd_t, cpu: u32, qsize: u32, prog_fd: ?linux.fd_t) PopulateError!void {
    var key: [4]u8 = undefined;
    std.mem.writeInt(u32, &key, cpu, @import("builtin").cpu.arch.endian());
    var value: CpumapVal = .{ .qsize = qsize, .bpf_prog = .{ .fd = prog_fd orelse 0 } };
    BPF.map_update_elem(map_fd, &key, std.mem.asBytes(&value), 0) catch |e| return mapPopulateError(e);
}

// ── tests ────────────────────────────────────────────────────────────────────

const testing = std.testing;
const builtin = @import("builtin");

test "smoke: map size/entry constants have the shape the LPM trie key layout expects" {
    try testing.expectEqual(@as(u32, 8), lpm_key_size);
    try testing.expectEqual(@as(u32, 4), lpm_value_size);
    try testing.expectEqual(@as(u32, 1), scratch_max_entries);
}

// F5: neprivileged anchors on the map creation/value-encoding decisions that
// used to be checked ONLY by CAP_BPF-gated round-trips -- and every one of
// the round-trips below is itself one of this module's six root-gated
// skips, so on an unprivileged host (the common case) none of them ever ran.

test "F5: createLpmTrieMap's attr carries BPF_F_NO_PREALLOC and the LPM_TRIE map type" {
    // BPF_MAP_TYPE_LPM_TRIE mandates this flag at creation time (the kernel
    // rejects map_create for this type without it, see createLpmTrieMap's
    // doc comment) -- a mutation dropping it would only be caught by a real
    // kernel map_create call, which needs CAP_BPF.
    const attr = lpmTrieCreateAttr(64);
    try testing.expectEqual(@intFromEnum(BPF.MapType.lpm_trie), attr.map_type);
    try testing.expectEqual(BPF.BPF_F_NO_PREALLOC, attr.map_flags);
    try testing.expectEqual(lpm_key_size, attr.key_size);
    try testing.expectEqual(lpm_value_size, attr.value_size);
    try testing.expectEqual(@as(u32, 64), attr.max_entries);
}

test "F5: the scratch map's type is PERCPU_ARRAY, not ARRAY" {
    // A plain ARRAY would race every packet classified concurrently on
    // different CPUs onto the same shared slot -- see scratch_map_type's doc
    // comment. createScratchMap uses this SAME named constant, so this test
    // and the production call site cannot desync silently.
    try testing.expectEqual(BPF.MapType.percpu_array, scratch_map_type);
}

test "F5: ruleValueBytes encodes the class handle in native byte order" {
    // populateRule's value encoding -- the counterpart to rules.LpmKey's own
    // (already-anchored) key encoding. A byte-order flip here would silently
    // misclassify a majority of rules on a little-endian host but was
    // reachable only via the CAP_BPF-gated round-trip.
    const bytes = ruleValueBytes(0x0102_0304);
    try testing.expectEqual(@as(u32, 0x0102_0304), std.mem.readInt(u32, &bytes, builtin.cpu.arch.endian()));
    // Cross-check against the same std primitive the kernel-facing
    // round-trip test compares against, so both paths commit to one
    // definition of "native order".
    var expected: [4]u8 = undefined;
    std.mem.writeInt(u32, &expected, 0x0102_0304, builtin.cpu.arch.endian());
    try testing.expectEqualSlices(u8, &expected, &bytes);
}

test "F5: the scratch map's single key is all-zero" {
    // scratch_max_entries == 1 -- the only valid key is 0. A mutation
    // reading/writing a nonzero key would be silently wrong on any map with
    // more than one slot, and every path that exercises this against a real
    // map is CAP_BPF-gated.
    try testing.expectEqual(@as(u32, 0), std.mem.readInt(u32, &scratch_key_bytes, builtin.cpu.arch.endian()));
}

// A bad fd is rejected by the kernel's fd-lookup before any privilege check,
// so this exercises mapPopulateError's BadFd mapping without needing
// CAP_BPF/root — unlike every other test in this file, this one is not
// skipped on an unprivileged host.
test "populateRule/populateCpu: an invalid map fd surfaces PopulateError.BadFd" {
    const rule: rules.ClassifierRule = .{
        .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 },
        .class = 1,
    };
    try testing.expectError(PopulateError.BadFd, populateRule(-1, rule));
    try testing.expectError(PopulateError.BadFd, populateCpu(-1, 0, 192, null));
}

test "createLpmTrieMap + populateRule + real lookup round-trip (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    // F7: no `hasBpfCapability()`/geteuid() pre-gate here -- that gate shut
    // out a CAP_BPF-without-root process (the exact configuration the
    // module's own docs recommend), skipping it before it ever reached the
    // syscall. Every call below already attempts the real syscall and
    // treats PermissionDenied as SkipZigTest, which is the correct test for
    // "does this process actually have the capability" -- see F7's
    // disposition for the measurement.

    const lpm_fd = createLpmTrieMap(16) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(lpm_fd);

    const rule: rules.ClassifierRule = .{
        .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 },
        .class = 7,
    };
    try populateRule(lpm_fd, rule);

    // Look up an address inside 10.0.0.0/8 with an exact-/32 key, the same
    // shape the generated program constructs at runtime.
    const lookup_key = rules.LpmKey.exact(.{ 10, 1, 2, 3 }).toBytes();
    var value: [4]u8 = undefined;
    try BPF.map_lookup_elem(lpm_fd, &lookup_key, &value);
    try testing.expectEqual(@as(u32, 7), std.mem.readInt(u32, &value, builtin.cpu.arch.endian()));
}

test "smoke: CpumapVal has the exact 8-byte struct bpf_cpumap_val layout" {
    // Non-privileged layout anchor for the CPUMAP steering path — the same
    // role the LPM key-size constants play above. If the kernel UAPI layout
    // and this struct ever disagree, populateCpu would write mis-aligned
    // bytes the kernel silently reinterprets, so pin size AND offsets.
    try testing.expectEqual(@as(usize, 8), @sizeOf(CpumapVal));
    try testing.expectEqual(@as(usize, 0), @offsetOf(CpumapVal, "qsize"));
    try testing.expectEqual(@as(usize, 4), @offsetOf(CpumapVal, "bpf_prog"));
    try testing.expectEqual(@as(u32, 4), cpumap_key_size);
    try testing.expectEqual(@as(u32, 8), cpumap_value_size);
}

test "createCpuMap + populateCpu + real lookup round-trip (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    // F7: no `hasBpfCapability()`/geteuid() pre-gate here -- that gate shut
    // out a CAP_BPF-without-root process (the exact configuration the
    // module's own docs recommend), skipping it before it ever reached the
    // syscall. Every call below already attempts the real syscall and
    // treats PermissionDenied as SkipZigTest, which is the correct test for
    // "does this process actually have the capability" -- see F7's
    // disposition for the measurement.

    const cpumap_fd = createCpuMap(4) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(cpumap_fd);

    // qsize 192 (LibreQoS's per-CPU backlog), no per-CPU program.
    populateCpu(cpumap_fd, 0, 192, null) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };

    var key: [4]u8 = undefined;
    std.mem.writeInt(u32, &key, 0, builtin.cpu.arch.endian());
    var value: [cpumap_value_size]u8 = undefined;
    try BPF.map_lookup_elem(cpumap_fd, &key, &value);
    const got: CpumapVal = std.mem.bytesToValue(CpumapVal, &value);
    try testing.expectEqual(@as(u32, 192), got.qsize);
    // No per-CPU program was written, so the read-back program id is 0.
    try testing.expectEqual(@as(u32, 0), got.bpf_prog.id);
}

test "createScratchMap + readScratchClass round-trip (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    // F7: no `hasBpfCapability()`/geteuid() pre-gate here -- that gate shut
    // out a CAP_BPF-without-root process (the exact configuration the
    // module's own docs recommend), skipping it before it ever reached the
    // syscall. Every call below already attempts the real syscall and
    // treats PermissionDenied as SkipZigTest, which is the correct test for
    // "does this process actually have the capability" -- see F7's
    // disposition for the measurement.

    const scratch_fd = createScratchMap() catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(scratch_fd);

    // ⛔ This used to pass a 4-byte `value` to `map_update_elem`. On a PERCPU
    // map that is the same defect as the read side -- the kernel copies
    // `round_up(value_size,8) * num_possible_cpus()` bytes OUT of this buffer,
    // so the test that was supposed to cover the path reproduced the bug
    // instead. And it is one of the module's root-gated skips, so nothing ever
    // ran it to find out.
    try writeScratchClassAll(testing.allocator, scratch_fd, 42);

    try testing.expectEqual(@as(u32, 42), try readScratchClass(scratch_fd));

    const all = try readScratchClassAll(testing.allocator, scratch_fd);
    defer testing.allocator.free(all);
    try testing.expect(all.len >= 1);
    for (all) |slot| try testing.expectEqual(@as(u32, 42), slot);
}

// ⭐ The anchor the unprivileged test below cannot be: it checks the module's
// transfer-length arithmetic against ITSELF, so a wrong model (online instead of
// possible CPUs, a stride without the round-up) would agree with itself and pass.
// This one hands the real kernel a canary-filled buffer far larger than any sane
// transfer and counts how far the kernel actually wrote — the same measurement
// that established F1 in the first place, now kept next to the code it checks.
//
// Discriminating only on a machine where possible != online CPUs.
// `scripts/vm/run.sh xdp-classifier` boots its guest as `-smp 2,maxcpus=4`
// (online 0-1, possible 0-3) and refuses to report SETUP_OK without that gap,
// so an online-sized model writes 16 bytes against the kernel's 32 there.
test "a scratch lookup moves exactly scratchTransferLen() bytes, measured against the kernel (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;

    const scratch_fd = createScratchMap() catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(scratch_fd);

    // Zero padding in every stride, so every byte the kernel moves differs
    // from the canary — including the last slot's padding.
    try writeScratchClassAll(testing.allocator, scratch_fd, 42);

    const canary: u8 = 0xAA;
    const raw = try testing.allocator.alloc(u8, 1 << 16);
    defer testing.allocator.free(raw);
    @memset(raw, canary);
    try BPF.map_lookup_elem(scratch_fd, &scratch_key_bytes, raw);

    var extent: usize = 0;
    for (raw, 0..) |b, i| {
        if (b != canary) extent = i + 1;
    }

    try testing.expectEqual(try scratchTransferLen(), extent);
    // And the fixed stack buffer `readScratchClass` hands the kernel holds it.
    try testing.expect(@as(usize, scratch_max_stack_cpus) * scratch_percpu_stride >= extent);
}

test "scratch transfer length is the kernel's per-CPU arithmetic, not the value size" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    // ⭐ Runs WITHOUT root, unlike every other test on this path -- which is the
    // point: the sizing bug was reachable from an unprivileged machine's
    // arithmetic, but the only test that touched it needed CAP_BPF and skipped.
    try testing.expectEqual(@as(u32, 8), scratch_percpu_stride);
    try testing.expect(scratch_percpu_stride >= scratch_value_size);

    const need = scratchTransferLen() catch |e| switch (e) {
        error.CpuEnumerationFailed => return error.SkipZigTest,
        else => return e,
    };
    // The whole finding in one assertion: what the kernel moves is strictly
    // more than the 4 bytes the old caller declared, on every real machine.
    try testing.expect(need >= scratch_percpu_stride);
    try testing.expect(need > scratch_value_size);
    try testing.expectEqual(@as(usize, 0), need % scratch_percpu_stride);
}

test "populateRuleSet loads every rule in a small ruleset (needs CAP_BPF/root)" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    // F7: no `hasBpfCapability()`/geteuid() pre-gate here -- that gate shut
    // out a CAP_BPF-without-root process (the exact configuration the
    // module's own docs recommend), skipping it before it ever reached the
    // syscall. Every call below already attempts the real syscall and
    // treats PermissionDenied as SkipZigTest, which is the correct test for
    // "does this process actually have the capability" -- see F7's
    // disposition for the measurement.

    const lpm_fd = createLpmTrieMap(16) catch |e| switch (e) {
        error.PermissionDenied => return error.SkipZigTest,
        else => return e,
    };
    defer _ = linux.close(lpm_fd);

    const rule_list = [_]rules.ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = 0 }, .class = 9 },
    };
    const rule_set: rules.RuleSet = .{ .rules = &rule_list };
    try rule_set.validate(16);
    try populateRuleSet(lpm_fd, rule_set);

    // 10.1.2.3 should resolve to the more specific /16's class (2), matching
    // rules.lookupReference's userspace prediction for the same ruleset.
    const key = rules.LpmKey.exact(.{ 10, 1, 2, 3 }).toBytes();
    var value: [4]u8 = undefined;
    try BPF.map_lookup_elem(lpm_fd, &key, &value);
    const found_class = std.mem.readInt(u32, &value, builtin.cpu.arch.endian());
    try testing.expectEqual(@as(u32, 2), found_class);
    try testing.expectEqual(found_class, rules.lookupReference(&rule_list, .{ 10, 1, 2, 3 }, 0));
}
