// SPDX-License-Identifier: MIT
//! xdp-classifier — an XDP packet classifier: subscriber IPv4 prefix ->
//! traffic-class handle, for a LibreQoS-style edge shaper. Given a set of
//! rules `{ ip_prefix -> class_handle }`, this module produces a valid,
//! verifier-passing XDP eBPF program that, per packet, parses
//! Ethernet+IPv4, performs a longest-prefix-match lookup against a
//! `BPF_MAP_TYPE_LPM_TRIE` map keyed on the packet's source (or
//! destination) IPv4 address, and stashes the resolved class handle into a
//! scratch map before returning `XDP_PASS`.
//!
//! **Status: fully implemented, no Fable-tier core.** Unlike the sibling
//! `ebpf` module (which genuinely needed a Fable pass for its three
//! from-scratch program builders), this module's bytecode generation is
//! MECHANICAL COMPOSITION of primitives `ebpf` already implements and
//! proves: the bounds-check-dominance pattern for direct packet access and
//! the map-lookup pseudo-fd/initialized-key/null-check-before-deref
//! discipline are both already golden-tested and CAP_BPF-load-verified in
//! `ebpf`'s `programs.zig` (`xdpFilter`/`kprobeCounter`). This module
//! sequences those SAME patterns at different packet offsets and with an
//! LPM-shaped key instead of an exact-match one — see `src/classifier.zig`'s
//! module doc for the full argument, including a `clang -O2 -target bpf`
//! cross-check of the genuinely new (non-`ebpf`-derived) parse/bounds-check
//! portion. Every test in this module runs and passes; nothing is gated
//! behind a stub.
//!
//! Provenance: models the packet-classification stage of a LibreQoS-style
//! edge shaper (subscriber IP/prefix -> traffic-class handle feeding a
//! downstream `tc`/CAKE queueing stage) and the BPF ISA / verifier-behavior
//! documentation the sibling `ebpf` module already cites. Clean-room from
//! the public LibreQoS architecture description and kernel UAPI/verifier
//! docs — no LibreQoS or libbpf source ported; see `../../NOTICE` if a
//! specific design reference needs recording.

const std = @import("std");

pub const meta = .{
    // The module catalog's one-line entry. This IS the source of truth:
    // README.md's table is rendered from it by `zig build gen-catalog`.
    .doc = "XDP packet classifier for a LibreQoS-style edge shaper — IPv4 prefix→traffic-class via LPM-trie lookup, per-CPU scratch handoff, CPUMAP steering (bpf_redirect_map)",
    // The catalog's Platform cell. Prose, because it carries nuance the
    // `platform` enum below cannot -- "any (packer: linux)", "amd64 asm +
    // portable fallback". Rendered by `gen-catalog` alongside `doc`.
    .platform_note = "**linux**",
    .targets = .{.linux64},
    .platform = .linux, // generated bytecode + map creation are raw std.os.linux.BPF — a conscious ceiling, same as ebpf
    .role = .util,
    // A program is built once per (ruleset epoch, map fd pair) at setup
    // time; no shared mutable state at build time. Not .threadsafe: the
    // instruction buffer is a file-scope static (see classifier.zig's
    // storage contract), same discipline as ebpf.programs.zig.
    .concurrency = .single_owner,
    .model_after = "LibreQoS (Rust/eBPF) — the classify-then-shape architecture (XDP classification stage feeding a downstream tc/CAKE queueing stage), API shape/design reference only; wire ABI and instruction-emission technique from the sibling ebpf module + kernel UAPI/verifier docs",
    .deps = .{"ebpf"},
};

// ── public API ──────────────────────────────────────────────────────────────

const rules_mod = @import("rules.zig");
pub const Ipv4Prefix = rules_mod.Ipv4Prefix;
pub const ClassifierRule = rules_mod.ClassifierRule;
pub const RuleSet = rules_mod.RuleSet;
pub const RuleSetError = rules_mod.RuleSetError;
pub const LpmKey = rules_mod.LpmKey;
pub const lookupReference = rules_mod.lookupReference;

const maps_mod = @import("maps.zig");
pub const createLpmTrieMap = maps_mod.createLpmTrieMap;
pub const createScratchMap = maps_mod.createScratchMap;
pub const populateRule = maps_mod.populateRule;
pub const populateRuleSet = maps_mod.populateRuleSet;
pub const readScratchClass = maps_mod.readScratchClass;
pub const CreateMapError = maps_mod.CreateMapError;
pub const PopulateError = maps_mod.PopulateError;
pub const lpm_key_size = maps_mod.lpm_key_size;
pub const lpm_value_size = maps_mod.lpm_value_size;
pub const scratch_key_size = maps_mod.scratch_key_size;
pub const scratch_value_size = maps_mod.scratch_value_size;
pub const scratch_max_entries = maps_mod.scratch_max_entries;
// CPUMAP steering (see classifier.buildCpumapSteerProgram).
pub const CpumapVal = maps_mod.CpumapVal;
pub const createCpuMap = maps_mod.createCpuMap;
pub const populateCpu = maps_mod.populateCpu;
pub const cpumap_key_size = maps_mod.cpumap_key_size;
pub const cpumap_value_size = maps_mod.cpumap_value_size;

const classifier_mod = @import("classifier.zig");
pub const KeyField = classifier_mod.KeyField;
pub const ClassifierOptions = classifier_mod.ClassifierOptions;
/// No Fable core — see this module's doc comment and `classifier.zig`'s.
/// Fully implemented, golden-tested, structurally verified, and
/// CAP_BPF-load-verified (gated).
pub const buildClassifierProgram = classifier_mod.buildClassifierProgram;
// CPUMAP steering: redirect a matched flow to a chosen CPU (the last
// LibreQoS shaper primitive) — see `classifier.buildCpumapSteerProgram`.
pub const CpumapSteerOptions = classifier_mod.CpumapSteerOptions;
pub const SteerBuildError = classifier_mod.SteerBuildError;
pub const buildCpumapSteerProgram = classifier_mod.buildCpumapSteerProgram;

// ── dark-tests aggregator (CONVENTIONS.md §6 step 3) ────────────────────────
//
// refAllDecls walks every pub declaration reachable from this file
// (including the sub-module re-exports above), which is what pulls
// rules.zig/maps.zig/classifier.zig's own `test` blocks into `zig build
// test-xdp-classifier` — a bare `pub const x = @import("x.zig")` re-export
// alone does NOT do this (see CONVENTIONS.md's "dark-tests rule").

test {
    std.testing.refAllDecls(@This());
    _ = @import("rules.zig");
    _ = @import("maps.zig");
    _ = @import("classifier.zig");
}

test "smoke: module imports and re-exports resolve" {
    const rule: ClassifierRule = .{
        .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 },
        .class = 1,
    };
    try std.testing.expectEqual(@as(u32, 1), rule.class);

    const insns = buildClassifierProgram(.{ .lpm_map_fd = 3, .scratch_map_fd = 4 });
    try std.testing.expect(insns.len > 0);
}
