// SPDX-License-Identifier: MIT
//! Rule-table types + LPM key encoding for `xdp-classifier`'s ruleset.
//!
//! A classifier rule maps one IPv4 CIDR prefix to a `u32` class handle. The
//! generated eBPF program (`classifier.zig`) never sees rule CONTENT — it
//! performs one runtime `bpf_map_lookup_elem` against a
//! `BPF_MAP_TYPE_LPM_TRIE` map that the caller populates separately (via
//! `maps.populateRule`), so the same compiled program works for any
//! ruleset. This file's job is (a) validating a caller's rule table before
//! it is loaded into the kernel map and (b) encoding each rule into the
//! exact 8-byte key layout the kernel's LPM trie implementation expects —
//! BYTE FOR BYTE the same layout `classifier.buildClassifierProgram`
//! constructs at runtime from a live packet (see that function's doc
//! comment point 4). A mismatch between the two encodings would silently
//! misclassify every packet rather than fail loudly, so `LpmKey.toBytes`
//! is the single, shared source of truth for the layout — both the
//! populate path (`maps.populateRule`, this file) and the runtime path
//! (the generated bytecode) are documented as committing to it, and
//! `classifier.zig`'s golden test cross-checks its own key-construction
//! instructions produce this exact byte pattern for a matching address.

const std = @import("std");
const builtin = @import("builtin");

/// One IPv4 CIDR prefix: `addr` in wire/dotted order (`addr[0]` is the most
/// significant octet, e.g. `10.0.0.0/8` is `.{ .addr = .{ 10, 0, 0, 0 },
/// .prefix_len = 8 }`) — the same byte order the generated program's
/// packet-to-key copy produces (see `classifier.zig` point 4), so a prefix
/// literal here can be compared directly against packet bytes without any
/// endian conversion.
pub const Ipv4Prefix = struct {
    addr: [4]u8,
    prefix_len: u6,
};

pub const ClassifierRule = struct {
    prefix: Ipv4Prefix,
    class: u32,
};

pub const RuleSetError = error{
    /// `prefix_len > 32` — not representable by an IPv4 LPM key.
    InvalidPrefixLen,
    /// A bit at or beyond `prefix_len` (i.e. a "host bit") is set — the rule
    /// is not in canonical/masked form. Not a kernel requirement (the LPM
    /// trie only ever compares the first `prefix_len` bits), but requiring
    /// canonical input here catches a real caller footgun: two rules that
    /// differ only in don't-care bits look distinct in the table but are
    /// indistinguishable to the trie, silently picking whichever was
    /// inserted last.
    NonCanonicalPrefix,
    /// Two rules share the exact same `(addr, prefix_len)` — ambiguous
    /// which class should win (`map_update_elem` would just let the later
    /// one silently overwrite the earlier).
    DuplicatePrefix,
    /// More rules than the target map's `max_entries` can hold.
    TooManyRules,
    /// `validateSorted`'s caller-supplied `scratch` is shorter than
    /// `rules.len` — it needs one `usize` slot per rule, see that
    /// function's doc comment.
    ScratchTooSmall,
};

/// A caller's full rule table, validated as a unit against the LPM map it
/// will be loaded into.
pub const RuleSet = struct {
    rules: []const ClassifierRule,

    /// Check every structural invariant `maps.populateRule` and the kernel
    /// LPM trie itself assume. `max_entries` is the target map's capacity
    /// (see `maps.LpmMapSpec`). Pure, allocation-free, cannot panic on any
    /// input — see the hostile/fuzz test below.
    ///
    /// ⚠ **O(n²) in `rules.len`** — the duplicate check is a nested linear
    /// scan (F3, `A1/xdp-classifier.md`: measured 256→0.023ms … 32768→322ms
    /// in ReleaseFast, ratio ~4.0x per doubling, i.e. quadratic). That is
    /// the price of staying allocation-free: `RuleSet.rules` is `[]const`
    /// and this function takes no allocator and no scratch memory, so
    /// there is nowhere to sort or hash into. Adequate for the module's
    /// README example (hundreds of rules) and for anything reloaded rarely
    /// relative to its size. A LibreQoS-scale table (tens of thousands of
    /// rules, reloaded on every subscriber change — see README "Design
    /// notes") should call `validateSorted` instead.
    pub fn validate(self: RuleSet, max_entries: usize) RuleSetError!void {
        if (self.rules.len > max_entries) return RuleSetError.TooManyRules;

        for (self.rules, 0..) |rule, i| {
            try checkStructural(rule.prefix);

            var j: usize = 0;
            while (j < i) : (j += 1) {
                const other = self.rules[j].prefix;
                if (other.prefix_len == rule.prefix.prefix_len and
                    std.mem.eql(u8, &other.addr, &rule.prefix.addr))
                {
                    return RuleSetError.DuplicatePrefix;
                }
            }
        }
    }

    /// Same checks as `validate` (byte-for-byte the same verdict on every
    /// input — see the differential test below), but the duplicate check is
    /// O(n log n): sort a caller-supplied index array by `(prefix_len,
    /// addr)` (`std.sort.pdq`, O(log n) stack space, no allocator) and scan
    /// it once for adjacent equal keys, instead of comparing every rule
    /// against every earlier one.
    ///
    /// `scratch` is the caller's own memory — this function does not
    /// allocate — and must hold at least `self.rules.len` `usize` slots
    /// (`error.ScratchTooSmall` otherwise); the caller picks where that
    /// memory comes from (a stack array sized to the target map's
    /// `max_entries`, an arena, a reused buffer across reloads, …), keeping
    /// `RuleSet` itself allocator-agnostic. `scratch`'s contents are
    /// overwritten and left in sorted-index order; callers must not rely on
    /// them after the call.
    pub fn validateSorted(self: RuleSet, max_entries: usize, scratch: []usize) RuleSetError!void {
        if (self.rules.len > max_entries) return RuleSetError.TooManyRules;
        if (scratch.len < self.rules.len) return RuleSetError.ScratchTooSmall;

        // Precedence must match `validate` bit-for-bit, not just agree on
        // whether *some* error exists: `validate` walks the table once, and
        // for each rule checks its OWN structure before ever comparing it
        // against earlier rules. So a duplicate can only preempt a
        // structural failure that comes AFTER it in the table -- never one
        // at or before it, because `validate` would already have returned
        // by the time it got there. Find the first structural failure
        // first, then look for a duplicate only among the rules strictly
        // before it: exactly the prefix of the table `validate` would ever
        // have reached a duplicate-check on.
        var first_bad: ?struct { index: usize, err: RuleSetError } = null;
        for (self.rules, 0..) |rule, i| {
            checkStructural(rule.prefix) catch |err| {
                first_bad = .{ .index = i, .err = err };
                break;
            };
        }
        const limit = if (first_bad) |fb| fb.index else self.rules.len;

        const idx = scratch[0..limit];
        for (idx, 0..) |*slot, i| slot.* = i;
        std.sort.pdq(usize, idx, self.rules, sortIndexLessThan);

        var i: usize = 1;
        while (i < idx.len) : (i += 1) {
            const prev = self.rules[idx[i - 1]].prefix;
            const cur = self.rules[idx[i]].prefix;
            if (prev.prefix_len == cur.prefix_len and std.mem.eql(u8, &prev.addr, &cur.addr)) {
                return RuleSetError.DuplicatePrefix;
            }
        }

        if (first_bad) |fb| return fb.err;
    }
};

/// The prefix_len/canonical half of `validate`'s per-rule check, factored
/// out so `validate` and `validateSorted` share one implementation instead
/// of two copies that could drift apart.
fn checkStructural(prefix: Ipv4Prefix) RuleSetError!void {
    if (prefix.prefix_len > 32) return RuleSetError.InvalidPrefixLen;
    if (!isCanonical(prefix)) return RuleSetError.NonCanonicalPrefix;
}

/// `(prefix_len, addr)` packed into one `u64` so "same prefix_len, same
/// addr" (the thing `validate`'s duplicate check tests) becomes "equal
/// sort key" — and equal keys land adjacent after a sort, turning an O(n²)
/// all-pairs scan into one O(n log n) sort plus an O(n) adjacent scan.
/// `prefix_len` (0..32) is the more significant half so a full sort orders
/// by prefix length first, matching how a human reads a rule table, though
/// nothing here depends on that tie-break order.
fn sortKey(prefix: Ipv4Prefix) u64 {
    const addr_bits: u32 = std.mem.readInt(u32, &prefix.addr, .big);
    return (@as(u64, prefix.prefix_len) << 32) | addr_bits;
}

fn sortIndexLessThan(rules: []const ClassifierRule, a: usize, b: usize) bool {
    return sortKey(rules[a].prefix) < sortKey(rules[b].prefix);
}

/// True if every bit at or beyond `prefix.prefix_len` is zero. `prefix_len
/// == 32` is trivially canonical (no host bits exist); `prefix_len == 0`
/// requires `addr` to be all-zero (the universal default-route rule).
fn isCanonical(prefix: Ipv4Prefix) bool {
    if (prefix.prefix_len >= 32) return true;
    const addr_bits: u32 = std.mem.readInt(u32, &prefix.addr, .big);
    if (prefix.prefix_len == 0) return addr_bits == 0; // every bit is a host bit
    // Host-bit mask: the low (32 - prefix_len) bits. prefix_len is 1..31
    // here, so 32-prefix_len is 1..31 and fits u5 (shifting by 32 would be
    // out of range for a u32 shift amount).
    const host_bits: u5 = @intCast(32 - @as(u32, prefix.prefix_len));
    const mask: u32 = (@as(u32, 1) << host_bits) -% 1;
    return (addr_bits & mask) == 0;
}

/// The exact 8-byte wire layout `BPF_MAP_TYPE_LPM_TRIE` expects for both
/// `map_update_elem` (populating a rule) and `map_lookup_elem` (a runtime
/// query): `struct { __u32 prefixlen; __u8 data[4]; }`, `prefixlen` in the
/// HOST's native byte order (the kernel reads it as a plain in-memory `u32`
/// — there is no network-order convention for this field, unlike the IPv4
/// address bytes themselves) and `data` in the address's own wire/dotted
/// order (see `Ipv4Prefix`'s doc).
pub const LpmKey = struct {
    prefixlen: u32,
    addr: [4]u8,

    pub fn fromPrefix(p: Ipv4Prefix) LpmKey {
        return .{ .prefixlen = p.prefix_len, .addr = p.addr };
    }

    /// A lookup key for one exact address (`prefixlen = 32`) — what the
    /// generated program constructs per-packet at runtime (see
    /// `classifier.zig` point 4); the kernel's LPM trie itself performs the
    /// longest-prefix search against however-specific each stored rule is.
    pub fn exact(addr: [4]u8) LpmKey {
        return .{ .prefixlen = 32, .addr = addr };
    }

    pub fn toBytes(self: LpmKey) [8]u8 {
        var buf: [8]u8 = undefined;
        std.mem.writeInt(u32, buf[0..4], self.prefixlen, builtin.cpu.arch.endian());
        buf[4..8].* = self.addr;
        return buf;
    }
};

/// Pure userspace longest-prefix-match reference — NOT what the eBPF
/// program executes (the kernel's `BPF_MAP_TYPE_LPM_TRIE` map performs the
/// real lookup at runtime, see `classifier.zig`). Provided so a ruleset's
/// intended behavior can be unit-tested and reasoned about without a
/// kernel: a linear scan is adequate here (rule tables in tests/tooling are
/// small; the kernel trie is what carries the real per-packet cost).
pub fn lookupReference(rules_: []const ClassifierRule, addr: [4]u8, default_class: u32) u32 {
    var best: ?ClassifierRule = null;
    for (rules_) |rule| {
        if (!prefixMatches(rule.prefix, addr)) continue;
        // `>=`, not `>`: on a tie (two rules with the same prefix_len both
        // match), the LATER rule in iteration order must win. This mirrors
        // `map_update_elem` on the real LPM trie -- a duplicate
        // `(addr, prefix_len)` key silently overwrites the earlier value, so
        // the kernel's answer for a duplicate ruleset is always the last one
        // loaded (see rules.zig's `DuplicatePrefix` doc comment and F4's
        // measurement: ref returned the FIRST match (111) where the kernel
        // trie returned the LAST (222) for the identical duplicate ruleset).
        // `RuleSet.validate` rejects duplicates outright, so this only
        // matters for a caller that bypasses validation -- but "matches the
        // kernel" is still the correct answer for an oracle, not "matches
        // whichever branch happened to run first".
        if (best == null or rule.prefix.prefix_len >= best.?.prefix.prefix_len) best = rule;
    }
    return if (best) |b| b.class else default_class;
}

fn prefixMatches(prefix: Ipv4Prefix, addr: [4]u8) bool {
    // `prefix_len > 32` never matches -- it does NOT clamp to /32. Such a
    // prefix is not representable by an IPv4 LPM key (`RuleSet.validate`
    // rejects it with `InvalidPrefixLen`, and `populateRuleSet` therefore
    // never loads it into the kernel map), so the kernel's trie can never
    // return a hit for it either. Clamping used to treat it as an exact /32
    // match instead, which made this reference answer for a rule that (by
    // the module's own contract) does not exist in the kernel: measured as
    // ref=7 vs kernel trie=0 for the same out-of-range rule (F4b). This is
    // still the userspace reference, callable on rules that never went
    // through `validate` -- so it must not panic (see the hostile test
    // below), just correctly report "no match" instead of a wrong one.
    if (prefix.prefix_len > 32) return false;
    const len: u32 = prefix.prefix_len;
    if (len == 0) return true;
    const bits: u32 = std.mem.readInt(u32, &prefix.addr, .big);
    const a: u32 = std.mem.readInt(u32, &addr, .big);
    const shift: u5 = @intCast(32 - len);
    return (bits >> shift) == (a >> shift);
}

// ── tests ────────────────────────────────────────────────────────────────────

const testing = std.testing;

test "smoke: RuleSet.validate accepts a well-formed small ruleset" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = 0 }, .class = 0 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try rs.validate(64);
}

test "RuleSet.validate rejects prefix_len > 32" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 33 }, .class = 1 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try testing.expectError(RuleSetError.InvalidPrefixLen, rs.validate(64));
}

test "RuleSet.validate rejects a non-canonical (host-bits-set) prefix" {
    const rules = [_]ClassifierRule{
        // 10.0.0.1/8 — bits below the /8 boundary are non-zero.
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 1 }, .prefix_len = 8 }, .class = 1 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try testing.expectError(RuleSetError.NonCanonicalPrefix, rs.validate(64));
}

test "RuleSet.validate rejects duplicate (addr, prefix_len) pairs" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try testing.expectError(RuleSetError.DuplicatePrefix, rs.validate(64));
}

test "RuleSet.validate rejects more rules than the map's max_entries" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 11, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try testing.expectError(RuleSetError.TooManyRules, rs.validate(1));
}

test "LpmKey.toBytes: exact(/32) key layout is prefixlen(native u32) ++ addr" {
    const key = LpmKey.exact(.{ 192, 168, 1, 1 });
    const bytes = key.toBytes();
    try testing.expectEqual(@as(usize, 8), bytes.len);
    try testing.expectEqual(@as(u32, 32), std.mem.readInt(u32, bytes[0..4], builtin.cpu.arch.endian()));
    try testing.expectEqualSlices(u8, &.{ 192, 168, 1, 1 }, bytes[4..8]);
}

test "LpmKey.fromPrefix round-trips a rule's prefix_len and address bytes" {
    const p: Ipv4Prefix = .{ .addr = .{ 172, 16, 0, 0 }, .prefix_len = 12 };
    const key = LpmKey.fromPrefix(p);
    try testing.expectEqual(@as(u32, 12), key.prefixlen);
    try testing.expectEqualSlices(u8, &p.addr, &key.addr);
}

test "lookupReference: longest prefix wins, default_class on total miss" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = 0 }, .class = 9 }, // default route
    };
    // Matches only the /8.
    try testing.expectEqual(@as(u32, 1), lookupReference(&rules, .{ 10, 2, 3, 4 }, 0));
    // Matches both /8 and /16 — the more specific /16 must win.
    try testing.expectEqual(@as(u32, 2), lookupReference(&rules, .{ 10, 1, 2, 3 }, 0));
    // Matches only the /0 default route.
    try testing.expectEqual(@as(u32, 9), lookupReference(&rules, .{ 8, 8, 8, 8 }, 0));
}

test "lookupReference: no rules at all falls straight to default_class" {
    try testing.expectEqual(@as(u32, 42), lookupReference(&.{}, .{ 1, 2, 3, 4 }, 42));
}

test "hostile: RuleSet.validate never panics across a wide sweep of prefix_len/addr/class values" {
    // Deterministic PRNG sweep (no allocation, no I/O) hammering validate()
    // with every prefix_len in u6's full 0..63 range (33..63 all
    // deliberately out-of-spec) crossed with pseudo-random addr/class
    // bytes, plus every ruleset size from 0 to 8. Success criterion: no
    // panic, and the result is always one of validate()'s declared errors
    // or success — never anything else (there's nothing else it could
    // return, but the point is exercising every code path without a crash,
    // matching this repo's other hostile-input tests, e.g. pping's
    // parse.zig).
    var prng = std.Random.DefaultPrng.init(0xC0FFEE);
    const rand = prng.random();

    var buf: [8]ClassifierRule = undefined;
    var n: usize = 0;
    while (n <= buf.len) : (n += 1) {
        var trial: usize = 0;
        while (trial < 64) : (trial += 1) {
            for (buf[0..n]) |*r| {
                r.* = .{
                    .prefix = .{
                        .addr = .{ rand.int(u8), rand.int(u8), rand.int(u8), rand.int(u8) },
                        .prefix_len = rand.int(u6), // full 0..63 range, including out-of-spec 33..63
                    },
                    .class = rand.int(u32),
                };
            }
            const rs: RuleSet = .{ .rules = buf[0..n] };
            const max_entries = rand.uintLessThan(usize, 16);
            _ = rs.validate(max_entries) catch {}; // any declared error is fine; a panic is not
        }
    }
}

test "hostile: prefixMatches/lookupReference never panic on an out-of-range prefix_len" {
    // prefix_len 33 pre-fix underflowed `32 - prefix_len` (u32) → panic, then
    // (F4b) clamped to /32 and reported a match that does not exist in the
    // kernel (`RuleSet.validate` rejects prefix_len > 32, so this rule can
    // never reach the LPM trie). It must now report NO match at all, for
    // every address including the address that used to "clamp-match" it.
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 255, 255, 255, 255 }, .prefix_len = 33 }, .class = 7 },
    };
    try testing.expectEqual(@as(u32, 0), lookupReference(&rules, .{ 255, 255, 255, 255 }, 0));
    try testing.expectEqual(@as(u32, 0), lookupReference(&rules, .{ 1, 2, 3, 4 }, 0));

    // Full out-of-spec sweep (33‥63) crossed with matching/non-matching
    // addresses: no path panics, and every one of them is a miss.
    var pl: u16 = 33;
    while (pl <= 63) : (pl += 1) {
        const rs = [_]ClassifierRule{
            .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = @intCast(pl) }, .class = 1 },
        };
        try testing.expectEqual(@as(u32, 0), lookupReference(&rs, .{ 10, 0, 0, 0 }, 0));
        try testing.expectEqual(@as(u32, 0), lookupReference(&rs, .{ 192, 168, 0, 1 }, 0));
    }
}

test "F4a: lookupReference ties on equal prefix_len resolve to the LAST-loaded rule, matching the kernel trie" {
    // Two rules with the SAME (addr, prefix_len) -- RuleSet.validate rejects
    // this as DuplicatePrefix, but lookupReference must still answer the way
    // the kernel trie would for a caller that populated the map directly
    // (map_update_elem lets the later write silently overwrite the earlier
    // one, see rules.RuleSetError.DuplicatePrefix's doc comment). Measured
    // pre-fix: ref picked the FIRST rule (111); the kernel trie picks the
    // LAST (222) -- this is F4's tie-break mismatch, reproduced directly.
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 111 },
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 222 },
    };
    try testing.expectEqual(@as(u32, 222), lookupReference(&rules, .{ 10, 1, 2, 3 }, 0));

    // Three-way tie: the last one in iteration order still wins.
    const rules3 = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 3 },
    };
    try testing.expectEqual(@as(u32, 3), lookupReference(&rules3, .{ 10, 1, 2, 3 }, 0));

    // A tie must NOT beat a genuinely longer (unique) prefix that also
    // matches -- the `>=` change must not weaken the longest-prefix-wins
    // invariant itself, only the equal-length tie-break.
    const mixed = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 }, // ties the /8 above
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 9 }, // more specific
    };
    try testing.expectEqual(@as(u32, 9), lookupReference(&mixed, .{ 10, 1, 2, 3 }, 0));
}

test "F5: prefixMatches is exact at the prefix_len bit boundary in both directions" {
    // A mutation that compares one bit too few/many is otherwise invisible
    // to whole-octet-aligned test data (8/16/24/32) -- probe boundaries that
    // fall INSIDE a byte too (1, 15, 31), on both sides of the boundary bit.
    const boundaries = [_]u6{ 1, 7, 8, 15, 16, 23, 24, 31, 32 };
    for (boundaries) |plen| {
        const prefix: Ipv4Prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = plen };
        // Flip only the bit exactly AT the boundary (the first host bit,
        // i.e. bit index `plen` counting from the MSB, 0-based) -- every bit
        // BEFORE it stays 0, matching the all-zero prefix.
        if (plen < 32) {
            var addr: [4]u8 = .{ 0, 0, 0, 0 };
            const bit_from_msb: u5 = @intCast(plen);
            const byte_i = bit_from_msb / 8;
            const bit_in_byte: u3 = @intCast(7 - (bit_from_msb % 8));
            addr[byte_i] |= @as(u8, 1) << bit_in_byte;
            // The host bit is set but every prefix bit (0..plen) is still 0
            // -- must still match (a "too many bits compared" mutation would
            // reject this).
            try testing.expect(prefixMatches(prefix, addr));
        }
        // Flip the LAST bit that IS part of the prefix (bit index plen-1) --
        // must NOT match (a "too few bits compared" mutation would accept
        // this).
        if (plen > 0) {
            var addr: [4]u8 = .{ 0, 0, 0, 0 };
            const bit_from_msb: u5 = @intCast(plen - 1);
            const byte_i = bit_from_msb / 8;
            const bit_in_byte: u3 = @intCast(7 - (bit_from_msb % 8));
            addr[byte_i] |= @as(u8, 1) << bit_in_byte;
            try testing.expect(!prefixMatches(prefix, addr));
        }
    }
}

test "F5: isCanonical rejects a /31 with its one host bit set" {
    // /31 has exactly one host bit (the LSB) -- a mutation treating /31 as
    // "no host bits" (i.e. always canonical) would accept a non-canonical
    // rule silently. Both parities of the LSB are checked so the test does
    // not depend on which octet the mutation touches.
    try testing.expect(isCanonical(.{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 31 })); // LSB 0: canonical
    try testing.expect(!isCanonical(.{ .addr = .{ 10, 0, 0, 1 }, .prefix_len = 31 })); // LSB 1: host bit set
    try testing.expect(!isCanonical(.{ .addr = .{ 255, 255, 255, 255 }, .prefix_len = 31 }));
}

test "hostile: LpmKey.toBytes never panics across the full prefix_len range" {
    var prefix_len: u16 = 0;
    while (prefix_len <= 63) : (prefix_len += 1) {
        const p: Ipv4Prefix = .{ .addr = .{ 255, 255, 255, 255 }, .prefix_len = @intCast(prefix_len) };
        const key = LpmKey.fromPrefix(p);
        _ = key.toBytes();
    }
}

// ── F8: fuzz harnesses ──────────────────────────────────────────────────────
//
// F8 measured 0 `testing.fuzz` harnesses in a module that is a parser (the
// generated eBPF bytecode's packet path, offline-unreachable without porting
// an interpreter -- see the audit record's `repro/xdp-classifier/vm.zig`,
// NOT ported here, still open) plus a rule-table validator (`RuleSet.validate`,
// `lookupReference`/`prefixMatches`) -- entirely ordinary Zig, and exactly
// what these two harnesses corpus-fuzz. The hand-rolled PRNG sweeps above
// stay (they pin specific deterministic scenarios); these add coverage-guided
// exploration on top, same role `testing.fuzz` plays in the other 168
// modules that already have it.

fn fuzzValidateNeverPanics(_: void, smith: *std.testing.Smith) !void {
    var buf: [8]ClassifierRule = undefined;
    const n = smith.index(buf.len + 1); // 0..8 rules
    for (buf[0..n]) |*r| {
        r.* = .{
            .prefix = .{
                .addr = .{ smith.value(u8), smith.value(u8), smith.value(u8), smith.value(u8) },
                .prefix_len = smith.value(u6), // full 0..63, including out-of-spec 33..63
            },
            .class = smith.value(u32),
        };
    }
    const rs: RuleSet = .{ .rules = buf[0..n] };
    // `usize` has no fixed bitsize (comptime error from Smith's weighting
    // machinery) -- draw a fixed-width value and widen it instead.
    const max_entries: usize = smith.valueRangeAtMost(u16, 0, 16);
    _ = rs.validate(max_entries) catch {}; // any declared error or success; a panic is not
}

test "fuzz: RuleSet.validate never panics on any (rules, max_entries)" {
    try std.testing.fuzz({}, fuzzValidateNeverPanics, .{});
}

fn fuzzLookupNeverPanics(_: void, smith: *std.testing.Smith) !void {
    var buf: [8]ClassifierRule = undefined;
    const n = smith.index(buf.len + 1);
    for (buf[0..n]) |*r| {
        r.* = .{
            .prefix = .{
                .addr = .{ smith.value(u8), smith.value(u8), smith.value(u8), smith.value(u8) },
                .prefix_len = smith.value(u6),
            },
            .class = smith.value(u32),
        };
    }
    const query: [4]u8 = .{ smith.value(u8), smith.value(u8), smith.value(u8), smith.value(u8) };
    const default_class = smith.value(u32);

    const got = lookupReference(buf[0..n], query, default_class);
    // Invariant that must hold for EVERY input, not just the hand-picked
    // scenarios above: the result is either the caller's default (no rule
    // matched) or the class of one of the rules actually loaded -- never a
    // value manufactured out of thin air.
    var found_among_rules = false;
    for (buf[0..n]) |r| {
        if (r.class == got) {
            found_among_rules = true;
            break;
        }
    }
    try testing.expect(got == default_class or found_among_rules);
}

test "fuzz: lookupReference never panics, and always returns default_class or a loaded rule's class" {
    try std.testing.fuzz({}, fuzzLookupNeverPanics, .{});
}

// ── F3: validateSorted (O(n log n) alternative to validate's O(n²)) ────────

test "validateSorted: accepts a well-formed small ruleset" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = 0 }, .class = 0 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    var scratch: [rules.len]usize = undefined;
    try rs.validateSorted(64, &scratch);
}

test "validateSorted: rejects prefix_len > 32" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 33 }, .class = 1 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    var scratch: [rules.len]usize = undefined;
    try testing.expectError(RuleSetError.InvalidPrefixLen, rs.validateSorted(64, &scratch));
}

test "validateSorted: rejects a non-canonical (host-bits-set) prefix" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 1 }, .prefix_len = 8 }, .class = 1 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    var scratch: [rules.len]usize = undefined;
    try testing.expectError(RuleSetError.NonCanonicalPrefix, rs.validateSorted(64, &scratch));
}

test "validateSorted: rejects duplicate (addr, prefix_len) pairs, however far apart in the table" {
    // Same F4-shaped duplicate as `validate`'s test, but with unrelated
    // rules interleaved so a sort is actually load-bearing: the two
    // duplicates are NOT adjacent in input order, only after sorting.
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 172, 16, 0, 0 }, .prefix_len = 12 }, .class = 3 },
        .{ .prefix = .{ .addr = .{ 192, 168, 0, 0 }, .prefix_len = 16 }, .class = 4 },
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    var scratch: [rules.len]usize = undefined;
    try testing.expectError(RuleSetError.DuplicatePrefix, rs.validateSorted(64, &scratch));
}

test "validateSorted: rejects more rules than the map's max_entries" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 11, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    var scratch: [rules.len]usize = undefined;
    try testing.expectError(RuleSetError.TooManyRules, rs.validateSorted(1, &scratch));
}

test "validateSorted: too-small scratch is rejected, not a silent out-of-bounds write" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 11, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    var scratch: [1]usize = undefined;
    try testing.expectError(RuleSetError.ScratchTooSmall, rs.validateSorted(64, &scratch));
}

fn fuzzValidateSortedAgreesWithValidate(_: void, smith: *std.testing.Smith) !void {
    // Differential test, not a reimplementation: both functions are called
    // on the SAME input and their verdicts compared. A bug that made
    // `validateSorted` agree with itself (e.g. a comparator that treats
    // every pair as unequal, so the sort never detects a duplicate) would
    // still show up here as a mismatch against `validate`'s independent
    // O(n²) all-pairs scan -- the two implementations don't share any
    // duplicate-detection code (see [[feedback_a_test_that_reimplements_the_code_cannot_fail]]).
    var buf: [40]ClassifierRule = undefined;
    const n = smith.index(buf.len + 1);
    for (buf[0..n]) |*r| {
        r.* = .{
            .prefix = .{
                .addr = .{ smith.value(u8), smith.value(u8), smith.value(u8), smith.value(u8) },
                .prefix_len = smith.value(u6), // full 0..63, including out-of-spec 33..63
            },
            .class = smith.value(u32),
        };
    }
    const rs: RuleSet = .{ .rules = buf[0..n] };
    const max_entries: usize = smith.valueRangeAtMost(u16, 0, 48);

    var scratch: [buf.len]usize = undefined;
    const want = rs.validate(max_entries);
    const got = rs.validateSorted(max_entries, scratch[0..n]);
    try testing.expectEqual(want, got);
}

test "fuzz: validateSorted agrees with validate on every (rules, max_entries)" {
    try std.testing.fuzz({}, fuzzValidateSortedAgreesWithValidate, .{});
}

test "F3: validateSorted agrees with validate across a deterministic sweep, including duplicate-heavy tables" {
    // Non-fuzz (runs on every `zig build test`, not just `--fuzz`) sweep
    // biased toward the case a naive sort-based dedup gets wrong: many
    // rules colliding on a SMALL set of (prefix_len, addr) pairs, so ties
    // land adjacent after sorting and the adjacent-scan must catch all of
    // them, not just the first collision.
    var prng = std.Random.DefaultPrng.init(0xF3F3);
    const rand = prng.random();

    var buf: [64]ClassifierRule = undefined;
    var scratch: [buf.len]usize = undefined;
    var n: usize = 0;
    while (n <= buf.len) : (n += 1) {
        var trial: usize = 0;
        while (trial < 32) : (trial += 1) {
            for (buf[0..n]) |*r| {
                r.* = .{
                    // Only 4 distinct addresses and 3 distinct prefix
                    // lengths -- with n up to 64, duplicates are near-
                    // guaranteed, and many of them.
                    .prefix = .{
                        .addr = .{ 10, 0, 0, rand.uintLessThan(u8, 4) },
                        .prefix_len = @as(u6, 24) + rand.uintLessThan(u6, 3),
                    },
                    .class = rand.int(u32),
                };
            }
            const rs: RuleSet = .{ .rules = buf[0..n] };
            const max_entries = rand.uintLessThan(usize, 96);
            const want = rs.validate(max_entries);
            const got = rs.validateSorted(max_entries, scratch[0..n]);
            try testing.expectEqual(want, got);
        }
    }
}
