// SPDX-License-Identifier: MIT
//! Rule-table types + LPM key encoding for `xdp-classifier`'s ruleset.
//!
//! A classifier rule maps one IPv4 CIDR prefix to a `u32` class handle. The
//! generated eBPF program (`classifier.zig`) never sees rule CONTENT — it
//! performs one runtime `bpf_map_lookup_elem` against a
//! `BPF_MAP_TYPE_LPM_TRIE` map that the caller populates separately (via
//! `maps.populateRule`), so the same compiled program works for any
//! ruleset. This file's job is (a) validating a caller's rule table before
//! it is loaded into the kernel map and (b) encoding each rule into the
//! exact 8-byte key layout the kernel's LPM trie implementation expects —
//! BYTE FOR BYTE the same layout `classifier.buildClassifierProgram`
//! constructs at runtime from a live packet (see that function's doc
//! comment point 4). A mismatch between the two encodings would silently
//! misclassify every packet rather than fail loudly, so `LpmKey.toBytes`
//! is the single, shared source of truth for the layout — both the
//! populate path (`maps.populateRule`, this file) and the runtime path
//! (the generated bytecode) are documented as committing to it, and
//! `classifier.zig`'s golden test cross-checks its own key-construction
//! instructions produce this exact byte pattern for a matching address.

const std = @import("std");
const builtin = @import("builtin");

/// One IPv4 CIDR prefix: `addr` in wire/dotted order (`addr[0]` is the most
/// significant octet, e.g. `10.0.0.0/8` is `.{ .addr = .{ 10, 0, 0, 0 },
/// .prefix_len = 8 }`) — the same byte order the generated program's
/// packet-to-key copy produces (see `classifier.zig` point 4), so a prefix
/// literal here can be compared directly against packet bytes without any
/// endian conversion.
pub const Ipv4Prefix = struct {
    addr: [4]u8,
    prefix_len: u6,
};

pub const ClassifierRule = struct {
    prefix: Ipv4Prefix,
    class: u32,
};

pub const RuleSetError = error{
    /// `prefix_len > 32` — not representable by an IPv4 LPM key.
    InvalidPrefixLen,
    /// A bit at or beyond `prefix_len` (i.e. a "host bit") is set — the rule
    /// is not in canonical/masked form. Not a kernel requirement (the LPM
    /// trie only ever compares the first `prefix_len` bits), but requiring
    /// canonical input here catches a real caller footgun: two rules that
    /// differ only in don't-care bits look distinct in the table but are
    /// indistinguishable to the trie, silently picking whichever was
    /// inserted last.
    NonCanonicalPrefix,
    /// Two rules share the exact same `(addr, prefix_len)` — ambiguous
    /// which class should win (`map_update_elem` would just let the later
    /// one silently overwrite the earlier).
    DuplicatePrefix,
    /// More rules than the target map's `max_entries` can hold.
    TooManyRules,
};

/// A caller's full rule table, validated as a unit against the LPM map it
/// will be loaded into.
pub const RuleSet = struct {
    rules: []const ClassifierRule,

    /// Check every structural invariant `maps.populateRule` and the kernel
    /// LPM trie itself assume. `max_entries` is the target map's capacity
    /// (see `maps.LpmMapSpec`). Pure, allocation-free, cannot panic on any
    /// input — see the hostile/fuzz test below.
    pub fn validate(self: RuleSet, max_entries: usize) RuleSetError!void {
        if (self.rules.len > max_entries) return RuleSetError.TooManyRules;

        for (self.rules, 0..) |rule, i| {
            if (rule.prefix.prefix_len > 32) return RuleSetError.InvalidPrefixLen;
            if (!isCanonical(rule.prefix)) return RuleSetError.NonCanonicalPrefix;

            var j: usize = 0;
            while (j < i) : (j += 1) {
                const other = self.rules[j].prefix;
                if (other.prefix_len == rule.prefix.prefix_len and
                    std.mem.eql(u8, &other.addr, &rule.prefix.addr))
                {
                    return RuleSetError.DuplicatePrefix;
                }
            }
        }
    }
};

/// True if every bit at or beyond `prefix.prefix_len` is zero. `prefix_len
/// == 32` is trivially canonical (no host bits exist); `prefix_len == 0`
/// requires `addr` to be all-zero (the universal default-route rule).
fn isCanonical(prefix: Ipv4Prefix) bool {
    if (prefix.prefix_len >= 32) return true;
    const addr_bits: u32 = std.mem.readInt(u32, &prefix.addr, .big);
    if (prefix.prefix_len == 0) return addr_bits == 0; // every bit is a host bit
    // Host-bit mask: the low (32 - prefix_len) bits. prefix_len is 1..31
    // here, so 32-prefix_len is 1..31 and fits u5 (shifting by 32 would be
    // out of range for a u32 shift amount).
    const host_bits: u5 = @intCast(32 - @as(u32, prefix.prefix_len));
    const mask: u32 = (@as(u32, 1) << host_bits) -% 1;
    return (addr_bits & mask) == 0;
}

/// The exact 8-byte wire layout `BPF_MAP_TYPE_LPM_TRIE` expects for both
/// `map_update_elem` (populating a rule) and `map_lookup_elem` (a runtime
/// query): `struct { __u32 prefixlen; __u8 data[4]; }`, `prefixlen` in the
/// HOST's native byte order (the kernel reads it as a plain in-memory `u32`
/// — there is no network-order convention for this field, unlike the IPv4
/// address bytes themselves) and `data` in the address's own wire/dotted
/// order (see `Ipv4Prefix`'s doc).
pub const LpmKey = struct {
    prefixlen: u32,
    addr: [4]u8,

    pub fn fromPrefix(p: Ipv4Prefix) LpmKey {
        return .{ .prefixlen = p.prefix_len, .addr = p.addr };
    }

    /// A lookup key for one exact address (`prefixlen = 32`) — what the
    /// generated program constructs per-packet at runtime (see
    /// `classifier.zig` point 4); the kernel's LPM trie itself performs the
    /// longest-prefix search against however-specific each stored rule is.
    pub fn exact(addr: [4]u8) LpmKey {
        return .{ .prefixlen = 32, .addr = addr };
    }

    pub fn toBytes(self: LpmKey) [8]u8 {
        var buf: [8]u8 = undefined;
        std.mem.writeInt(u32, buf[0..4], self.prefixlen, builtin.cpu.arch.endian());
        buf[4..8].* = self.addr;
        return buf;
    }
};

/// Pure userspace longest-prefix-match reference — NOT what the eBPF
/// program executes (the kernel's `BPF_MAP_TYPE_LPM_TRIE` map performs the
/// real lookup at runtime, see `classifier.zig`). Provided so a ruleset's
/// intended behavior can be unit-tested and reasoned about without a
/// kernel: a linear scan is adequate here (rule tables in tests/tooling are
/// small; the kernel trie is what carries the real per-packet cost).
pub fn lookupReference(rules_: []const ClassifierRule, addr: [4]u8, default_class: u32) u32 {
    var best: ?ClassifierRule = null;
    for (rules_) |rule| {
        if (!prefixMatches(rule.prefix, addr)) continue;
        if (best == null or rule.prefix.prefix_len > best.?.prefix.prefix_len) best = rule;
    }
    return if (best) |b| b.class else default_class;
}

fn prefixMatches(prefix: Ipv4Prefix, addr: [4]u8) bool {
    // Clamp to /32: an out-of-range prefix_len (> 32; `prefix_len` is u6 so a
    // caller can pass up to 63) means "compare all 32 bits". Without the clamp
    // `32 - prefix_len` underflows the u32 subtraction and panics — this is
    // the userspace reference, callable on rules that never went through
    // `RuleSet.validate` (which is the real gate that rejects prefix_len > 32).
    const len = @min(@as(u32, prefix.prefix_len), 32);
    if (len == 0) return true;
    const bits: u32 = std.mem.readInt(u32, &prefix.addr, .big);
    const a: u32 = std.mem.readInt(u32, &addr, .big);
    const shift: u5 = @intCast(32 - len);
    return (bits >> shift) == (a >> shift);
}

// ── tests ────────────────────────────────────────────────────────────────────

const testing = std.testing;

test "smoke: RuleSet.validate accepts a well-formed small ruleset" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = 0 }, .class = 0 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try rs.validate(64);
}

test "RuleSet.validate rejects prefix_len > 32" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 33 }, .class = 1 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try testing.expectError(RuleSetError.InvalidPrefixLen, rs.validate(64));
}

test "RuleSet.validate rejects a non-canonical (host-bits-set) prefix" {
    const rules = [_]ClassifierRule{
        // 10.0.0.1/8 — bits below the /8 boundary are non-zero.
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 1 }, .prefix_len = 8 }, .class = 1 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try testing.expectError(RuleSetError.NonCanonicalPrefix, rs.validate(64));
}

test "RuleSet.validate rejects duplicate (addr, prefix_len) pairs" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try testing.expectError(RuleSetError.DuplicatePrefix, rs.validate(64));
}

test "RuleSet.validate rejects more rules than the map's max_entries" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 11, 0, 0, 0 }, .prefix_len = 8 }, .class = 2 },
    };
    const rs: RuleSet = .{ .rules = &rules };
    try testing.expectError(RuleSetError.TooManyRules, rs.validate(1));
}

test "LpmKey.toBytes: exact(/32) key layout is prefixlen(native u32) ++ addr" {
    const key = LpmKey.exact(.{ 192, 168, 1, 1 });
    const bytes = key.toBytes();
    try testing.expectEqual(@as(usize, 8), bytes.len);
    try testing.expectEqual(@as(u32, 32), std.mem.readInt(u32, bytes[0..4], builtin.cpu.arch.endian()));
    try testing.expectEqualSlices(u8, &.{ 192, 168, 1, 1 }, bytes[4..8]);
}

test "LpmKey.fromPrefix round-trips a rule's prefix_len and address bytes" {
    const p: Ipv4Prefix = .{ .addr = .{ 172, 16, 0, 0 }, .prefix_len = 12 };
    const key = LpmKey.fromPrefix(p);
    try testing.expectEqual(@as(u32, 12), key.prefixlen);
    try testing.expectEqualSlices(u8, &p.addr, &key.addr);
}

test "lookupReference: longest prefix wins, default_class on total miss" {
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = 8 }, .class = 1 },
        .{ .prefix = .{ .addr = .{ 10, 1, 0, 0 }, .prefix_len = 16 }, .class = 2 },
        .{ .prefix = .{ .addr = .{ 0, 0, 0, 0 }, .prefix_len = 0 }, .class = 9 }, // default route
    };
    // Matches only the /8.
    try testing.expectEqual(@as(u32, 1), lookupReference(&rules, .{ 10, 2, 3, 4 }, 0));
    // Matches both /8 and /16 — the more specific /16 must win.
    try testing.expectEqual(@as(u32, 2), lookupReference(&rules, .{ 10, 1, 2, 3 }, 0));
    // Matches only the /0 default route.
    try testing.expectEqual(@as(u32, 9), lookupReference(&rules, .{ 8, 8, 8, 8 }, 0));
}

test "lookupReference: no rules at all falls straight to default_class" {
    try testing.expectEqual(@as(u32, 42), lookupReference(&.{}, .{ 1, 2, 3, 4 }, 42));
}

test "hostile: RuleSet.validate never panics across a wide sweep of prefix_len/addr/class values" {
    // Deterministic PRNG sweep (no allocation, no I/O) hammering validate()
    // with every prefix_len in u6's full 0..63 range (33..63 all
    // deliberately out-of-spec) crossed with pseudo-random addr/class
    // bytes, plus every ruleset size from 0 to 8. Success criterion: no
    // panic, and the result is always one of validate()'s declared errors
    // or success — never anything else (there's nothing else it could
    // return, but the point is exercising every code path without a crash,
    // matching this repo's other hostile-input tests, e.g. pping's
    // parse.zig).
    var prng = std.Random.DefaultPrng.init(0xC0FFEE);
    const rand = prng.random();

    var buf: [8]ClassifierRule = undefined;
    var n: usize = 0;
    while (n <= buf.len) : (n += 1) {
        var trial: usize = 0;
        while (trial < 64) : (trial += 1) {
            for (buf[0..n]) |*r| {
                r.* = .{
                    .prefix = .{
                        .addr = .{ rand.int(u8), rand.int(u8), rand.int(u8), rand.int(u8) },
                        .prefix_len = rand.int(u6), // full 0..63 range, including out-of-spec 33..63
                    },
                    .class = rand.int(u32),
                };
            }
            const rs: RuleSet = .{ .rules = buf[0..n] };
            const max_entries = rand.uintLessThan(usize, 16);
            _ = rs.validate(max_entries) catch {}; // any declared error is fine; a panic is not
        }
    }
}

test "hostile: prefixMatches/lookupReference never panic on an out-of-range prefix_len" {
    // prefix_len 33 pre-fix underflows `32 - prefix_len` (u32) → panic. It now
    // clamps to /32 (compare all 32 bits): an exact match on the stored addr.
    const rules = [_]ClassifierRule{
        .{ .prefix = .{ .addr = .{ 255, 255, 255, 255 }, .prefix_len = 33 }, .class = 7 },
    };
    try testing.expectEqual(@as(u32, 7), lookupReference(&rules, .{ 255, 255, 255, 255 }, 0));
    try testing.expectEqual(@as(u32, 0), lookupReference(&rules, .{ 1, 2, 3, 4 }, 0));

    // Full out-of-spec sweep (33‥63) crossed with matching/non-matching
    // addresses: no path panics.
    var pl: u16 = 33;
    while (pl <= 63) : (pl += 1) {
        const rs = [_]ClassifierRule{
            .{ .prefix = .{ .addr = .{ 10, 0, 0, 0 }, .prefix_len = @intCast(pl) }, .class = 1 },
        };
        _ = lookupReference(&rs, .{ 10, 0, 0, 0 }, 0);
        _ = lookupReference(&rs, .{ 192, 168, 0, 1 }, 0);
    }
}

test "hostile: LpmKey.toBytes never panics across the full prefix_len range" {
    var prefix_len: u16 = 0;
    while (prefix_len <= 63) : (prefix_len += 1) {
        const p: Ipv4Prefix = .{ .addr = .{ 255, 255, 255, 255 }, .prefix_len = @intCast(prefix_len) };
        const key = LpmKey.fromPrefix(p);
        _ = key.toBytes();
    }
}
