#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for src/attestation_fixtures.zig (synthetic, NOT W3C vectors).

Mutation run 2026-10-05: the attestation-certificate paths for Ed25519, RSA
and non-P-256 EC keys, and the id-fido-gen-ce-aaguid extension check, had no
test with a certificate that exercised them. The W3C §16 corpus only ships
ES256 attestation certificates without that extension, so these are made
here with python `cryptography` (50.0.0):

  * attestation certificates (self-signed, fixed names and dates) for an
    Ed25519 key, an RSA-2048 key and a P-384 key, each carrying the AAGUID
    extension with the AAGUID of W3C §16.7 (`packed_es256_full`);
  * two P-256 certificates whose AAGUID extension is wrong: a different
    AAGUID, and the right 16 octets encoded as a UTF8String instead of an
    OCTET STRING;
  * for the Ed25519 and RSA certificates, a signature over §16.7's
    authData || SHA-256(clientDataJSON) — a valid `packed` attestation
    with that certificate;
  * two RSA credential keys of 2047 and 2048 bits with an RS256 signature
    over `rsa_floor_msg`, for the credential-key modulus floor.

Run from the module directory:  python3 tools/gen_attestation_fixtures.py
> src/attestation_fixtures.zig. RSA and ECDSA keys are fresh on every run,
so the output differs byte-wise between runs; the tests depend only on each
run being internally consistent. Ed25519 keys come from fixed seeds.
"""
import datetime, hashlib, re

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, ed25519, padding, rsa
from cryptography.x509.oid import NameOID, ObjectIdentifier

AAGUID_OID = ObjectIdentifier("1.3.6.1.4.1.45724.1.1.4")


def vector_hex(struct, field):
    src = open("src/vectors.zig").read()
    body = src[src.index(f"pub const {struct} = struct"):]
    return bytes.fromhex(re.search(rf'pub const {field} = hexLit\("([0-9a-f]+)"\)', body).group(1))


att_obj = vector_hex("packed_es256_full", "attestation_object")
cdj = vector_hex("packed_es256_full", "registration_client_data_json")
# authData is the last CBOR item: key "authData" (68 61757468 44617461), then bytes header 58 a4.
i = att_obj.index(bytes.fromhex("68617574684461746158"))
auth_len = att_obj[i + 10]
auth_data = att_obj[i + 11 : i + 11 + auth_len]
assert len(auth_data) == auth_len and i + 11 + auth_len == len(att_obj)
aaguid = auth_data[37:53]
assert aaguid.hex() == "876ca4f52071c3e9b25509ef2cdf7ed6"
msg = auth_data + hashlib.sha256(cdj).digest()


def cert(key, cn, ext_value):
    name = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, cn),
        x509.NameAttribute(NameOID.ORGANIZATIONAL_UNIT_NAME, "Authenticator Attestation"),
    ])
    b = (x509.CertificateBuilder()
         .subject_name(name).issuer_name(name)
         .public_key(key.public_key())
         .serial_number(1)
         .not_valid_before(datetime.datetime(2026, 1, 1))
         .not_valid_after(datetime.datetime(3025, 12, 31))
         .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True))
    if ext_value is not None:
        b = b.add_extension(x509.UnrecognizedExtension(AAGUID_OID, ext_value), critical=False)
    algo = None if isinstance(key, ed25519.Ed25519PrivateKey) else hashes.SHA256()
    return b.sign(key, algo).public_bytes(serialization.Encoding.DER)


octet = bytes([0x04, 0x10]) + aaguid
ed_key = ed25519.Ed25519PrivateKey.from_private_bytes(bytes(range(32)))
rsa_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
p384_key = ec.generate_private_key(ec.SECP384R1())
p256_key = ec.generate_private_key(ec.SECP256R1())

out = {
    "ed25519_attestation_cert_der": cert(ed_key, "ed25519-attestation", octet),
    "ed25519_attestation_sig": ed_key.sign(msg),
    "rsa2048_attestation_cert_der": cert(rsa_key, "rsa2048-attestation", octet),
    "rsa2048_attestation_sig": rsa_key.sign(msg, padding.PKCS1v15(), hashes.SHA256()),
    "p384_attestation_cert_der": cert(p384_key, "p384-attestation", octet),
    "p256_wrong_aaguid_cert_der": cert(p256_key, "wrong-aaguid", bytes([0x04, 0x10]) + bytes(16)),
    "p256_aaguid_not_octet_string_cert_der": cert(p256_key, "aaguid-utf8string", bytes([0x0c, 0x10]) + aaguid),
}

rsa_floor_msg = b"webauthn RS256 credential modulus floor"
for bits in (2047, 2048):
    k = rsa.generate_private_key(public_exponent=65537, key_size=bits)
    nums = k.public_key().public_numbers()
    assert nums.n.bit_length() == bits
    out[f"rsa{bits}_credential_n"] = nums.n.to_bytes((bits + 7) // 8, "big")
    out[f"rsa{bits}_credential_e"] = nums.e.to_bytes(3, "big")
    out[f"rsa{bits}_credential_sig"] = k.sign(rsa_floor_msg, padding.PKCS1v15(), hashes.SHA256())

print("// SPDX-License-Identifier: MIT")
print("//! GENERATED by tools/gen_attestation_fixtures.py -- synthetic fixtures, NOT")
print("//! W3C vectors. See that script for what each one is for.")
print()
print('pub const rsa_floor_msg = "%s";' % rsa_floor_msg.decode())
print()
for name, b in out.items():
    print(f'pub const {name} = hexLit("{b.hex()}");')
print()
print("fn hexLit(comptime hex: []const u8) [hex.len / 2]u8 {")
print("    comptime {")
print("        @setEvalBranchQuota(200_000);")
print("        var out: [hex.len / 2]u8 = undefined;")
print("        _ = @import(\"std\").fmt.hexToBytes(&out, hex) catch unreachable;")
print("        return out;")
print("    }")
print("}")
