// SPDX-License-Identifier: MIT
//! GENERATED by modules/zstd/tools/gen-goldens.sh -- do not edit.
//! libzstd v1.5.7 (f8745da6ff1ad1e7bab384bd1f9d742439278e99), one-shot through tools/zref.c with a destination
//! capacity. Each row: for room case `case` (`corpus.room_cases`), the
//! least capacity libzstd succeeds in (bisected; one byte less fails with
//! dstSize_tooSmall) and the length and SHA-256 of the frame it writes there.

pub const Golden = struct { case: []const u8, room: usize, len: usize, sha256: *const [64]u8 };

pub const rows = [_]Golden{
    .{ .case = "room-empty", .room = 18, .len = 9, .sha256 = "6fb8543883dafcc2ed0934866b8b3f775231f5b0933add08bf502e9e84944cbd" },
    .{ .case = "room-empty-ck", .room = 18, .len = 13, .sha256 = "f96deff1816083fdff8bc3e46c3fe6ca46a6bb49f4d5a00627616c13237a512c" },
    .{ .case = "room-one", .room = 18, .len = 10, .sha256 = "82473988a809598f10b9a40a405db57c1235ddadc5a06d83190d7fc877ff017f" },
    .{ .case = "room-seven-ck", .room = 20, .len = 20, .sha256 = "87a3cdacba134a5727a70f9f5d0a3704fbb2e24c9759cae15880f687abfeee9c" },
    .{ .case = "room-mix-772", .room = 302, .len = 294, .sha256 = "9a85fc86da443e3fd371c6f805688a0e8611b8c0186d43b825a076c4258fc30d" },
    .{ .case = "room-skewed-180", .room = 99, .len = 91, .sha256 = "2544ff31c370a5e4bcb2528a7f76a91d4b6fccb2d9b0f3c1f410130c30c08532" },
    .{ .case = "room-csv-33-raw", .room = 42, .len = 42, .sha256 = "c356ad0ec6ba1a0866975f341f416fe77ac6bf7c2f523e9d36083f0bcdcd1f7b" },
    .{ .case = "room-csv-33-l19-ck", .room = 43, .len = 39, .sha256 = "4ed058783948823e73672c5541c415c93d5f4c95f8f6bdd3ad0f9bc7dea33612" },
    .{ .case = "room-words-1000", .room = 337, .len = 328, .sha256 = "494140dade50e0d06898e91515b86562b5c156cf39ad7593aa5f8b3cca862c24" },
    .{ .case = "room-words-1000-l19", .room = 322, .len = 318, .sha256 = "6eeb3696599f6e3ddae841f3a9c13bb030c595a36041fa50a003352bb2f5e1c7" },
    .{ .case = "room-words-16385-fast", .room = 4340, .len = 4332, .sha256 = "5d10e2891917cef46f290417cc92bef217260d4d73a1635e91575e2d83bae5ae" },
    .{ .case = "room-words-16385-lazy", .room = 3556, .len = 3548, .sha256 = "cd93f98cafc54c887043e17f72ff46d6e6e7eeb7f9c763ed3e262d4cb8e72841" },
    .{ .case = "room-csv-600000-l1", .room = 207437, .len = 207433, .sha256 = "15f188f65daacb2ccf72e9b9f2a925024350f363a8690e031999a51b0560d818" },
    .{ .case = "room-csv-600000-l3", .room = 229254, .len = 229246, .sha256 = "1b2130850b793e394f501576b5011778606ab4614e3d1aa74fc65621c7ace088" },
    .{ .case = "room-csv-600000-l12", .room = 213525, .len = 213517, .sha256 = "97dec4adeebdf7079e4ad4fd9c0a6f7224c297c1c401d8005fec09829a9194f9" },
    .{ .case = "room-csv-600000-l19", .room = 180374, .len = 180366, .sha256 = "0c928b51fe1380a139cb058f042404cab4307e8d18d8d85feac08b5d73d94085" },
    .{ .case = "room-alternating-l16", .room = 570546, .len = 570538, .sha256 = "7f4ce31a8a34c21b16f5d75331c0aa7a2c57f7d64723811349da9ddd67574e34" },
    .{ .case = "room-random-300000", .room = 300022, .len = 300022, .sha256 = "4fb9a3b1071b7054eb3a261734163451cc4d9e2ea4bc97a75df53b4b378260b6" },
    .{ .case = "room-zeros-300000", .room = 46, .len = 30, .sha256 = "6ddbf9bcdc6b51be2f72cda91542ddb3d5448e0b1092ba36eaa8d16988cb843a" },
    .{ .case = "room-rle-text-rle", .room = 41326, .len = 41314, .sha256 = "ff36a5073786e1934496a16a19ad5408d08c6425d908fbd2cc3030c3f46d3eae" },
    .{ .case = "room-csv-131073-tcb", .room = 52131, .len = 52127, .sha256 = "25a08fa25ea15d5f6c7d6f3c4a0db8593c9dfcd95120789dfdf93ecda6e2fe38" },
    .{ .case = "room-words-262145-split", .room = 52967, .len = 52963, .sha256 = "ffec5ec3658c7782219631f521882faf07c04b397766cb8c2ed9a077cd665627" },
    .{ .case = "room-words-262145-post", .room = 45626, .len = 45622, .sha256 = "e471c10c8defb09ba29168c59aa86de96fd63b4977302570e6d78af34052af7e" },
    .{ .case = "room-words-262145-mbs", .room = 55415, .len = 55411, .sha256 = "527a0aca7a818baf60d2fd300772bb2df77c09a93982a90c81c4bc29a7e8af34" },
    .{ .case = "room-words-16385-magicless", .room = 3600, .len = 3592, .sha256 = "d7bc1e29e8265fa13637672149640c87d5be14e0497c976c9df536e4419623b8" },
    .{ .case = "room-csv-600000-ldm", .room = 215169, .len = 215161, .sha256 = "57b1d6a44da11209d5f796faaa5f09b7eebcfec394e572e7e6113ad1c709cde1" },
    .{ .case = "room-far-repeat-mt", .room = 263380, .len = 263380, .sha256 = "16c27ffccba1551a33f9194d3c634224773002fb154d68495599c0d6872b93b7" },
    .{ .case = "room-alternating-mt-ck", .room = 604561, .len = 604561, .sha256 = "a428e2091e8058816f7210e995852ddfe14dbc2b3884930c6b8c6bb026f296ef" },
    .{ .case = "room-usingdict", .room = 51777, .len = 51772, .sha256 = "e0ef6ed9d6506b0651cc9150d328fc726370009d2962bf68ebda7971fffdbd65" },
    .{ .case = "room-usingcdict-ck", .room = 3440, .len = 3436, .sha256 = "a489afe8a8361c7bf4a7032e97451debdb5f7646d16814c1b58f5f89732a1cd9" },
    .{ .case = "room-cdict-attached", .room = 3413, .len = 3404, .sha256 = "3ef1c3ff2c36428cb23622627962e2466e5596d762976a9fa6bc436ad0f96e6c" },
    .{ .case = "room-load", .room = 209890, .len = 209882, .sha256 = "3f0c079b99d3fc87209b5f83efa5da9ff18e1be49557bab7fa3ce1dd6ac417c3" },
    .{ .case = "room-prefix", .room = 224, .len = 215, .sha256 = "adefabbb5f43a2cdfc7a779401e56db1f7208283a527cd011b3774cc28f7f93b" },
};
