// SPDX-License-Identifier: MIT
//! GENERATED by modules/zstd/tools/gen-seekable-goldens.sh -- do not edit.
//! libzstd v1.5.7 (f8745da6ff1ad1e7bab384bd1f9d742439278e99), contrib/seekable_format driven by tools/zseekable.c.
//! Each row: length and SHA-256 of everything ZSTD_seekable_CStream emits
//! for corpus case `case` at `level`, with or without frame checksums, at
//! `max_frame_size` (0: the 1 GiB default), following `schedule`.

pub const Golden = struct { case: []const u8, level: i32, checksum: bool, max_frame_size: u32, schedule: []const u8, len: usize, sha256: *const [64]u8 };

pub const rows = [_]Golden{
    .{ .case = "empty", .level = 3, .checksum = false, .max_frame_size = 0, .schedule = "e", .len = 34, .sha256 = "15216a2d9f8d47aebf9cc447ab40f34d34aaf301f95507e0480ab09799f18e1c" },
    .{ .case = "empty", .level = 3, .checksum = true, .max_frame_size = 0, .schedule = "e", .len = 38, .sha256 = "0989764aadd3b9fddeb50570c7b987bdb9c774bc3392bb6be59c4f40817c4e10" },
    .{ .case = "empty", .level = 3, .checksum = true, .max_frame_size = 1024, .schedule = "f,e", .len = 59, .sha256 = "967b963a2921be381d326e9be188171eb045fff8500390451961a47135311a7e" },
    .{ .case = "empty", .level = 3, .checksum = false, .max_frame_size = 1024, .schedule = "f,f,e", .len = 68, .sha256 = "f27996c8f3c9be1912191b37e89a3860e3df760e57cbcb6aac4e9684f63c7eee" },
    .{ .case = "one", .level = 3, .checksum = true, .max_frame_size = 0, .schedule = "c*,e", .len = 39, .sha256 = "d39c64fc67107794a2b33eca6c4701c71b98a0a7537bc9d840555305d96eb872" },
    .{ .case = "seven", .level = 1, .checksum = false, .max_frame_size = 3, .schedule = "c*,e", .len = 75, .sha256 = "1bc5bf1ed23254b017acaf96bb6af7dd48f11c919f0b0bcba1ea86d76e246e50" },
    .{ .case = "words-1000", .level = 3, .checksum = true, .max_frame_size = 100, .schedule = "c*,e", .len = 1011, .sha256 = "a32651886b72b8c680c12a5a5146a30474895e4049555e08afb956f896a11cac" },
    .{ .case = "words-1000", .level = 3, .checksum = false, .max_frame_size = 100, .schedule = "c1,c7,c500,c*,e", .len = 967, .sha256 = "6b1c45cffee6cca731c7a1fc7174a1e1d0c13d365491795228906926a54701f3" },
    .{ .case = "words-16385", .level = 3, .checksum = true, .max_frame_size = 4096, .schedule = "o7,c*,e", .len = 4205, .sha256 = "f059e906617f0b933e1faba9b083bf479f9fc34ed29c55510cf60bd2086ec0ca" },
    .{ .case = "words-16385", .level = 3, .checksum = false, .max_frame_size = 4096, .schedule = "o1,c*,e", .len = 4185, .sha256 = "de950028b0a42006df6c6e87773f3a6aed75e5f49c9b9e00f044c66661c07b48" },
    .{ .case = "words-16385", .level = 3, .checksum = true, .max_frame_size = 4096, .schedule = "c*,o3,e", .len = 4205, .sha256 = "f059e906617f0b933e1faba9b083bf479f9fc34ed29c55510cf60bd2086ec0ca" },
    .{ .case = "csv-131073", .level = 1, .checksum = false, .max_frame_size = 0, .schedule = "c*,e", .len = 44887, .sha256 = "1d5eb9c57d3d2f30a8cb6546c877983afd72fc312959f648b8f3bd66d85e83f2" },
    .{ .case = "csv-131073", .level = 3, .checksum = true, .max_frame_size = 0, .schedule = "c*,e", .len = 49053, .sha256 = "03d121ecda01bcbd7fa3e4dd6745b3eccf9c11b42f364e833a439b92f4e9642c" },
    .{ .case = "csv-131073", .level = 19, .checksum = false, .max_frame_size = 0, .schedule = "c*,e", .len = 39305, .sha256 = "13f2696073aab85be5ecae04129f825a1202a5b235d50d64a402ffd61a4b8a66" },
    .{ .case = "words-262145", .level = -5, .checksum = false, .max_frame_size = 65536, .schedule = "c*,e", .len = 64172, .sha256 = "9c9f6e6301a00f49e171fb1d28b11672c5ce261e4bc97f2c426524a2ed55b47f" },
    .{ .case = "words-262145", .level = 3, .checksum = true, .max_frame_size = 65536, .schedule = "c*,e", .len = 54292, .sha256 = "9727c6fc6deb451f138b58e9c91cc2f66d9f54102d5e866683ac490e05c755d1" },
    .{ .case = "words-262145", .level = 9, .checksum = false, .max_frame_size = 65536, .schedule = "c*,e", .len = 50197, .sha256 = "66aac1e33c5d247b0a1684a0189b4479786403126d446d815077339f17f74470" },
    .{ .case = "csv-600000", .level = 3, .checksum = true, .max_frame_size = 262144, .schedule = "c*,e", .len = 237793, .sha256 = "33dbefe328864a42b14bce7510f786559070cbe50ad56e3ad03e62eb1eb14939" },
    .{ .case = "csv-600000", .level = 3, .checksum = false, .max_frame_size = 262144, .schedule = "c100000,f,c*,e", .len = 237878, .sha256 = "0ade9fe54bfc1718750a70c11a2271776cc6e8cb2078c50061da8d7c4bfb6656" },
    .{ .case = "csv-600000", .level = 6, .checksum = true, .max_frame_size = 100000, .schedule = "o4096,c*,e", .len = 221648, .sha256 = "651cad954bdf0db2be85c03a310356367c4783262bfeefd8366108f38c847ef9" },
    .{ .case = "random-300000", .level = 3, .checksum = true, .max_frame_size = 65536, .schedule = "c*,e", .len = 300134, .sha256 = "10b76393a1ada4a215ef77485d327e59db42e413f1678265c8d8a5e48b30231b" },
    .{ .case = "zeros-300000", .level = 3, .checksum = false, .max_frame_size = 1000, .schedule = "c*,e", .len = 7834, .sha256 = "4944f6f7f6f51daaca50c0662a0a2d51d459427ecc6e4f4f532a0e18a7d64d05" },
    .{ .case = "mix-300000-9", .level = 12, .checksum = true, .max_frame_size = 131072, .schedule = "c50000,c50000,f,c*,e", .len = 93207, .sha256 = "d8d2a42bfb4db18d95cb361ae546e1d80357490401b5db77e34c0cec0999ce80" },
    .{ .case = "mix-140000-1", .level = 16, .checksum = false, .max_frame_size = 70000, .schedule = "c*,e", .len = 53893, .sha256 = "4fc47351e830f09dabbfa39cdb595d39a8573afd78e5e79499c01c12ee23258d" },
    .{ .case = "words-1000", .level = 3, .checksum = true, .max_frame_size = 1, .schedule = "c*,e", .len = 22038, .sha256 = "1590a13091d7297d236d946ac7c92f79ef4e5a6870c9fa1c2b21d03f42846cb5" },
    .{ .case = "far-repeat", .level = 3, .checksum = true, .max_frame_size = 0, .schedule = "c*,e", .len = 140873, .sha256 = "0fcdc128a02be98c1550ef059659cb223ee250136a7f1794e1221f9b351c03f1" },
};
