// SPDX-License-Identifier: MIT
//! Tests for `chain.zig`'s RFC 5280 §6 path-validation algorithm.
//!
//! The end-to-end tests use real DER certificates from `fixtures_test.zig`
//! (root/intermediate/leaf PKIs generated by a real OpenSSL 3.5 — the test
//! oracle — for every supported signature algorithm plus dedicated
//! rejection-case hierarchies; see that file's doc comment). Every "valid
//! chain" fixture was cross-checked with `openssl verify` at generation
//! time (recorded in the scratch generation script, not part of this repo);
//! these tests re-verify the same DER bytes against THIS module's
//! `verifyChain`, so a pass here means both oracles agree.
//!
//! Sub-algorithm unit tests (`checkPathLength`, `checkNameConstraints`,
//! `checkExtendedKeyUsage`, `parsePssParams`) use hand-built DER fixtures
//! for shapes the openssl-generated certificates don't exercise on their
//! own (e.g. the RFC 4055 all-defaults PSS-params encoding), following the
//! same pattern `extensions.zig`'s own tests already use.

const std = @import("std");
const testing = std.testing;
const chain_mod = @import("chain.zig");
const extensions = @import("extensions.zig");
const rsa = @import("rsa");
const fx = @import("fixtures_test.zig");

// All fixtures were generated with notBefore ~= 2026-07-11T00:00:00Z and
// notAfter ~= 2036-07-08T00:00:00Z (see fixtures_test.zig / the generation
// script's `-days 3650`).
const now_valid: i64 = 1798761600; // 2027-01-01T00:00:00Z
const now_before: i64 = 1262304000; // 2010-01-01T00:00:00Z
const now_after: i64 = 2208988800; // 2040-01-01T00:00:00Z

// ── end-to-end: one valid chain per signature algorithm ─────────────────────

test "valid RSA PKCS1v15 chain verifies (openssl-oracle cross-checked); hostname + EKU positive" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_rsa, &fx.inter_rsa };
    const anchors = [_]chain_mod.CertDer{&fx.root_rsa};
    const result = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{
        .now_sec = now_valid,
        .expected_host = "leaf.example.org",
        .required_eku = .server_auth,
    });
    try testing.expectEqual(@as(u32, 2), result.depth);
    try testing.expectEqual(@as(usize, 0), result.trust_anchor_index);
}

test "valid RSA-PSS chain verifies (root->intermediate link is RSASSA-PSS, exercises verifyPssLink)" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_pss, &fx.inter_pss };
    const anchors = [_]chain_mod.CertDer{&fx.root_pss};
    _ = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid });
}

test "valid ECDSA P-256 chain verifies (openssl-oracle cross-checked)" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_ec256, &fx.inter_ec256 };
    const anchors = [_]chain_mod.CertDer{&fx.root_ec256};
    _ = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid });
}

test "valid ECDSA P-384 chain verifies (openssl-oracle cross-checked)" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_ec384, &fx.inter_ec384 };
    const anchors = [_]chain_mod.CertDer{&fx.root_ec384};
    _ = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid });
}

test "valid Ed25519 chain verifies (openssl-oracle cross-checked)" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_ed, &fx.inter_ed };
    const anchors = [_]chain_mod.CertDer{&fx.root_ed};
    _ = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid });
}

// ── rejection cases: each maps to a distinct typed error ───────────────────

test "expired leaf rejected with CertificateExpired" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_rsa, &fx.inter_rsa };
    const anchors = [_]chain_mod.CertDer{&fx.root_rsa};
    try testing.expectError(error.CertificateExpired, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_after }));
}

test "not-yet-valid leaf rejected with CertificateNotYetValid" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_rsa, &fx.inter_rsa };
    const anchors = [_]chain_mod.CertDer{&fx.root_rsa};
    try testing.expectError(error.CertificateNotYetValid, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_before }));
}

test "name constraint violation rejected with NameConstraintViolated" {
    // Same intermediate as the valid RSA chain (permits only *.example.org);
    // this leaf's SAN is leaf.evil.com instead.
    const chain = [_]chain_mod.CertDer{ &fx.leaf_rsa_bad, &fx.inter_rsa };
    const anchors = [_]chain_mod.CertDer{&fx.root_rsa};
    try testing.expectError(error.NameConstraintViolated, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid }));
}

test "non-CA certificate used as issuer rejected with NotACertificateAuthority" {
    // subleaf_rsa was (mechanically, via openssl) signed by leaf_rsa's key,
    // even though leaf_rsa's basicConstraints says cA:FALSE.
    const chain = [_]chain_mod.CertDer{ &fx.subleaf_rsa, &fx.leaf_rsa };
    const anchors = [_]chain_mod.CertDer{&fx.inter_rsa};
    try testing.expectError(error.NotACertificateAuthority, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid }));
}

test "pathLenConstraint exceeded rejected with PathLenConstraintExceeded" {
    // root_pl has pathlen:0 (no intermediate CAs allowed at all), but the
    // chain has one (inter_pl).
    const chain = [_]chain_mod.CertDer{ &fx.leaf_pl, &fx.inter_pl };
    const anchors = [_]chain_mod.CertDer{&fx.root_pl};
    try testing.expectError(error.PathLenConstraintExceeded, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid }));
}

test "self-issued certificate is not counted against pathLenConstraint (positive)" {
    // root_si has pathlen:1. Path: leaf_si -> inter_si -> root_si_prime
    // (self-issued: same subject as root_si, different key, signed BY
    // root_si) -> root_si. Two CA certificates sit between the leaf and the
    // anchor, but root_si_prime is self-issued and must NOT count — only
    // inter_si does, so pathlen:1 is satisfied. A naive implementation that
    // counts both would wrongly reject this with PathLenConstraintExceeded.
    const chain = [_]chain_mod.CertDer{ &fx.leaf_si, &fx.inter_si, &fx.root_si_prime };
    const anchors = [_]chain_mod.CertDer{&fx.root_si};
    const result = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid });
    try testing.expectEqual(@as(u32, 3), result.depth);
}

test "tampered signature byte rejected with CertificateSignatureInvalid" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_rsa_tampered, &fx.inter_rsa };
    const anchors = [_]chain_mod.CertDer{&fx.root_rsa};
    try testing.expectError(error.CertificateSignatureInvalid, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid }));
}

test "unknown trust anchor rejected with NoTrustedPath" {
    const chain = [_]chain_mod.CertDer{ &fx.leaf_rsa, &fx.inter_rsa };
    const anchors = [_]chain_mod.CertDer{};
    try testing.expectError(error.NoTrustedPath, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid }));
}

test "required EKU mismatch rejected with ExtendedKeyUsageMismatch" {
    // leaf_rsa's extKeyUsage is serverAuth only.
    const chain = [_]chain_mod.CertDer{ &fx.leaf_rsa, &fx.inter_rsa };
    const anchors = [_]chain_mod.CertDer{&fx.root_rsa};
    try testing.expectError(error.ExtendedKeyUsageMismatch, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{
        .now_sec = now_valid,
        .required_eku = .client_auth,
    }));
}

test "empty chain rejected with EmptyChain" {
    const chain = [_]chain_mod.CertDer{};
    const anchors = [_]chain_mod.CertDer{&fx.root_rsa};
    try testing.expectError(error.EmptyChain, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_valid }));
}

// ── checkPathLength ──────────────────────────────────────────────────────

test "checkPathLength: unconstrained always passes" {
    try chain_mod.checkPathLength(null, 0);
    try chain_mod.checkPathLength(null, 1000);
}

test "checkPathLength: within budget passes, exceeded fails" {
    try chain_mod.checkPathLength(2, 0);
    try chain_mod.checkPathLength(2, 2);
    try testing.expectError(error.PathLenConstraintExceeded, chain_mod.checkPathLength(2, 3));
    try testing.expectError(error.PathLenConstraintExceeded, chain_mod.checkPathLength(0, 1));
    try chain_mod.checkPathLength(0, 0);
}

// ── checkNameConstraints ──────────────────────────────────────────────────

/// `GeneralSubtree ::= SEQUENCE { base GeneralName }` wrapping one dNSName
/// base (`[2] IMPLICIT IA5String`, tag 0x82) — the shape
/// `extensions.subtreeIterator` walks. Short-form DER lengths only (test
/// names are always < 128 bytes).
fn dnsSubtree(comptime name: []const u8) [4 + name.len]u8 {
    var buf: [4 + name.len]u8 = undefined;
    buf[0] = 0x30;
    buf[1] = 2 + name.len;
    buf[2] = 0x82;
    buf[3] = name.len;
    for (name, 0..) |c, i| buf[4 + i] = c;
    return buf;
}

/// `GeneralNames ::= SEQUENCE OF GeneralName` wrapping one dNSName entry —
/// the shape `checkNameConstraints`'s `subject_san` parameter expects
/// (same as a real `subjectAltName` extnValue).
fn generalNamesWithDns(comptime name: []const u8) [4 + name.len]u8 {
    var buf: [4 + name.len]u8 = undefined;
    buf[0] = 0x30;
    buf[1] = 2 + name.len;
    buf[2] = 0x82;
    buf[3] = name.len;
    for (name, 0..) |c, i| buf[4 + i] = c;
    return buf;
}

test "checkNameConstraints: dNSName label-suffix match, default-deny once a permitted set exists" {
    const subtree = dnsSubtree("example.org");
    const permitted = [_][]const u8{&subtree};
    const excluded = [_][]const u8{};

    // No SAN at all: only the (absent) directoryName constraint applies -> passes.
    try chain_mod.checkNameConstraints(&permitted, &excluded, "irrelevant subject dn", "");

    // SAN dNSName "www.example.org" -> matches the permitted suffix.
    const good = generalNamesWithDns("www.example.org");
    try chain_mod.checkNameConstraints(&permitted, &excluded, "dn", &good);

    // SAN dNSName "evilexample.org" -> same trailing bytes as a raw
    // substring, but NOT on a label boundary; must NOT match.
    const bad = generalNamesWithDns("evilexample.org");
    try testing.expectError(error.NameConstraintViolated, chain_mod.checkNameConstraints(&permitted, &excluded, "dn", &bad));

    // SAN dNSName "example.net" -> different domain entirely, no permitted
    // subtree covers it (a permitted dNSName set exists, so this is a
    // default-deny, not merely "unconstrained").
    const other = generalNamesWithDns("example.net");
    try testing.expectError(error.NameConstraintViolated, chain_mod.checkNameConstraints(&permitted, &excluded, "dn", &other));
}

test "checkNameConstraints: excluded wins even when a name would also be permitted" {
    const permitted_tree = dnsSubtree("example.org");
    const excluded_tree = dnsSubtree("bad.example.org");
    const permitted = [_][]const u8{&permitted_tree};
    const excluded = [_][]const u8{&excluded_tree};

    // Within the permitted domain overall, but also within the excluded subdomain.
    const name = generalNamesWithDns("host.bad.example.org");
    try testing.expectError(error.NameConstraintViolated, chain_mod.checkNameConstraints(&permitted, &excluded, "dn", &name));

    // Within the permitted domain, outside the excluded subdomain -> passes.
    const ok_name = generalNamesWithDns("host.example.org");
    try chain_mod.checkNameConstraints(&permitted, &excluded, "dn", &ok_name);
}

test "checkNameConstraints: no constraints at all always passes" {
    const permitted = [_][]const u8{};
    const excluded = [_][]const u8{};
    const name = generalNamesWithDns("anything.example.com");
    try chain_mod.checkNameConstraints(&permitted, &excluded, "any subject dn", &name);
}

test "checkNameConstraints: iPAddress CIDR containment" {
    // base = 10.0.0.0/255.255.0.0 (a /16), i.e. addr=10.0.0.0 mask=255.255.0.0
    const subtree_content = [_]u8{ 0x30, 10, 0x87, 8, 10, 0, 0, 0, 255, 255, 0, 0 };
    const permitted = [_][]const u8{&subtree_content};
    const excluded = [_][]const u8{};

    const in_range = [_]u8{ 0x30, 6, 0x87, 4, 10, 0, 55, 66 };
    try chain_mod.checkNameConstraints(&permitted, &excluded, "dn", &in_range);

    const out_of_range = [_]u8{ 0x30, 6, 0x87, 4, 10, 1, 55, 66 };
    try testing.expectError(error.NameConstraintViolated, chain_mod.checkNameConstraints(&permitted, &excluded, "dn", &out_of_range));
}

test "checkNameConstraints: directoryName RDN-sequence prefix containment" {
    // `dnMatchesPrefix` matches generic DER elements one at a time (the
    // encoded byte span of each successive "RDN" must be identical) — it
    // doesn't need real X.501 AttributeTypeAndValue structure to exercise
    // the prefix-containment algorithm itself, so plain OCTET STRING
    // elements stand in for RDNs here.
    const rdn_org = [_]u8{ 0x04, 3, 'O', 'r', 'g' }; // one "RDN": "Org"
    const rdn_sub = [_]u8{ 0x04, 3, 'S', 'u', 'b' }; // another: "Sub"
    const rdn_other = [_]u8{ 0x04, 5, 'O', 't', 'h', 'e', 'r' };

    const base = rdn_org; // base DN = [Org]
    const name_prefixed = rdn_org ++ rdn_sub; // name DN = [Org, Sub] -> base is a strict prefix
    const name_unrelated = rdn_other ++ rdn_sub; // name DN = [Other, Sub] -> base is NOT a prefix

    // `permitted`/`excluded` are raw `GeneralSubtrees` blobs (`SEQUENCE OF
    // GeneralSubtree`, `GeneralSubtree ::= SEQUENCE { base GeneralName }`) —
    // NOT the bare RDN content on its own. `base` (the constraint's
    // directoryName) must be wrapped in the `[4] Name` CHOICE tag (0xa4)
    // and then in the `GeneralSubtree` SEQUENCE tag (0x30), matching exactly
    // what `subtreeIterator`/`SubtreeIterator.next` expect to walk — feeding
    // it the unwrapped `base` alone previously crashed the parser (it tried
    // to read `base`'s own 5 bytes as if they were an outer `GeneralSubtree`
    // SEQUENCE, then walked off the end looking for a nested `base` inside).
    const base_general_name = [_]u8{ 0xa4, base.len } ++ base;
    const general_subtree = [_]u8{ 0x30, base_general_name.len } ++ base_general_name;
    const permitted = [_][]const u8{&general_subtree};
    const excluded = [_][]const u8{};

    // directoryName is CHOICE-tagged `[4] Name` — context-specific,
    // constructed (identifier byte 0xa4) — wrapped in an outer
    // `GeneralNames SEQUENCE` for feeding to `checkNameConstraints`.
    //
    // `checkNameConstraints` always ALSO checks the subject DN itself against
    // any accumulated directoryName constraint (see the two calls below this
    // block), so these SAN-focused checks pass `&name_prefixed` (which
    // itself satisfies the permitted base) as the subject DN — isolating
    // what's under test here to the SAN entry's own good/bad match, not a
    // spurious subject_dn violation.
    const good_entry = [_]u8{ 0xa4, name_prefixed.len } ++ name_prefixed;
    const good = [_]u8{ 0x30, good_entry.len } ++ good_entry;
    try chain_mod.checkNameConstraints(&permitted, &excluded, &name_prefixed, &good);

    const bad_entry = [_]u8{ 0xa4, name_unrelated.len } ++ name_unrelated;
    const bad = [_]u8{ 0x30, bad_entry.len } ++ bad_entry;
    try testing.expectError(error.NameConstraintViolated, chain_mod.checkNameConstraints(&permitted, &excluded, &name_prefixed, &bad));

    // The subject DN itself is always checked against directoryName
    // constraints too, independent of any SAN.
    try chain_mod.checkNameConstraints(&permitted, &excluded, &name_prefixed, "");
    try testing.expectError(error.NameConstraintViolated, chain_mod.checkNameConstraints(&permitted, &excluded, &name_unrelated, ""));
}

// ── checkExtendedKeyUsage ──────────────────────────────────────────────────

// ExtKeyUsageSyntax ::= SEQUENCE OF KeyPurposeId, one OID: serverAuth (1.3.6.1.5.5.7.3.1).
const eku_server_auth = [_]u8{ 0x30, 0x0a, 0x06, 0x08, 0x2b, 0x06, 0x01, 0x05, 0x05, 0x07, 0x03, 0x01 };
// ...clientAuth (1.3.6.1.5.5.7.3.2).
const eku_client_auth = [_]u8{ 0x30, 0x0a, 0x06, 0x08, 0x2b, 0x06, 0x01, 0x05, 0x05, 0x07, 0x03, 0x02 };
// ...anyExtendedKeyUsage (2.5.29.37.0).
const eku_any = [_]u8{ 0x30, 0x06, 0x06, 0x04, 0x55, 0x1d, 0x25, 0x00 };

test "checkExtendedKeyUsage: required=null is a no-op regardless of EKUs present" {
    const intermediates = [_]?[]const u8{&eku_client_auth};
    try chain_mod.checkExtendedKeyUsage(&intermediates, &eku_client_auth, null);
}

test "checkExtendedKeyUsage: leaf EKU must include the required purpose" {
    const intermediates = [_]?[]const u8{null};
    try chain_mod.checkExtendedKeyUsage(&intermediates, &eku_server_auth, .server_auth);
    try testing.expectError(
        error.ExtendedKeyUsageMismatch,
        chain_mod.checkExtendedKeyUsage(&intermediates, &eku_client_auth, .server_auth),
    );
}

test "checkExtendedKeyUsage: leaf EKU absent is unrestricted" {
    const intermediates = [_]?[]const u8{null};
    try chain_mod.checkExtendedKeyUsage(&intermediates, null, .server_auth);
}

test "checkExtendedKeyUsage: an intermediate's EKU must permit the leaf purpose too" {
    const bad_intermediates = [_]?[]const u8{&eku_client_auth};
    try testing.expectError(
        error.ExtendedKeyUsageMismatch,
        chain_mod.checkExtendedKeyUsage(&bad_intermediates, &eku_server_auth, .server_auth),
    );

    const any_intermediates = [_]?[]const u8{&eku_any};
    try chain_mod.checkExtendedKeyUsage(&any_intermediates, &eku_server_auth, .server_auth);
}

// ── parsePssParams (RFC 4055 §3.1) ──────────────────────────────────────────

test "parsePssParams: null params (AlgorithmIdentifier omitted parameters) -> RFC 4055 defaults" {
    const params = try chain_mod.parsePssParams(null);
    try testing.expectEqual(@as(usize, 20), params.salt_len);
}

test "parsePssParams: empty SEQUENCE (all fields omitted) -> RFC 4055 defaults (sha1, salt 20)" {
    const empty_seq = [_]u8{ 0x30, 0x00 };
    const params = try chain_mod.parsePssParams(&empty_seq);
    try testing.expectEqual(@as(usize, 20), params.salt_len);
}

test "parsePssParams: explicit sha256/MGF1-sha256/saltLen 32 (matches openssl's own encoding)" {
    // RSASSA-PSS-params ::= SEQUENCE {
    //   hashAlgorithm    [0] { SEQUENCE { OID sha256 } },
    //   maskGenAlgorithm [1] { SEQUENCE { OID mgf1, SEQUENCE { OID sha256 } } },
    //   saltLength       [2] { INTEGER 32 },
    // }
    const sha256_alg = [_]u8{ 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x01 };
    const hash_field = [_]u8{ 0xa0, sha256_alg.len } ++ sha256_alg;

    const mgf1_alg = [_]u8{ 0x30, 0x18, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x08 } ++ sha256_alg;
    const mgf_field = [_]u8{ 0xa1, mgf1_alg.len } ++ mgf1_alg;

    const salt_field = [_]u8{ 0xa2, 0x03, 0x02, 0x01, 32 };

    const content = hash_field ++ mgf_field ++ salt_field;
    const seq = [_]u8{ 0x30, content.len } ++ content;

    const params = try chain_mod.parsePssParams(&seq);
    try testing.expectEqual(@as(usize, 32), params.salt_len);
}

test "parsePssParams: mismatched digest vs MGF1 inner hash rejected (this module's documented restriction)" {
    const sha256_alg = [_]u8{ 0x30, 0x0b, 0x06, 0x09, 0x60, 0x86, 0x48, 0x01, 0x65, 0x03, 0x04, 0x02, 0x01 };
    const sha1_alg = [_]u8{ 0x30, 0x07, 0x06, 0x05, 0x2b, 0x0e, 0x03, 0x02, 0x1a };
    const hash_field = [_]u8{ 0xa0, sha256_alg.len } ++ sha256_alg; // hashAlgorithm = sha256

    // mgf1-OID element (11 bytes) ++ sha1_alg (9 bytes) = 20-byte content.
    const mgf1_alg = [_]u8{ 0x30, 0x14, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x08 } ++ sha1_alg; // MGF1 inner hash = sha1 (mismatch)
    const mgf_field = [_]u8{ 0xa1, mgf1_alg.len } ++ mgf1_alg;

    const content = hash_field ++ mgf_field;
    const seq = [_]u8{ 0x30, content.len } ++ content;

    try testing.expectError(error.UnsupportedPssParams, chain_mod.parsePssParams(&seq));
}
