// SPDX-License-Identifier: MIT
//! ECDSA P-521 in path validation and CRLs: std's `Parsed.verify` refuses
//! the curve, so links under a P-521 issuer go through `chain.zig`'s
//! `verifyP521Link` (the `p521` module). Fixtures: `data/p521/`, generated by
//! `tools/gen_p521_fixtures.py` with every verdict below first agreed by
//! `openssl verify` (OpenSSL 3.5.5).

const std = @import("std");
const testing = std.testing;
const chain_mod = @import("chain.zig");
const crl = @import("crl.zig");
const safe = @import("safe.zig");

const root521 = @embedFile("data/p521/root521.der");
const inter521 = @embedFile("data/p521/inter521.der");
const leaf521 = @embedFile("data/p521/leaf521.der");
const leaf256 = @embedFile("data/p521/leaf256.der");
const root384 = @embedFile("data/p521/root384.der");
const interB521 = @embedFile("data/p521/interB521.der");
const leafB521 = @embedFile("data/p521/leafB521.der");
const crl_inter521 = @embedFile("data/p521/crl_inter521.der");

const now: i64 = 1767225600; // 2026-01-01T00:00:00Z
const now_after: i64 = 1924992000; // 2031-01-01T00:00:00Z

test "P-521 chain (root SHA-512, inter SHA-384, leaf SHA-256) verifies, hostname included" {
    const chain = [_]chain_mod.CertDer{ leaf521, inter521 };
    const anchors = [_]chain_mod.CertDer{root521};
    const v = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now, .expected_host = "p521.example" });
    try testing.expectEqual(@as(u32, 2), v.depth);
    // std parses a P-521 leaf (it names the curve), so the convenience view is there.
    try testing.expect(v.leaf != null);
    try testing.expectError(error.CertificateHostMismatch, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now, .expected_host = "other.example" }));
}

test "P-256 leaf under a P-521 CA (ecdsa-with-SHA512)" {
    const chain = [_]chain_mod.CertDer{ leaf256, inter521 };
    const anchors = [_]chain_mod.CertDer{root521};
    _ = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now });
}

test "P-521 intermediate under a P-384 root: std's link, then ours" {
    const chain = [_]chain_mod.CertDer{ leafB521, interB521 };
    const anchors = [_]chain_mod.CertDer{root384};
    _ = try chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now });
}

test "P-521: flipped signature byte, expiry, wrong anchor are refused" {
    const anchors = [_]chain_mod.CertDer{root521};
    // The ECDSA signature's last byte (the end of s) sits at the end of the DER.
    var bad: [leaf521.len]u8 = leaf521.*;
    bad[bad.len - 1] ^= 0x01;
    const tampered = [_]chain_mod.CertDer{ &bad, inter521 };
    try testing.expectError(error.CertificateSignatureInvalid, chain_mod.verifyChain(testing.allocator, &tampered, &anchors, .{ .now_sec = now }));
    const chain = [_]chain_mod.CertDer{ leaf521, inter521 };
    try testing.expectError(error.CertificateExpired, chain_mod.verifyChain(testing.allocator, &chain, &anchors, .{ .now_sec = now_after }));
    const wrong = [_]chain_mod.CertDer{root384};
    try testing.expectError(error.NoTrustedPath, chain_mod.verifyChain(testing.allocator, &chain, &wrong, .{ .now_sec = now }));
}

test "P-521 CRL (ecdsa-with-SHA512): revoked, good, tampered" {
    const opts: crl.Options = .{ .now_sec = now };
    try testing.expect(try crl.checkRevocation(crl_inter521, leaf521, inter521, opts) == .good);
    const st = try crl.checkRevocation(crl_inter521, leaf256, inter521, opts);
    try testing.expect(st == .revoked);
    var bad: [crl_inter521.len]u8 = crl_inter521.*;
    bad[bad.len - 1] ^= 0x01;
    try testing.expectError(error.CertificateSignatureInvalid, crl.checkRevocation(&bad, leaf521, inter521, opts));
}

test "spkiOf: a P-521 key reports secp521r1 and a 133-byte SEC1 point" {
    const spki = try safe.spkiOf(leaf521);
    try testing.expect(spki.algorithmIs(&safe.oid_ec_public_key));
    try testing.expectEqualSlices(u8, &safe.oid_secp521r1, spki.namedCurveOid().?);
    try testing.expectEqual(@as(usize, 133), spki.key_bits.len);
    _ = try @import("p521").EcdsaP521Sha512.PublicKey.fromSec1(spki.key_bits);
}
