// SPDX-License-Identifier: MIT
//! x509 — X.509 certificate CHAIN / path validation (RFC 5280 §6): the
//! multi-certificate trust-chain verifier this collection lacks (the `rsa`
//! module only self-SIGNS a single certificate; `std.crypto.Certificate`
//! only parses + verifies ONE certificate against ONE candidate issuer).
//! Consumers: mutual-TLS client-certificate authentication on a
//! TLS-terminated server, and OPC-UA trust-list validation (`opcua`
//! module's F9 security layer).
//!
//! **Implemented.** `verifyChain` performs full RFC 5280 §6 path validation:
//! RFC 4158-style path building with backtracking over multiple
//! same-subject-DN candidates, per-link signature verification (RSA
//! PKCS1v15/ECDSA P-256+P-384/Ed25519 via `std.crypto.Certificate.Parsed.verify`,
//! RSASSA-PSS via this module's own `verifyPssLink` + the `rsa` module,
//! ML-DSA-44/65/87 via `verifyMlDsaLink` + std's `std.crypto.sign.mldsa`),
//! basicConstraints/keyUsage CA-signer enforcement, pathLenConstraint
//! bookkeeping with the self-issued-certificate exception, accumulated
//! nameConstraints, extended-key-usage chaining, and hostname matching
//! (delegated to std's RFC-6125-tested `verifyHostName`). Cross-checked
//! against real root/intermediate/leaf hierarchies generated by OpenSSL 3.5
//! (the test oracle) for every supported signature algorithm plus dedicated
//! rejection-case hierarchies (expired/not-yet-valid, name-constraint
//! violation, non-CA issuer, pathLenConstraint exceeded, self-issued not
//! counted, tampered signature, EKU mismatch, unknown anchor) — see
//! `chain_test.zig`. Out of scope, by design: CRL/OCSP revocation and
//! certificate policy processing — see below and `chain.zig`'s doc comment.
//!
//! ## What `std.crypto.Certificate` already gives us (recon; see also
//! `chain.zig`'s doc comment for how each piece is used)
//!
//! - **DER primitives** (`Certificate.der.Element.parse`, `Tag`/`Identifier`/
//!   `Class`/`PC`, all `pub`): reused directly, not reimplemented — see
//!   `extensions.zig`.
//! - **Single-certificate parse** (`Certificate.parse` → `Parsed`): exposes
//!   version, issuer/subject (raw DN bytes + `commonName` alone pulled out —
//!   NOT a decomposed RDN/attribute list), validity (`not_before`/`not_after`
//!   as unix seconds), `signature_algorithm`, `pub_key_algo`, and
//!   `subjectAltName` (raw slice; `verifyHostName` decodes `dNSName` entries
//!   from it, nothing else). It does **NOT** expose `basicConstraints`,
//!   `keyUsage`, `extKeyUsage`, `subjectKeyIdentifier`,
//!   `authorityKeyIdentifier`, or `nameConstraints` at all — those OIDs are
//!   *recognized* (`Certificate.ExtensionId`) but their VALUES are never
//!   extracted into `Parsed`, since std's own extension-walk loop only
//!   special-cases `subject_alt_name`. `extensions.zig` fills exactly this
//!   gap.
//! - **Single-link verify** (`Parsed.verify(issuer, now_sec)`): checks
//!   issuer==subject DN match, validity window, AND the signature — for RSA
//!   PKCS1v15 (SHA-1/224/256/384/512), ECDSA (P-256/P-384 — **not** P-521,
//!   `error.CertificateSignatureNamedCurveUnsupported`), and Ed25519.
//!   **RSA-PSS is not supported at all**: `Certificate.Algorithm` (the
//!   certificate's `signatureAlgorithm`) has no `rsassa_pss` variant, so
//!   `Certificate.parse` itself fails
//!   (`error.CertificateHasUnrecognizedObjectId`) on a PSS-signed
//!   certificate before verification is even reached. See
//!   `chain.zig`'s `verifyPssLink` for the isolated gap-filler.
//! - **A closed algorithm table.** `AlgorithmCategory`/`Algorithm` are
//!   exhaustive enums with `StaticStringMap` OID tables, so an algorithm std
//!   does not carry cannot be added from outside — the failure is
//!   `error.CertificateHasUnrecognizedObjectId` at `Certificate.parse`, i.e.
//!   before anything is verified. ML-DSA (RFC 9881, 2025-10) is the current
//!   instance: std has the *primitives* (`std.crypto.sign.mldsa`, measured
//!   faster than OpenSSL 3.5 on every operation) but no X.509 name for them.
//!   `algorithm.zig` is this module's own table for exactly that reason; it
//!   consults std's first and passes std's answers through unchanged, so no
//!   certificate resolves differently than it did before.
//! - **Multi-certificate path building / RFC 5280 §6 policy: NOT provided.**
//!   `Certificate.Bundle` stores a flat set of trust anchors keyed by
//!   subject DN and its `verify` finds exactly ONE issuer candidate
//!   (`Bundle.find`, a hashmap lookup — no handling of multiple
//!   same-subject-DN candidates, no backtracking) then calls the same
//!   single-link `Parsed.verify`. `Certificate.Chain` (Windows-only; aliased
//!   to `void` elsewhere) delegates the ENTIRE path-building + policy
//!   decision to the Windows CryptoAPI (`CertGetCertificateChain`) — it is
//!   not a portable implementation to study or extract logic from, just an
//!   OS-API shim. There is no cross-platform §6 implementation anywhere in
//!   std to build on for the actual path-building/policy decision.
//!
//! **Verdict:** the real gap is path-building + RFC 5280 §6 POLICY on top of
//! std's already-correct single-link parse/verify — not re-parsing DER or
//! re-implementing signature crypto (both reused directly, except the
//! narrow RSA-PSS and ML-DSA carve-outs above, neither of which adds a
//! parser or an algorithm: only a lookup std has no seam for). This module
//! is built ON
//! `std.crypto.Certificate`, not instead of it.
//!
//! ## What this module provides
//!
//! - `extensions` — REAL, tested DER parsing for the extension fields std
//!   omits: `parseBasicConstraints`, `parseKeyUsage`, `parseExtKeyUsage`/
//!   `hasPurpose`, `parseSubjectKeyIdentifier`, `parseAuthorityKeyIdentifier`,
//!   `parseNameConstraints`/`subtreeIterator`, plus `findExtensions`/`iterate`
//!   to locate and walk a certificate's extension block at all (std doesn't
//!   expose this either). No policy decisions here — pure TLV → typed value.
//! - `chain` — the public `verifyChain(gpa, chain, trust_anchors, opts)`
//!   API surface (`Options`, `VerifiedChain`, typed `VerifyChainError`) plus
//!   five named RFC 5280 §6 sub-algorithms, all implemented: `buildPath`,
//!   `checkNameConstraints`, `checkPathLength`, `checkExtendedKeyUsage`,
//!   `verifyPssLink`. See each one's doc comment in `chain.zig` for exactly
//!   what it does and which RFC clause it covers.
//!
//! Every raw DER walk in `extensions.zig`/`chain.zig` goes through
//! `extensions.parseElement`, a bounds-safe wrapper around
//! `std.crypto.Certificate.der.Element.parse`: the std primitive computes a
//! TLV's content-slice purely from the encoded length field without ever
//! validating it against the buffer length, so a malformed length (a
//! corrupt or hostile certificate extension) can otherwise turn a later
//! direct slice index into an uncontrolled process abort rather than a
//! catchable error. `parseElement` pre- and post-validates every offset
//! instead, so malformed input always yields
//! `error.CertificateFieldHasInvalidLength`, never a panic.
//!
//! **Out of scope, by design, not silently skipped:** CRL/OCSP revocation
//! checking (RFC 5280 §6.3 — a separate online/offline data-fetching
//! concern) and certificate policy processing (§6.1.5's explicit-policy /
//! policy-mapping state machine — most TLS/mTLS/OPC-UA deployments don't
//! rely on policy OIDs). A consumer needing either must add it explicitly.
//! `rfc822Name`/`uniformResourceIdentifier`/other `GeneralName` types are
//! recognized by `checkNameConstraints` but have no matching rule
//! implemented (only `dNSName`, `directoryName`, `iPAddress` per RFC 5280
//! §4.2.1.10) — a constraint of one of those types is parsed but never
//! matched, which is a fail-*open* gap for that specific name type;
//! flagged here and in `SPEC.md`.
//!
//! Provenance: clean-room from RFC 5280 (X.509 v3 / PKIX Certificate and CRL
//! Profile) — a public IETF specification, not a copyrightable work (see
//! `CONVENTIONS.md` §5 / `NOTICE` policy). Built directly on
//! `std.crypto.Certificate` (MIT, part of Zig std) for DER primitives and
//! single-link parse/verify, and this repo's own `rsa` module (RFC 8017) for
//! the RSASSA-PSS gap. RFC 4055 (RSASSA-PSS in X.509) and RFC 6125 (hostname
//! matching — reused via std's `verifyHostName`, not reimplemented) are
//! referenced but not re-derived from source.

const std = @import("std");

pub const extensions = @import("extensions.zig");

/// This module's own AlgorithmIdentifier OID table — the one thing that could
/// not be borrowed from `std.crypto.Certificate`, whose table is a closed
/// enum. Public because `VerifiedChain.leaf_pub_key_algo` is one of its
/// types: a caller has to be able to name what was verified.
pub const algorithm = @import("algorithm.zig");
pub const chain = @import("chain.zig");

/// Certificate-DER safety guard: a recursive-descent DER well-formedness
/// validator (`safe.validate` / `safe.validateCertificate`) plus
/// `safe.safeCertificate`, which returns a validated, zero-padded
/// `std.crypto.Certificate` that is safe to hand to `std.crypto.Certificate.parse`
/// without risk of the panic / out-of-bounds read std's unchecked DER reader
/// exhibits on a malformed, attacker-supplied certificate. This is the shared
/// home for the guard the `iec62351` and `opcua` modules route through — see
/// `safe.zig`'s doc comment and `SPEC.md`.
pub const safe = @import("safe.zig");

/// Re-exported at the top level for ergonomic `x509.verifyChain(...)` — the
/// module's single most important entry point once implemented.
pub const verifyChain = chain.verifyChain;
pub const Options = chain.Options;
pub const VerifiedChain = chain.VerifiedChain;
pub const VerifyChainError = chain.VerifyChainError;
pub const PubKeyAlgo = algorithm.PubKeyAlgo;
pub const MlDsa = algorithm.MlDsa;
/// Single-link verification for the two algorithms std cannot parse, for
/// consumers holding a certificate and its issuer without a path to build.
pub const verifyPssLink = chain.verifyPssLink;
pub const verifyMlDsaLink = chain.verifyMlDsaLink;

/// `x509.spkiOf(cert_der)` — the supported way to name a certificate's public
/// key without verifying anything about the certificate: it returns the
/// `SubjectPublicKeyInfo` TLV (plus its decomposed algorithm OID, parameters
/// and key bits) from untrusted DER, over the defensive walk in `safe.zig`
/// and **never** through `std.crypto.Certificate.parse`. Every returned slice
/// borrows the caller's buffer — see `safe.Spki`'s doc comment for the full
/// lifetime contract, and `safe.spkiOf`'s for what it does and does not prove.
pub const spkiOf = safe.spkiOf;
pub const Spki = safe.Spki;
pub const SpkiError = safe.SpkiError;

pub const meta = .{
    .targets = .{.linux64},
    .platform = .any,
    .role = .util, // pure verification logic; no I/O, no wire framing of its own
    .concurrency = .reentrant, // no shared/global state; every function is a pure value-in/value-out check
    .model_after = "RFC 5280 (X.509 v3 / PKIX) + RFC 9881 (ML-DSA in X.509); built on std.crypto.Certificate (MIT) for DER + single-link verify",
    .deps = .{"rsa"}, // rsa.PublicKey / rsa.verifyPss for the RSASSA-PSS gap (see chain.zig's verifyPssLink)
};

// ── dark-tests aggregator (CONVENTIONS.md §6 step 3) ────────────────────────
//
// A bare `pub const x = @import("x.zig")` re-export does NOT pull `x`'s
// tests into the test binary on its own — every submodule must be named
// here too.
test {
    _ = extensions;
    _ = algorithm;
    _ = chain;
    _ = safe;
}
