// SPDX-License-Identifier: MIT

// Differential oracle for modules/http: Go's standard library (net/http,
// mime/multipart, net/url) as an independent implementation. Each case's
// input bytes are OURS (the tables in this directory); Go only answers them.
// The answers are written out as a Zig file that the module's own tests
// replay hermetically -- no Go at test time.
//
//	cd modules/http/tools/go_oracle && go run . -out ../../src/go_oracle_vectors.zig
//
// Stdlib only, no network. The h1 area runs a real net/http.Server on a
// loopback port (the only way to ask Go's server, not just its parser).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"runtime"
	"strings"
)

func main() {
	out := flag.String("out", "", "write the Zig vectors file here (default stdout)")
	flag.Parse()

	var b bytes.Buffer
	fmt.Fprintf(&b, "// SPDX-License-Identifier: MIT\n")
	fmt.Fprintf(&b, "// GENERATED by modules/http/tools/go_oracle (%s) -- do not hand-edit.\n", runtime.Version())
	fmt.Fprintf(&b, "//! Go standard-library verdicts on this module's own case tables, replayed\n")
	fmt.Fprintf(&b, "//! by `go_oracle.zig`. Regenerate with the command in tools/go_oracle/main.go.\n\n")
	fmt.Fprintf(&b, "pub const go_version = %s;\n\n", zigStr(runtime.Version()))

	emitH1(&b)
	emitServe(&b)
	emitURL(&b)
	emitMultipart(&b)
	emitClient(&b)
	// Every area ends its table with a blank line; the file ends with one newline.
	b.Truncate(b.Len() - 1)

	if *out == "" {
		os.Stdout.Write(b.Bytes())
		return
	}
	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

// zigStr renders s as a Zig string literal: printable ASCII as is, \r \n \t
// by name, everything else as \xHH. Byte-exact, so a case can carry any byte.
func zigStr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString(`\"`)
		case c == '\\':
			b.WriteString(`\\`)
		case c == '\r':
			b.WriteString(`\r`)
		case c == '\n':
			b.WriteString(`\n`)
		case c == '\t':
			b.WriteString(`\t`)
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, `\x%02x`, c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// zigList renders items as an anonymous-list literal the way `zig fmt` does:
// `&.{}`, `&.{x}` for one item, `&.{ x, y }` for more.
func zigList(items []string) string {
	switch len(items) {
	case 0:
		return "&.{}"
	case 1:
		return "&.{" + items[0] + "}"
	}
	return "&.{ " + strings.Join(items, ", ") + " }"
}

func zigOptStr(s *string) string {
	if s == nil {
		return "null"
	}
	return zigStr(*s)
}
