// SPDX-License-Identifier: MIT
//! Generated vector list over a LICENSE-FILTERED SLICE of the W3C XML
//! Conformance Test Suite (xmlconf, see ../NOTICE for the full provenance and
//! license accounting, and ../../NOTICE for the root-level attribution index).
//! The xmltest sub-suite (James Clark) is excluded entirely: its own license
//! permits redistribution only as the unmodified xmltest.zip, not as this kind
//! of extracted subset -- see NOTICE. One entry per vendored fixture file; DO
//! NOT hand-edit the `content` field -- regenerate from testdata/xmlconf/ if
//! the corpus is ever re-vendored.
//!
//! Two directions, matching xmlconf.xml TYPE:
//!  - `reject_vectors` (xmlconf TYPE="not-wf"): must be rejected by `parse`
//!    under DEFAULT Options (doctype=.reject). Every case here is DOCTYPE-free
//!    in its own source -- see xmlconf_test.zig / NOTICE for why DOCTYPE-bearing
//!    not-wf cases are excluded (DoctypeForbidden would fire first regardless of
//!    the labeled defect, proving nothing).
//!  - `accept_vectors` (xmlconf TYPE="valid", i.e. well-formed): must parse
//!    successfully. `needs_doctype_ignore` is true for all of them -- xmlconf's
//!    "valid" category is DTD-validity by definition, so every case carries a
//!    DOCTYPE; they are vendored anyway (with Options{.doctype = .ignore}) because
//!    each one's internal subset is a no-op for well-formedness (ENTITIES="none",
//!    no external subset) and this exercises the real doctype=.ignore skip path
//!    against real-world DTD shapes, not just hand-written ones.

pub const RejectVector = struct {
    id: []const u8,
    suite: []const u8,
    sections: []const u8,
    desc: []const u8,
    content: []const u8,
};

pub const AcceptVector = struct {
    id: []const u8,
    suite: []const u8,
    sections: []const u8,
    desc: []const u8,
    needs_doctype_ignore: bool,
    content: []const u8,
};

pub const reject_vectors = [_]RejectVector{
    .{
        .id = "element00",
        .suite = "sun-not-wf",
        .sections = "3.1 [42]",
        .desc = "EOF in middle of incomplete ETAG",
        .content = @embedFile("testdata/xmlconf/sun-not-wf/not-wf/element00.xml"),
    },
    .{
        .id = "element01",
        .suite = "sun-not-wf",
        .sections = "3.1 [42]",
        .desc = "EOF in middle of incomplete ETAG",
        .content = @embedFile("testdata/xmlconf/sun-not-wf/not-wf/element01.xml"),
    },
    .{
        .id = "encoding01",
        .suite = "sun-not-wf",
        .sections = "4.3.3 [81]",
        .desc = "Illegal character \" \" in encoding name",
        .content = @embedFile("testdata/xmlconf/sun-not-wf/not-wf/encoding01.xml"),
    },
    .{
        .id = "encoding02",
        .suite = "sun-not-wf",
        .sections = "4.3.3 [81]",
        .desc = "Illegal character \"/\" in encoding name",
        .content = @embedFile("testdata/xmlconf/sun-not-wf/not-wf/encoding02.xml"),
    },
    .{
        .id = "encoding03",
        .suite = "sun-not-wf",
        .sections = "4.3.3 [81]",
        .desc = "Illegal character reference in encoding name",
        .content = @embedFile("testdata/xmlconf/sun-not-wf/not-wf/encoding03.xml"),
    },
    .{
        .id = "encoding04",
        .suite = "sun-not-wf",
        .sections = "4.3.3 [81]",
        .desc = "Illegal character \":\" in encoding name",
        .content = @embedFile("testdata/xmlconf/sun-not-wf/not-wf/encoding04.xml"),
    },
    .{
        .id = "encoding05",
        .suite = "sun-not-wf",
        .sections = "4.3.3 [81]",
        .desc = "Illegal character \"@\" in encoding name",
        .content = @embedFile("testdata/xmlconf/sun-not-wf/not-wf/encoding05.xml"),
    },
    .{
        .id = "encoding06",
        .suite = "sun-not-wf",
        .sections = "4.3.3 [81]",
        .desc = "Illegal character \"+\" in encoding name",
        .content = @embedFile("testdata/xmlconf/sun-not-wf/not-wf/encoding06.xml"),
    },
    .{
        .id = "ibm-not-wf-P28-ibm28n05.xml",
        .suite = "ibm-not-wf",
        .sections = "2.8",
        .desc = "Tests doctypedecl with wrong key word. A wrong key word \"DOCtYPE\" occurs on line 2.",
        .content = @embedFile("testdata/xmlconf/ibm-not-wf/not-wf/P28/ibm28n05.xml"),
    },
    .{
        .id = "ibm-not-wf-P28-ibm28n08.xml",
        .suite = "ibm-not-wf",
        .sections = "2.8",
        .desc = "Tests doctypedecl with wrong opening sequence. The opening sequence \"(less than)?DOCTYPE\" occurs in the DTD.",
        .content = @embedFile("testdata/xmlconf/ibm-not-wf/not-wf/P28/ibm28n08.xml"),
    },
    .{
        .id = "rmt-ns10-013",
        .suite = "eduni-ns10",
        .sections = "3",
        .desc = "Bad QName syntax: multiple colons",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/013.xml"),
    },
    .{
        .id = "rmt-ns10-014",
        .suite = "eduni-ns10",
        .sections = "3",
        .desc = "Bad QName syntax: colon at end",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/014.xml"),
    },
    .{
        .id = "rmt-ns10-015",
        .suite = "eduni-ns10",
        .sections = "3",
        .desc = "Bad QName syntax: colon at start",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/015.xml"),
    },
    .{
        .id = "rmt-ns10-016",
        .suite = "eduni-ns10",
        .sections = "2",
        .desc = "Bad QName syntax: xmlns:",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/016.xml"),
    },
    .{
        .id = "rmt-ns10-023",
        .suite = "eduni-ns10",
        .sections = "2",
        .desc = "Illegal use of 1.1-style prefix unbinding in 1.0 document",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/023.xml"),
    },
    .{
        .id = "rmt-ns10-025",
        .suite = "eduni-ns10",
        .sections = "4",
        .desc = "Unbound element prefix",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/025.xml"),
    },
    .{
        .id = "rmt-ns10-026",
        .suite = "eduni-ns10",
        .sections = "4",
        .desc = "Unbound attribute prefix",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/026.xml"),
    },
    .{
        .id = "rmt-ns10-029",
        .suite = "eduni-ns10",
        .sections = "NE05",
        .desc = "Reserved prefixes and namespaces: declaring the xml prefix incorrectly",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/029.xml"),
    },
    .{
        .id = "rmt-ns10-030",
        .suite = "eduni-ns10",
        .sections = "NE05",
        .desc = "Reserved prefixes and namespaces: binding another prefix to the xml namespace",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/030.xml"),
    },
    .{
        .id = "rmt-ns10-031",
        .suite = "eduni-ns10",
        .sections = "NE05",
        .desc = "Reserved prefixes and namespaces: declaring the xmlns prefix with its correct URI (illegal)",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/031.xml"),
    },
    .{
        .id = "rmt-ns10-032",
        .suite = "eduni-ns10",
        .sections = "NE05",
        .desc = "Reserved prefixes and namespaces: declaring the xmlns prefix with an incorrect URI",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/032.xml"),
    },
    .{
        .id = "rmt-ns10-033",
        .suite = "eduni-ns10",
        .sections = "NE05",
        .desc = "Reserved prefixes and namespaces: binding another prefix to the xmlns namespace",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/033.xml"),
    },
    .{
        .id = "rmt-ns10-035",
        .suite = "eduni-ns10",
        .sections = "5.3",
        .desc = "Attribute uniqueness: repeated identical attribute",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/035.xml"),
    },
    .{
        .id = "rmt-ns10-036",
        .suite = "eduni-ns10",
        .sections = "5.3",
        .desc = "Attribute uniqueness: repeated attribute with different prefixes",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/036.xml"),
    },
    .{
        .id = "rmt-ns10-042",
        .suite = "eduni-ns10",
        .sections = "NE08",
        .desc = "Colon in PI name",
        .content = @embedFile("testdata/xmlconf/eduni-ns10/042.xml"),
    },
};

pub const accept_vectors = [_]AcceptVector{
    .{
        .id = "dtd00",
        .suite = "sun-valid",
        .sections = "3.2.2 [51]",
        .desc = "Tests parsing of alternative forms of text-only mixed content declaration.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/dtd00.xml"),
    },
    .{
        .id = "dtd01",
        .suite = "sun-valid",
        .sections = "2.5 [15]",
        .desc = "Comments don't get parameter entity expansion",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/dtd01.xml"),
    },
    .{
        .id = "element",
        .suite = "sun-valid",
        .sections = "3",
        .desc = "Tests clauses 1, 3, and 4 of the Element Valid validity constraint.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/element.xml"),
    },
    .{
        .id = "required00",
        .suite = "sun-valid",
        .sections = "3.3.2 [60]",
        .desc = "Tests the #REQUIRED attribute declaration syntax, and the associated validity constraint.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/required00.xml"),
    },
    .{
        .id = "sa01",
        .suite = "sun-valid",
        .sections = "2.9 [32]",
        .desc = "A document may be marked 'standalone' if any optional whitespace is defined within the internal DTD subset.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/sa01.xml"),
    },
    .{
        .id = "v-sgml01",
        .suite = "sun-valid",
        .sections = "3.3.1 [59]",
        .desc = "XML permits token reuse, while SGML does not.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/sgml01.xml"),
    },
    .{
        .id = "v-lang01",
        .suite = "sun-valid",
        .sections = "2.12 [35]",
        .desc = "Tests a lowercase ISO language code.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/v-lang01.xml"),
    },
    .{
        .id = "v-lang02",
        .suite = "sun-valid",
        .sections = "2.12 [35]",
        .desc = "Tests a ISO language code with a subcode.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/v-lang02.xml"),
    },
    .{
        .id = "v-lang03",
        .suite = "sun-valid",
        .sections = "2.12 [36]",
        .desc = "Tests a IANA language code with a subcode.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/v-lang03.xml"),
    },
    .{
        .id = "v-lang04",
        .suite = "sun-valid",
        .sections = "2.12 [37]",
        .desc = "Tests a user language code with a subcode.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/v-lang04.xml"),
    },
    .{
        .id = "v-lang05",
        .suite = "sun-valid",
        .sections = "2.12 [35]",
        .desc = "Tests an uppercase ISO language code.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/v-lang05.xml"),
    },
    .{
        .id = "v-lang06",
        .suite = "sun-valid",
        .sections = "2.12 [37]",
        .desc = "Tests a user language code.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/sun-valid/valid/v-lang06.xml"),
    },
    .{
        .id = "ibm-valid-P01-ibm01v01.xml",
        .suite = "ibm-valid",
        .sections = "2.1",
        .desc = "Tests with a xml document consisting of <EM>prolog</EM> followed by <EM>element</EM> then <EM>Misc</EM>",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P01/ibm01v01.xml"),
    },
    .{
        .id = "ibm-valid-P02-ibm02v01.xml",
        .suite = "ibm-valid",
        .sections = "2.2",
        .desc = "This test case covers legal character ranges plus discrete legal characters for production 02.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P02/ibm02v01.xml"),
    },
    .{
        .id = "ibm-valid-P03-ibm03v01.xml",
        .suite = "ibm-valid",
        .sections = "2.3",
        .desc = "Tests all 4 legal white space characters - #x20 #x9 #xD #xA",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P03/ibm03v01.xml"),
    },
    .{
        .id = "ibm-valid-P14-ibm14v01.xml",
        .suite = "ibm-valid",
        .sections = "2.4",
        .desc = "Testing CharData with empty string",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P14/ibm14v01.xml"),
    },
    .{
        .id = "ibm-valid-P14-ibm14v02.xml",
        .suite = "ibm-valid",
        .sections = "2.4",
        .desc = "Testing CharData with white space character",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P14/ibm14v02.xml"),
    },
    .{
        .id = "ibm-valid-P14-ibm14v03.xml",
        .suite = "ibm-valid",
        .sections = "2.4",
        .desc = "Testing CharData with a general text string",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P14/ibm14v03.xml"),
    },
    .{
        .id = "ibm-valid-P15-ibm15v01.xml",
        .suite = "ibm-valid",
        .sections = "2.5",
        .desc = "Tests empty comment",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P15/ibm15v01.xml"),
    },
    .{
        .id = "ibm-valid-P15-ibm15v02.xml",
        .suite = "ibm-valid",
        .sections = "2.5",
        .desc = "Tests comment with regular text",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P15/ibm15v02.xml"),
    },
    .{
        .id = "ibm-valid-P15-ibm15v03.xml",
        .suite = "ibm-valid",
        .sections = "2.5",
        .desc = "Tests comment with one dash inside",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P15/ibm15v03.xml"),
    },
    .{
        .id = "ibm-valid-P15-ibm15v04.xml",
        .suite = "ibm-valid",
        .sections = "2.5",
        .desc = "Tests comment with more comprehensive content",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P15/ibm15v04.xml"),
    },
    .{
        .id = "ibm-valid-P16-ibm16v01.xml",
        .suite = "ibm-valid",
        .sections = "2.6",
        .desc = "Tests PI definition with only PItarget name and nothing else",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P16/ibm16v01.xml"),
    },
    .{
        .id = "ibm-valid-P16-ibm16v02.xml",
        .suite = "ibm-valid",
        .sections = "2.6",
        .desc = "Tests PI definition with only PItarget name and a white space",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P16/ibm16v02.xml"),
    },
    .{
        .id = "ibm-valid-P16-ibm16v03.xml",
        .suite = "ibm-valid",
        .sections = "2.6",
        .desc = "Tests PI definition with PItarget name and text that contains question mark and right angle",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P16/ibm16v03.xml"),
    },
    .{
        .id = "ibm-valid-P17-ibm17v01.xml",
        .suite = "ibm-valid",
        .sections = "2.6",
        .desc = "Tests PITarget name",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P17/ibm17v01.xml"),
    },
    .{
        .id = "ibm-valid-P18-ibm18v01.xml",
        .suite = "ibm-valid",
        .sections = "2.7",
        .desc = "Tests CDSect with CDStart CData CDEnd",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P18/ibm18v01.xml"),
    },
    .{
        .id = "ibm-valid-P19-ibm19v01.xml",
        .suite = "ibm-valid",
        .sections = "2.7",
        .desc = "Tests CDStart",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P19/ibm19v01.xml"),
    },
    .{
        .id = "ibm-valid-P20-ibm20v01.xml",
        .suite = "ibm-valid",
        .sections = "2.7",
        .desc = "Tests CDATA with empty string",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P20/ibm20v01.xml"),
    },
    .{
        .id = "ibm-valid-P20-ibm20v02.xml",
        .suite = "ibm-valid",
        .sections = "2.7",
        .desc = "Tests CDATA with regular content",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P20/ibm20v02.xml"),
    },
    .{
        .id = "ibm-valid-P21-ibm21v01.xml",
        .suite = "ibm-valid",
        .sections = "2.7",
        .desc = "Tests CDEnd",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P21/ibm21v01.xml"),
    },
    .{
        .id = "ibm-valid-P22-ibm22v01.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests prolog with XMLDecl and doctypedecl",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P22/ibm22v01.xml"),
    },
    .{
        .id = "ibm-valid-P22-ibm22v02.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests prolog with doctypedecl",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P22/ibm22v02.xml"),
    },
    .{
        .id = "ibm-valid-P22-ibm22v03.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests prolog with Misc doctypedecl",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P22/ibm22v03.xml"),
    },
    .{
        .id = "ibm-valid-P22-ibm22v04.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests prolog with doctypedecl Misc",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P22/ibm22v04.xml"),
    },
    .{
        .id = "ibm-valid-P22-ibm22v05.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests prolog with XMLDecl Misc doctypedecl",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P22/ibm22v05.xml"),
    },
    .{
        .id = "ibm-valid-P22-ibm22v06.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests prolog with XMLDecl doctypedecl Misc",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P22/ibm22v06.xml"),
    },
    .{
        .id = "ibm-valid-P22-ibm22v07.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests prolog with XMLDecl Misc doctypedecl Misc",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P22/ibm22v07.xml"),
    },
    .{
        .id = "ibm-valid-P23-ibm23v01.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests XMLDecl with VersionInfo only",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P23/ibm23v01.xml"),
    },
    .{
        .id = "ibm-valid-P23-ibm23v02.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests XMLDecl with VersionInfo EncodingDecl",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P23/ibm23v02.xml"),
    },
    .{
        .id = "ibm-valid-P23-ibm23v03.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests XMLDecl with VersionInfo SDDecl",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P23/ibm23v03.xml"),
    },
    .{
        .id = "ibm-valid-P23-ibm23v04.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests XMLDecl with VerstionInfo and a trailing whitespace char",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P23/ibm23v04.xml"),
    },
    .{
        .id = "ibm-valid-P23-ibm23v05.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests XMLDecl with VersionInfo EncodingDecl SDDecl",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P23/ibm23v05.xml"),
    },
    .{
        .id = "ibm-valid-P23-ibm23v06.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests XMLDecl with VersionInfo EncodingDecl SDDecl and a trailing whitespace",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P23/ibm23v06.xml"),
    },
    .{
        .id = "ibm-valid-P24-ibm24v01.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests VersionInfo with single quote",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P24/ibm24v01.xml"),
    },
    .{
        .id = "ibm-valid-P24-ibm24v02.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests VersionInfo with double quote",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P24/ibm24v02.xml"),
    },
    .{
        .id = "ibm-valid-P25-ibm25v01.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests EQ with =",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P25/ibm25v01.xml"),
    },
    .{
        .id = "ibm-valid-P25-ibm25v02.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests EQ with = and spaces on both sides",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P25/ibm25v02.xml"),
    },
    .{
        .id = "ibm-valid-P25-ibm25v03.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests EQ with = and space in front of it",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P25/ibm25v03.xml"),
    },
    .{
        .id = "ibm-valid-P25-ibm25v04.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests EQ with = and space after it",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P25/ibm25v04.xml"),
    },
    .{
        .id = "ibm-valid-P26-ibm26v01.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests VersionNum 1.0",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P26/ibm26v01.xml"),
    },
    .{
        .id = "ibm-valid-P27-ibm27v01.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests Misc with comment",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P27/ibm27v01.xml"),
    },
    .{
        .id = "ibm-valid-P27-ibm27v02.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests Misc with PI",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P27/ibm27v02.xml"),
    },
    .{
        .id = "ibm-valid-P27-ibm27v03.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests Misc with white spaces",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P27/ibm27v03.xml"),
    },
    .{
        .id = "ibm-valid-P28-ibm28v01.xml",
        .suite = "ibm-valid",
        .sections = "2.8",
        .desc = "Tests doctypedecl with internal DTD only",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P28/ibm28v01.xml"),
    },
    .{
        .id = "ibm-valid-P33-ibm33v01.xml",
        .suite = "ibm-valid",
        .sections = "2.12",
        .desc = "Tests LanguageID with Langcode - Subcode",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P33/ibm33v01.xml"),
    },
    .{
        .id = "ibm-valid-P34-ibm34v01.xml",
        .suite = "ibm-valid",
        .sections = "2.12",
        .desc = "Duplicate Test as ibm33v01.xml",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P34/ibm34v01.xml"),
    },
    .{
        .id = "ibm-valid-P35-ibm35v01.xml",
        .suite = "ibm-valid",
        .sections = "2.12",
        .desc = "Tests ISO639Code",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P35/ibm35v01.xml"),
    },
    .{
        .id = "ibm-valid-P36-ibm36v01.xml",
        .suite = "ibm-valid",
        .sections = "2.12",
        .desc = "Tests IanaCode",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P36/ibm36v01.xml"),
    },
    .{
        .id = "ibm-valid-P37-ibm37v01.xml",
        .suite = "ibm-valid",
        .sections = "2.12",
        .desc = "Tests UserCode",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P37/ibm37v01.xml"),
    },
    .{
        .id = "ibm-valid-P38-ibm38v01.xml",
        .suite = "ibm-valid",
        .sections = "2.12",
        .desc = "Tests SubCode",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P38/ibm38v01.xml"),
    },
    .{
        .id = "ibm-valid-P39-ibm39v01.xml",
        .suite = "ibm-valid",
        .sections = "3",
        .desc = "Tests element with EmptyElemTag and STag content Etag, also tests the VC: Element Valid with elements that have children, Mixed and ANY contents",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P39/ibm39v01.xml"),
    },
    .{
        .id = "ibm-valid-P40-ibm40v01.xml",
        .suite = "ibm-valid",
        .sections = "3.1",
        .desc = "Tests STag with possible combinations of its fields, also tests WFC: Unique Att Spec.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P40/ibm40v01.xml"),
    },
    .{
        .id = "ibm-valid-P41-ibm41v01.xml",
        .suite = "ibm-valid",
        .sections = "3.1",
        .desc = "Tests Attribute with Name Eq AttValue and VC: Attribute Value Type",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P41/ibm41v01.xml"),
    },
    .{
        .id = "ibm-valid-P42-ibm42v01.xml",
        .suite = "ibm-valid",
        .sections = "3.1",
        .desc = "Tests ETag with possible combinations of its fields",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P42/ibm42v01.xml"),
    },
    .{
        .id = "ibm-valid-P44-ibm44v01.xml",
        .suite = "ibm-valid",
        .sections = "3.1",
        .desc = "Tests EmptyElemTag with possible combinations of its fields",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P44/ibm44v01.xml"),
    },
    .{
        .id = "ibm-valid-P45-ibm45v01.xml",
        .suite = "ibm-valid",
        .sections = "3.2",
        .desc = "Tests both P45 elementDecl and P46 contentspec with possible combinations of their constructs",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P45/ibm45v01.xml"),
    },
    .{
        .id = "ibm-valid-P47-ibm47v01.xml",
        .suite = "ibm-valid",
        .sections = "3.2.1",
        .desc = "Tests all possible children,cp,choice,seq patterns in P47,P48,P49,P50",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P47/ibm47v01.xml"),
    },
    .{
        .id = "ibm-valid-P51-ibm51v01.xml",
        .suite = "ibm-valid",
        .sections = "3.2.2",
        .desc = "Tests Mixed with possible combinations of its fields amd VC: No Duplicate Types",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P51/ibm51v01.xml"),
    },
    .{
        .id = "ibm-valid-P52-ibm52v01.xml",
        .suite = "ibm-valid",
        .sections = "3.3",
        .desc = "Tests all AttlistDecl and AttDef Patterns in P52 and P53",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P52/ibm52v01.xml"),
    },
    .{
        .id = "ibm-valid-P54-ibm54v02.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests all AttTypes : StringType, TokenizedType, EnumeratedTypes in P55,P56,P57.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P54/ibm54v02.xml"),
    },
    .{
        .id = "ibm-valid-P54-ibm54v03.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests AttTypes with StringType in P55.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P54/ibm54v03.xml"),
    },
    .{
        .id = "ibm-valid-P55-ibm55v01.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests StringType for P55. The \"CDATA\" occurs in the StringType for the attribute \"att\" for the element \"a\".",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P55/ibm55v01.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v01.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56. The \"ID\", \"IDREF\", \"IDREFS\", \"ENTITY\", \"ENTITIES\", \"NMTOKEN\", and \"NMTOKENS\" occur in the TokenizedType for the attribute \"attr\".",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v01.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v02.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56 VC: ID Attribute Default. The value \"AC1999\" is assigned to the ID attribute \"attr\" with \"#REQUIRED\" in the DeaultDecl.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v02.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v03.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56 VC: ID Attribute Default. The value \"AC1999\" is assigned to the ID attribute \"attr\" with \"#IMPLIED\" in the DeaultDecl.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v03.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v04.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56 VC: ID. The ID attribute \"UniqueName\" appears only once in the document.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v04.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v05.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56 VC: One ID per element type. The element \"a\" or \"b\" has only one ID attribute.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v05.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v06.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56 VC: IDREF. The IDREF value \"AC456\" matches the value assigned to an ID attribute \"UniqueName\".",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v06.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v07.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56 VC: IDREF. The IDREFS value \"AC456 Q123\" matches the values assigned to the ID attribute \"UniqueName\" and \"Uname\".",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v07.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v09.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56 VC: Name Token. The value of the NMTOKEN attribute \"thistoken\" matches the Nmtoken production.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v09.xml"),
    },
    .{
        .id = "ibm-valid-P56-ibm56v10.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests TokenizedType for P56 VC: Name Token. The value of the NMTOKENS attribute \"thistoken\" matches the Nmtoken production.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P56/ibm56v10.xml"),
    },
    .{
        .id = "ibm-valid-P57-ibm57v01.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests EnumeratedType in the AttType. The attribute \"att\" has a type (a|b) with the element \"a\". the",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P57/ibm57v01.xml"),
    },
    .{
        .id = "ibm-valid-P58-ibm58v01.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests NotationType for P58. It shows different patterns fro the NOTATION attribute \"attr\".",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P58/ibm58v01.xml"),
    },
    .{
        .id = "ibm-valid-P58-ibm58v02.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests NotationType for P58: Notation Attributes. The value \"base64\" of the NOTATION attribute \"attr\" matches one of the notation names declared.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P58/ibm58v02.xml"),
    },
    .{
        .id = "ibm-valid-P59-ibm59v01.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests Enumeration in the EnumeratedType for P59. It shows different patterns for the Enumeration attribute \"attr\".",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P59/ibm59v01.xml"),
    },
    .{
        .id = "ibm-valid-P59-ibm59v02.xml",
        .suite = "ibm-valid",
        .sections = "3.3.1",
        .desc = "Tests Enumeration for P59 VC: Enumeration. The value \"one\" of the Enumeration attribute \"attr\" matches one of the element names declared.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P59/ibm59v02.xml"),
    },
    .{
        .id = "ibm-valid-P60-ibm60v01.xml",
        .suite = "ibm-valid",
        .sections = "3.3.2",
        .desc = "Tests DefaultDecl for P60. It shows different options \"#REQUIRED\", \"#FIXED\", \"#IMPLIED\", and default for the attribute \"chapter\".",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P60/ibm60v01.xml"),
    },
    .{
        .id = "ibm-valid-P60-ibm60v02.xml",
        .suite = "ibm-valid",
        .sections = "3.3.2",
        .desc = "Tests DefaultDecl for P60 VC: Required Attribute. In the element \"one\" and \"two\" the value of the #REQUIRED attribute \"chapter\" is given.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P60/ibm60v02.xml"),
    },
    .{
        .id = "ibm-valid-P60-ibm60v03.xml",
        .suite = "ibm-valid",
        .sections = "3.3.2",
        .desc = "Tests DefaultDecl for P60 VC: Fixed Attribute Default. The value of the #FIXED attribute \"chapter\" is exactly the same as the default value.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P60/ibm60v03.xml"),
    },
    .{
        .id = "ibm-valid-P60-ibm60v04.xml",
        .suite = "ibm-valid",
        .sections = "3.3.2",
        .desc = "Tests DefaultDecl for P60 VC: Attribute Default Legal. The default value specified for the attribute \"attr\" meets the lexical constraints of the declared attribute type.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P60/ibm60v04.xml"),
    },
    .{
        .id = "ibm-valid-P66-ibm66v01.xml",
        .suite = "ibm-valid",
        .sections = "4.1",
        .desc = "Tests all legal CharRef's.",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P66/ibm66v01.xml"),
    },
    .{
        .id = "ibm-valid-P68-ibm68v02.xml",
        .suite = "ibm-valid",
        .sections = "4.1",
        .desc = "Tests P68 VC:Entity Declared with Entities in External Parameter Entities , standalone is no",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P68/ibm68v02.xml"),
    },
    .{
        .id = "ibm-valid-P69-ibm69v02.xml",
        .suite = "ibm-valid",
        .sections = "4.1",
        .desc = "Tests P68 VC:Entity Declared with Parameter Entities in External Parameter Entities, standalone is no",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P69/ibm69v02.xml"),
    },
    .{
        .id = "ibm-valid-P79-ibm79v01.xml",
        .suite = "ibm-valid",
        .sections = "4.3.2",
        .desc = "Tests extPE",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P79/ibm79v01.xml"),
    },
    .{
        .id = "ibm-valid-P85-ibm85v01.xml",
        .suite = "ibm-valid",
        .sections = "B.",
        .desc = "This test case covers 149 legal character ranges plus 51 single legal characters for BaseChar in P85 using a PI target Name",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P85/ibm85v01.xml"),
    },
    .{
        .id = "ibm-valid-P86-ibm86v01.xml",
        .suite = "ibm-valid",
        .sections = "B.",
        .desc = "This test case covers 2 legal character ranges plus 1 single legal characters for IdeoGraphic in P86 using a PI target Name",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P86/ibm86v01.xml"),
    },
    .{
        .id = "ibm-valid-P87-ibm87v01.xml",
        .suite = "ibm-valid",
        .sections = "B.",
        .desc = "This test case covers 65 legal character ranges plus 30 single legal characters for CombiningChar in P87 using a PI target Name",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P87/ibm87v01.xml"),
    },
    .{
        .id = "ibm-valid-P88-ibm88v01.xml",
        .suite = "ibm-valid",
        .sections = "B.",
        .desc = "This test case covers 15 legal character ranges for Digit in P88 using a PI target Name",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P88/ibm88v01.xml"),
    },
    .{
        .id = "ibm-valid-P89-ibm89v01.xml",
        .suite = "ibm-valid",
        .sections = "B.",
        .desc = "This test case covers 3 legal character ranges plus 8 single legal characters for Extender in P89 using a PI target Name",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/ibm-valid/valid/P89/ibm89v01.xml"),
    },
    .{
        .id = "rmt-ns10-001",
        .suite = "eduni-ns10",
        .sections = "2",
        .desc = "Namespace name test: a perfectly good http URI",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/eduni-ns10/001.xml"),
    },
    .{
        .id = "rmt-ns10-002",
        .suite = "eduni-ns10",
        .sections = "2",
        .desc = "Namespace name test: a syntactically plausible URI with a fictitious scheme",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/eduni-ns10/002.xml"),
    },
    .{
        .id = "rmt-ns10-003",
        .suite = "eduni-ns10",
        .sections = "2",
        .desc = "Namespace name test: a perfectly good http URI with a fragment",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/eduni-ns10/003.xml"),
    },
    .{
        .id = "rmt-ns10-007",
        .suite = "eduni-ns10",
        .sections = "1",
        .desc = "Namespace inequality test: different capitalization",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/eduni-ns10/007.xml"),
    },
    .{
        .id = "rmt-ns10-008",
        .suite = "eduni-ns10",
        .sections = "1",
        .desc = "Namespace inequality test: different escaping",
        .needs_doctype_ignore = true,
        .content = @embedFile("testdata/xmlconf/eduni-ns10/008.xml"),
    },
};
