#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for `src/testdata/merge_vectors.zig`: PyYAML (MIT; 6.0.3, with
libyaml) driven as a BLACK-BOX oracle on YAML 1.1 merge keys
(yaml.org/type/merge.html) -- `yaml.load(doc, Loader=yaml.CSafeLoader)`
then `json.dumps`. Public API only; no source read.

Run:  python3 gen_merge_vectors.py > ../src/testdata/merge_vectors.zig

The documents use only strings, integers and mappings, where YAML 1.1 and
1.2 resolve alike. `json = null` means PyYAML refused the document; `ours`
names the error this module returns where it is deliberately stricter
(duplicate explicit keys, rejected by default -- SPEC.md section 8).
"""
import json, yaml

L = getattr(yaml, "CSafeLoader", yaml.SafeLoader)
cases = [
    ("merge one mapping", "b: &b {a: 1, b: 2}\nx: {<<: *b, c: 3}\n", None),
    ("explicit key after the merge wins", "b: &b {a: 1, b: 2}\nx: {<<: *b, a: 9}\n", None),
    ("explicit key before the merge wins", "b: &b {a: 1, b: 2}\nx: {a: 9, <<: *b}\n", None),
    ("sequence: the earlier mapping wins", "p: &p {a: 1}\nq: &q {a: 2, c: 3}\nx: {<<: [*p, *q]}\n", None),
    ("sequence and an explicit override", "p: &p {a: 1, b: 1}\nq: &q {b: 2, c: 2}\nx: {c: 9, <<: [*p, *q]}\n", None),
    ("block style, compose-file shape",
     "x-common: &common\n  restart: always\n  env:\n    A: \"1\"\nservices:\n  web:\n    <<: *common\n    image: nginx\n  db:\n    <<: *common\n    restart: \"no\"\n", None),
    ("a merged mapping that merged itself", "a: &a {k: 1}\nb: &b {<<: *a, m: 2}\nc: {<<: *b, n: 3}\n", None),
    ("inline mapping merged without an anchor", "x: {<<: {a: 1}, b: 2}\n", None),
    ("quoted << is an ordinary key", "x: {\"<<\": 1}\n", None),
    ("!!merge tag", "b: &b {a: 1}\nx: {!!merge <<: *b}\n", None),
    ("merge of a scalar is an error", "x: {<<: 1}\n", "InvalidMerge"),
    ("merge of a sequence holding a scalar is an error", "b: &b {a: 1}\nx: {<<: [*b, 2]}\n", "InvalidMerge"),
    ("duplicate explicit keys stay a duplicate", "b: &b {a: 1}\nx: {<<: *b, c: 1, c: 2}\n", "DuplicateKey"),
]

def zs(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

print("// SPDX-License-Identifier: MIT")
print("//! GENERATED by tools/gen_merge_vectors.py (PyYAML as a black-box oracle) -- do not edit.")
print("pub const Case = struct { name: []const u8, yaml: []const u8, json: ?[]const u8, ours: ?[]const u8 };")
print("pub const cases = [_]Case{")
for name, doc, ours in cases:
    try:
        j = zs(json.dumps(yaml.load(doc, Loader=L), sort_keys=True))
    except yaml.YAMLError:
        j = "null"
    o = "null" if ours is None else '"%s"' % ours
    print("    .{ .name = %s, .yaml = %s, .json = %s, .ours = %s }," % (zs(name), zs(doc), j, o))
print("};")
