// SPDX-License-Identifier: MIT
// Generated by gen_vectors.py from official public sources -- see doc comment below.
// Do not hand-edit hex payloads; regenerate instead.

//! Real, externally-sourced transaction fixtures for `tx_kat_test.zig`.
//!
//! `legacy_*`: the earliest known peer-to-peer Bitcoin transaction (mainnet
//! block 170, the "Satoshi -> Hal Finney" P2PK transaction), fetched live
//! from a block explorer (blockstream.info) by block height, keyed by that
//! explorer's own reported txid -- a value independently established by the
//! Bitcoin network, not derived from anything this module computes.
//!
//! `segwit_*`: BIP143's own published "Native P2WPKH" worked example (the
//! *signed* serialized transaction, bip-0143.mediawiki "Example" section)
//! -- an officially-published, canonical interop reference. `segwit_txid`/
//! `segwit_wtxid` were independently derived in Python (a from-scratch
//! double-SHA256 cross-check, separate from this module's own Zig hashing
//! path) directly over BIP143's published bytes.

pub const legacy_raw_tx_hex = "0100000001c997a5e56e104102fa209c6a852dd90660a20b2d9c352423edce25857fcd3704000000004847304402204e45e16932b8af514961a1d3a1a25fdf3f4f7732e9d624c6c61548ab5fb8cd410220181522ec8eca07de4860a4acdd12909d831cc56cbbac4622082221a8768d1d0901ffffffff0200ca9a3b00000000434104ae1a62fe09c5f51b13905f07f06b99a2f7159b2225f374cd378d71302fa28414e7aab37397f554a7df5f142c21c1b7303b8a0626f1baded5c72a704f7e6cd84cac00286bee0000000043410411db93e1dcdb8a016b49840f8c53bc1eb68a382e97b1482ecad7b148a6909a5cb2e0eaddfb84ccf9744464f82e160bfa9b8b64f9d4c03f999b8643f656b412a3ac00000000";

/// Internal (wire) byte order -- sha256d(legacy_raw_tx_hex bytes). Reverse
/// for the conventional display form ("f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16").
pub const legacy_txid_hex = "169e1e83e930853391bc6f35f605c6754cfead57cf8387639d3b4096c54f18f4";

pub const segwit_raw_tx_hex = "01000000000102fff7f7881a8099afa6940d42d1e7f6362bec38171ea3edf433541db4e4ad969f00000000494830450221008b9d1dc26ba6a9cb62127b02742fa9d754cd3bebf337f7a55d114c8e5cdd30be022040529b194ba3f9281a99f2b1c0a19c0489bc22ede944ccf4ecbab4cc618ef3ed01eeffffffef51e1b804cc89d182d279655c3aa89e815b1b309fe287d9b2b55d57b90ec68a0100000000ffffffff02202cb206000000001976a9148280b37df378db99f66f85c95a783a76ac7a6d5988ac9093510d000000001976a9143bde42dbee7e4dbe6a21b2d50ce2f0167faa815988ac000247304402203609e17b84f6a7d30c80bfa610b5b4542f32a8a0d5447a12fb1366d7f01cc44a0220573a954c4518331561406f90300e8f3358f51928d43c212a8caed02de67eebee0121025476c2e83188368da1ff3e292e7acafcdb3566bb0ad253f62fc70f07aeee635711000000";

/// Internal (wire) byte order.
pub const segwit_txid_hex = "09462d604a3102fae083ada369c795855a28db4bdd3d05358a361cf32a1a15e8";
/// Internal (wire) byte order.
pub const segwit_wtxid_hex = "62b709c9126ae7782ea86576b338f39211199d149dced92423df070937386cc3";
