// SPDX-License-Identifier: MIT

// Differential oracle for modules/encoding: golang.org/x/text (BSD-3-Clause)
// -- encoding/htmlindex for the WHATWG Encoding Standard's label table, and
// encoding/charmap for which code points each single-byte page can encode.
// The label list is ours; Go only answers it. The answers are written out as
// a Zig file that the module's own tests replay hermetically.
//
//	cd modules/encoding/tools/go_oracle && GOPROXY=off go run . -out ../../src/go_oracle_vectors.zig
//
// Needs golang.org/x/text v0.42.0 in the module cache (go.sum pins it).
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"runtime"
	"strings"
	"unicode/utf8"

	"golang.org/x/text/encoding"
	"golang.org/x/text/encoding/charmap"
	"golang.org/x/text/encoding/htmlindex"
)

// Every label the WHATWG table lists for the six encodings this module has,
// labels of encodings it does not have, spellings that are NOT labels, and
// whitespace / case variants.
var labels = []string{
	// utf-8
	"unicode-1-1-utf-8", "unicode11utf8", "unicode20utf8", "utf-8", "utf8", "x-unicode20utf8",
	// windows-1250
	"cp1250", "windows-1250", "x-cp1250",
	// windows-1252 (the WHATWG list, incl. the iso-8859-1 family)
	"ansi_x3.4-1968", "ascii", "cp1252", "cp819", "csisolatin1", "ibm819", "iso-8859-1", "iso-ir-100",
	"iso8859-1", "iso88591", "iso_8859-1", "iso_8859-1:1987", "l1", "latin1", "us-ascii", "windows-1252", "x-cp1252",
	// iso-8859-2
	"csisolatin2", "iso-8859-2", "iso-ir-101", "iso8859-2", "iso88592", "iso_8859-2", "iso_8859-2:1987", "l2", "latin2",
	// iso-8859-15
	"csisolatin9", "iso-8859-15", "iso8859-15", "iso885915", "iso_8859-15", "l9",
	// spellings this module accepts that WHATWG does not list
	"windows1250", "win1250", "windows1252", "win1252", "latin-1", "latin-2", "latin-9", "latin9", "iso-ir-203",
	// other encodings' labels
	"utf-16le", "utf-16", "utf-16be", "iso-8859-3", "iso-8859-16", "windows-1251", "koi8-r", "gbk", "shift_jis",
	"euc-kr", "big5", "x-user-defined", "replacement", "iso-2022-kr", "macintosh", "ibm866", "windows-874",
	// near misses
	"utf-8 ", " utf-8", "\tutf-8\r\n", "\x0cutf-8", "\vutf-8", "UTF-8", "Windows-1250", "LATIN2", "utf_8",
	"utf-8\x00", "", " ", "iso-8859-1 latin1", "windows-125", "cp-1250",
}

type page struct {
	name string
	cm   *charmap.Charmap
}

func main() {
	out := flag.String("out", "", "write the Zig vectors file here (default stdout)")
	flag.Parse()
	var b bytes.Buffer
	fmt.Fprintf(&b, "// SPDX-License-Identifier: MIT\n")
	fmt.Fprintf(&b, "// GENERATED by modules/encoding/tools/go_oracle (%s, golang.org/x/text v0.42.0) -- do not hand-edit.\n", runtime.Version())
	fmt.Fprintf(&b, "//! htmlindex and charmap verdicts, replayed by `go_oracle.zig`.\n\n")

	b.WriteString("pub const Label = struct { label: []const u8, name: ?[]const u8 };\n\n")
	b.WriteString("/// htmlindex.Get: the WHATWG encoding a label names (htmlindex.Name of it), or null.\npub const labels = [_]Label{\n")
	for _, l := range labels {
		name := "null"
		if e, err := htmlindex.Get(l); err == nil {
			if n, err := htmlindex.Name(e); err == nil {
				name = zigStr(n)
			}
		}
		fmt.Fprintf(&b, "    .{ .label = %s, .name = %s },\n", zigStr(l), name)
	}
	b.WriteString("};\n\n")

	pages := []page{{"windows_1250", charmap.Windows1250}, {"windows_1252", charmap.Windows1252}, {"iso_8859_1", charmap.ISO8859_1},
		{"iso_8859_2", charmap.ISO8859_2}, {"iso_8859_15", charmap.ISO8859_15}}
	b.WriteString("pub const Pair = struct { cp: u21, byte: u8 };\n\n")
	b.WriteString("/// charmap: every code point from U+0080 up that each page's strict encoder accepts, with its\n/// byte. Any other code point is unencodable there.\n")
	for _, p := range pages {
		enc := p.cm.NewEncoder()
		var pairs []string
		for cp := rune(0x80); cp <= utf8.MaxRune; cp++ {
			if cp >= 0xd800 && cp <= 0xdfff {
				continue
			}
			got, err := enc.String(string(cp))
			if err != nil || len(got) != 1 {
				continue
			}
			pairs = append(pairs, fmt.Sprintf(".{ .cp = 0x%x, .byte = 0x%02x }", cp, got[0]))
		}
		fmt.Fprintf(&b, "pub const encodable_%s = [_]Pair{\n    %s,\n};\n\n", p.name, strings.Join(pairs, ",\n    "))
	}
	_ = encoding.Nop
	b.Truncate(b.Len() - 1)
	if *out == "" {
		os.Stdout.Write(b.Bytes())
		return
	}
	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
