#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for `src/json_path_vectors.zig`: what Python reads back from a JSON
access-log line's `target` when the request target held arbitrary bytes.
(Moved from `metrics` with its access-log writer, 2026-10-06.)

    python3 modules/accesslog/tools/json_path_oracle.py > modules/accesslog/src/json_path_vectors.zig

`want` is `path.decode('utf-8', 'replace')` -- one U+FFFD per maximal subpart
(Unicode 16.0 §3.9) -- re-encoded as UTF-8. The replay (`writeJsonLines:
target reads back ...` in root.zig) writes each path as `Entry.target` in JSON
Lines, parses the line, and needs the `target` field to be exactly `want`.
No Python at test time.
"""
import random

FIXED = [
    b"/", b"/a b", b'/q"x', b"/back\\slash", b"/\x00\x01\x1f\x7f", b"/\t\n\r\x08\x0c",
    b"/\xc3\xa9", b"/\xe2\x82\xac", b"/\xf0\x9f\x98\x80",
    b"/\xff", b"/a\xffb", b"/\xe2\x82", b"/\xe2\x82x", b"/\xe2", b"/\xf0\x9f\x98", b"/\xf0\x9f",
    b"/\xed\xa0\x80", b"/\xed\x9f\xbf", b"/\xc0\xaf", b"/\xc1\xbf", b"/\xe0\x80\xaf", b"/\xe0\xa0\x80",
    b"/\xf0\x80\x80\x80", b"/\xf0\x90\x80\x80", b"/\xf4\x8f\xbf\xbf", b"/\xf4\x90\x80\x80", b"/\xf5\x80\x80\x80",
    b"/\x80", b"/\x80\x80", b"/\xc2", b"/\xc2\xc2\xa9", b"/\xe2\x82\xe2\x82\xac", b"/\xfe\xff",
]


def zstr(b):
    out = []
    for c in b:
        if c == 0x22:
            out.append('\\"')
        elif c == 0x5C:
            out.append("\\\\")
        elif 0x20 <= c < 0x7F:
            out.append(chr(c))
        else:
            out.append("\\x%02x" % c)
    return '"' + "".join(out) + '"'


rnd = random.Random(20261006)
pool = [0x2F, 0x61, 0x22, 0x5C, 0x00, 0x7F, 0x80, 0xBF, 0xC2, 0xC3, 0xA9, 0xE2, 0x82, 0xAC, 0xED, 0xA0,
        0xF0, 0x9F, 0x98, 0xF4, 0x90, 0xFF]
paths = list(FIXED)
for _ in range(300):
    paths.append(b"/" + bytes(rnd.choice(pool) for _ in range(rnd.randint(1, 10))))

print("// SPDX-License-Identifier: MIT")
print("// GENERATED by modules/accesslog/tools/json_path_oracle.py -- do not hand-edit.")
print("//! Request paths and what Python's decode('utf-8', 'replace') reads them as (UTF-8).")
print()
print("pub const Case = struct { path: []const u8, want: []const u8 };")
print()
print("pub const cases = [_]Case{")
for p in paths:
    print(f"    .{{ .path = {zstr(p)}, .want = {zstr(p.decode('utf-8', 'replace').encode('utf-8'))} }},")
print("};")
