// SPDX-License-Identifier: MIT

// Differential oracle for modules/tar: Go's standard library archive/tar as
// an independent implementation. The read-area inputs are OURS -- headers
// built field by field in read.go, plus archives Go's own Writer produced for
// entry tables in read.go -- and Go only answers them. The write area reads
// archives that THIS module's Writer produced (tools/interop.zig writes them
// under src/testdata/go_write/) and records what Go makes of them.
// The answers are written out as a Zig file that the module's own tests
// replay hermetically -- no Go at test time.
//
//	zig build interop-tar -- --regen   (writes the go_write archives, then runs this)
//	cd modules/tar/tools/go_oracle && go run . -write ../../src/testdata/go_write -out ../../src/go_oracle_vectors.zig
//
// Stdlib only, no network.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"runtime"
	"strings"
)

func main() {
	out := flag.String("out", "", "write the Zig vectors file here (default stdout)")
	writeDir := flag.String("write", "", "directory holding this module's Writer output (src/testdata/go_write)")
	dump := flag.String("dump", "", "write every read-area case to <dir>/<id>.tar and exit (to ask another tar)")
	flag.Parse()
	if *dump != "" {
		for _, c := range append(goWritten(), crafted()...) {
			if err := os.WriteFile(*dump+"/"+c.id+".tar", c.data, 0o644); err != nil {
				fmt.Fprintln(os.Stderr, err)
				os.Exit(1)
			}
		}
		return
	}
	if *writeDir == "" {
		fmt.Fprintln(os.Stderr, "-write <dir> is required (see the header of main.go)")
		os.Exit(2)
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, "// SPDX-License-Identifier: MIT\n")
	fmt.Fprintf(&b, "// GENERATED by modules/tar/tools/go_oracle (%s) -- do not hand-edit.\n", runtime.Version())
	fmt.Fprintf(&b, "//! Go archive/tar verdicts on this module's own case tables, replayed\n")
	fmt.Fprintf(&b, "//! by `go_oracle.zig`. Regenerate with the command in tools/go_oracle/main.go.\n\n")
	fmt.Fprintf(&b, "pub const go_version = %s;\n\n", zigStr(runtime.Version()))
	emitTypes(&b)
	emitRead(&b)
	if err := emitWrite(&b, *writeDir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	b.Truncate(b.Len() - 1)

	if *out == "" {
		os.Stdout.Write(b.Bytes())
		return
	}
	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func emitTypes(b *bytes.Buffer) {
	b.WriteString(`/// One header Go's Reader returned, with the content it then read.
pub const Entry = struct {
    name: []const u8,
    /// Go's Header.Typeflag after its own normalisation.
    typeflag: u8,
    mode: i64,
    uid: i64,
    gid: i64,
    /// ModTime as Unix seconds (floor) + nanoseconds 0..999_999_999.
    mtime: i64,
    nsec: u32,
    /// Header.Size as Go reports it (for a header-only type it may be the
    /// header's claim, not the content present: compare ` + "`content`" + ` there).
    size: i64,
    link: []const u8,
    content: []const u8,
};

/// An archive as runs of non-zero bytes: ` + "`len`" + ` bytes, zero except at each run.
pub const Run = struct { off: u32, bytes: []const u8 };
pub const Archive = struct { len: u32, runs: []const Run };

pub const Case = struct {
    id: []const u8,
    archive: Archive,
    /// Every header Go returned before it stopped.
    entries: []const Entry,
    /// Go stopped with an error (not a clean end of archive); the text is Go's.
    err: ?[]const u8,
};

`)
}

// zigStr renders s as a Zig string literal: printable ASCII as is, \r \n \t
// by name, everything else as \xHH. Byte-exact, so a case can carry any byte.
func zigStr(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString(`\"`)
		case c == '\\':
			b.WriteString(`\\`)
		case c == '\r':
			b.WriteString(`\r`)
		case c == '\n':
			b.WriteString(`\n`)
		case c == '\t':
			b.WriteString(`\t`)
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, `\x%02x`, c)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// zigList renders items as an anonymous-list literal the way `zig fmt` does.
func zigList(items []string) string {
	switch len(items) {
	case 0:
		return "&.{}"
	case 1:
		return "&.{" + items[0] + "}"
	}
	return "&.{ " + strings.Join(items, ", ") + " }"
}

// zigArchive renders data as runs of non-zero bytes; a zero gap shorter than
// 8 bytes stays inside its run, so a header is one or two runs, not dozens.
func zigArchive(data []byte) string {
	var runs []string
	i := 0
	for i < len(data) {
		if data[i] == 0 {
			i++
			continue
		}
		start, end := i, i
		for j := i; j < len(data); j++ {
			if data[j] != 0 {
				end = j + 1
			} else if j-end >= 8 {
				break
			}
		}
		runs = append(runs, fmt.Sprintf(".{ .off = %d, .bytes = %s }", start, zigStr(string(data[start:end]))))
		i = end
	}
	if len(runs) == 0 {
		return fmt.Sprintf(".{ .len = %d, .runs = &.{} }", len(data))
	}
	return fmt.Sprintf(".{ .len = %d, .runs = &.{\n            %s,\n        } }", len(data), strings.Join(runs, ",\n            "))
}
