// SPDX-License-Identifier: MIT
// GENERATED by modules/cookies/tools/go_oracle (go1.26.0) -- do not hand-edit.
//! Go's net/http/cookiejar on our scenarios; replayed by `jar_go_oracle.zig`.

pub const go_version = "go1.26.0";
/// When the scenarios ran (Unix seconds): the replay's clock.
pub const now: i64 = 1791176584;

/// `fields` set = Set-Cookie fields from `url`; null = a request to `url`, which Go answered with `go`.
pub const Step = struct { url: []const u8, fields: ?[]const []const u8 = null, go: []const u8 = "" };
pub const Scenario = struct { id: []const u8, steps: []const Step };

pub const scenarios = [_]Scenario{
    .{ .id = "host-only", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1"} }, .{ .url = "http://www.example.test/", .go = "a=1" }, .{ .url = "http://example.test/", .go = "" }, .{ .url = "http://x.www.example.test/", .go = "" } } },
    .{ .id = "domain-parent", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1; Domain=example.test"} }, .{ .url = "http://example.test/", .go = "a=1" }, .{ .url = "http://a.b.example.test/", .go = "a=1" }, .{ .url = "http://other.test/", .go = "" } } },
    .{ .id = "domain-leading-dot", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1; Domain=.example.test"} }, .{ .url = "http://a.example.test/", .go = "a=1" } } },
    .{ .id = "domain-uppercase", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1; Domain=EXAMPLE.test"} }, .{ .url = "http://a.example.test/", .go = "a=1" } } },
    .{ .id = "domain-public-suffix", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1; Domain=test"} }, .{ .url = "http://www.example.test/", .go = "" }, .{ .url = "http://other.test/", .go = "" } } },
    .{ .id = "domain-is-host-suffix", .steps = &.{ .{ .url = "http://test/", .fields = &.{"a=1; Domain=test"} }, .{ .url = "http://test/", .go = "a=1" }, .{ .url = "http://x.test/", .go = "" } } },
    .{ .id = "domain-mismatch", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1; Domain=other.test"} }, .{ .url = "http://other.test/", .go = "" }, .{ .url = "http://www.example.test/", .go = "" } } },
    .{ .id = "domain-sibling", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1; Domain=api.example.test"} }, .{ .url = "http://api.example.test/", .go = "" } } },
    .{ .id = "domain-empty", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1; Domain="} }, .{ .url = "http://www.example.test/", .go = "a=1" }, .{ .url = "http://example.test/", .go = "" } } },
    .{ .id = "domain-self", .steps = &.{ .{ .url = "http://www.example.test/", .fields = &.{"a=1; Domain=www.example.test"} }, .{ .url = "http://www.example.test/", .go = "a=1" }, .{ .url = "http://x.www.example.test/", .go = "a=1" } } },
    .{ .id = "ip-host", .steps = &.{ .{ .url = "http://192.0.2.1/", .fields = &.{"a=1"} }, .{ .url = "http://192.0.2.1/", .go = "a=1" }, .{ .url = "http://192.0.2.1:8080/", .go = "a=1" } } },
    .{ .id = "ip-domain-self", .steps = &.{ .{ .url = "http://192.0.2.1/", .fields = &.{"a=1; Domain=192.0.2.1"} }, .{ .url = "http://192.0.2.1/", .go = "a=1" } } },
    .{ .id = "ip-domain-suffix", .steps = &.{ .{ .url = "http://192.0.2.1/", .fields = &.{"a=1; Domain=0.2.1"} }, .{ .url = "http://192.0.2.1/", .go = "" } } },
    .{ .id = "port-ignored", .steps = &.{ .{ .url = "http://www.example.test:8080/", .fields = &.{"a=1"} }, .{ .url = "http://www.example.test/", .go = "a=1" }, .{ .url = "http://www.example.test:9090/", .go = "a=1" } } },
    .{ .id = "path-default", .steps = &.{ .{ .url = "http://h.test/a/b/page", .fields = &.{"a=1"} }, .{ .url = "http://h.test/a/b/x", .go = "a=1" }, .{ .url = "http://h.test/a/b", .go = "a=1" }, .{ .url = "http://h.test/a/", .go = "" }, .{ .url = "http://h.test/a/bc", .go = "" } } },
    .{ .id = "path-default-root", .steps = &.{ .{ .url = "http://h.test/page", .fields = &.{"a=1"} }, .{ .url = "http://h.test/other", .go = "a=1" } } },
    .{ .id = "path-attr", .steps = &.{ .{ .url = "http://h.test/x/y", .fields = &.{"a=1; Path=/p"} }, .{ .url = "http://h.test/p", .go = "a=1" }, .{ .url = "http://h.test/p/q", .go = "a=1" }, .{ .url = "http://h.test/pq", .go = "" }, .{ .url = "http://h.test/x/y", .go = "" } } },
    .{ .id = "path-attr-trailing-slash", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; Path=/p/"} }, .{ .url = "http://h.test/p", .go = "" }, .{ .url = "http://h.test/p/q", .go = "a=1" } } },
    .{ .id = "path-attr-relative", .steps = &.{ .{ .url = "http://h.test/x/y", .fields = &.{"a=1; Path=rel"} }, .{ .url = "http://h.test/x/z", .go = "a=1" }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "path-order", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{ "short=1; Path=/", "long=1; Path=/a/b", "mid=1; Path=/a" } }, .{ .url = "http://h.test/a/b/c", .go = "long=1; mid=1; short=1" } } },
    .{ .id = "creation-order", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{ "z=1", "a=1", "m=1" } }, .{ .url = "http://h.test/", .go = "z=1; a=1; m=1" } } },
    .{ .id = "replace-keeps-order", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{ "a=1", "b=1" } }, .{ .url = "http://h.test/", .fields = &.{"a=2"} }, .{ .url = "http://h.test/", .go = "a=2; b=1" } } },
    .{ .id = "same-name-two-paths", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{ "a=1", "a=2; Path=/x" } }, .{ .url = "http://h.test/x/y", .go = "a=2; a=1" } } },
    .{ .id = "secure-from-https", .steps = &.{ .{ .url = "https://h.test/", .fields = &.{"s=1; Secure"} }, .{ .url = "https://h.test/", .go = "s=1" }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "secure-from-http", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"s=1; Secure"} }, .{ .url = "https://h.test/", .go = "s=1" } } },
    .{ .id = "secure-shadow", .steps = &.{ .{ .url = "https://h.test/", .fields = &.{"s=1; Secure"} }, .{ .url = "http://h.test/", .fields = &.{"s=2"} }, .{ .url = "https://h.test/", .go = "s=2" }, .{ .url = "http://h.test/", .go = "s=2" } } },
    .{ .id = "max-age-zero", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1"} }, .{ .url = "http://h.test/", .fields = &.{"a=1; Max-Age=0"} }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "max-age-negative", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1"} }, .{ .url = "http://h.test/", .fields = &.{"a=1; Max-Age=-1"} }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "max-age-future", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; Max-Age=3600"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "max-age-invalid", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; Max-Age=abc"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "max-age-over-expires", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; Max-Age=3600; Expires=Thu, 01 Jan 1970 00:00:00 GMT"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "expires-past", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1"} }, .{ .url = "http://h.test/", .fields = &.{"a=1; Expires=Thu, 01 Jan 1970 00:00:00 GMT"} }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "expires-future", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; Expires=Fri, 01 Jan 2100 00:00:00 GMT"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "expires-rfc850", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1"} }, .{ .url = "http://h.test/", .fields = &.{"a=1; Expires=Thursday, 01-Jan-70 00:00:00 GMT"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "expires-asctime-past", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1"} }, .{ .url = "http://h.test/", .fields = &.{"a=1; Expires=Thu Jan  1 00:00:00 1970"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "expires-garbage", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; Expires=tomorrow"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "expires-dashes-past", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1"} }, .{ .url = "http://h.test/", .fields = &.{"a=1; Expires=Thu, 01-Jan-1970 00:00:00 GMT"} }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "value-empty", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a="} }, .{ .url = "http://h.test/", .go = "a=" } } },
    .{ .id = "value-quoted", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=\"x y\""} }, .{ .url = "http://h.test/", .go = "a=x y" } } },
    .{ .id = "value-quoted-plain", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=\"xy\""} }, .{ .url = "http://h.test/", .go = "a=xy" } } },
    .{ .id = "value-space", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=x y"} }, .{ .url = "http://h.test/", .go = "a=x y" } } },
    .{ .id = "value-comma", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=x,y"} }, .{ .url = "http://h.test/", .go = "a=x,y" } } },
    .{ .id = "value-equals", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=x=y"} }, .{ .url = "http://h.test/", .go = "a=x=y" } } },
    .{ .id = "value-ows", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a =  1  ; Path=/"} }, .{ .url = "http://h.test/", .go = "a=  1" } } },
    .{ .id = "name-space", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a b=1"} }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "name-empty", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"=1"} }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "no-equals", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"justname"} }, .{ .url = "http://h.test/", .go = "" } } },
    .{ .id = "attr-case", .steps = &.{ .{ .url = "http://h.test/x", .fields = &.{"a=1; PATH=/; DOMAIN=h.test; MAX-AGE=60"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "attr-last-wins", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; Path=/x; Path=/"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "httponly-sent", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; HttpOnly"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "samesite-sent", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{"a=1; SameSite=Strict"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "case-sensitive-names", .steps = &.{ .{ .url = "http://h.test/", .fields = &.{ "A=1", "a=2" } }, .{ .url = "http://h.test/", .go = "A=1; a=2" } } },
    .{ .id = "host-case", .steps = &.{ .{ .url = "http://H.Test/", .fields = &.{"a=1"} }, .{ .url = "http://h.test/", .go = "a=1" } } },
    .{ .id = "localhost", .steps = &.{ .{ .url = "http://localhost/", .fields = &.{"a=1; Domain=localhost"} }, .{ .url = "http://localhost/", .go = "a=1" } } },
};
