// SPDX-License-Identifier: MIT

// Command gen_kat writes src/kat_vectors.zig: CRC-32 (IEEE) values computed by Go's
// hash/crc32 (IEEE table), used only as a black-box oracle. Nothing of
// Go's implementation is copied.
//
// What it anchors: `combine` at lengths no test can afford to hash. For each
// prefix P and each length n it records crc32(P ‖ n zero bytes). The test
// then requires combine(hash(P), Z(n), n) to equal that value, where Z(n) is
// the recorded checksum of the n zero bytes alone — so every byte of the
// expected values comes from Go, and the only computation left to this module
// is the one under test. The lengths sit around the powers of two where a
// periodic table of x^(2^k) goes wrong (zlib folds that table to period 32; a wrong period first shows at 2^29)
// and past 2^32, where a 32-bit length would wrap.
//
// Usage (from modules/crc32): go run tools/gen_kat.go > src/kat_vectors.zig
// It streams ~26 GB of zeros through hash/crc32; a few seconds with PCLMUL.
package main

import (
	"fmt"
	"hash/crc32"
	"os"
	"sort"
	"strings"
)

func lengths() []uint64 {
	set := map[uint64]bool{}
	for _, k := range []uint{28, 29, 30, 31, 32, 33} {
		p := uint64(1) << k
		set[p-1] = true
		set[p] = true
		set[p+1] = true
	}
	set[3<<31+12345] = true
	set[5_000_000_007] = true
	out := make([]uint64, 0, len(set))
	for n := range set {
		out = append(out, n)
	}
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	return out
}

func prefixes() [][]byte {
	pattern := make([]byte, 1000)
	for i := range pattern {
		pattern[i] = byte(i*37 + 5)
	}
	return [][]byte{{}, []byte("123456789"), pattern}
}

func zigString(b []byte) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, c := range b {
		if c >= 0x20 && c < 0x7f && c != '"' && c != '\\' {
			sb.WriteByte(c)
		} else {
			fmt.Fprintf(&sb, "\\x%02x", c)
		}
	}
	sb.WriteByte('"')
	return sb.String()
}

func main() {
	table := crc32.IEEETable
	ps := prefixes()
	ns := lengths()
	zeros := make([]byte, 1<<20)

	// One pass per prefix: extend the running checksum by zeros up to each
	// recorded length in turn.
	got := make([][]uint32, len(ps))
	for pi, p := range ps {
		crc := crc32.Checksum(p, table)
		var at uint64
		for _, n := range ns {
			for at < n {
				step := n - at
				if step > uint64(len(zeros)) {
					step = uint64(len(zeros))
				}
				crc = crc32.Update(crc, table, zeros[:step])
				at += step
			}
			got[pi] = append(got[pi], crc)
		}
	}

	w := os.Stdout
	fmt.Fprintln(w, "// SPDX-License-Identifier: MIT")
	fmt.Fprintln(w, "//! GENERATED by tools/gen_kat.go -- do not edit by hand.")
	fmt.Fprintln(w, "//!")
	fmt.Fprintln(w, "//! CRC-32 of a prefix followed by n zero bytes, computed by Go's")
	fmt.Fprintln(w, "//! hash/crc32 (IEEE) as a black-box oracle. `crc[p][i]` is the")
	fmt.Fprintln(w, "//! checksum of `prefixes[p]` followed by `lengths[i]` zero bytes;")
	fmt.Fprintln(w, "//! `prefixes[0]` is empty, so `crc[0]` is the zero bytes alone.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "pub const prefixes = [_][]const u8{")
	for _, p := range ps {
		fmt.Fprintf(w, "    %s,\n", zigString(p))
	}
	fmt.Fprintln(w, "};")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "pub const lengths = [_]u64{")
	for _, n := range ns {
		fmt.Fprintf(w, "    %d,\n", n)
	}
	fmt.Fprintln(w, "};")
	fmt.Fprintln(w)
	fmt.Fprintf(w, "pub const crc = [prefixes.len][lengths.len]u32{\n")
	for pi := range ps {
		fmt.Fprint(w, "    .{")
		for i, c := range got[pi] {
			if i%6 == 0 {
				fmt.Fprint(w, "\n       ")
			}
			fmt.Fprintf(w, " 0x%08X,", c)
		}
		fmt.Fprintln(w, "\n    },")
	}
	fmt.Fprintln(w, "};")
}
