#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Regenerates modules/k256/src/wycheproof_kat_vectors.zig and
# wycheproof_bitcoin_vectors.zig from Google/C2SP's Wycheproof ECDSA
# secp256k1 / SHA-256 vectors — k256 shipped NO ECDSA vectors of its own
# (audit G3); the sibling p256 module has the same shape via
# scripts/gen-p256-wycheproof.py, and this mirrors it for secp256k1's two
# published Wycheproof files.
#
#   curl -sSLO https://raw.githubusercontent.com/C2SP/wycheproof/main/\
#testvectors_v1/ecdsa_secp256k1_sha256_p1363_test.json
#   curl -sSLO https://raw.githubusercontent.com/C2SP/wycheproof/main/\
#testvectors_v1/ecdsa_secp256k1_sha256_bitcoin_test.json
#   python3 modules/k256/tools/gen-k256-wycheproof.py ecdsa_secp256k1_sha256_p1363_test.json \
#     > modules/k256/src/wycheproof_kat_vectors.zig
#   python3 modules/k256/tools/gen-k256-wycheproof.py --bitcoin \
#     ecdsa_secp256k1_sha256_bitcoin_test.json \
#     > modules/k256/src/wycheproof_bitcoin_vectors.zig
#
# P1363 mode keeps every row whose signature is exactly 64 bytes (`sign
# .ecdsaVerify`'s parameter is `[64]u8`; a wrong-length signature cannot be
# handed to it at all, so rejecting one measures the type system, not the
# verifier). Bitcoin mode is DER, and k256 has no DER parser (`sign
# .ecdsaVerifyLowS` takes raw `r || s`), so only rows whose DER is STRICTLY
# canonical are converted to raw r||s; the dropped rows attack the DER
# ENCODING, which is not k256's surface at all. Drop counts are printed into
# each generated file's header so the omission stays visible.
import json
import sys

bitcoin = "--bitcoin" in sys.argv[1:]
path = [a for a in sys.argv[1:] if not a.startswith("--")][0]
data = json.load(open(path))


def der_to_raw(b):
    if len(b) < 8 or b[0] != 0x30 or b[1] != len(b) - 2:
        return None
    i, out = 2, []
    for _ in range(2):
        if i >= len(b) or b[i] != 0x02:
            return None
        ln = b[i + 1]
        i += 2
        v = b[i:i + ln]
        i += ln
        if len(v) != ln or ln == 0 or v[0] & 0x80 or len(v) > 32:
            return None
        if len(v) > 1 and v[0] == 0 and not (v[1] & 0x80):
            return None
        out.append(v.rjust(32, b"\0"))
    return out[0] + out[1] if i == len(b) else None


rows, dropped = [], 0
for g in data["testGroups"]:
    assert g["sha"] == "SHA-256", g["sha"]
    key = g["publicKey"]["uncompressed"]
    for t in g["tests"]:
        if bitcoin:
            raw = der_to_raw(bytes.fromhex(t["sig"]))
            if raw is None:
                dropped += 1
                continue
            sig = raw.hex()
        else:
            if len(t["sig"]) != 128:
                dropped += 1
                continue
            sig = t["sig"]
        rows.append((key, t["tcId"], t["msg"], sig, t["result"], t["comment"]))

valid = sum(1 for r in rows if r[4] == "valid")
invalid = len(rows) - valid

print("// SPDX-License-Identifier: MIT")
if bitcoin:
    print("// Generated by modules/k256/tools/gen-k256-wycheproof.py --bitcoin -- do not hand-edit hex payloads.")
    print("")
    print("//! Wycheproof ECDSA secp256k1 / SHA-256 vectors, Bitcoin/low-S DER form")
    print("//! converted to raw `r || s` where the DER is strictly canonical, from")
    print("//! C2SP/wycheproof `testvectors_v1/ecdsa_secp256k1_sha256_bitcoin_test.json`.")
    print("//!")
    print("//! %d vectors: %d must verify, %d must not. %d further upstream rows are"
          % (len(rows), valid, invalid, dropped))
    print("//! omitted: their DER is not strictly canonical (this module has no DER")
    print("//! parser -- `sign.ecdsaVerifyLowS` takes raw `r || s` -- so a non-canonical")
    print("//! encoding is not this module's surface at all; see `gen-k256-wycheproof.py`'s")
    print("//! `der_to_raw`).")
else:
    print("// Generated by modules/k256/tools/gen-k256-wycheproof.py -- see doc comment below.")
    print("// Do not hand-edit hex payloads; regenerate instead.")
    print("")
    print("//! Wycheproof ECDSA secp256k1 / SHA-256 verification vectors, IEEE P1363")
    print("//! (raw `r || s`) form, from C2SP/wycheproof `testvectors_v1`")
    print("//! (`ecdsa_secp256k1_sha256_p1363_test.json`).")
    print("//!")
    print("//! %d vectors: %d must verify, %d must not." % (len(rows), valid, invalid))
    print("//! %d further rows in the upstream file are omitted: their signature is"
          % dropped)
    print("//! not 64 bytes, and `ecdsaVerify` takes a `[64]u8`, so rejecting them is")
    print("//! the type system's doing rather than the verifier's -- including them")
    print("//! would inflate the count without testing anything (same convention as")
    print("//! the sibling `p256` module's own P1363 file).")
print("")
print("pub const Vector = struct {")
print("    /// SEC1 uncompressed public key (0x04 || x || y).")
print("    pubkey_hex: []const u8,")
print("    /// Upstream `tcId`, so a failure names the row to look up.")
print("    tc_id: u32,")
print("    msg_hex: []const u8,")
if bitcoin:
    print("    /// `r (32) || s (32)`, big-endian -- converted from the upstream DER.")
else:
    print("    /// `r (32) || s (32)`, big-endian.")
print("    sig_hex: []const u8,")
print("    should_verify: bool,")
print("    comment: []const u8,")
print("};")
print("")
print("pub const vectors = [_]Vector{")
for k, tc, msg, sig, res, com in rows:
    print('    .{ .pubkey_hex = "%s", .tc_id = %d, .msg_hex = "%s", .sig_hex = "%s",'
          ' .should_verify = %s, .comment = "%s" },'
          % (k, tc, msg, sig, "true" if res == "valid" else "false",
             com.replace('"', '\\"')))
print("};")
