// SPDX-License-Identifier: MIT
//! The official RFC 9381 Appendix B.3 test vectors for
//! ECVRF-EDWARDS25519-SHA512-TAI (Examples 16, 17, 18 in the RFC's own
//! numbering — the secret keys/messages themselves are drawn from RFC
//! 8032 §7.1's Ed25519 vectors, but every ECVRF-specific field (`x`, `H`,
//! `k_string`, `k`, `U`, `V`, `pi`, `beta`) is unique to RFC 9381 and was
//! generated by the reference implementation the RFC itself cites,
//! <https://github.com/reyzin/ecvrf> — see Appendix B's own preamble).
//!
//! Fetched directly from `https://www.rfc-editor.org/rfc/rfc9381.txt`
//! (the IETF's own canonical RFC repository) and extracted with a
//! regex-based structured-extraction pass (joining each field's
//! line-wrapped hex digits, stripping the `k*B =`/`k*H =` inline
//! annotations on the `U`/`V` lines) rather than hand-transcribed, to
//! avoid manual hex-transcription error on 80-plus-byte fields; every
//! field's byte length was then cross-checked against RFC 9381 §5.5's
//! own stated widths (`SK`/`PK`/`x`/`H`/`k` = 32 bytes, `k_string` = 64
//! bytes, `U`/`V` = 32 bytes, `pi` = `ptLen+cLen+qLen` = 80 bytes,
//! `beta` = `hLen` = 64 bytes) before being trusted — see `../NOTICE`.

pub const Vector = struct {
    /// RFC 9381's own example number (16, 17, 18) — kept for cross-
    /// referencing back to the RFC text in test failure messages.
    example: u8,
    /// 64 hex chars (32-byte secret key seed).
    sk: []const u8,
    /// 64 hex chars (32-byte compressed public key `Y`).
    pk: []const u8,
    /// Variable-length hex VRF input `alpha_string` (0, 2, or 4 hex chars
    /// in this set — the empty string, 1 byte, and 2 bytes respectively).
    alpha: []const u8,
    /// 64 hex chars (32-byte clamped VRF secret scalar `x`).
    x: []const u8,
    /// The `try_and_increment` counter that produced `H` (0, 1, or 0).
    ctr: u8,
    /// 64 hex chars (32-byte compressed `H = encode_to_curve(...)`).
    h: []const u8,
    /// 128 hex chars (64-byte SHA-512 output BEFORE reduction mod q —
    /// RFC 9381 §5.4.2.2's `k_string`).
    k_string: []const u8,
    /// 64 hex chars (32-byte nonce `k = k_string mod q`).
    k: []const u8,
    /// 64 hex chars (32-byte compressed `U = k*B`).
    u: []const u8,
    /// 64 hex chars (32-byte compressed `V = k*H`).
    v: []const u8,
    /// 160 hex chars (80-byte proof `pi_string = Gamma || c || s`).
    pi: []const u8,
    /// 128 hex chars (64-byte VRF output `beta_string`).
    beta: []const u8,
};

pub const vectors = [_]Vector{
    // RFC 9381 Appendix B.3, Example 16 (alpha = the empty string; SK/PK
    // from RFC 8032 §7.1's first Ed25519 test vector).
    .{
        .example = 16,
        .sk = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60",
        .pk = "d75a980182b10ab7d54bfed3c964073a0ee172f3daa62325af021a68f707511a",
        .alpha = "",
        .x = "307c83864f2833cb427a2ef1c00a013cfdff2768d980c0a3a520f006904de94f",
        .ctr = 0,
        .h = "91bbed02a99461df1ad4c6564a5f5d829d0b90cfc7903e7a5797bd658abf3318",
        .k_string = "7100f3d9eadb6dc4743b029736ff283f5be494128df128df2817106f345b8594b6d6da2d6fb0b4c0257eb337675d96eab49cf39e66cc2c9547c2bf8b2a6afae4",
        .k = "8a49edbd1492a8ee09766befe50a7d563051bf3406cbffc20a88def030730f0f",
        .u = "aef27c725be964c6a9bf4c45ca8e35df258c1878b838f37d9975523f09034071",
        .v = "5016572f71466c646c119443455d6cb9b952f07d060ec8286d678615d55f954f",
        .pi = "8657106690b5526245a92b003bb079ccd1a92130477671f6fc01ad16f26f723f26f8a57ccaed74ee1b190bed1f479d9727d2d0f9b005a6e456a35d4fb0daab1268a1b0db10836d9826a528ca76567805",
        .beta = "90cf1df3b703cce59e2a35b925d411164068269d7b2d29f3301c03dd757876ff66b71dda49d2de59d03450451af026798e8f81cd2e333de5cdf4f3e140fdd8ae",
    },
    // Example 17 (alpha = 1 byte, 0x72 = ASCII 'r').
    .{
        .example = 17,
        .sk = "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb",
        .pk = "3d4017c3e843895a92b70aa74d1b7ebc9c982ccf2ec4968cc0cd55f12af4660c",
        .alpha = "72",
        .x = "68bd9ed75882d52815a97585caf4790a7f6c6b3b7f821c5e259a24b02e502e51",
        .ctr = 1,
        .h = "5b659fc3d4e9263fd9a4ed1d022d75eaacc20df5e09f9ea937502396598dc551",
        .k_string = "42589bbf0c485c3c91c1621bb4bfe04aed7be76ee48f9b00793b2342acb9c167cab856f9f9d4febc311330c20b0a8afd3743d05433e8be8d32522ecdc16cc5ce",
        .k = "d8c3a66921444cb3427d5d989f9b315aa8ca3375e9ec4d52207711a1fdb44107",
        .u = "1dcb0a4821a2c48bf53548228b7f170962988f6d12f5439f31987ef41f034ab3",
        .v = "fd03c0bf498c752161bae4719105a074630a2aa5f200ff7b3995f7bfb1513423",
        .pi = "f3141cd382dc42909d19ec5110469e4feae18300e94f304590abdced48aed5933bf0864a62558b3ed7f2fea45c92a465301b3bbf5e3e54ddf2d935be3b67926da3ef39226bbc355bdc9850112c8f4b02",
        .beta = "eb4440665d3891d668e7e0fcaf587f1b4bd7fbfe99d0eb2211ccec90496310eb5e33821bc613efb94db5e5b54c70a848a0bef4553a41befc57663b56373a5031",
    },
    // Example 18 (alpha = 2 bytes, 0xaf82).
    .{
        .example = 18,
        .sk = "c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7",
        .pk = "fc51cd8e6218a1a38da47ed00230f0580816ed13ba3303ac5deb911548908025",
        .alpha = "af82",
        .x = "909a8b755ed902849023a55b15c23d11ba4d7f4ec5c2f51b1325a181991ea95c",
        .ctr = 0,
        .h = "bf4339376f5542811de615e3313d2b36f6f53c0acfebb482159711201192576a",
        .k_string = "38b868c335ccda94a088428cbf3ec8bc7955bfaffe1f3bd2aa2c59fc31a0febc59d0e1af3715773ce11b3bbdd7aba8e3505d4b9de6f7e4a96e67e0d6bb6d6c3a",
        .k = "5ffdbc72135d936014e8ab708585fda379405542b07e3bd2c0bd48437fbac60a",
        .u = "2bae73e15a64042fcebf062abe7e432b2eca6744f3e8265bc38e009cd577ecd5",
        .v = "88cba1cb0d4f9b649d9a86026b69de076724a93a65c349c988954f0961c5d506",
        .pi = "9bc0f79119cc5604bf02d23b4caede71393cedfbb191434dd016d30177ccbf8096bb474e53895c362d8628ee9f9ea3c0e52c7a5c691b6c18c9979866568add7a2d41b00b05081ed0f58ee5e31b3a970e",
        .beta = "645427e5d00c62a23fb703732fa5d892940935942101e456ecca7bb217c61c452118fec1219202a0edcf038bb6373241578be7217ba85a2687f7a0310b2df19f",
    },
};

test "vector count matches RFC 9381 Appendix B.3 (Examples 16, 17, 18)" {
    const std = @import("std");
    try std.testing.expectEqual(@as(usize, 3), vectors.len);
}

test "hex field lengths match RFC 9381 §5.5's stated widths" {
    const std = @import("std");
    for (vectors) |vec| {
        try std.testing.expectEqual(@as(usize, 64), vec.sk.len);
        try std.testing.expectEqual(@as(usize, 64), vec.pk.len);
        try std.testing.expectEqual(@as(usize, 0), vec.alpha.len % 2);
        try std.testing.expectEqual(@as(usize, 64), vec.x.len);
        try std.testing.expectEqual(@as(usize, 64), vec.h.len);
        try std.testing.expectEqual(@as(usize, 128), vec.k_string.len);
        try std.testing.expectEqual(@as(usize, 64), vec.k.len);
        try std.testing.expectEqual(@as(usize, 64), vec.u.len);
        try std.testing.expectEqual(@as(usize, 64), vec.v.len);
        try std.testing.expectEqual(@as(usize, 160), vec.pi.len);
        try std.testing.expectEqual(@as(usize, 128), vec.beta.len);
    }
}
