// SPDX-License-Identifier: MIT
//! GENERATED by tools/gen_merge_vectors.py (PyYAML as a black-box oracle) -- do not edit.
pub const Case = struct { name: []const u8, yaml: []const u8, json: ?[]const u8, ours: ?[]const u8 };
pub const cases = [_]Case{
    .{ .name = "merge one mapping", .yaml = "b: &b {a: 1, b: 2}\nx: {<<: *b, c: 3}\n", .json = "{\"b\": {\"a\": 1, \"b\": 2}, \"x\": {\"a\": 1, \"b\": 2, \"c\": 3}}", .ours = null },
    .{ .name = "explicit key after the merge wins", .yaml = "b: &b {a: 1, b: 2}\nx: {<<: *b, a: 9}\n", .json = "{\"b\": {\"a\": 1, \"b\": 2}, \"x\": {\"a\": 9, \"b\": 2}}", .ours = null },
    .{ .name = "explicit key before the merge wins", .yaml = "b: &b {a: 1, b: 2}\nx: {a: 9, <<: *b}\n", .json = "{\"b\": {\"a\": 1, \"b\": 2}, \"x\": {\"a\": 9, \"b\": 2}}", .ours = null },
    .{ .name = "sequence: the earlier mapping wins", .yaml = "p: &p {a: 1}\nq: &q {a: 2, c: 3}\nx: {<<: [*p, *q]}\n", .json = "{\"p\": {\"a\": 1}, \"q\": {\"a\": 2, \"c\": 3}, \"x\": {\"a\": 1, \"c\": 3}}", .ours = null },
    .{ .name = "sequence and an explicit override", .yaml = "p: &p {a: 1, b: 1}\nq: &q {b: 2, c: 2}\nx: {c: 9, <<: [*p, *q]}\n", .json = "{\"p\": {\"a\": 1, \"b\": 1}, \"q\": {\"b\": 2, \"c\": 2}, \"x\": {\"a\": 1, \"b\": 1, \"c\": 9}}", .ours = null },
    .{ .name = "block style, compose-file shape", .yaml = "x-common: &common\n  restart: always\n  env:\n    A: \"1\"\nservices:\n  web:\n    <<: *common\n    image: nginx\n  db:\n    <<: *common\n    restart: \"no\"\n", .json = "{\"services\": {\"db\": {\"env\": {\"A\": \"1\"}, \"restart\": \"no\"}, \"web\": {\"env\": {\"A\": \"1\"}, \"image\": \"nginx\", \"restart\": \"always\"}}, \"x-common\": {\"env\": {\"A\": \"1\"}, \"restart\": \"always\"}}", .ours = null },
    .{ .name = "a merged mapping that merged itself", .yaml = "a: &a {k: 1}\nb: &b {<<: *a, m: 2}\nc: {<<: *b, n: 3}\n", .json = "{\"a\": {\"k\": 1}, \"b\": {\"k\": 1, \"m\": 2}, \"c\": {\"k\": 1, \"m\": 2, \"n\": 3}}", .ours = null },
    .{ .name = "inline mapping merged without an anchor", .yaml = "x: {<<: {a: 1}, b: 2}\n", .json = "{\"x\": {\"a\": 1, \"b\": 2}}", .ours = null },
    .{ .name = "quoted << is an ordinary key", .yaml = "x: {\"<<\": 1}\n", .json = "{\"x\": {\"<<\": 1}}", .ours = null },
    .{ .name = "!!merge tag", .yaml = "b: &b {a: 1}\nx: {!!merge <<: *b}\n", .json = "{\"b\": {\"a\": 1}, \"x\": {\"a\": 1}}", .ours = null },
    .{ .name = "merge of a scalar is an error", .yaml = "x: {<<: 1}\n", .json = null, .ours = "InvalidMerge" },
    .{ .name = "merge of a sequence holding a scalar is an error", .yaml = "b: &b {a: 1}\nx: {<<: [*b, 2]}\n", .json = null, .ours = "InvalidMerge" },
    .{ .name = "duplicate explicit keys stay a duplicate", .yaml = "b: &b {a: 1}\nx: {<<: *b, c: 1, c: 2}\n", .json = "{\"b\": {\"a\": 1}, \"x\": {\"a\": 1, \"c\": 2}}", .ours = "DuplicateKey" },
};
