#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Regenerates modules/p256/src/wycheproof_kat_vectors.zig from Google/C2SP's
# Wycheproof ECDSA P-256 / SHA-256 vectors in IEEE P1363 (raw r||s) form —
# the encoding `p256.sign.ecdsaVerify` actually takes, so no DER parser sits
# between the fixture and the code under test.
#
#   curl -sSLO https://raw.githubusercontent.com/C2SP/wycheproof/main/\
#testvectors_v1/ecdsa_secp256r1_sha256_p1363_test.json
#   python3 scripts/gen-p256-wycheproof.py ecdsa_secp256r1_sha256_p1363_test.json \
#     > modules/p256/src/wycheproof_kat_vectors.zig
#
# Vectors whose signature is not exactly 64 bytes are dropped: our verifier's
# parameter is `[64]u8`, so a wrong-length signature cannot be handed to it at
# all — the length is enforced by the type, not by the code being tested, and
# a fixture that "passes" on that basis would be measuring the compiler. The
# count of dropped rows is emitted into the header so the omission stays
# visible rather than looking like full coverage.
import json
import sys

data = json.load(open(sys.argv[1]))
rows, dropped = [], 0
for g in data["testGroups"]:
    assert g["sha"] == "SHA-256", g["sha"]
    key = g["publicKey"]["uncompressed"]
    for t in g["tests"]:
        if len(t["sig"]) != 128:
            dropped += 1
            continue
        rows.append((key, t["tcId"], t["msg"], t["sig"], t["result"], t["comment"]))

valid = sum(1 for r in rows if r[4] == "valid")
print("// SPDX-License-Identifier: MIT")
print("// Generated by scripts/gen-p256-wycheproof.py -- see doc comment below.")
print("// Do not hand-edit hex payloads; regenerate instead.")
print()
print("//! Wycheproof ECDSA P-256 / SHA-256 verification vectors, IEEE P1363")
print("//! (raw `r || s`) form, from C2SP/wycheproof `testvectors_v1`")
print("//! (`%s`)." % data.get("algorithm", "ECDSA"))
print("//!")
print("//! %d vectors: %d must verify, %d must not." % (len(rows), valid, len(rows) - valid))
print("//! %d further rows in the upstream file are omitted: their signature is" % dropped)
print("//! not 64 bytes, and `ecdsaVerify` takes a `[64]u8`, so rejecting them is")
print("//! the type system's doing rather than the verifier's -- including them")
print("//! would inflate the count without testing anything.")
print()
print("pub const Vector = struct {")
print("    /// SEC1 uncompressed public key (0x04 || x || y).")
print("    pubkey_hex: []const u8,")
print("    /// Upstream `tcId`, so a failure names the row to look up.")
print("    tc_id: u32,")
print("    msg_hex: []const u8,")
print("    /// `r (32) || s (32)`, big-endian.")
print("    sig_hex: []const u8,")
print("    should_verify: bool,")
print("    comment: []const u8,")
print("};")
print()
print("pub const vectors = [_]Vector{")
for key, tc, msg, sig, result, comment in rows:
    print("    .{")
    print('        .pubkey_hex = "%s",' % key)
    print("        .tc_id = %d," % tc)
    print('        .msg_hex = "%s",' % msg)
    print('        .sig_hex = "%s",' % sig)
    print("        .should_verify = %s," % ("true" if result == "valid" else "false"))
    print('        .comment = "%s",' % comment.replace('"', "'"))
    print("    },")
print("};")
