#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""gen_cavp.py — the recipe behind `src/testdata/cavp_ecb192.zig`.

Reads the six AES-192 ECB response files of NIST's CAVP AESAVS suite and
emits them as a Zig table. Nothing in them is changed: every COUNT of both
[ENCRYPT] and [DECRYPT] sections is carried over, hex verbatim.

Source (US Government work, public domain):
  https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/aes/KAT_AES.zip
    sha256 a203b16c9246b2ebae31dee5de21a606be80cf78ceabaca37150236fa098eb60 (fetched 2026-10-10)
  https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/aes/aesmmt.zip
    sha256 12d1616f7a713e807714055973f04efc402f46a14e3d81869717c7ace4ecbaf0 (fetched 2026-10-10)

Usage (from any directory; the .rsp files are DATA, this script is not
inside their directory):
    mkdir x && unzip KAT_AES.zip -d x && unzip aesmmt.zip -d x
    python3 -I modules/aes192/tools/gen_cavp.py x > modules/aes192/src/testdata/cavp_ecb192.zig

The script refuses a file whose sha256 differs from the one pinned below.
"""

import hashlib
import os
import sys

FILES = {
    "ECBGFSbox192.rsp": "885364c3f424477e5b878b13c4b3ffcf11f4501cb1223cf25d06180915d4f070",
    "ECBKeySbox192.rsp": "3c3f1531fba163287b3deb001cdbf666ebc1fe70afee4a071abbefb8d4544556",
    "ECBVarKey192.rsp": "d94b0fbedab3607bdb22d5fde635915ce5adfd97ae6da4ce136f4b2ad5b0cb6d",
    "ECBVarTxt192.rsp": "ece3fb1795a461127b4c69c8d852ec9323c88acbb037c198376b71b7d888b68f",
    "ECBMMT192.rsp": "fb45f113ad649b6441651f4467196a297649cc74185b8d56ce65a4c0150260e4",
}


def parse(text):
    section = None
    cur = {}
    out = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            if cur and "CIPHERTEXT" in cur and "PLAINTEXT" in cur:
                out.append((section, cur))
                cur = {}
            continue
        if line.startswith("["):
            section = line.strip("[]")
            continue
        k, v = (s.strip() for s in line.split("=", 1))
        cur[k] = v.lower()
    if cur and "CIPHERTEXT" in cur:
        out.append((section, cur))
    return out


def main():
    root = sys.argv[1]
    print("// SPDX-License-Identifier: MIT")
    print("// Generated by modules/aes192/tools/gen_cavp.py from NIST CAVP AESAVS")
    print("// (KAT_AES.zip + aesmmt.zip, AES-192 ECB files). Do not edit by hand.")
    print("// The vectors are a US Government work (public domain).")
    print()
    print("pub const Op = enum { encrypt, decrypt };")
    print()
    print("pub const Vector = struct { file: []const u8, op: Op, count: u16, key: *const [48]u8, pt: []const u8, ct: []const u8 };")
    print()
    print("pub const vectors = [_]Vector{")
    total = 0
    for name, want in FILES.items():
        path = os.path.join(root, name)
        data = open(path, "rb").read()
        got = hashlib.sha256(data).hexdigest()
        if got != want:
            sys.exit(f"{name}: sha256 {got} != pinned {want}")
        for section, v in parse(data.decode("ascii")):
            op = {"ENCRYPT": "encrypt", "DECRYPT": "decrypt"}[section]
            assert len(v["KEY"]) == 48
            assert len(v["PLAINTEXT"]) == len(v["CIPHERTEXT"]) and len(v["PLAINTEXT"]) % 32 == 0
            print(
                f'    .{{ .file = "{name}", .op = .{op}, .count = {int(v["COUNT"])}, '
                f'.key = "{v["KEY"]}", .pt = "{v["PLAINTEXT"]}", .ct = "{v["CIPHERTEXT"]}" }},'
            )
            total += 1
    print("};")
    print()
    print(f"pub const total = {total};")


if __name__ == "__main__":
    main()
