// SPDX-License-Identifier: MIT

//! kat_test — the two DF functions against `kat_vectors.zig`, generated by
//! `tools/rederive.py`: an independent Python re-derivation from the RFC text
//! (RFC 7432 §8.5 mod N, RFC 8584 §3.2 HRW), with CRC-32 from `zlib` rather
//! than `std.hash.Crc32` and unbounded integers rather than wrapping `u32`.
//! Oracle REDERIVED: it catches implementation slips (byte order of the tag,
//! the MSB drop, the tie-break direction, the mod-2^31 shortcut); it does not
//! catch a misreading of the RFC shared with the script. The black-box
//! comparison with FRRouting lives in `tools/frr/`.

const std = @import("std");
const types = @import("types.zig");
const election = @import("election.zig");
const vectors = @import("kat_vectors.zig");

const testing = std.testing;

fn membersOf(addrs: []const u32, buf: []types.Member) []types.Member {
    for (addrs, 0..) |a, i| buf[i] = .{ .node = @intCast(i), .addr = a };
    return buf[0..addrs.len];
}

test "REDERIVED: HRW weights match the Python re-derivation for every (tag, address)" {
    var n: usize = 0;
    for (vectors.cases) |c| for (c.rows) |row| for (c.addrs, row.weights) |addr, w| {
        try testing.expectEqual(w, election.hrwWeight(row.tag, c.esi, addr));
        n += 1;
    };
    try testing.expect(n >= 40);
}

test "REDERIVED: modulo and HRW name the same DF as the Python re-derivation" {
    var buf: [types.max_members]types.Member = undefined;
    for (vectors.cases) |c| {
        const members = membersOf(c.addrs, &buf);
        for (c.rows) |row| {
            const m = election.moduloDf(members, row.tag).?;
            try testing.expectEqual(row.modulo_df, c.addrs[m]);
            const h = election.hrwDf(members, row.tag, c.esi).?;
            try testing.expectEqual(row.hrw_df, c.addrs[h]);
        }
    }
}
