#!/usr/bin/env python3
"""Independent re-derivation of the two DF functions `df-elect` implements.

Recipe (CONVENTIONS.md section 9), run by hand, never by a test:

    python3 modules/df-elect/tools/rederive.py > modules/df-elect/src/kat_vectors.zig

Python 3, standard library only. Written from the RFC text, not from the Zig
source:

  * RFC 7432 section 8.5 step 3: the PE addresses sorted ascending, ordinals
    from 0; the DF for <ES, VLAN V> is the PE with ordinal V mod N.
  * RFC 8584 section 3.2: D(V, Es) = CRC-32 of the 4-octet Ethernet tag
    followed by the 10-octet ESI, network byte order, most significant bit
    discarded; Wrand(V, Es, Si) = (1103515245 * ((1103515245 * Si + 12345)
    XOR D(V, Es)) + 12345) mod 2^31; DF = highest weight, ties to the
    numerically least address.

CRC-32 comes from `zlib.crc32` (the IEEE 802.3 polynomial, reflected, the
CRC the RFC's [HRW1999] reference uses), a separate implementation from Zig's
`std.hash.Crc32`. Arbitrary-precision integers, reduced mod 2^31 only at the
end, so the Zig side's "wrapping u32, masked" shortcut is checked, not
copied.
"""

import zlib

CASES = [
    # (name, esi, [addresses], [tags])
    ("three_pe", bytes([0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x01]),
     [0x0A000003, 0x0A000004, 0x0A000005], [0, 1, 10, 11, 12, 13, 14, 15, 100, 4094]),
    ("two_pe", bytes([0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x02]),
     [0x0A000006, 0x0A000007], [10, 11, 20, 4095]),
    ("five_pe_high_bit", bytes(range(10)),
     [0x0A000001, 0x7FFFFFFF, 0x80000001, 0xC0A80101, 0xFFFFFFFE], [0, 7, 31, 1000, 0xFFFFFFFF]),
    ("one_pe", bytes(10), [0xC0000201], [5]),
]


def digest(tag: int, esi: bytes) -> int:
    stream = tag.to_bytes(4, "big") + esi
    return zlib.crc32(stream) & 0x7FFFFFFF


def weight(tag: int, esi: bytes, addr: int) -> int:
    return (1103515245 * ((1103515245 * addr + 12345) ^ digest(tag, esi)) + 12345) % (1 << 31)


def hrw_df(addrs, tag, esi):
    best = None
    for a in addrs:
        w = weight(tag, esi, a)
        if best is None or w > best[0] or (w == best[0] and a < best[1]):
            best = (w, a)
    return best[1]


def modulo_df(addrs, tag):
    s = sorted(addrs)
    return s[tag % len(s)]


def zbytes(b: bytes) -> str:
    return "&.{ " + ", ".join(f"0x{x:02x}" for x in b) + " }"


def main():
    out = []
    out.append("// SPDX-License-Identifier: MIT")
    out.append("// GENERATED by modules/df-elect/tools/rederive.py -- do not edit.")
    out.append("// Independent re-derivation of RFC 7432 section 8.5 (mod N) and RFC 8584 section 3.2 (HRW).")
    out.append("// zig fmt: off")
    out.append("")
    out.append("pub const Row = struct { tag: u32, modulo_df: u32, hrw_df: u32, weights: []const u32 };")
    out.append("pub const Case = struct { name: []const u8, esi: [10]u8, addrs: []const u32, rows: []const Row };")
    out.append("")
    out.append("pub const cases = [_]Case{")
    for name, esi, addrs, tags in CASES:
        out.append(f'    .{{ .name = "{name}", .esi = .{{ ' + ", ".join(f"0x{x:02x}" for x in esi) + " },")
        out.append("        .addrs = &.{ " + ", ".join(f"0x{a:08x}" for a in addrs) + " },")
        out.append("        .rows = &.{")
        for t in tags:
            ws = ", ".join(str(weight(t, esi, a)) for a in addrs)
            out.append(f"            .{{ .tag = {t}, .modulo_df = 0x{modulo_df(addrs, t):08x}, .hrw_df = 0x{hrw_df(addrs, t, esi):08x}, .weights = &.{{ {ws} }} }},")
        out.append("        },")
        out.append("    },")
    out.append("};")
    print("\n".join(out))


if __name__ == "__main__":
    main()
