// SPDX-License-Identifier: MIT
// GENERATED by modules/metrics/tools/go_oracle (register; client_golang v1.24.1, prometheus/common v0.71.0, prometheus v0.315.0, go1.26.0) -- do not hand-edit.
//! Registration sequences and client_golang's verdict on each call, replayed by `go_register_test.zig`.

const std = @import("std");

pub const Kind = enum { counter, gauge, histogram };
pub const Label = struct { name: []const u8, value: []const u8 };
/// `go`: client_golang's reason for refusing (empty: it accepted, the scrape included). `want`: what
/// the module's get-or-register must do; `class` names the rule in go_oracle/register.go that decided
/// it when it is not client_golang's verdict.
pub const Op = struct { kind: Kind, name: []const u8, help: []const u8, labels: []const Label, buckets: []const f64, go: []const u8, want: bool, class: []const u8 };

pub const classes = [_][]const u8{ "TOO_MANY_LABELS", "BUCKETS_DIFFER", "NONFINITE_BUCKET", "LABEL_ORDER", "EMPTY_BUCKETS" };

pub const cases = [_][]const Op{
    &.{
        .{ .kind = .counter, .name = "a", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "a1", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "_a", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = ":a", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "a:b", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "__a", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "1a", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "legacy: invalid metric name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "a-b", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "legacy: invalid metric name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "a.b", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "legacy: invalid metric name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "\xc3\xa9", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "legacy: invalid metric name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "legacy: invalid metric name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "a b", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "legacy: invalid metric name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "A_Z09", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "v" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "_a", .value = "v" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "_a", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a1", .value = "v" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "a1", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "A", .value = "v" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "A", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "__a", .value = "v" }}, .buckets = &.{}, .go = "register: descriptor Desc{fqName: \"m\", help: \"h\", unit: \"\", constLabels: {}, variableLabels: {__a}} is invalid: \"__a\" is...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "__a", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "register: descriptor Desc{fqName: \"m\", help: \"h\", unit: \"\", constLabels: {}, variableLabels: {__a}} is invalid: \"__a\" is...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "__", .value = "v" }}, .buckets = &.{}, .go = "register: descriptor Desc{fqName: \"m\", help: \"h\", unit: \"\", constLabels: {}, variableLabels: {__}} is invalid: \"__\" is n...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "__", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "register: descriptor Desc{fqName: \"m\", help: \"h\", unit: \"\", constLabels: {}, variableLabels: {__}} is invalid: \"__\" is n...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "1a", .value = "v" }}, .buckets = &.{}, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "1a", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a:b", .value = "v" }}, .buckets = &.{}, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "a:b", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a-b", .value = "v" }}, .buckets = &.{}, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "a-b", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "\xc3\xa9", .value = "v" }}, .buckets = &.{}, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "\xc3\xa9", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "", .value = "v" }}, .buckets = &.{}, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "legacy: invalid label name", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "le", .value = "v" }}, .buckets = &.{}, .go = "panic: strconv.ParseFloat: parsing \"v\": invalid syntax", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "le", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "panic: \"le\" is not allowed as label name in histograms", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "quantile", .value = "v" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "quantile", .value = "v" }}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .gauge, .name = "m", .help = "h", .labels = &.{.{ .name = "quantile", .value = "v" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .gauge, .name = "m", .help = "h", .labels = &.{.{ .name = "le", .value = "v" }}, .buckets = &.{}, .go = "panic: strconv.ParseFloat: parsing \"v\": invalid syntax", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{ .{ .name = "a", .value = "1" }, .{ .name = "a", .value = "2" } }, .buckets = &.{}, .go = "register: descriptor Desc{fqName: \"m\", help: \"h\", unit: \"\", constLabels: {}, variableLabels: {a,a}} is invalid: duplicat...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{ .{ .name = "a", .value = "1" }, .{ .name = "b", .value = "2" }, .{ .name = "a", .value = "3" } }, .buckets = &.{}, .go = "register: descriptor Desc{fqName: \"m\", help: \"h\", unit: \"\", constLabels: {}, variableLabels: {a,b,a}} is invalid: duplic...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{ .{ .name = "l0", .value = "v" }, .{ .name = "l1", .value = "v" }, .{ .name = "l2", .value = "v" }, .{ .name = "l3", .value = "v" }, .{ .name = "l4", .value = "v" }, .{ .name = "l5", .value = "v" }, .{ .name = "l6", .value = "v" }, .{ .name = "l7", .value = "v" }, .{ .name = "l8", .value = "v" } }, .buckets = &.{}, .go = "", .want = false, .class = "TOO_MANY_LABELS" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{ .{ .name = "l0", .value = "v" }, .{ .name = "l1", .value = "v" }, .{ .name = "l2", .value = "v" }, .{ .name = "l3", .value = "v" }, .{ .name = "l4", .value = "v" }, .{ .name = "l5", .value = "v" }, .{ .name = "l6", .value = "v" }, .{ .name = "l7", .value = "v" } }, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "\xff" }}, .buckets = &.{}, .go = "panic: label value \"\\xff\" is not valid UTF-8", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "\xff", .labels = &.{}, .buckets = &.{}, .go = "scrape: help text \"\\xff\" is not a valid utf8 string", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "1" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "1" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "2" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "m", .help = "other", .labels = &.{}, .buckets = &.{}, .go = "register: a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"m\", help: \"other\", unit...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "1" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "b", .value = "1" }}, .buckets = &.{}, .go = "register: a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"m\", help: \"h\", unit: \"\"...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "1" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "register: a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"m\", help: \"h\", unit: \"\"...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{ .{ .name = "a", .value = "1" }, .{ .name = "b", .value = "2" } }, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{ .{ .name = "b", .value = "2" }, .{ .name = "a", .value = "1" } }, .buckets = &.{}, .go = "", .want = false, .class = "LABEL_ORDER" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "1" }}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{ .{ .name = "a", .value = "1" }, .{ .name = "b", .value = "2" } }, .buckets = &.{}, .go = "register: a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"m\", help: \"h\", unit: \"\"...", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "m", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .gauge, .name = "m", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "register: duplicate metrics collector registration attempted", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .gauge, .name = "m", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "register: duplicate metrics collector registration attempted", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 3.0 }, .go = "", .want = false, .class = "BUCKETS_DIFFER" },
    },
    &.{
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "1" }}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
        .{ .kind = .histogram, .name = "m", .help = "h", .labels = &.{.{ .name = "a", .value = "2" }}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "h_bucket", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "gather: collected metric named \"h_bucket\" collides with previously collected histogram named \"h\"", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .gauge, .name = "h_bucket", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "gather: collected histogram named \"h\" collides with previously collected metric named \"h_bucket\"", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "h_bucket", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "h_sum", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "gather: collected metric named \"h_sum\" collides with previously collected histogram named \"h\"", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .gauge, .name = "h_sum", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "gather: collected histogram or summary named \"h\" collides with previously collected metric named \"h_sum\"", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "h_sum", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "h_count", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "gather: collected histogram or summary named \"h\" collides with previously collected metric named \"h_count\"", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .gauge, .name = "h_count", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "gather: collected histogram or summary named \"h\" collides with previously collected metric named \"h_count\"", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .counter, .name = "h_count", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
        .{ .kind = .histogram, .name = "h_bucket", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "gather: collected metric named \"h_bucket\" collides with previously collected histogram named \"h\"", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 2.0 }, .go = "", .want = true, .class = "" },
        .{ .kind = .counter, .name = "h_total", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{}, .go = "", .want = true, .class = "EMPTY_BUCKETS" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{1.0}, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ -1.0, 0.0, 1.0 }, .go = "", .want = true, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, 1.0 }, .go = "panic: histogram buckets must be in increasing order: 1.000000 >= 1.000000", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 2.0, 1.0 }, .go = "panic: histogram buckets must be in increasing order: 2.000000 >= 1.000000", .want = false, .class = "" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, std.math.inf(f64) }, .go = "", .want = false, .class = "NONFINITE_BUCKET" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ -std.math.inf(f64), 1.0 }, .go = "", .want = false, .class = "NONFINITE_BUCKET" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{std.math.nan(f64)}, .go = "", .want = false, .class = "NONFINITE_BUCKET" },
    },
    &.{
        .{ .kind = .histogram, .name = "h", .help = "h", .labels = &.{}, .buckets = &.{ 1.0, std.math.nan(f64) }, .go = "", .want = false, .class = "NONFINITE_BUCKET" },
    },
};
