#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""libpsl (the Public Suffix List C library, MIT) as a black-box oracle for
modules/cookies/src/psl.zig. Only its observable answers are used.

  psl_oracle.py vectors > ../src/psl_vectors.zig   # libpsl over ../src/psl_mini.dat
  psl_oracle.py check LIST IN OUT                  # one answer line per domain of IN

An answer line is `domain<TAB>public-suffix<TAB>registrable-or-->`.
Needs libpsl.so.5 (Debian/Ubuntu: libpsl5t64).
"""
import ctypes
import os
import sys

lib = ctypes.CDLL("libpsl.so.5")
lib.psl_load_file.restype = ctypes.c_void_p
lib.psl_load_file.argtypes = [ctypes.c_char_p]
lib.psl_unregistrable_domain.restype = ctypes.c_char_p
lib.psl_unregistrable_domain.argtypes = [ctypes.c_void_p, ctypes.c_char_p]
lib.psl_registrable_domain.restype = ctypes.c_char_p
lib.psl_registrable_domain.argtypes = [ctypes.c_void_p, ctypes.c_char_p]


def answer(ctx, domain):
    d = domain.encode()
    ps = lib.psl_unregistrable_domain(ctx, d)
    reg = lib.psl_registrable_domain(ctx, d)
    return (ps.decode() if ps is not None else "?"), (reg.decode() if reg is not None else "-")


# Hosts as a client sees them: lowercase ASCII, IDN already punycoded.
DOMAINS = [
    "com", "example.com", "a.b.example.com",
    "example", "x.example",
    "uk", "co.uk", "bank.co.uk", "www.bank.co.uk", "gov.uk", "a.gov.uk", "notco.uk",
    "jp", "kobe.jp", "x.kobe.jp", "a.x.kobe.jp", "city.kobe.jp", "a.city.kobe.jp",
    "ck", "foo.ck", "a.foo.ck", "www.ck", "a.www.ck",
    "wild.example", "a.wild.example", "b.a.wild.example", "keep.wild.example", "a.keep.wild.example",
    "deep.a.b.example", "x.deep.a.b.example", "a.b.example", "b.example",
    "github.io", "me.github.io", "a.me.github.io", "io",
    "cn", "xn--55qx5d.cn", "shop.xn--55qx5d.cn", "a.shop.xn--55qx5d.cn",
    "xn--p1ai", "xn--d1acufc.xn--p1ai",
    "xn--bcher-kva.example", "store.xn--bcher-kva.example",
    "test", "a.test", "a.b.test", "localhost",
]


def zig_str(s):
    out = []
    for ch in s.encode():
        if ch in (0x22, 0x5C):
            out.append("\\" + chr(ch))
        elif 0x20 <= ch < 0x7F:
            out.append(chr(ch))
        else:
            out.append("\\x%02x" % ch)
    return '"' + "".join(out) + '"'


def vectors():
    here = os.path.dirname(os.path.abspath(__file__))
    ctx = lib.psl_load_file(os.path.join(here, "..", "src", "psl_mini.dat").encode())
    if not ctx:
        sys.exit("libpsl could not load psl_mini.dat")
    print("// SPDX-License-Identifier: MIT")
    print("// GENERATED by modules/cookies/tools/psl_oracle.py (libpsl over src/psl_mini.dat) -- do not hand-edit.")
    print("//! Replayed by `psl_oracle.zig`.")
    print()
    print('pub const list = @embedFile("psl_mini.dat");')
    print()
    print("pub const Case = struct { host: []const u8, public_suffix: []const u8, registrable: ?[]const u8 };")
    print()
    print("pub const cases = [_]Case{")
    for d in DOMAINS:
        ps, reg = answer(ctx, d)
        print("    .{ .host = %s, .public_suffix = %s, .registrable = %s }," % (zig_str(d), zig_str(ps), "null" if reg == "-" else zig_str(reg)))
    print("};")


def check(path, in_path, out_path):
    ctx = lib.psl_load_file(path.encode())
    if not ctx:
        sys.exit("libpsl could not load " + path)
    with open(in_path) as inp, open(out_path, "w") as out:
        for line in inp:
            d = line.strip()
            if d:
                ps, reg = answer(ctx, d)
                out.write("%s\t%s\t%s\n" % (d, ps, reg))


if __name__ == "__main__":
    if sys.argv[1:] == ["vectors"]:
        vectors()
    elif len(sys.argv) == 5 and sys.argv[1] == "check":
        check(sys.argv[2], sys.argv[3], sys.argv[4])
    else:
        sys.exit(__doc__)
