#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Recipe for `src/testdata/kernel_families.zig`: real `CTRL_CMD_GETFAMILY`
exchanges with the running kernel's generic-netlink controller, for families
with SEVERAL multicast groups (the existing nlctrl capture in `root.zig` has
one), and for a family that does not exist.

    python3 modules/genetlink/tools/families_capture.py | zig fmt --stdin > modules/genetlink/src/testdata/kernel_families.zig

Unprivileged. Python's own socket and struct do the talking and the decoding,
independently of this module: each request is the shape `buildGetFamilyRequest`
emits (REQUEST|ACK, seq 1), every datagram the kernel answers with is frozen
as hex, and the expected family id and group ids are decoded here from the
same bytes, so the replay in `root.zig` checks this module's parser against a
second decoder and against the kernel's own encoding. Families the running
kernel lacks are left out and named in the header.
"""
import socket
import struct
import sys

FAMILIES = ["netdev", "nl80211", "thermal", "mptcp_pm", "zig-libs-nope"]
NLMSG_ERROR = 2


def attrs(b):
    o = 0
    while o + 4 <= len(b):
        ln, t = struct.unpack_from("=HH", b, o)
        if ln < 4:
            return
        yield t & 0x3FFF, b[o + 4:o + ln]
        o += (ln + 3) & ~3


def request(name):
    nm = name.encode() + b"\0"
    attr = struct.pack("=HH", 4 + len(nm), 2) + nm
    attr += b"\0" * (((len(attr) + 3) & ~3) - len(attr))
    body = struct.pack("=BBH", 3, 1, 0) + attr
    return struct.pack("=IHHII", 16 + len(body), 0x10, 0x05, 1, 0) + body


def exchange(name):
    s = socket.socket(socket.AF_NETLINK, socket.SOCK_RAW, 16)
    s.bind((0, 0))
    pid = s.getsockname()[0]
    s.send(request(name))
    dgrams = []
    while True:
        d = s.recv(65536)
        dgrams.append(d)
        o, acked = 0, False
        while o < len(d):
            ln, t = struct.unpack_from("=IH", d, o)
            if t == NLMSG_ERROR:
                acked = True
            o += (ln + 3) & ~3
        if acked:
            s.close()
            return pid, dgrams


def decode(dgrams):
    """(errno, family id, [(group, id)]) from the kernel's datagrams."""
    err, fid, groups = 0, None, []
    for d in dgrams:
        o = 0
        while o < len(d):
            ln, t = struct.unpack_from("=IH", d, o)
            body = d[o + 16:o + ln]
            if t == NLMSG_ERROR:
                err = -struct.unpack_from("=i", body)[0]
            elif t == 0x10:
                for at, av in attrs(body[4:]):
                    if at == 1:
                        fid = struct.unpack_from("=H", av)[0]
                    if at == 7:
                        for _, g in attrs(av):
                            kv = dict(attrs(g))
                            groups.append((kv[1].rstrip(b"\0").decode(), struct.unpack_from("=I", kv[2])[0]))
            o += (ln + 3) & ~3
    return err, fid, groups


def main():
    rows, absent = [], []
    for name in FAMILIES:
        pid, dgrams = exchange(name)
        err, fid, groups = decode(dgrams)
        if name != "zig-libs-nope" and err:
            absent.append(name)
            continue
        rows.append((name, pid, dgrams, err, fid, groups))
    o = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by modules/genetlink/tools/families_capture.py: real CTRL_CMD_GETFAMILY",
        "// exchanges with the kernel's generic-netlink controller, decoded independently by",
        "// the generator. Replayed by root.zig. Do not edit by hand.",
        f"// Not present on the capturing kernel, so not recorded: {', '.join(absent) or 'none'}.",
        "",
        "pub const Group = struct { name: []const u8, id: u32 };",
        "pub const Exchange = struct { family: []const u8, pid: u32, datagrams: []const []const u8, errno: u32, id: ?u16, groups: []const Group };",
        "",
        "pub const exchanges = [_]Exchange{",
    ]
    for name, pid, dgrams, err, fid, groups in rows:
        ds = ", ".join(f'"{d.hex()}"' for d in dgrams)
        gs = ", ".join(f'.{{ .name = "{g}", .id = {i} }}' for g, i in groups)
        o.append(f'    .{{ .family = "{name}", .pid = {pid}, .datagrams = &.{{{ds}}}, .errno = {err}, .id = {"null" if fid is None else fid}, .groups = &.{{{gs}}} }},')
    o.append("};")
    sys.stdout.write("\n".join(o) + "\n")


if __name__ == "__main__":
    main()
