// SPDX-License-Identifier: MIT
//! Noise_IKpsk2 handshake — the WireGuard cryptographic session handshake:
//! message wire layouts (`MessageInitiation`/`MessageResponse`/`CookieReply`/
//! `MessageTransport`) and the `Handshake` state machine that produces and
//! consumes them, ending in a split pair of transport data-plane keys.
//! Plus the cookie/mac2 layer (whitepaper 5.4.7): `CookieChecker.admit` is
//! the responder's cheap under-load gate in FRONT of that state machine, and
//! `PeerCookie` the initiator's side of the same round trip.
//!
//! This is the DATA-PLANE crypto handshake — distinct from (and independent
//! of) `../src/root.zig` (plus the `genetlink` module it builds on), which
//! speak the kernel's genetlink CONTROL-plane protocol (`wg`-style
//! device/peer configuration).
//! A handshake never touches netlink; a configured `Wireguard` device never
//! touches Noise. Both live under the one `wireguard` module because they
//! are the same protocol's two halves.
//!
//! Verification: a fixed-input known-answer test (deterministic static +
//! ephemeral keys, PSK, timestamp and indices) asserts the exact 148-byte
//! `MessageInitiation`, 92-byte `MessageResponse` and both transport keys
//! against a vector generated by an independent reference implementation
//! (Python: hashlib BLAKE2s/HMAC + OpenSSL X25519/ChaCha20-Poly1305 via
//! cryptography.io), itself validated against the wireguard-go KDF vectors
//! (no official full-handshake vector is published by the WireGuard
//! project). A gated integration test additionally completes a live
//! handshake as responder against the Linux kernel's WireGuard
//! implementation and decrypts a kernel-encrypted transport packet with the
//! derived keys. See `noise.zig` for the Noise primitives this state
//! machine is built on.
//!
//! Provenance: clean-room from the WireGuard protocol description
//! (J. A. Donenfeld, "WireGuard: Next Generation Kernel Network Tunnel",
//! NDSS 2017, https://www.wireguard.com/papers/wireguard.pdf, and
//! https://www.wireguard.com/protocol/), which documents the exact message
//! layouts and handshake steps reserved below. Design reference:
//! wireguard-go (golang.zx2c4.com/wireguard, MIT) and the Linux kernel
//! WireGuard implementation (GPL-2.0) — behavior/shape only; the message
//! layout and handshake step order are the standardized wire protocol, not
//! copyrightable expression; no source consulted or copied. See ../NOTICE.

const std = @import("std");
const builtin = @import("builtin");
const entropy = @import("entropy");
const noise = @import("noise.zig");
/// The transport-data (type 4) seal/open data plane the completed handshake
/// keys. Imported one way only — `transport.zig` knows nothing about the
/// handshake, so it stays usable with keys from any source.
const transport = @import("transport.zig");

comptime {
    // The mac1/mac2 computations and the KAT/interop tests view the extern
    // structs below as wire bytes via `std.mem.asBytes`, which is byte-exact
    // only on a little-endian host. Fail the build rather than silently emit
    // byte-swapped handshakes; `@compileError` instead of `assert` so the
    // message says what is wrong and how to fix it, not "reached unreachable
    // code".
    if (builtin.cpu.arch.endian() != .little) @compileError(
        "wireguard/handshake.zig assumes a little-endian host: WireGuard's wire " ++
            "integers are little-endian and this file views its `extern struct`s " ++
            "as wire bytes via `std.mem.asBytes`. To build for a big-endian " ++
            "target, first encode/decode the u32/u64 fields explicitly with " ++
            "`std.mem.writeInt`/`readInt` and `.little` (as `root.zig`'s " ++
            "`parseEndpoint`/`appendEndpoint` already do), then lift this guard.",
    );
}

// Note: `pub const meta` is declared once, canonically, in `root.zig` (per
// CONVENTIONS.md §4) — submodule files like this one do not repeat it. This
// file itself has no dependency on `netlink`/`genetlink` (those are the
// sibling control-plane half of the module, in root.zig).

// ── message type tag (first 4 bytes of every WireGuard wire message) ───────

/// `message_type` values — the little-endian `u32` at offset 0 of every
/// WireGuard wire message, used to dispatch an incoming UDP datagram.
pub const MessageType = enum(u32) {
    handshake_initiation = 1,
    handshake_response = 2,
    cookie_reply = 3,
    transport_data = 4,
    _,
};

// ── key types ───────────────────────────────────────────────────────────────

/// Raw X25519 scalar (private/secret key), 32 bytes.
pub const PrivateKey = [noise.X25519.secret_length]u8;
/// Raw X25519 point (public key), 32 bytes.
pub const PublicKey = [noise.X25519.public_length]u8;
/// Pre-shared symmetric key mixed into message 2 (psk2), 32 bytes. All-zero
/// is the WireGuard convention for "no PSK configured" (mixed in anyway —
/// mixing a fixed zero key is a no-op that keeps the code path uniform).
pub const PresharedKey = [32]u8;

/// A static or ephemeral X25519 identity.
pub const Keypair = struct {
    private: PrivateKey,
    public: PublicKey,

    /// Generate a fresh keypair (used for the per-handshake ephemeral).
    /// `io` supplies entropy, matching the `sealedbox` module's convention
    /// for std.crypto operations that need randomness.
    pub fn generate(io: std.Io) Keypair {
        const kp = noise.X25519.KeyPair.generate(io);
        return .{ .private = kp.secret_key, .public = kp.public_key };
    }

    /// Rebuild a keypair from a stored private key (recomputes the public
    /// key via X25519 base-point multiplication).
    pub fn fromPrivateKey(private: PrivateKey) error{IdentityElement}!Keypair {
        return .{ .private = private, .public = try noise.X25519.recoverPublicKey(private) };
    }
};

// ── wire message layouts (WireGuard protocol, byte-exact) ──────────────────
//
// Endianness: WireGuard's wire integers are little-endian, and these are
// `extern struct`s whose in-memory layout matches the wire byte-for-byte only
// on a little-endian host. That is enforced by the `comptime` guard at the top
// of this file, which fails the build on a big-endian target with an
// explanation — verified to fire by cross-compiling for s390x-linux. Lifting
// it means encoding the `u32`/`u64` fields explicitly with
// `std.mem.readInt`/`writeInt` and `.little`, the way `root.zig`'s
// `parseEndpoint`/`appendEndpoint` do. Field order below is chosen so no
// implicit padding is inserted (every multi-byte integer field already falls
// on a naturally aligned offset).

/// Type 1 — Initiator → Responder. 148 bytes on the wire.
pub const MessageInitiation = extern struct {
    /// `MessageType.handshake_initiation` (1), little-endian.
    type: u32,
    /// Locally assigned session index; echoed back by the responder as
    /// `receiver_index` in `MessageResponse`.
    sender_index: u32,
    /// The initiator's ephemeral public key, sent in the clear.
    unencrypted_ephemeral: [32]u8,
    /// `AEAD(k, 0, initiator_static_public, Hi)` — the initiator's static
    /// public key, encrypted+authenticated (32-byte key + 16-byte Poly1305 tag).
    encrypted_static: [32 + 16]u8,
    /// `AEAD(k, 0, TAI64N(now), Hi)` — a TAI64N timestamp, encrypted (12-byte
    /// TAI64N label + 16-byte tag), used for replay/most-recent-handshake
    /// detection.
    encrypted_timestamp: [12 + 16]u8,
    /// `MAC(mac1_key, message[0 .. end-32])` — cheap DoS-resistant check;
    /// always present.
    mac1: [16]u8,
    /// `MAC(cookie, message[0 .. end-16])` if a valid responder cookie is
    /// held, else all-zero.
    mac2: [16]u8,
};

/// Type 2 — Responder → Initiator. 92 bytes on the wire.
pub const MessageResponse = extern struct {
    /// `MessageType.handshake_response` (2), little-endian.
    type: u32,
    /// The responder's own newly assigned session index.
    sender_index: u32,
    /// Echo of the initiator's `sender_index` (`MessageInitiation.sender_index`).
    receiver_index: u32,
    /// The responder's ephemeral public key, sent in the clear.
    unencrypted_ephemeral: [32]u8,
    /// `AEAD(k, 0, ε, Hr)` — an empty-plaintext AEAD, just a 16-byte
    /// Poly1305 tag; confirms both sides agree on every derived key so far.
    encrypted_nothing: [0 + 16]u8,
    /// `MAC(mac1_key, message[0 .. end-32])`.
    mac1: [16]u8,
    /// `MAC(cookie, message[0 .. end-16])` if held, else all-zero.
    mac2: [16]u8,
};

/// Type 3 — either side → the other, only ever sent in reply to a message
/// whose mac2 the receiver could not validate against its current cookie
/// (i.e. under load, as an unforgeable "here is a fresh cookie" nudge).
/// **Not part of the Noise transcript** — no chaining-key/hash mixing;
/// authenticated instead by XChaCha20-Poly1305 keyed with the sender's own
/// mac1 key and a random 24-byte nonce (so it needs no handshake state).
/// 64 bytes on the wire.
pub const CookieReply = extern struct {
    /// `MessageType.cookie_reply` (3), little-endian.
    type: u32,
    /// Echoes the `sender_index` of the message being replied to.
    receiver_index: u32,
    /// Random nonce for the `XAead` encryption below (`noise.XAead.nonce_length`).
    nonce: [24]u8,
    /// `XAEAD(cookie_key, nonce, cookie, mac1_of_replied_message)` — a fresh
    /// 16-byte cookie plus its 16-byte Poly1305 tag.
    encrypted_cookie: [16 + 16]u8,
};

/// Fixed header of type 4 (transport data) messages — 16 bytes, followed by
/// a variable-length AEAD ciphertext (plaintext IP packet + 16-byte
/// Poly1305 tag), which is why this is a header-only type rather than a
/// fixed-size `extern struct` like the handshake messages.
pub const MessageTransportHeader = extern struct {
    /// `MessageType.transport_data` (4), little-endian.
    type: u32,
    /// The receiver's session index (theirs, learned during the handshake).
    receiver_index: u32,
    /// Monotonic nonce counter, doubling as the low 8 bytes of the AEAD
    /// nonce (the high 4 bytes are always zero, per the Noise/WireGuard
    /// convention of a 12-byte nonce = 4 zero bytes || 8-byte LE counter).
    counter: u64,
};

/// A full transport-data message: fixed header plus a caller-owned
/// ciphertext slice. Not an `extern struct` (variable length).
pub const MessageTransport = struct {
    header: MessageTransportHeader,
    /// `AEAD(T_send, counter, plaintext_packet, ε)` — ciphertext + 16-byte tag.
    ciphertext: []const u8,
};

comptime {
    // Byte-exact wire sizes (WireGuard protocol) — guards against accidental
    // padding if a field is ever reordered.
    std.debug.assert(@sizeOf(MessageInitiation) == 148);
    std.debug.assert(@sizeOf(MessageResponse) == 92);
    std.debug.assert(@sizeOf(CookieReply) == 64);
    std.debug.assert(@sizeOf(MessageTransportHeader) == 16);
}

// ── handshake state machine ─────────────────────────────────────────────────

/// One in-flight Noise_IKpsk2 handshake attempt (initiator or responder
/// side — the same struct plays both roles depending which method is
/// called first). Single-owner: one `Handshake` per session attempt, not
/// shared across threads.
pub const Handshake = struct {
    /// Our long-term (static) identity keypair.
    static_keypair: Keypair,
    /// The peer's long-term public key — known ahead of time (Noise `IK`:
    /// the initiator already knows the responder's static key).
    remote_static_public: PublicKey,
    /// Pre-shared key (psk2 — mixed in message 2). All-zero if unconfigured.
    preshared_key: PresharedKey = @splat(0),

    /// Our ephemeral keypair for this attempt, generated on the first step
    /// we take (`createInitiation` for the initiator, `createResponse` for
    /// the responder).
    local_ephemeral: ?Keypair = null,
    /// The peer's ephemeral public key, learned from their message.
    remote_ephemeral: ?PublicKey = null,

    /// Noise chaining key `ck` — the running KDF ratchet state.
    chaining_key: noise.ChainKey = undefined,
    /// Noise transcript hash `h`.
    hash: noise.HandshakeHash = undefined,

    /// Our locally assigned session index (goes out as `sender_index` on
    /// our own messages).
    local_index: u32 = 0,
    /// The peer's session index, learned from their message (goes out as
    /// `receiver_index` on our replies / all transport packets to them).
    remote_index: u32 = 0,

    /// The cookie most recently learned from this peer's `CookieReply`, or
    /// null when we hold none that is still fresh — which is the normal
    /// steady state, since cookies only ever appear when the peer is under
    /// load. Set it from `PeerCookie.current(now_s)` before
    /// `createInitiation`/`createResponse`: non-null stamps a real `mac2`
    /// into the message we build, null stamps the protocol's all-zero mac2.
    /// Kept as a plain value (not a `*PeerCookie`) so this struct stays
    /// clock-free — freshness is `PeerCookie`'s job.
    cookie: ?noise.Mac = null,

    /// The initiator's decrypted TAI64N timestamp, recorded by
    /// `consumeInitiation` so the caller can do the required per-peer
    /// most-recent-handshake bookkeeping (this module keeps no cross-attempt
    /// state, so it cannot reject `StaleTimestamp` itself).
    remote_timestamp: ?[12]u8 = null,

    /// Which step this attempt has completed — enforces the call order
    /// (`createInitiation` → `consumeResponse` for the initiator,
    /// `consumeInitiation` → `createResponse` for the responder).
    state: enum { idle, initiation_sent, initiation_consumed, complete } = .idle,

    pub const InitiationError = error{
        /// `local_ephemeral`/`chaining_key` already set — call once per attempt.
        AlreadyStarted,
        /// `remote_static_public` is a low-order/identity X25519 point.
        InvalidPublicKey,
    };
    pub const ConsumeInitiationError = error{
        /// mac1 did not match `HASH(LABEL_MAC1 || our_static_public)`.
        InvalidMac1,
        /// The encrypted static key or timestamp failed AEAD authentication
        /// (or the peer's ephemeral/static key was a low-order X25519 point
        /// — fail closed, indistinguishably from a bad tag).
        DecryptionFailed,
        /// Decrypted static key does not match a known peer (caller-side
        /// peer lookup failed before/while calling this).
        UnknownPeer,
        /// Timestamp is not newer than the last one seen from this peer
        /// (replay / out-of-order handshake rejection). Never returned here
        /// — reserved for callers doing the cross-attempt bookkeeping over
        /// `remote_timestamp` (see that field).
        StaleTimestamp,
    };
    pub const ResponseError = error{
        /// A response was already created for this attempt.
        AlreadyStarted,
        /// `consumeInitiation` has not succeeded on this handshake yet.
        NoInitiationConsumed,
        /// A peer key is a low-order/identity X25519 point.
        InvalidPublicKey,
    };
    pub const ConsumeResponseError = error{
        InvalidMac1,
        /// The empty-plaintext AEAD tag failed to verify (also covers a
        /// low-order ephemeral from the peer and a PSK mismatch — all
        /// indistinguishable by design).
        DecryptionFailed,
        /// This handshake never sent a `MessageInitiation` to respond to.
        NoPendingInitiation,
    };

    /// `Ck0/H0` derivation shared by both roles (whitepaper 5.4.2 first
    /// three lines): `ck = HASH(CONSTRUCTION)`, `h = HASH(ck || IDENTIFIER)`,
    /// `h = HASH(h || responder_static_public)`.
    fn initialState(responder_static_public: PublicKey) struct { ck: noise.ChainKey, h: noise.HandshakeHash } {
        var ck: noise.ChainKey = undefined;
        noise.Blake2s.hash(noise.CONSTRUCTION, &ck, .{});
        var h: noise.HandshakeHash = ck;
        noise.mixHash(&h, noise.IDENTIFIER);
        noise.mixHash(&h, &responder_static_public);
        return .{ .ck = ck, .h = h };
    }

    /// The 12-byte AEAD nonce for a 64-bit counter: 4 zero bytes followed by
    /// the counter, little-endian (whitepaper 5.4.6). Handshake messages
    /// always use counter 0 — which is why the handshake KATs below cannot
    /// detect an endianness error here and `transport.zig` pins the layout
    /// against fixed bytes. ONE definition, shared with the data plane, so
    /// that pinning covers this call site too.
    const counterNonce = transport.counterNonce;

    /// Initiator step 1: derive `Ci`/`Hi` from `noise.CONSTRUCTION` +
    /// `noise.IDENTIFIER` + `remote_static_public`, generate an ephemeral
    /// keypair, and produce the encrypted static-key + timestamp message.
    /// `io` supplies entropy for the ephemeral keypair; `now_tai64n` is the
    /// caller-supplied current TAI64N timestamp (12 bytes) — kept out of
    /// this module so it stays platform-agnostic (no clock syscalls here,
    /// consistent with the rest of `wireguard` treating wire codecs as pure
    /// functions over bytes).
    /// (A pre-seeded `local_ephemeral` is used instead of generating one —
    /// deterministic-test hook; leave it null in production.)
    pub fn createInitiation(
        self: *Handshake,
        io: std.Io,
        now_tai64n: [12]u8,
    ) InitiationError!MessageInitiation {
        if (self.state != .idle) return error.AlreadyStarted;
        const eph = self.local_ephemeral orelse Keypair.generate(io);
        self.local_ephemeral = eph;

        var st = initialState(self.remote_static_public);
        var msg: MessageInitiation = undefined;
        msg.type = @intFromEnum(MessageType.handshake_initiation);
        msg.sender_index = self.local_index;

        // e: ephemeral in the clear, mixed into ck and h.
        msg.unencrypted_ephemeral = eph.public;
        noise.kdf1(&st.ck, &eph.public);
        noise.mixHash(&st.h, &eph.public);

        // es: DH(Ei, Sr) → key for the encrypted static.
        var es = noise.X25519.scalarmult(eph.private, self.remote_static_public) catch
            return error.InvalidPublicKey;
        var k = noise.mixKey(&st.ck, &es);
        std.crypto.secureZero(u8, &es);
        noise.Aead.encrypt(
            msg.encrypted_static[0..32],
            msg.encrypted_static[32..48],
            &self.static_keypair.public,
            &st.h,
            counterNonce(0),
            k,
        );
        noise.mixHash(&st.h, &msg.encrypted_static);

        // ss: DH(Si, Sr) → key for the encrypted timestamp.
        var ss = noise.X25519.scalarmult(self.static_keypair.private, self.remote_static_public) catch
            return error.InvalidPublicKey;
        k = noise.mixKey(&st.ck, &ss);
        std.crypto.secureZero(u8, &ss);
        noise.Aead.encrypt(
            msg.encrypted_timestamp[0..12],
            msg.encrypted_timestamp[12..28],
            &now_tai64n,
            &st.h,
            counterNonce(0),
            k,
        );
        std.crypto.secureZero(u8, &k);
        noise.mixHash(&st.h, &msg.encrypted_timestamp);

        self.chaining_key = st.ck;
        self.hash = st.h;
        std.crypto.secureZero(u8, &st.ck);

        msg.mac1 = self.computeMac1(std.mem.asBytes(&msg)[0..@offsetOf(MessageInitiation, "mac1")]);
        msg.mac2 = self.stampMac2(std.mem.asBytes(&msg)[0..@offsetOf(MessageInitiation, "mac2")]);
        self.state = .initiation_sent;
        return msg;
    }

    /// Responder validates an incoming `MessageInitiation`: checks mac1,
    /// replays the initiator's transcript to decrypt+authenticate the
    /// static key and timestamp, and (on success) records the peer's
    /// ephemeral public key and session index so `createResponse` can reply.
    /// The caller is responsible for looking up which configured peer
    /// `remote_static_public` (decrypted here) belongs to, and for
    /// last-handshake/timestamp bookkeeping across repeated attempts.
    ///
    /// This is the EXPENSIVE path (one X25519 before anything can be
    /// rejected as forged), and it deliberately does not check mac2: mac2 is
    /// a MAC over the sender's source ADDRESS, which a `Handshake` never
    /// sees. Under load, run `CookieChecker.admit` on the raw datagram first
    /// — it checks mac1 and mac2 and answers with a `CookieReply` without
    /// constructing a `Handshake` at all, which is the only ordering in which
    /// the cookie layer actually sheds a flood.
    pub fn consumeInitiation(self: *Handshake, msg: MessageInitiation) ConsumeInitiationError!void {
        std.debug.assert(self.state == .idle); // one attempt per Handshake

        // mac1 first — cheap rejection before any DH (keyed with OUR static
        // public key: that is what the initiator derived the mac1 key from).
        const our_mac1_key = noise.mac1Key(self.static_keypair.public);
        const expected_mac1 = noise.keyedMac(
            &our_mac1_key,
            std.mem.asBytes(&msg)[0..@offsetOf(MessageInitiation, "mac1")],
        );
        if (!std.crypto.timing_safe.eql(noise.Mac, expected_mac1, msg.mac1))
            return error.InvalidMac1;

        // Replay the initiator's transcript (we are the responder — Ck0/H0
        // are derived from our own static public key).
        var st = initialState(self.static_keypair.public);
        noise.kdf1(&st.ck, &msg.unencrypted_ephemeral);
        noise.mixHash(&st.h, &msg.unencrypted_ephemeral);

        // es: DH(Sr, Ei) → decrypt the initiator's static public key.
        var es = noise.X25519.scalarmult(self.static_keypair.private, msg.unencrypted_ephemeral) catch
            return error.DecryptionFailed;
        var k = noise.mixKey(&st.ck, &es);
        std.crypto.secureZero(u8, &es);
        var peer_static: PublicKey = undefined;
        noise.Aead.decrypt(
            &peer_static,
            msg.encrypted_static[0..32],
            msg.encrypted_static[32..48].*,
            &st.h,
            counterNonce(0),
            k,
        ) catch return error.DecryptionFailed;
        noise.mixHash(&st.h, &msg.encrypted_static);
        if (!std.mem.eql(u8, &peer_static, &self.remote_static_public))
            return error.UnknownPeer;

        // ss: DH(Sr, Si) → decrypt + authenticate the timestamp.
        var ss = noise.X25519.scalarmult(self.static_keypair.private, peer_static) catch
            return error.DecryptionFailed;
        k = noise.mixKey(&st.ck, &ss);
        std.crypto.secureZero(u8, &ss);
        var ts: [12]u8 = undefined;
        noise.Aead.decrypt(
            &ts,
            msg.encrypted_timestamp[0..12],
            msg.encrypted_timestamp[12..28].*,
            &st.h,
            counterNonce(0),
            k,
        ) catch return error.DecryptionFailed;
        std.crypto.secureZero(u8, &k);
        noise.mixHash(&st.h, &msg.encrypted_timestamp);

        self.chaining_key = st.ck;
        self.hash = st.h;
        std.crypto.secureZero(u8, &st.ck);
        self.remote_ephemeral = msg.unencrypted_ephemeral;
        self.remote_timestamp = ts;
        self.remote_index = msg.sender_index;
        self.state = .initiation_consumed;
    }

    /// Responder step 2: generate our own ephemeral keypair, mix in the
    /// pre-shared key (psk2 — WireGuard's `Kdf3` step), and produce the
    /// empty-payload confirmation message. Requires `consumeInitiation` to
    /// have succeeded first.
    /// (A pre-seeded `local_ephemeral` is used instead of generating one —
    /// deterministic-test hook; leave it null in production.)
    pub fn createResponse(self: *Handshake, io: std.Io) ResponseError!MessageResponse {
        switch (self.state) {
            .initiation_consumed => {},
            .idle, .initiation_sent => return error.NoInitiationConsumed,
            .complete => return error.AlreadyStarted,
        }
        const remote_eph = self.remote_ephemeral.?; // set by consumeInitiation
        const eph = self.local_ephemeral orelse Keypair.generate(io);
        self.local_ephemeral = eph;

        var msg: MessageResponse = undefined;
        msg.type = @intFromEnum(MessageType.handshake_response);
        msg.sender_index = self.local_index;
        msg.receiver_index = self.remote_index;

        // e: our ephemeral in the clear.
        msg.unencrypted_ephemeral = eph.public;
        noise.kdf1(&self.chaining_key, &eph.public);
        noise.mixHash(&self.hash, &eph.public);

        // ee: DH(Er, Ei) — chaining-key only, no key output.
        var ee = noise.X25519.scalarmult(eph.private, remote_eph) catch
            return error.InvalidPublicKey;
        noise.kdf1(&self.chaining_key, &ee);
        std.crypto.secureZero(u8, &ee);

        // se: DH(Er, Si) — chaining-key only.
        var se = noise.X25519.scalarmult(eph.private, self.remote_static_public) catch
            return error.InvalidPublicKey;
        noise.kdf1(&self.chaining_key, &se);
        std.crypto.secureZero(u8, &se);

        // psk2: (ck, tau, k) = KDF3(ck, psk); h = HASH(h || tau).
        var psk_out = noise.kdf3(&self.chaining_key, &self.preshared_key);
        noise.mixHash(&self.hash, &psk_out.out1);

        // Empty-plaintext AEAD — proves agreement on every key derived so far.
        noise.Aead.encrypt(
            msg.encrypted_nothing[0..0],
            msg.encrypted_nothing[0..16],
            "",
            &self.hash,
            counterNonce(0),
            psk_out.out2,
        );
        std.crypto.secureZero(u8, std.mem.asBytes(&psk_out));
        noise.mixHash(&self.hash, &msg.encrypted_nothing);

        msg.mac1 = self.computeMac1(std.mem.asBytes(&msg)[0..@offsetOf(MessageResponse, "mac1")]);
        msg.mac2 = self.stampMac2(std.mem.asBytes(&msg)[0..@offsetOf(MessageResponse, "mac2")]);
        self.state = .complete;
        return msg;
    }

    /// Initiator validates the incoming `MessageResponse`: replays the
    /// responder's derivation (ephemeral DHs + psk2 mix) and authenticates
    /// the empty-payload AEAD tag. On success the handshake is complete and
    /// `deriveTransportKeys` may be called.
    pub fn consumeResponse(self: *Handshake, msg: MessageResponse) ConsumeResponseError!void {
        if (self.state != .initiation_sent) return error.NoPendingInitiation;
        const eph = self.local_ephemeral.?; // set by createInitiation

        // mac1 — keyed with OUR static public key (the responder derived it
        // from ours, since the message is addressed to us).
        const our_mac1_key = noise.mac1Key(self.static_keypair.public);
        const expected_mac1 = noise.keyedMac(
            &our_mac1_key,
            std.mem.asBytes(&msg)[0..@offsetOf(MessageResponse, "mac1")],
        );
        if (!std.crypto.timing_safe.eql(noise.Mac, expected_mac1, msg.mac1))
            return error.InvalidMac1;

        // Work on copies so a failed (possibly forged) response cannot
        // corrupt the pending handshake state.
        var ck = self.chaining_key;
        var h = self.hash;

        noise.kdf1(&ck, &msg.unencrypted_ephemeral);
        noise.mixHash(&h, &msg.unencrypted_ephemeral);

        // ee: DH(Ei, Er), then se: DH(Si, Er) — chaining-key only.
        var ee = noise.X25519.scalarmult(eph.private, msg.unencrypted_ephemeral) catch
            return error.DecryptionFailed;
        noise.kdf1(&ck, &ee);
        std.crypto.secureZero(u8, &ee);
        var se = noise.X25519.scalarmult(self.static_keypair.private, msg.unencrypted_ephemeral) catch
            return error.DecryptionFailed;
        noise.kdf1(&ck, &se);
        std.crypto.secureZero(u8, &se);

        // psk2 mix, then authenticate the empty payload.
        var psk_out = noise.kdf3(&ck, &self.preshared_key);
        defer std.crypto.secureZero(u8, std.mem.asBytes(&psk_out));
        noise.mixHash(&h, &psk_out.out1);
        var empty: [0]u8 = .{};
        noise.Aead.decrypt(
            &empty,
            msg.encrypted_nothing[0..0],
            msg.encrypted_nothing[0..16].*,
            &h,
            counterNonce(0),
            psk_out.out2,
        ) catch return error.DecryptionFailed;
        noise.mixHash(&h, &msg.encrypted_nothing);

        self.chaining_key = ck;
        self.hash = h;
        std.crypto.secureZero(u8, &ck);
        self.remote_ephemeral = msg.unencrypted_ephemeral;
        self.remote_index = msg.sender_index;
        self.state = .complete;
    }

    /// Final step, either side, once the handshake completed (initiator
    /// after `consumeResponse`, responder after `createResponse`): split
    /// the chaining key into the two directional transport keys.
    /// `Kdf2(ck, ε) = (k1, k2)`; the initiator's `send` is the responder's
    /// `recv` and vice versa — WireGuard fixes this by having the
    /// *initiator* take `(send, recv) = (k1, k2)` and the *responder* take
    /// `(send, recv) = (k2, k1)`, so both sides must know which role they
    /// played to call this correctly.
    /// Consumes the handshake: the chaining key, transcript hash and the
    /// ephemeral private key are wiped — only the returned keys survive.
    pub fn deriveTransportKeys(self: *Handshake, is_initiator: bool) transport.TransportKeys {
        std.debug.assert(self.state == .complete);
        // Kdf2(ck, ε) = (T1, T2): kdf2 leaves T1 in the chaining key and
        // returns T2.
        const t2 = noise.kdf2(&self.chaining_key, "");
        const t1 = self.chaining_key;
        std.crypto.secureZero(u8, &self.chaining_key);
        std.crypto.secureZero(u8, &self.hash);
        if (self.local_ephemeral) |*kp| std.crypto.secureZero(u8, &kp.private);
        return if (is_initiator)
            .{ .send = t1, .recv = t2 }
        else
            .{ .send = t2, .recv = t1 };
    }

    /// The one-call bridge from a completed handshake to the data plane:
    /// derive the transport keys and wire them, with both session indices,
    /// into a `transport.Session`. Prefer this over calling
    /// `deriveTransportKeys` by hand — it is what makes the send/receive key
    /// and the local/remote index assignment impossible to swap (a swap
    /// round-trips against yourself and fails against every real peer).
    /// Consumes the handshake exactly as `deriveTransportKeys` does.
    ///
    /// `now_s` is the caller's clock at the moment the handshake completed —
    /// the session's `born_s`, from which `transport.reject_after_time_s` (180 s)
    /// and `transport.rekey_after_time_s` (120 s) are measured. Required, not
    /// optional: a session with no birth time is a session that never expires,
    /// and the same `now_s` convention already runs through this file's cookie
    /// layer (`CookieChecker.refresh`, `PeerCookie.current`).
    pub fn transportSession(self: *Handshake, is_initiator: bool, now_s: u64) transport.Session {
        const local = self.local_index;
        const remote = self.remote_index;
        return transport.Session.init(self.deriveTransportKeys(is_initiator), local, remote, now_s);
    }

    /// `MAC(mac1_key(remote_static_public), msg_bytes_before_mac1)` — the
    /// mac1 field of any message we send to this peer. `msg_bytes_before_mac1`
    /// is the wire encoding of the message up to (not including) its mac1
    /// field.
    pub fn computeMac1(self: *const Handshake, msg_bytes_before_mac1: []const u8) noise.Mac {
        const key = noise.mac1Key(self.remote_static_public);
        return noise.keyedMac(&key, msg_bytes_before_mac1);
    }

    /// `MAC(cookie, msg_bytes_before_mac2)` if `cookie` is a currently-valid
    /// cookie received from this peer, else an all-zero mac2 (per protocol,
    /// only computed under load after receiving a `CookieReply`).
    pub fn computeMac2(
        self: *const Handshake,
        msg_bytes_before_mac2: []const u8,
        cookie: [16]u8,
    ) noise.Mac {
        _ = self;
        return noise.keyedMac(&cookie, msg_bytes_before_mac2);
    }

    /// The mac2 field of a message we are building: `computeMac2` under the
    /// cookie held in `self.cookie`, or the protocol's all-zero mac2 when we
    /// hold none. This is the ONE place the two cases are decided, so no
    /// message-building path can forget either half.
    fn stampMac2(self: *const Handshake, msg_bytes_before_mac2: []const u8) noise.Mac {
        const cookie = self.cookie orelse return @splat(0);
        return self.computeMac2(msg_bytes_before_mac2, cookie);
    }
};

// ── cookie / mac2: the under-load DoS mitigation (whitepaper 5.4.7) ────────
//
// mac1 alone is not a DoS defense: its key is `HASH(LABEL_MAC1 ||
// responder_static_public)`, derived from a PUBLIC value, so anyone who knows
// the responder's public key can forge a mac1-passing initiation from a
// spoofed source address and make the responder spend an X25519 plus two AEAD
// opens on it. The cookie layer is what turns that into a round-trip
// requirement: a loaded responder answers with a `CookieReply` carrying
// `cookie = MAC(Rm, Am)` — a MAC of the SOURCE ADDRESS under a secret that
// rotates every two minutes — and thereafter only accepts messages from that
// address whose `mac2` proves possession of the cookie. A spoofed source never
// receives the reply, so it can never produce the mac2.
//
// Two pieces of state, one per role:
//   * `CookieChecker` — responder side: the rotating secret `Rm`, mac2
//     validation, and cookie-reply generation.
//   * `PeerCookie` — initiator side: the cookie learned from a peer's reply
//     and how long it stays usable.
// Neither reads a clock or a socket: the caller passes `now_s` (seconds, any
// monotonic epoch) and the opaque source-address bytes, matching this module's
// standing rule that its codecs are pure functions over bytes.

/// The responder's cookie secret `Rm` "changes every two minutes" (5.4.7).
pub const cookie_secret_lifetime_s: u64 = 120;
/// …and a cookie is derived from that secret, so an initiator must stop using
/// one after the same two minutes: past that the responder has (or is about to
/// have) rotated `Rm` and the mac2 would simply be rejected.
pub const cookie_lifetime_s: u64 = 120;

/// The three regions of a handshake message the cookie layer works on, plus
/// the two MACs already in it. Slices borrow the caller's buffer.
pub const MacFields = struct {
    /// `msg.sender_index` — echoed as the cookie reply's `receiver_index`.
    sender_index: u32,
    /// `msg[0 .. offsetof(msg.mac1)]` — what mac1 is computed over.
    mac1_input: []const u8,
    /// `msg[0 .. offsetof(msg.mac2)]` — what mac2 is computed over (mac1
    /// included: mac2 covers the whole message before itself).
    mac2_input: []const u8,
    /// The mac1 carried by the message. Doubles as the associated data of a
    /// cookie reply sent in answer to it.
    mac1: noise.Mac,
    /// The mac2 carried by the message (all-zero when the sender held no cookie).
    mac2: noise.Mac,
};

pub const MacFieldsError = error{
    /// Not a type-1/type-2 handshake message of the exact protocol length —
    /// nothing the cookie layer has any business MACing.
    NotAHandshakeMessage,
};

comptime {
    // `macFields` below indexes both message types by the same rule (indices
    // at 4, the two MACs as the trailing 32 bytes). Assert that rather than
    // trust it, so a field reorder fails the build instead of MACing garbage.
    std.debug.assert(@offsetOf(MessageInitiation, "sender_index") == 4);
    std.debug.assert(@offsetOf(MessageResponse, "sender_index") == 4);
    std.debug.assert(@offsetOf(MessageInitiation, "mac1") == @sizeOf(MessageInitiation) - 32);
    std.debug.assert(@offsetOf(MessageResponse, "mac1") == @sizeOf(MessageResponse) - 32);
    std.debug.assert(@offsetOf(MessageInitiation, "mac2") == @sizeOf(MessageInitiation) - 16);
    std.debug.assert(@offsetOf(MessageResponse, "mac2") == @sizeOf(MessageResponse) - 16);
}

/// Locate the mac1/mac2 regions of a raw handshake datagram, rejecting
/// anything that is not exactly a `MessageInitiation` or `MessageResponse`.
/// Length is checked against the type tag (not merely `>= 32`) so a truncated
/// or oversized datagram is dropped before any MAC is computed over it.
pub fn macFields(msg_bytes: []const u8) MacFieldsError!MacFields {
    if (msg_bytes.len < 8) return error.NotAHandshakeMessage;
    const wire_len: usize = switch (@as(MessageType, @enumFromInt(
        std.mem.readInt(u32, msg_bytes[0..4], .little),
    ))) {
        .handshake_initiation => @sizeOf(MessageInitiation),
        .handshake_response => @sizeOf(MessageResponse),
        else => return error.NotAHandshakeMessage,
    };
    if (msg_bytes.len != wire_len) return error.NotAHandshakeMessage;
    return .{
        .sender_index = std.mem.readInt(u32, msg_bytes[4..8], .little),
        .mac1_input = msg_bytes[0 .. wire_len - 32],
        .mac2_input = msg_bytes[0 .. wire_len - 16],
        .mac1 = msg_bytes[wire_len - 32 ..][0..16].*,
        .mac2 = msg_bytes[wire_len - 16 ..][0..16].*,
    };
}

/// What a responder should do with an inbound handshake datagram, decided
/// before any Diffie-Hellman happens — the whole point of the layer.
pub const Admission = union(enum) {
    /// mac1 is valid and either we are not under load or mac2 checked out:
    /// go ahead and spend the asymmetric crypto (`Handshake.consumeInitiation`
    /// / `consumeResponse`).
    accept,
    /// Under load and the sender has no valid cookie for this source address:
    /// send these 64 bytes back and do NO further work on the datagram.
    cookie_reply: CookieReply,
    /// Not a handshake message, or mac1 does not verify: drop silently, as
    /// WireGuard's design requires (never answer an unauthenticated packet
    /// with anything but a cookie reply).
    drop,
};

/// Responder-side cookie state — one per local device (it is keyed on OUR
/// static public key, not on any peer's), shared across every peer and every
/// in-flight handshake.
pub const CookieChecker = struct {
    /// `HASH(LABEL_MAC1 || our_static_public)` — precomputed mac1 key for
    /// messages addressed to us.
    mac1_key: noise.HandshakeHash,
    /// `HASH(LABEL_COOKIE || our_static_public)` — the XAEAD key our cookie
    /// replies are encrypted under. Derived from a public value by design:
    /// the reply is meant to be readable by whoever actually received it, and
    /// its authentication comes from the associated data (the mac1 of the
    /// message being answered), which only someone on the path or the genuine
    /// sender knows.
    cookie_key: noise.HandshakeHash,
    /// `Rm` — the rotating secret every cookie is MACed under. Secret: wipe
    /// with `wipe()` when discarding the checker.
    secret: [32]u8,
    /// When `secret` was generated, in the caller's `now_s` epoch.
    secret_born_s: u64,

    /// Fresh checker with a random `Rm`. Fail-closed: `initWithSecret`'s
    /// own doc says it — a predictable `Rm` makes every cookie forgeable,
    /// which is the whole security of this layer — and this signature
    /// returns a `CookieChecker`, so a weak draw could not be reported.
    pub fn init(our_static_public: PublicKey, io: std.Io, now_s: u64) CookieChecker {
        var self = initWithSecret(our_static_public, undefined, now_s);
        entropy.fill(io, &self.secret);
        return self;
    }

    /// Deterministic-test seam: a checker with a caller-chosen `Rm`. Use
    /// `init` in production — a predictable secret makes every cookie
    /// forgeable, which is the whole security of this layer.
    pub fn initWithSecret(our_static_public: PublicKey, secret: [32]u8, now_s: u64) CookieChecker {
        return .{
            .mac1_key = noise.mac1Key(our_static_public),
            .cookie_key = noise.cookieKey(our_static_public),
            .secret = secret,
            .secret_born_s = now_s,
        };
    }

    /// Wipe `Rm`. Every cookie issued under it stops verifying.
    pub fn wipe(self: *CookieChecker) void {
        std.crypto.secureZero(u8, &self.secret);
        self.secret_born_s = 0;
    }

    /// Roll `Rm` once it has lived `cookie_secret_lifetime_s`, which is what
    /// bounds a stolen cookie's usefulness. A clock that moved BACKWARDS also
    /// rolls it: extending a secret's life on a bad timestamp is the one
    /// failure mode worth avoiding here, and re-rolling only costs the peers
    /// one extra round trip.
    pub fn refresh(self: *CookieChecker, io: std.Io, now_s: u64) void {
        if (now_s >= self.secret_born_s and
            now_s - self.secret_born_s < cookie_secret_lifetime_s) return;
        // Same fail-closed reason as `init` — rotating onto a guessable
        // `Rm` is strictly worse than not rotating at all.
        entropy.fill(io, &self.secret);
        self.secret_born_s = now_s;
    }

    /// `cookie = MAC(Rm, Am)` for one source address, rotating `Rm` first if
    /// it is due. `source_address` is opaque to this module — whatever stable
    /// encoding of the peer's address the caller uses (e.g. 4-or-16 IP bytes
    /// plus the 2 port bytes). It only has to be the SAME bytes when the
    /// cookie is issued and when a later mac2 is checked; anything that varies
    /// per packet would issue cookies that can never be used.
    pub fn cookieFor(
        self: *CookieChecker,
        io: std.Io,
        now_s: u64,
        source_address: []const u8,
    ) noise.Mac {
        self.refresh(io, now_s);
        return noise.keyedMac(&self.secret, source_address);
    }

    /// Constant-time mac1 check — the cheap "is this even addressed to us"
    /// filter that runs before everything else.
    pub fn checkMac1(self: *const CookieChecker, f: MacFields) bool {
        const expected = noise.keyedMac(&self.mac1_key, f.mac1_input);
        return std.crypto.timing_safe.eql(noise.Mac, expected, f.mac1);
    }

    /// Constant-time mac2 check against the cookie this source address would
    /// currently be issued. An all-zero mac2 (the sender holds no cookie)
    /// simply fails to match, which is exactly the desired outcome.
    pub fn checkMac2(
        self: *CookieChecker,
        io: std.Io,
        now_s: u64,
        f: MacFields,
        source_address: []const u8,
    ) bool {
        const cookie = self.cookieFor(io, now_s, source_address);
        const expected = noise.keyedMac(&cookie, f.mac2_input);
        return std.crypto.timing_safe.eql(noise.Mac, expected, f.mac2);
    }

    /// Build the type-3 answer to a message we refuse to work on:
    /// `encrypted_cookie = XAEAD(cookie_key, nonce, cookie, msg.mac1)` with a
    /// fresh random nonce (5.4.7).
    pub fn createReply(
        self: *CookieChecker,
        io: std.Io,
        now_s: u64,
        f: MacFields,
        source_address: []const u8,
    ) CookieReply {
        var nonce: [noise.XAead.nonce_length]u8 = undefined;
        // Fail-closed: this nonce's only job is to never repeat under one
        // `Rm`, and a repeat leaks the XOR of two cookies (see
        // `createReplyWithNonce`). Returns a `CookieReply`, no error channel.
        entropy.fill(io, &nonce);
        return self.createReplyWithNonce(io, now_s, f, source_address, nonce);
    }

    /// Deterministic-test seam for `createReply`. Production callers use
    /// `createReply`: two replies under one `Rm` with the same nonce leak the
    /// XOR of their cookies.
    pub fn createReplyWithNonce(
        self: *CookieChecker,
        io: std.Io,
        now_s: u64,
        f: MacFields,
        source_address: []const u8,
        nonce: [noise.XAead.nonce_length]u8,
    ) CookieReply {
        const cookie = self.cookieFor(io, now_s, source_address);
        var reply: CookieReply = .{
            .type = @intFromEnum(MessageType.cookie_reply),
            .receiver_index = f.sender_index,
            .nonce = nonce,
            .encrypted_cookie = undefined,
        };
        noise.XAead.encrypt(
            reply.encrypted_cookie[0..16],
            reply.encrypted_cookie[16..32],
            &cookie,
            &f.mac1, // associated data — binds the reply to the exact message
            nonce,
            self.cookie_key,
        );
        return reply;
    }

    /// The complete inbound decision for one handshake datagram: parse, mac1,
    /// then (only when `under_load`) mac2, answering with a cookie reply when
    /// the sender cannot prove a round trip. Runs before any `Handshake`
    /// exists — that is what makes it a defense rather than a formality, since
    /// the expensive X25519 lives on the far side of `.accept`.
    ///
    /// `under_load` is the caller's policy call (queue depth, handshakes/sec —
    /// whatever it measures); this module has no view of the socket. Callers
    /// should additionally rate-limit replies per source address, so that a
    /// flood cannot turn one 148-byte initiation into one 64-byte reply
    /// forever.
    pub fn admit(
        self: *CookieChecker,
        io: std.Io,
        now_s: u64,
        msg_bytes: []const u8,
        source_address: []const u8,
        under_load: bool,
    ) Admission {
        const f = macFields(msg_bytes) catch return .drop;
        if (!self.checkMac1(f)) return .drop;
        if (!under_load) return .accept;
        if (self.checkMac2(io, now_s, f, source_address)) return .accept;
        return .{ .cookie_reply = self.createReply(io, now_s, f, source_address) };
    }
};

/// Initiator-side cookie state — one per peer we send handshake messages to
/// (it is keyed on THAT peer's static public key). Feed `Handshake.cookie`
/// from `current(now_s)`.
pub const PeerCookie = struct {
    /// `HASH(LABEL_COOKIE || peer_static_public)` — the key the peer encrypts
    /// its cookie replies to us under.
    cookie_key: noise.HandshakeHash,
    /// The cookie from the peer's last reply, if any.
    cookie: ?noise.Mac = null,
    /// When that cookie arrived, in the caller's `now_s` epoch.
    cookie_born_s: u64 = 0,
    /// mac1 of the last handshake message we sent this peer — the associated
    /// data any cookie reply to it will be authenticated with, so a reply can
    /// only be consumed by whoever actually saw that message.
    last_sent_mac1: ?noise.Mac = null,

    pub fn init(peer_static_public: PublicKey) PeerCookie {
        return .{ .cookie_key = noise.cookieKey(peer_static_public) };
    }

    /// Record a handshake message we just put on the wire. Call it for every
    /// initiation/response sent to this peer: without the stored mac1 a reply
    /// to it cannot be opened.
    pub fn recordSent(self: *PeerCookie, msg_bytes: []const u8) MacFieldsError!void {
        self.last_sent_mac1 = (try macFields(msg_bytes)).mac1;
    }

    pub const ConsumeReplyError = error{
        /// No `recordSent` since the last consumed reply — nothing this reply
        /// could be an answer to.
        NoPendingMessage,
        /// The XAEAD tag did not verify under `cookie_key` and the stored
        /// mac1: a reply to some other message, or a forgery by someone who
        /// never saw ours.
        DecryptionFailed,
    };

    /// Decrypt a peer's `CookieReply` and adopt the cookie inside it. Callers
    /// route the datagram here by its `receiver_index` (our own session index
    /// on the message we sent). On failure nothing is adopted — a bad reply
    /// cannot clear a cookie we already hold.
    pub fn consumeReply(
        self: *PeerCookie,
        reply: CookieReply,
        now_s: u64,
    ) ConsumeReplyError!void {
        const aad = self.last_sent_mac1 orelse return error.NoPendingMessage;
        var cookie: noise.Mac = undefined;
        noise.XAead.decrypt(
            &cookie,
            reply.encrypted_cookie[0..16],
            reply.encrypted_cookie[16..32].*,
            &aad,
            reply.nonce,
            self.cookie_key,
        ) catch return error.DecryptionFailed;
        self.cookie = cookie;
        self.cookie_born_s = now_s;
    }

    /// The cookie to stamp into `Handshake.cookie`, or null once it has aged
    /// past `cookie_lifetime_s` (or the clock moved backwards) — at which
    /// point the protocol says to go back to an all-zero mac2 rather than send
    /// one the peer will reject.
    pub fn current(self: *const PeerCookie, now_s: u64) ?noise.Mac {
        const cookie = self.cookie orelse return null;
        if (now_s < self.cookie_born_s) return null;
        if (now_s - self.cookie_born_s >= cookie_lifetime_s) return null;
        return cookie;
    }
};

// ── dark-tests: pulled into the aggregator via ../root.zig `test { }` ──────

const testing = std.testing;

test "message type wire values" {
    try testing.expectEqual(@as(u32, 1), @intFromEnum(MessageType.handshake_initiation));
    try testing.expectEqual(@as(u32, 2), @intFromEnum(MessageType.handshake_response));
    try testing.expectEqual(@as(u32, 3), @intFromEnum(MessageType.cookie_reply));
    try testing.expectEqual(@as(u32, 4), @intFromEnum(MessageType.transport_data));
    // `transport.zig` carries its own copy of the type tag (it deliberately
    // does not import this file, so the dependency runs one way only). Pin
    // the two together here rather than trusting they stay equal.
    try testing.expectEqual(@intFromEnum(MessageType.transport_data), transport.message_type);
    try testing.expectEqual(@sizeOf(MessageTransportHeader), transport.header_len);
    try testing.expectEqual(noise.tag_len, transport.tag_len);
}

test "wire message sizes match the WireGuard protocol exactly" {
    try testing.expectEqual(@as(usize, 148), @sizeOf(MessageInitiation));
    try testing.expectEqual(@as(usize, 92), @sizeOf(MessageResponse));
    try testing.expectEqual(@as(usize, 64), @sizeOf(CookieReply));
    try testing.expectEqual(@as(usize, 16), @sizeOf(MessageTransportHeader));
}

test "key type widths" {
    try testing.expectEqual(@as(usize, 32), @sizeOf(PrivateKey));
    try testing.expectEqual(@as(usize, 32), @sizeOf(PublicKey));
    try testing.expectEqual(@as(usize, 32), @sizeOf(PresharedKey));
}

// ── known-answer test (independent reference vector) ───────────────────────
//
// No official fixed-input full-handshake vector is published by the
// WireGuard project (wireguard-go's noise tests are self-consistency only;
// its published vectors cover just the KDF — used in noise.zig). This
// vector was therefore generated by an INDEPENDENT reference implementation
// (Python: hashlib BLAKE2s/HMAC + OpenSSL X25519/ChaCha20-Poly1305 via
// cryptography.io) written directly from whitepaper sec 5.4, and that
// reference was itself validated against the official wireguard-go KDF
// vectors before generating this. The kernel interop test below provides
// the non-derived, third-party oracle for the full wire protocol.

/// Hex-decode a compile-time string into a fixed byte array (test helper).
fn hex(comptime s: []const u8) [s.len / 2]u8 {
    var out: [s.len / 2]u8 = undefined;
    _ = std.fmt.hexToBytes(&out, s) catch unreachable;
    return out;
}

/// The fixed inputs of the known-answer vector (also reused as deterministic
/// keys by other tests below).
const kat = struct {
    // Private keys are raw seeds; X25519 clamps on use, identically in the
    // reference and here.
    const si_priv = hex("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20");
    const sr_priv = hex("404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f");
    const ei_priv = hex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f");
    const er_priv = hex("c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf");
    const psk: PresharedKey = @splat(0x55);
    const timestamp = hex("400000005e6b0d3d0e2f6b4a");
    const idx_i: u32 = 0x11111111;
    const idx_r: u32 = 0x22222222;

    const msg1 = hex(
        "0100000011111111493e82fc74464a59268817623d2053c5eb8e2cc4a988b4fe" ++
            "e179ec6b010d531dd05176bd13b73f6ff41b1954d28c67af91790e19d64a9030" ++
            "feed78efce91efb40d8a7b62a50bd07538b50822dff5bfb49f103fa19145fd4a" ++
            "8414b756bb2c8bfc4a84bb31c3e5e33f6cffb83bba50ec6761870416da24b7e4" ++
            "38717f2b00000000000000000000000000000000",
    );
    const msg2 = hex(
        "020000002222222211111111dc2cca31e8e43bbd91dff7e475cca3347eb47810" ++
            "7d5bd765aba4ae4a30c35d44a3d294a74fbd0353246e2063f25fddc75e975f76" ++
            "e9840213a22cbadcca574ff500000000000000000000000000000000",
    );
    const t_initiator_send = hex("6c6fbee3c6e669a8dcce54ea527169647f2d8b940f7ce7321cc5d8b334d3902a");
    const t_initiator_recv = hex("df5019942bc7d12e983a480f2136056a37e169fc54ef49c97b60ab90af76c4c7");

    fn initiator() Handshake {
        return .{
            .static_keypair = Keypair.fromPrivateKey(si_priv) catch unreachable,
            .remote_static_public = (Keypair.fromPrivateKey(sr_priv) catch unreachable).public,
            .preshared_key = psk,
            .local_index = idx_i,
            .local_ephemeral = Keypair.fromPrivateKey(ei_priv) catch unreachable,
        };
    }

    fn responder() Handshake {
        return .{
            .static_keypair = Keypair.fromPrivateKey(sr_priv) catch unreachable,
            .remote_static_public = (Keypair.fromPrivateKey(si_priv) catch unreachable).public,
            .preshared_key = psk,
            .local_index = idx_r,
            .local_ephemeral = Keypair.fromPrivateKey(er_priv) catch unreachable,
        };
    }
};

test "KAT: full handshake, byte-exact messages and transport keys" {
    const io = std.testing.io;
    var ini = kat.initiator();
    var rsp = kat.responder();

    const msg1 = try ini.createInitiation(io, kat.timestamp);
    try testing.expectEqualSlices(u8, &kat.msg1, std.mem.asBytes(&msg1));

    try rsp.consumeInitiation(msg1);
    try testing.expectEqual(kat.timestamp, rsp.remote_timestamp.?);
    try testing.expectEqual(kat.idx_i, rsp.remote_index);
    // Both transcripts agree mid-handshake.
    try testing.expectEqual(ini.chaining_key, rsp.chaining_key);
    try testing.expectEqual(ini.hash, rsp.hash);

    const msg2 = try rsp.createResponse(io);
    try testing.expectEqualSlices(u8, &kat.msg2, std.mem.asBytes(&msg2));

    try ini.consumeResponse(msg2);
    try testing.expectEqual(ini.chaining_key, rsp.chaining_key);
    try testing.expectEqual(ini.hash, rsp.hash);
    try testing.expectEqual(kat.idx_r, ini.remote_index);

    const ki = ini.deriveTransportKeys(true);
    const kr = rsp.deriveTransportKeys(false);
    try testing.expectEqual(kat.t_initiator_send, ki.send);
    try testing.expectEqual(kat.t_initiator_recv, ki.recv);
    try testing.expectEqual(ki.send, kr.recv);
    try testing.expectEqual(ki.recv, kr.send);

    // deriveTransportKeys wiped the session secrets.
    try testing.expectEqual(@as(noise.ChainKey, @splat(0)), ini.chaining_key);
    try testing.expectEqual(@as(PrivateKey, @splat(0)), ini.local_ephemeral.?.private);
}

// ── differential: the std -> chachapoly AEAD swap is inert ────────────────
//
// `noise.Aead` is the SIMD `chachapoly` sibling; `noise.StdAead` is
// `std.crypto.aead.chacha_poly.ChaCha20Poly1305`. The KAT above already pins
// the HANDSHAKE messages byte-exact against an independent reference under
// the swapped-in AEAD. This pins the raw AEAD call underneath the
// TRANSPORT-DATA direction: `AEAD(T_send, counterNonce(counter), packet, ε)`,
// empty associated data, over every length across the ChaCha block boundaries
// up to a full 1500-byte MTU and the counter values that exercise the nonce
// encoding. The FRAMING on top of it (header, padding, limits, replay) is
// `transport.zig`'s, and is differentially anchored there.
test "differential: transport-data seal is byte-identical under chachapoly and std" {
    const key = kat.t_initiator_send;
    var packet: [1500]u8 = undefined;
    var prng = std.Random.DefaultPrng.init(0x5A17_C0DE);
    prng.random().bytes(&packet);

    var ours: [1500]u8 = undefined;
    var theirs: [1500]u8 = undefined;
    var ours_tag: [16]u8 = undefined;
    var theirs_tag: [16]u8 = undefined;
    var back: [1500]u8 = undefined;

    const lens = [_]usize{ 0, 1, 63, 64, 65, 127, 128, 512, 513, 1280, 1420, 1500 };
    const counters = [_]u64{ 0, 1, 1023, 0xFFFF_FFFF, 0x1_0000_0000, std.math.maxInt(u64) };

    for (lens) |len| {
        for (counters) |ctr| {
            const npub = Handshake.counterNonce(ctr);
            noise.Aead.encrypt(ours[0..len], &ours_tag, packet[0..len], "", npub, key);
            noise.StdAead.encrypt(theirs[0..len], &theirs_tag, packet[0..len], "", npub, key);

            // Ciphertext AND tag byte-identical — this is the whole claim.
            try testing.expectEqualSlices(u8, theirs[0..len], ours[0..len]);
            try testing.expectEqualSlices(u8, &theirs_tag, &ours_tag);

            // …and each implementation opens the other's packet, so a peer
            // running either one interoperates with a peer running the other.
            try noise.Aead.decrypt(back[0..len], theirs[0..len], theirs_tag, "", npub, key);
            try testing.expectEqualSlices(u8, packet[0..len], back[0..len]);
            try noise.StdAead.decrypt(back[0..len], ours[0..len], ours_tag, "", npub, key);
            try testing.expectEqualSlices(u8, packet[0..len], back[0..len]);
        }
    }
}

test "differential: the handshake KAT messages are identical under std's AEAD too" {
    // The KAT above proves `chachapoly` reproduces the independent reference's
    // bytes. Recompute the SAME two messages' AEAD fields with std's AEAD from
    // the same transcript inputs: if the two AEADs ever diverged, exactly one
    // of these two tests would go red, and the pair says which side moved.
    const io = std.testing.io;
    var ini = kat.initiator();
    const msg1 = try ini.createInitiation(io, kat.timestamp);

    // Replay message 1's transcript with std's AEAD (mirrors createInitiation).
    var st = Handshake.initialState(ini.remote_static_public);
    noise.kdf1(&st.ck, &msg1.unencrypted_ephemeral);
    noise.mixHash(&st.h, &msg1.unencrypted_ephemeral);
    var es = try noise.X25519.scalarmult(ini.local_ephemeral.?.private, ini.remote_static_public);
    var k = noise.mixKey(&st.ck, &es);
    std.crypto.secureZero(u8, &es);
    var enc_static: [48]u8 = undefined;
    noise.StdAead.encrypt(
        enc_static[0..32],
        enc_static[32..48],
        &ini.static_keypair.public,
        &st.h,
        Handshake.counterNonce(0),
        k,
    );
    try testing.expectEqualSlices(u8, &msg1.encrypted_static, &enc_static);
    noise.mixHash(&st.h, &enc_static);

    var ss = try noise.X25519.scalarmult(ini.static_keypair.private, ini.remote_static_public);
    k = noise.mixKey(&st.ck, &ss);
    std.crypto.secureZero(u8, &ss);
    var enc_ts: [28]u8 = undefined;
    noise.StdAead.encrypt(
        enc_ts[0..12],
        enc_ts[12..28],
        &kat.timestamp,
        &st.h,
        Handshake.counterNonce(0),
        k,
    );
    try testing.expectEqualSlices(u8, &msg1.encrypted_timestamp, &enc_ts);
}

test "handshake → data plane: the KAT session carries packets both ways" {
    // The seam this covers: `transportSession` must hand each half the key and
    // index it needs. The KAT above pins the two transport keys against an
    // independent reference, so this asserts the WIRING against those pinned
    // values — a swapped pair would still round-trip, so the equality checks
    // below (not the round trip) are the test.
    //
    // The session is born at `kat_now_s` and every seal/open here happens at
    // the same instant, i.e. at age 0 — comfortably inside
    // `transport.reject_after_time_s`. The lifetime rule itself is pinned in
    // `transport.zig`; this test is about the wiring.
    const kat_now_s: u64 = 1_700_000_000;
    const io = std.testing.io;
    var ini = kat.initiator();
    var rsp = kat.responder();
    const msg1 = try ini.createInitiation(io, kat.timestamp);
    try rsp.consumeInitiation(msg1);
    const msg2 = try rsp.createResponse(io);
    try ini.consumeResponse(msg2);

    var i_sess = ini.transportSession(true, kat_now_s);
    var r_sess = rsp.transportSession(false, kat_now_s);

    // Keys land on the half that uses them, against the KAT's fixed values.
    try testing.expectEqual(kat.t_initiator_send, i_sess.send.key);
    try testing.expectEqual(kat.t_initiator_recv, i_sess.recv.key);
    try testing.expectEqual(kat.t_initiator_send, r_sess.recv.key);
    try testing.expectEqual(kat.t_initiator_recv, r_sess.send.key);
    // Indices: we stamp the PEER's index on what we send, and expect our own
    // on what we receive.
    try testing.expectEqual(kat.idx_r, i_sess.send.receiver_index);
    try testing.expectEqual(kat.idx_i, i_sess.recv.local_index);
    try testing.expectEqual(kat.idx_i, r_sess.send.receiver_index);
    try testing.expectEqual(kat.idx_r, r_sess.recv.local_index);

    var wire: [1500]u8 = undefined;
    var out: [1500]u8 = undefined;
    const packet = "an inner IP packet";
    const sr = try i_sess.send.seal(&wire, packet, kat_now_s);
    // The header carries the responder's index, as any real peer would expect.
    try testing.expectEqual(kat.idx_r, (try transport.parseHeader(wire[0..sr.len])).receiver_index);
    // Cross-wiring fails: the initiator's own receiver cannot open what the
    // initiator sent — it is addressed to the responder's index.
    try testing.expectError(error.WrongReceiver, i_sess.recv.open(&out, wire[0..sr.len], kat_now_s));

    const orr = try r_sess.recv.open(&out, wire[0..sr.len], kat_now_s);
    try testing.expectEqualSlices(u8, packet, out[0..packet.len]);
    try testing.expectEqual(transport.paddedLen(packet.len), orr.len);

    // …and the reverse direction, under the other key.
    var wire2: [1500]u8 = undefined;
    const sr2 = try r_sess.send.seal(&wire2, "and one back", kat_now_s);
    const orr2 = try i_sess.recv.open(&out, wire2[0..sr2.len], kat_now_s);
    try testing.expectEqualSlices(u8, "and one back", out[0..12]);
    try testing.expectEqual(@as(usize, 16), orr2.len);
}

test "self-consistency: full handshake with fresh random keys" {
    const io = std.testing.io;
    const si = Keypair.generate(io);
    const sr = Keypair.generate(io);
    var psk: PresharedKey = undefined;
    io.random(&psk);

    var ini: Handshake = .{
        .static_keypair = si,
        .remote_static_public = sr.public,
        .preshared_key = psk,
        .local_index = 7,
    };
    var rsp: Handshake = .{
        .static_keypair = sr,
        .remote_static_public = si.public,
        .preshared_key = psk,
        .local_index = 9,
    };

    const msg1 = try ini.createInitiation(io, @splat(0x42));
    try rsp.consumeInitiation(msg1);
    try testing.expectEqual(ini.chaining_key, rsp.chaining_key);
    try testing.expectEqual(ini.hash, rsp.hash);
    const msg2 = try rsp.createResponse(io);
    try ini.consumeResponse(msg2);
    try testing.expectEqual(ini.chaining_key, rsp.chaining_key);
    try testing.expectEqual(ini.hash, rsp.hash);

    const ki = ini.deriveTransportKeys(true);
    const kr = rsp.deriveTransportKeys(false);
    try testing.expectEqual(ki.send, kr.recv);
    try testing.expectEqual(ki.recv, kr.send);
    try testing.expect(!std.mem.eql(u8, &ki.send, &ki.recv));
}

test "auth failures: tampering, wrong PSK, wrong peer are all rejected" {
    const io = std.testing.io;

    // Tampered mac1 → InvalidMac1 (cheap rejection).
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        var msg1 = try ini.createInitiation(io, kat.timestamp);
        msg1.mac1[0] ^= 1;
        try testing.expectError(error.InvalidMac1, rsp.consumeInitiation(msg1));
    }
    // Tampered ciphertext with a fixed-up mac1 → DecryptionFailed.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        var msg1 = try ini.createInitiation(io, kat.timestamp);
        msg1.encrypted_timestamp[3] ^= 1;
        msg1.mac1 = ini.computeMac1(std.mem.asBytes(&msg1)[0..@offsetOf(MessageInitiation, "mac1")]);
        try testing.expectError(error.DecryptionFailed, rsp.consumeInitiation(msg1));
    }
    // Responder expecting a different peer → UnknownPeer.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        rsp.remote_static_public = (try Keypair.fromPrivateKey(kat.er_priv)).public;
        const msg1 = try ini.createInitiation(io, kat.timestamp);
        try testing.expectError(error.UnknownPeer, rsp.consumeInitiation(msg1));
    }
    // PSK mismatch → the responder's msg2 fails AEAD on the initiator.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        rsp.preshared_key = @splat(0x66);
        const msg1 = try ini.createInitiation(io, kat.timestamp);
        try rsp.consumeInitiation(msg1); // psk not mixed until message 2
        const msg2 = try rsp.createResponse(io);
        try testing.expectError(error.DecryptionFailed, ini.consumeResponse(msg2));
    }
    // Tampered response mac1 / ciphertext.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        const msg1 = try ini.createInitiation(io, kat.timestamp);
        try rsp.consumeInitiation(msg1);
        var msg2 = try rsp.createResponse(io);
        var bad = msg2;
        bad.mac1[5] ^= 1;
        try testing.expectError(error.InvalidMac1, ini.consumeResponse(bad));
        msg2.encrypted_nothing[0] ^= 1;
        msg2.mac1 = rsp.computeMac1(std.mem.asBytes(&msg2)[0..@offsetOf(MessageResponse, "mac1")]);
        try testing.expectError(error.DecryptionFailed, ini.consumeResponse(msg2));
    }
}

test "hostile: an all-zero ephemeral (X25519 identity element) is rejected, not crashed on" {
    // Every DH in this handshake feeds an attacker-controlled public key
    // (`unencrypted_ephemeral` travels in the clear) straight into
    // `X25519.scalarmult`, which is `IdentityElementError!` — std itself
    // rejects the all-zero output an all-zero/low-order input point
    // produces (RFC 7748's contributory-behaviour concern). Both `catch
    // return error.InvalidPublicKey`/`DecryptionFailed` sites this exercises
    // are real code, but nothing in the suite ever supplies a key that
    // trips them: every KAT and every other adversarial test uses a
    // genuine, non-degenerate ephemeral. This is the identity-element case
    // the module doc's own DH calls implicitly assume can't reach them
    // unhandled.
    const io = std.testing.io;

    // Responder side: initiator's message 1 carries an all-zero ephemeral.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        var msg1 = try ini.createInitiation(io, kat.timestamp);
        msg1.unencrypted_ephemeral = @splat(0);
        msg1.mac1 = ini.computeMac1(std.mem.asBytes(&msg1)[0..@offsetOf(MessageInitiation, "mac1")]);
        try testing.expectError(error.DecryptionFailed, rsp.consumeInitiation(msg1));
    }
    // Initiator side: responder's message 2 carries an all-zero ephemeral.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        const msg1 = try ini.createInitiation(io, kat.timestamp);
        try rsp.consumeInitiation(msg1);
        var msg2 = try rsp.createResponse(io);
        msg2.unencrypted_ephemeral = @splat(0);
        msg2.mac1 = rsp.computeMac1(std.mem.asBytes(&msg2)[0..@offsetOf(MessageResponse, "mac1")]);
        try testing.expectError(error.DecryptionFailed, ini.consumeResponse(msg2));
    }
}

test "auth failure does not corrupt pending initiator state" {
    const io = std.testing.io;
    var ini = kat.initiator();
    var rsp = kat.responder();
    const msg1 = try ini.createInitiation(io, kat.timestamp);
    try rsp.consumeInitiation(msg1);
    const msg2 = try rsp.createResponse(io);

    var forged = msg2;
    forged.encrypted_nothing[7] ^= 1;
    forged.mac1 = rsp.computeMac1(std.mem.asBytes(&forged)[0..@offsetOf(MessageResponse, "mac1")]);
    try testing.expectError(error.DecryptionFailed, ini.consumeResponse(forged));

    // The genuine response still completes the handshake afterwards.
    try ini.consumeResponse(msg2);
    const ki = ini.deriveTransportKeys(true);
    try testing.expectEqual(kat.t_initiator_send, ki.send);
}

test "call-order errors" {
    const io = std.testing.io;
    var ini = kat.initiator();
    _ = try ini.createInitiation(io, kat.timestamp);
    try testing.expectError(error.AlreadyStarted, ini.createInitiation(io, kat.timestamp));

    var rsp = kat.responder();
    try testing.expectError(error.NoInitiationConsumed, rsp.createResponse(io));

    var idle = kat.initiator();
    const msg2: MessageResponse = std.mem.zeroes(MessageResponse);
    try testing.expectError(error.NoPendingInitiation, idle.consumeResponse(msg2));
}

// ── cookie / mac2 KAT (independent reference for whitepaper 5.4.7) ─────────
//
// No official cookie test vector is published by the WireGuard project (the
// same situation as the full handshake above), so this vector was produced by
// an INDEPENDENT implementation of 5.4.7 — Python `hashlib.blake2s` (keyed,
// 16-byte parameterised output) for the MACs and libsodium's
// `crypto_aead_xchacha20poly1305_ietf_encrypt` (via PyNaCl) for the XAEAD —
// written straight from the protocol description and sharing no code with
// this file. Its inputs are the ALREADY-ANCHORED KAT initiation above: the
// generator recomputes that message's mac1 from `LABEL_MAC1 || Sr_pub` and
// asserts it equals the pinned byte, which is what ties this vector to the
// same protocol as the rest of the module rather than to our encoder.
const cookie_kat = struct {
    /// `Rm`, the responder's rotating secret.
    const secret = hex("606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f");
    /// The XAEAD nonce (fixed here; random in production).
    const nonce = hex("a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7");
    /// `Am` — an opaque source-address blob (192.0.2.33 : 51820).
    const addr = hex("c0000221ca6c");
    /// A different source address, for the anti-spoofing assertions.
    const other_addr = hex("c000020bca6c");
    /// The responder's static public key (`X25519(sr_priv, base)`).
    const responder_pub = hex("79a631eede1bf9c98f12032cdeadd0e7a079398fc786b88cc846ec89af85a51a");
    /// `HASH(LABEL_COOKIE || Sr_pub)`.
    const cookie_key = hex("ee8d30ab43585e5d27713eb4488a5f275a6a7e26d5ccf3bbbd6f4b8b53a21975");
    /// `cookie = MAC(Rm, Am)`.
    const cookie = hex("c8ee034b61e95b02fd1c9a49446b57d6");
    /// `MAC(cookie, kat.msg1[0 .. offsetof(mac2)])` — the mac2 the initiator
    /// stamps on its retry once it holds that cookie.
    const mac2 = hex("44160b966e907b635f23ae541472f9a1");
    /// The whole 64-byte type-3 reply, byte for byte.
    const reply = hex(
        "0300000011111111a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7" ++
            "72de0f334caad275e56c278656d0c2a55e2bc097c515e4d2426a1cd7cd15530f",
    );
};

fn expectAdmission(actual: Admission, want: std.meta.Tag(Admission)) !void {
    try testing.expectEqual(want, std.meta.activeTag(actual));
}

test "KAT: cookie reply and mac2 byte-exact against the independent reference" {
    const io = std.testing.io;

    // The message being answered is the pinned KAT initiation.
    const f = try macFields(&kat.msg1);
    try testing.expectEqual(kat.idx_i, f.sender_index);
    try testing.expectEqual(@as(usize, 148 - 32), f.mac1_input.len);
    try testing.expectEqual(@as(usize, 148 - 16), f.mac2_input.len);
    // The sender held no cookie, so it sent the protocol's all-zero mac2 —
    // which is exactly the case a loaded responder has to answer.
    try testing.expectEqual(@as(noise.Mac, @splat(0)), f.mac2);

    const rpub = (try Keypair.fromPrivateKey(kat.sr_priv)).public;
    try testing.expectEqual(cookie_kat.responder_pub, rpub);
    try testing.expectEqual(cookie_kat.cookie_key, noise.cookieKey(rpub));

    var checker = CookieChecker.initWithSecret(rpub, cookie_kat.secret, 1_000);
    try testing.expectEqual(cookie_kat.cookie, checker.cookieFor(io, 1_000, &cookie_kat.addr));

    const reply = checker.createReplyWithNonce(io, 1_000, f, &cookie_kat.addr, cookie_kat.nonce);
    try testing.expectEqualSlices(u8, &cookie_kat.reply, std.mem.asBytes(&reply));

    // The retry the initiator then sends: identical to the pinned initiation
    // up to mac2 (the cookie changes nothing inside the Noise transcript) and
    // carrying the reference's mac2, which the responder accepts.
    var ini = kat.initiator();
    ini.cookie = cookie_kat.cookie;
    const retry = try ini.createInitiation(io, kat.timestamp);
    try testing.expectEqualSlices(u8, kat.msg1[0 .. 148 - 16], std.mem.asBytes(&retry)[0 .. 148 - 16]);
    try testing.expectEqual(cookie_kat.mac2, retry.mac2);
    try testing.expect(checker.checkMac2(
        io,
        1_000,
        try macFields(std.mem.asBytes(&retry)),
        &cookie_kat.addr,
    ));

    // Without a cookie the same message still goes out with an all-zero mac2 —
    // the pre-existing behavior, unchanged.
    var plain = kat.initiator();
    const first = try plain.createInitiation(io, kat.timestamp);
    try testing.expectEqual(@as(noise.Mac, @splat(0)), first.mac2);
    try testing.expectEqualSlices(u8, &kat.msg1, std.mem.asBytes(&first));
}

test "cookie reply: our decryptor opens the independent reference's bytes, and is AAD-bound" {
    var reply: CookieReply = undefined;
    @memcpy(std.mem.asBytes(&reply), &cookie_kat.reply);
    try testing.expectEqual(@intFromEnum(MessageType.cookie_reply), reply.type);
    try testing.expectEqual(kat.idx_i, reply.receiver_index);

    var peer = PeerCookie.init(cookie_kat.responder_pub);
    // Nothing sent yet → no associated data → nothing this could answer.
    try testing.expectError(error.NoPendingMessage, peer.consumeReply(reply, 5));

    try peer.recordSent(&kat.msg1);
    try peer.consumeReply(reply, 5);
    try testing.expectEqual(cookie_kat.cookie, peer.cookie.?);

    // The reply is bound to the mac1 of the message it answers: replayed
    // against a different sent message it does not open, and the cookie we
    // already hold survives the failure.
    try peer.recordSent(&kat.msg2);
    try testing.expectError(error.DecryptionFailed, peer.consumeReply(reply, 9));
    try testing.expectEqual(cookie_kat.cookie, peer.cookie.?);
    try testing.expectEqual(@as(u64, 5), peer.cookie_born_s);

    // A tampered ciphertext does not open either.
    try peer.recordSent(&kat.msg1);
    var bad = reply;
    bad.encrypted_cookie[0] ^= 1;
    try testing.expectError(error.DecryptionFailed, peer.consumeReply(bad, 9));
}

test "admit: a mac1-only flood is shed under load until the cookie round trip completes" {
    const io = std.testing.io;
    const rpub = (try Keypair.fromPrivateKey(kat.sr_priv)).public;
    var checker = CookieChecker.init(rpub, io, 1_000); // random secret, as in production
    defer checker.wipe();

    var ini = kat.initiator();
    const msg1 = try ini.createInitiation(io, kat.timestamp);
    const bytes1 = std.mem.asBytes(&msg1);

    // Not under load: mac1 is all that is asked for (today's behavior).
    try expectAdmission(checker.admit(io, 1_000, bytes1, &cookie_kat.addr, false), .accept);

    // Under load, mac1 alone buys nothing: the responder answers with 64 bytes
    // and does zero asymmetric work.
    const adm = checker.admit(io, 1_000, bytes1, &cookie_kat.addr, true);
    const reply = switch (adm) {
        .cookie_reply => |r| r,
        else => return error.TestUnexpectedResult,
    };
    try testing.expectEqual(@intFromEnum(MessageType.cookie_reply), reply.type);
    try testing.expectEqual(kat.idx_i, reply.receiver_index);

    // The genuine initiator — which, unlike a spoofed source, actually
    // receives the reply — retries with a valid mac2 and is admitted.
    var peer = PeerCookie.init(rpub);
    try peer.recordSent(bytes1);
    try peer.consumeReply(reply, 1_000);
    var ini2 = kat.initiator();
    ini2.cookie = peer.current(1_000);
    try testing.expect(ini2.cookie != null);
    const retry = try ini2.createInitiation(io, kat.timestamp);
    const bytes2 = std.mem.asBytes(&retry);
    try expectAdmission(checker.admit(io, 1_000, bytes2, &cookie_kat.addr, true), .accept);

    // THE anti-spoofing claim: the cookie is a MAC of the source address, so
    // the very same mac2-bearing message replayed from another address is
    // still shed.
    try expectAdmission(
        checker.admit(io, 1_000, bytes2, &cookie_kat.other_addr, true),
        .cookie_reply,
    );

    // Unauthenticated junk is dropped silently, never answered: a bad mac1, a
    // truncated datagram, and a type we do not MAC.
    var forged = msg1;
    forged.mac1[0] ^= 1;
    try expectAdmission(
        checker.admit(io, 1_000, std.mem.asBytes(&forged), &cookie_kat.addr, true),
        .drop,
    );
    try expectAdmission(checker.admit(io, 1_000, bytes1[0..100], &cookie_kat.addr, true), .drop);
    try expectAdmission(
        checker.admit(io, 1_000, &cookie_kat.reply, &cookie_kat.addr, true),
        .drop,
    );

    // A response (type 2) travels the same gate — mac2 is on both message types.
    var rsp = kat.responder();
    try rsp.consumeInitiation(msg1);
    const msg2 = try rsp.createResponse(io);
    try expectAdmission(
        checker.admit(io, 1_000, std.mem.asBytes(&msg2), &cookie_kat.addr, false),
        .drop, // msg2's mac1 is keyed on the INITIATOR's static key, not ours
    );
}

test "cookie secret rotates after two minutes, on both sides of the exchange" {
    const io = std.testing.io;
    const rpub = cookie_kat.responder_pub;

    // The two-minute figure itself, pinned (whitepaper 5.4.7 "every two
    // minutes"). The behavioral assertions below use literal seconds, not
    // these constants, so moving the value goes red here AND there.
    try testing.expectEqual(@as(u64, 120), cookie_secret_lifetime_s);
    try testing.expectEqual(@as(u64, 120), cookie_lifetime_s);

    var checker = CookieChecker.initWithSecret(rpub, cookie_kat.secret, 1_000);
    const at_0 = checker.cookieFor(io, 1_000, &cookie_kat.addr);
    try testing.expectEqual(cookie_kat.cookie, at_0);

    // 119 s in: same secret, same cookie.
    try testing.expectEqual(at_0, checker.cookieFor(io, 1_119, &cookie_kat.addr));
    try testing.expectEqual(cookie_kat.secret, checker.secret);

    // 120 s in: rolled, and every cookie issued under the old secret dies.
    const at_120 = checker.cookieFor(io, 1_120, &cookie_kat.addr);
    try testing.expect(!std.mem.eql(u8, &at_0, &at_120));
    try testing.expect(!std.mem.eql(u8, &cookie_kat.secret, &checker.secret));
    try testing.expectEqual(@as(u64, 1_120), checker.secret_born_s);

    // A clock that jumps backwards rolls it too, rather than extending its life.
    const rolled = checker.secret;
    _ = checker.cookieFor(io, 999, &cookie_kat.addr);
    try testing.expect(!std.mem.eql(u8, &rolled, &checker.secret));

    // wipe() ends the secret's life immediately.
    checker.wipe();
    try testing.expectEqual(@as([32]u8, @splat(0)), checker.secret);

    // Initiator side: the same two minutes bound how long a cookie is stamped.
    var peer = PeerCookie.init(rpub);
    peer.cookie = cookie_kat.cookie;
    peer.cookie_born_s = 1_000;
    try testing.expectEqual(cookie_kat.cookie, peer.current(1_119).?);
    try testing.expectEqual(@as(?noise.Mac, null), peer.current(1_120));
    try testing.expectEqual(@as(?noise.Mac, null), peer.current(999));
    try testing.expectEqual(@as(?noise.Mac, null), (PeerCookie.init(rpub)).current(1_000));
}

test "macFields admits exactly the two handshake message shapes" {
    var buf: [200]u8 = undefined;
    @memset(&buf, 0);

    // Too short to even hold a type tag and an index.
    try testing.expectError(error.NotAHandshakeMessage, macFields(buf[0..7]));
    // Right type, wrong length — both directions.
    @memcpy(buf[0..148], &kat.msg1);
    try testing.expectError(error.NotAHandshakeMessage, macFields(buf[0..147]));
    try testing.expectError(error.NotAHandshakeMessage, macFields(buf[0..149]));
    _ = try macFields(buf[0..148]);
    // A response's bytes are 92, not 148: mislabeling either way is rejected.
    @memcpy(buf[0..92], &kat.msg2);
    _ = try macFields(buf[0..92]);
    std.mem.writeInt(u32, buf[0..4], @intFromEnum(MessageType.handshake_initiation), .little);
    try testing.expectError(error.NotAHandshakeMessage, macFields(buf[0..92]));
    // Types the cookie layer does not MAC.
    for ([_]u32{ 0, 3, 4, 5, 0xFFFF_FFFF }) |t| {
        std.mem.writeInt(u32, buf[0..4], t, .little);
        try testing.expectError(error.NotAHandshakeMessage, macFields(buf[0..92]));
        try testing.expectError(error.NotAHandshakeMessage, macFields(buf[0..148]));
    }
    // recordSent inherits the same gate rather than storing garbage as a mac1.
    var peer = PeerCookie.init(cookie_kat.responder_pub);
    try testing.expectError(error.NotAHandshakeMessage, peer.recordSent(buf[0..64]));
    try testing.expectEqual(@as(?noise.Mac, null), peer.last_sent_mac1);
}

// ── integration test (real kernel WireGuard as the protocol oracle) ────────
//
// Gated like root.zig's netlink integration tests: Linux + euid 0 (run under
// `unshare -rn` for an isolated netns with CAP_NET_ADMIN) + the `ip`/`wg`
// tools + the wireguard kernel module, else `error.SkipZigTest`.
//
// The KERNEL plays the initiator (so it owns TAI64N clocking and retries);
// we are the responder on a plain UDP socket. Proof of key agreement: the
// kernel's post-handshake keepalive — a transport-data packet encrypted by
// the kernel under ITS T_send — must AEAD-decrypt under OUR derived
// `recv` key. That authenticates the entire handshake (both messages, PSK
// mix and transport-key split) against an implementation we did not write.

/// Run an external command; `error.SkipZigTest` when it cannot be spawned.
fn runCmd(gpa: std.mem.Allocator, io: std.Io, argv: []const []const u8) !u8 {
    const res = std.process.run(gpa, io, .{ .argv = argv }) catch return error.SkipZigTest;
    defer gpa.free(res.stdout);
    defer gpa.free(res.stderr);
    return switch (res.term) {
        .exited => |code| code,
        else => 255,
    };
}

/// Print an external command's output; `false` when it could not be spawned.
/// Diagnostics only, on a failure path — a failing diagnostic must never
/// replace the real error, so this reports and returns rather than failing.
fn dumpCmd(gpa: std.mem.Allocator, io: std.Io, argv: []const []const u8) bool {
    const res = std.process.run(gpa, io, .{ .argv = argv }) catch return false;
    defer gpa.free(res.stdout);
    defer gpa.free(res.stderr);
    std.debug.print("  --- ", .{});
    for (argv) |a| std.debug.print("{s} ", .{a});
    std.debug.print("---\n{s}{s}", .{ res.stdout, res.stderr });
    return true;
}

/// The netfilter ruleset, which is the first thing an EPERM from `sendto`
/// asks about. `nft` usually lives in sbin, which spawn's PATH lookup may not
/// cover — `modules/nftables` carries the same candidate list for the same
/// reason.
fn dumpRuleset(gpa: std.mem.Allocator, io: std.Io) void {
    for ([_][]const u8{ "nft", "/usr/sbin/nft", "/sbin/nft" }) |argv0| {
        if (dumpCmd(gpa, io, &.{ argv0, "list", "ruleset" })) return;
    }
    std.debug.print("  (no nft binary — netfilter state unknown)\n", .{});
}

/// Wall-clock seconds for the live interop test — the one place in this module
/// that needs a real clock, and it is a *test harness*, which is exactly the
/// role `transport.zig` assigns to the caller. Product code here never reads a
/// clock; it takes `now_s`.
fn nowSeconds() u64 {
    var ts: std.os.linux.timespec = undefined;
    _ = std.os.linux.clock_gettime(.REALTIME, &ts);
    return @intCast(ts.sec);
}

test "integration (root): live handshake with kernel WireGuard, keepalive decrypts" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    const linux = std.os.linux;
    if (linux.geteuid() != 0) return error.SkipZigTest; // needs CAP_NET_ADMIN
    const gpa = testing.allocator;

    var threaded = std.Io.Threaded.init(gpa, .{});
    defer threaded.deinit();
    const io = threaded.io();

    // Fresh identities: ours (userspace responder) and the kernel's.
    const our_kp = Keypair.generate(io);
    const kernel_kp = Keypair.generate(io);
    var psk: PresharedKey = undefined;
    io.random(&psk);

    // UDP socket on loopback; the kernel peer's endpoint points at it.
    const sock_rc = linux.socket(linux.AF.INET, linux.SOCK.DGRAM | linux.SOCK.CLOEXEC, 0);
    if (linux.errno(sock_rc) != .SUCCESS) return error.SkipZigTest;
    const fd: i32 = @intCast(sock_rc);
    defer _ = linux.close(fd);
    var bind_addr: linux.sockaddr.in = .{
        .port = 0,
        .addr = std.mem.nativeToBig(u32, 0x7f000001), // 127.0.0.1
    };
    if (linux.errno(linux.bind(fd, @ptrCast(&bind_addr), @sizeOf(linux.sockaddr.in))) != .SUCCESS)
        return error.SkipZigTest;
    var bound: linux.sockaddr.in = undefined;
    var bound_len: linux.socklen_t = @sizeOf(linux.sockaddr.in);
    try testing.expectEqual(
        .SUCCESS,
        linux.errno(linux.getsockname(fd, @ptrCast(&bound), &bound_len)),
    );
    const our_port = std.mem.bigToNative(u16, bound.port);

    // Kernel-side device: our public key as its peer, endpoint = our socket,
    // persistent keepalive so the kernel initiates immediately. Configured
    // through this module's OWN genl control plane (root.zig) — not the `wg`
    // tool, which Ubuntu's AppArmor profile confines to /etc/wireguard key
    // files — dogfooding both halves of the module in one test.
    const wgctl = @import("root.zig");
    const ifname = "zigwghs0";
    if (try runCmd(gpa, io, &.{ "ip", "link", "add", ifname, "type", "wireguard" }) != 0)
        return error.SkipZigTest; // wireguard module unavailable
    defer _ = runCmd(gpa, io, &.{ "ip", "link", "del", ifname }) catch {};
    _ = try runCmd(gpa, io, &.{ "ip", "link", "set", "lo", "up" }); // fresh netns has lo down
    var wg = wgctl.Wireguard.open(gpa) catch return error.SkipZigTest;
    defer wg.close();
    try wg.setDevice(.{
        .ifname = ifname,
        .private_key = kernel_kp.private,
        .peers = &.{.{
            .public_key = our_kp.public,
            .preshared_key = psk,
            .endpoint = .{ .v4 = .{ .addr = .{ 127, 0, 0, 1 }, .port = our_port } },
            .persistent_keepalive_interval = 1,
        }},
    });
    try testing.expectEqual(@as(u8, 0), try runCmd(gpa, io, &.{ "ip", "link", "set", ifname, "up" }));

    // Responder state: we know the kernel's static public key (Noise IK).
    // A `Handshake` consumes exactly one initiation (`consumeInitiation`
    // asserts `state == .idle`), so a RETRY needs a fresh one — see the
    // initiation branch below.
    const freshHandshake = struct {
        fn make(kp: Keypair, remote: [32]u8, k: [32]u8) Handshake {
            return .{
                .static_keypair = kp,
                .remote_static_public = remote,
                .preshared_key = k,
                .local_index = 0x5a5a5a5a,
            };
        }
    }.make;
    var hs: Handshake = freshHandshake(our_kp, kernel_kp.public, psk);
    var session: ?transport.Session = null;

    // Exercise the retry path on every run instead of waiting for a loaded
    // machine to produce it: the FIRST response is deliberately not sent, so
    // the kernel's rekey timer must fire and re-initiate, and this responder
    // must handle that second initiation as a new handshake. Without that,
    // one lost or late response strands the test for its whole budget — which
    // is exactly how this test failed 1-in-60 under load (see
    // `~/CML/20260808-zig-libs-audit/modules/wireguard.md`, 2026-08-12).
    var drop_first_response = true;

    // Drive the exchange: initiation in → response out → keepalive in.
    var buf: [2048]u8 = undefined;
    // 60 × 500 ms = 30 s. The old budget was 20 s for a clean exchange; the
    // injected loss above deliberately costs one kernel REKEY_TIMEOUT (5 s,
    // plus up to 333 ms of jitter) before the retry arrives, so the budget
    // covers that on purpose rather than being widened to hide a race.
    var polls_left: u32 = 60;
    while (polls_left > 0) : (polls_left -= 1) {
        var pfd = [1]linux.pollfd{.{ .fd = fd, .events = linux.POLL.IN, .revents = 0 }};
        const prc = linux.poll(&pfd, 1, 500);
        try testing.expectEqual(.SUCCESS, linux.errno(prc));
        if (prc == 0) continue;

        var src: linux.sockaddr.in = undefined;
        var src_len: linux.socklen_t = @sizeOf(linux.sockaddr.in);
        const rrc = linux.recvfrom(fd, &buf, buf.len, 0, @ptrCast(&src), &src_len);
        try testing.expectEqual(.SUCCESS, linux.errno(rrc));
        const n = rrc;
        if (n < 4) continue;

        switch (std.mem.readInt(u32, buf[0..4], .little)) {
            @intFromEnum(MessageType.handshake_initiation) => {
                if (n != @sizeOf(MessageInitiation)) continue;
                // A retry is a NEW handshake, not a duplicate of the one we
                // already answered: the kernel picks fresh ephemerals, so the
                // response we sent for the previous initiation is dead to it.
                // Answering the retry is therefore mandatory, and this code
                // used to `continue` past it — which meant a single lost or
                // late response could never be recovered from.
                if (hs.state != .idle) {
                    hs = freshHandshake(our_kp, kernel_kp.public, psk);
                    session = null;
                }
                var msg1: MessageInitiation = undefined;
                @memcpy(std.mem.asBytes(&msg1), buf[0..@sizeOf(MessageInitiation)]);
                try hs.consumeInitiation(msg1);
                var msg2 = try hs.createResponse(io);
                // Through the real data-plane API, not a hand-rolled AEAD
                // call: this is what makes the kernel an oracle for
                // `transport.zig`'s framing, not only for the handshake.
                session = hs.transportSession(false, nowSeconds());
                if (drop_first_response) {
                    // The injected loss. Everything above already ran, so the
                    // kernel's rekey timer is what has to rescue this — the
                    // very path the retry handling above exists for.
                    drop_first_response = false;
                    continue;
                }
                const src_len_const: linux.socklen_t = src_len;
                const wrc = linux.sendto(
                    fd,
                    std.mem.asBytes(&msg2),
                    @sizeOf(MessageResponse),
                    0,
                    @ptrCast(&src),
                    src_len_const,
                );
                // A blink here is expensive to diagnose after the fact: the
                // errno alone cannot tell a netfilter LOCAL_OUT/POSTROUTING
                // drop (which the kernel reports as EPERM) from a cgroup BPF
                // egress program (also EPERM, and orthogonal to the network
                // namespace) from a malformed destination. Print what
                // separates them, so one future occurrence is conclusive
                // instead of costing another reproduction campaign.
                if (linux.errno(wrc) != .SUCCESS) {
                    var self_addr: linux.sockaddr.in = undefined;
                    var self_len: linux.socklen_t = @sizeOf(linux.sockaddr.in);
                    const gs = linux.getsockname(fd, @ptrCast(&self_addr), &self_len);
                    std.debug.print(
                        "\nwireguard live interop: sendto failed\n" ++
                            "  errno={s} ret={d}\n" ++
                            "  dst: family={d} addr=0x{x:0>8} port={d} (addrlen={d}, sizeof(sockaddr_in)={d})\n" ++
                            "  src: family={d} addr=0x{x:0>8} port={d} (getsockname errno={s})\n" ++
                            "  cgroup: ",
                        .{
                            @tagName(linux.errno(wrc)),
                            @as(isize, @bitCast(wrc)),
                            src.family,
                            std.mem.bigToNative(u32, src.addr),
                            std.mem.bigToNative(u16, src.port),
                            src_len_const,
                            @sizeOf(linux.sockaddr.in),
                            self_addr.family,
                            std.mem.bigToNative(u32, self_addr.addr),
                            std.mem.bigToNative(u16, self_addr.port),
                            @tagName(linux.errno(gs)),
                        },
                    );
                    _ = dumpCmd(gpa, io, &.{ "cat", "/proc/self/cgroup" });
                    dumpRuleset(gpa, io);
                    _ = dumpCmd(gpa, io, &.{ "ip", "-o", "addr" });
                    _ = dumpCmd(gpa, io, &.{ "ip", "-o", "link" });
                    _ = dumpCmd(gpa, io, &.{ "ip", "route", "show", "table", "all" });
                }
                try testing.expectEqual(.SUCCESS, linux.errno(wrc));
                try testing.expectEqual(@sizeOf(MessageResponse), wrc);
            },
            @intFromEnum(MessageType.transport_data) => {
                // Keepalive: 16-byte header + empty plaintext + 16-byte tag —
                // i.e. `transport.sealedLen(0)`, which is what the protocol's
                // "pad to a multiple of 16" rule yields for an EMPTY payload
                // (a rule that padded 0 up to 16 would make this 48).
                if (n != transport.sealedLen(0)) continue;
                if (session == null) continue; // transport before our response? ignore
                const sess = &session.?;
                try testing.expectEqual(hs.local_index, std.mem.readInt(u32, buf[4..8], .little));
                var empty: [0]u8 = .{};
                // THE oracle assertion: a kernel-encrypted packet opens
                // through our data-plane API under our derived receive key.
                // Everything the kernel had to agree with us about is in this
                // one call — nonce layout and endianness, empty AAD, header
                // layout, receiver index, and the padding rule.
                const r = try sess.recv.open(&empty, buf[0..n], nowSeconds());
                try testing.expectEqual(@as(usize, 0), r.len);
                return; // interop proven
            },
            else => continue,
        }
    }
    std.debug.print("kernel WireGuard interop: no decryptable keepalive within budget\n", .{});
    return error.TestUnexpectedResult;
}
