// SPDX-License-Identifier: MIT
//! Noise_IKpsk2 handshake — the WireGuard cryptographic session handshake:
//! message wire layouts (`MessageInitiation`/`MessageResponse`/`CookieReply`/
//! `MessageTransport`) and the `Handshake` state machine that produces and
//! consumes them, ending in a split pair of transport data-plane keys.
//!
//! This is the DATA-PLANE crypto handshake — distinct from (and independent
//! of) `../src/root.zig` (plus the `genetlink` module it builds on), which
//! speak the kernel's genetlink CONTROL-plane protocol (`wg`-style
//! device/peer configuration).
//! A handshake never touches netlink; a configured `Wireguard` device never
//! touches Noise. Both live under the one `wireguard` module because they
//! are the same protocol's two halves.
//!
//! Verification: a fixed-input known-answer test (deterministic static +
//! ephemeral keys, PSK, timestamp and indices) asserts the exact 148-byte
//! `MessageInitiation`, 92-byte `MessageResponse` and both transport keys
//! against a vector generated by an independent reference implementation
//! (Python: hashlib BLAKE2s/HMAC + OpenSSL X25519/ChaCha20-Poly1305 via
//! cryptography.io), itself validated against the wireguard-go KDF vectors
//! (no official full-handshake vector is published by the WireGuard
//! project). A gated integration test additionally completes a live
//! handshake as responder against the Linux kernel's WireGuard
//! implementation and decrypts a kernel-encrypted transport packet with the
//! derived keys. See `noise.zig` for the Noise primitives this state
//! machine is built on.
//!
//! Provenance: clean-room from the WireGuard protocol description
//! (J. A. Donenfeld, "WireGuard: Next Generation Kernel Network Tunnel",
//! NDSS 2017, https://www.wireguard.com/papers/wireguard.pdf, and
//! https://www.wireguard.com/protocol/), which documents the exact message
//! layouts and handshake steps reserved below. Design reference:
//! wireguard-go (golang.zx2c4.com/wireguard, MIT) and the Linux kernel
//! WireGuard implementation (GPL-2.0) — behavior/shape only; the message
//! layout and handshake step order are the standardized wire protocol, not
//! copyrightable expression; no source consulted or copied. See ../NOTICE.

const std = @import("std");
const builtin = @import("builtin");
const noise = @import("noise.zig");

comptime {
    // Option (a) of the endianness note below: the mac1/mac2 computations and
    // the KAT/interop tests view the extern structs as wire bytes via
    // `std.mem.asBytes`, which is only byte-exact on a little-endian host
    // (matching the sibling `root.zig` and the `genetlink` module, which
    // assume native endianness). Port the u32/u64 fields to explicit `std.mem.writeInt`
    // encoding before lifting this guard.
    std.debug.assert(builtin.cpu.arch.endian() == .little);
}

// Note: `pub const meta` is declared once, canonically, in `root.zig` (per
// CONVENTIONS.md §4) — submodule files like this one do not repeat it. This
// file itself has no dependency on `netlink`/`genetlink` (those are the
// sibling control-plane half of the module, in root.zig).

// ── message type tag (first 4 bytes of every WireGuard wire message) ───────

/// `message_type` values — the little-endian `u32` at offset 0 of every
/// WireGuard wire message, used to dispatch an incoming UDP datagram.
pub const MessageType = enum(u32) {
    handshake_initiation = 1,
    handshake_response = 2,
    cookie_reply = 3,
    transport_data = 4,
    _,
};

// ── key types ───────────────────────────────────────────────────────────────

/// Raw X25519 scalar (private/secret key), 32 bytes.
pub const PrivateKey = [noise.X25519.secret_length]u8;
/// Raw X25519 point (public key), 32 bytes.
pub const PublicKey = [noise.X25519.public_length]u8;
/// Pre-shared symmetric key mixed into message 2 (psk2), 32 bytes. All-zero
/// is the WireGuard convention for "no PSK configured" (mixed in anyway —
/// mixing a fixed zero key is a no-op that keeps the code path uniform).
pub const PresharedKey = [32]u8;

/// A static or ephemeral X25519 identity.
pub const Keypair = struct {
    private: PrivateKey,
    public: PublicKey,

    /// Generate a fresh keypair (used for the per-handshake ephemeral).
    /// `io` supplies entropy, matching the `sealedbox` module's convention
    /// for std.crypto operations that need randomness.
    pub fn generate(io: std.Io) Keypair {
        const kp = noise.X25519.KeyPair.generate(io);
        return .{ .private = kp.secret_key, .public = kp.public_key };
    }

    /// Rebuild a keypair from a stored private key (recomputes the public
    /// key via X25519 base-point multiplication).
    pub fn fromPrivateKey(private: PrivateKey) error{IdentityElement}!Keypair {
        return .{ .private = private, .public = try noise.X25519.recoverPublicKey(private) };
    }
};

// ── wire message layouts (WireGuard protocol, byte-exact) ──────────────────
//
// NOTE (endianness — flag for owner review): WireGuard's wire integers are
// little-endian. These are `extern struct`s so their in-memory layout
// matches the wire byte-for-byte ONLY on a little-endian host (true for all
// platforms zig-libs currently targets: x86_64/aarch64). Encoding/decoding
// MUST NOT rely on a raw `@bitCast`/`@ptrCast` of these structs if this
// module is ever built for a big-endian target — the crypto agent should
// either (a) add a `comptime { std.debug.assert(builtin.cpu.arch.endian() == .little); }`
// guard (matching this module's sibling `root.zig`/`genl.zig`, which assume
// native endianness and are linux/x86-family-only anyway), or (b) encode/
// decode the `u32`/`u64` fields explicitly via `std.mem.readInt`/`writeInt`
// with `.little`, the way `root.zig`'s `parseEndpoint`/`appendEndpoint` do
// for the netlink control-plane messages. Field order below is chosen so no
// implicit padding is inserted (every multi-byte integer field already
// falls on a naturally aligned offset).

/// Type 1 — Initiator → Responder. 148 bytes on the wire.
pub const MessageInitiation = extern struct {
    /// `MessageType.handshake_initiation` (1), little-endian.
    type: u32,
    /// Locally assigned session index; echoed back by the responder as
    /// `receiver_index` in `MessageResponse`.
    sender_index: u32,
    /// The initiator's ephemeral public key, sent in the clear.
    unencrypted_ephemeral: [32]u8,
    /// `AEAD(k, 0, initiator_static_public, Hi)` — the initiator's static
    /// public key, encrypted+authenticated (32-byte key + 16-byte Poly1305 tag).
    encrypted_static: [32 + 16]u8,
    /// `AEAD(k, 0, TAI64N(now), Hi)` — a TAI64N timestamp, encrypted (12-byte
    /// TAI64N label + 16-byte tag), used for replay/most-recent-handshake
    /// detection.
    encrypted_timestamp: [12 + 16]u8,
    /// `MAC(mac1_key, message[0 .. end-32])` — cheap DoS-resistant check;
    /// always present.
    mac1: [16]u8,
    /// `MAC(cookie, message[0 .. end-16])` if a valid responder cookie is
    /// held, else all-zero.
    mac2: [16]u8,
};

/// Type 2 — Responder → Initiator. 92 bytes on the wire.
pub const MessageResponse = extern struct {
    /// `MessageType.handshake_response` (2), little-endian.
    type: u32,
    /// The responder's own newly assigned session index.
    sender_index: u32,
    /// Echo of the initiator's `sender_index` (`MessageInitiation.sender_index`).
    receiver_index: u32,
    /// The responder's ephemeral public key, sent in the clear.
    unencrypted_ephemeral: [32]u8,
    /// `AEAD(k, 0, ε, Hr)` — an empty-plaintext AEAD, just a 16-byte
    /// Poly1305 tag; confirms both sides agree on every derived key so far.
    encrypted_nothing: [0 + 16]u8,
    /// `MAC(mac1_key, message[0 .. end-32])`.
    mac1: [16]u8,
    /// `MAC(cookie, message[0 .. end-16])` if held, else all-zero.
    mac2: [16]u8,
};

/// Type 3 — either side → the other, only ever sent in reply to a message
/// whose mac2 the receiver could not validate against its current cookie
/// (i.e. under load, as an unforgeable "here is a fresh cookie" nudge).
/// **Not part of the Noise transcript** — no chaining-key/hash mixing;
/// authenticated instead by XChaCha20-Poly1305 keyed with the sender's own
/// mac1 key and a random 24-byte nonce (so it needs no handshake state).
/// 64 bytes on the wire.
pub const CookieReply = extern struct {
    /// `MessageType.cookie_reply` (3), little-endian.
    type: u32,
    /// Echoes the `sender_index` of the message being replied to.
    receiver_index: u32,
    /// Random nonce for the `XAead` encryption below (`noise.XAead.nonce_length`).
    nonce: [24]u8,
    /// `XAEAD(cookie_key, nonce, cookie, mac1_of_replied_message)` — a fresh
    /// 16-byte cookie plus its 16-byte Poly1305 tag.
    encrypted_cookie: [16 + 16]u8,
};

/// Fixed header of type 4 (transport data) messages — 16 bytes, followed by
/// a variable-length AEAD ciphertext (plaintext IP packet + 16-byte
/// Poly1305 tag), which is why this is a header-only type rather than a
/// fixed-size `extern struct` like the handshake messages.
pub const MessageTransportHeader = extern struct {
    /// `MessageType.transport_data` (4), little-endian.
    type: u32,
    /// The receiver's session index (theirs, learned during the handshake).
    receiver_index: u32,
    /// Monotonic nonce counter, doubling as the low 8 bytes of the AEAD
    /// nonce (the high 4 bytes are always zero, per the Noise/WireGuard
    /// convention of a 12-byte nonce = 4 zero bytes || 8-byte LE counter).
    counter: u64,
};

/// A full transport-data message: fixed header plus a caller-owned
/// ciphertext slice. Not an `extern struct` (variable length).
pub const MessageTransport = struct {
    header: MessageTransportHeader,
    /// `AEAD(T_send, counter, plaintext_packet, ε)` — ciphertext + 16-byte tag.
    ciphertext: []const u8,
};

comptime {
    // Byte-exact wire sizes (WireGuard protocol) — guards against accidental
    // padding if a field is ever reordered.
    std.debug.assert(@sizeOf(MessageInitiation) == 148);
    std.debug.assert(@sizeOf(MessageResponse) == 92);
    std.debug.assert(@sizeOf(CookieReply) == 64);
    std.debug.assert(@sizeOf(MessageTransportHeader) == 16);
}

// ── handshake state machine ─────────────────────────────────────────────────

/// One in-flight Noise_IKpsk2 handshake attempt (initiator or responder
/// side — the same struct plays both roles depending which method is
/// called first). Single-owner: one `Handshake` per session attempt, not
/// shared across threads.
pub const Handshake = struct {
    /// Our long-term (static) identity keypair.
    static_keypair: Keypair,
    /// The peer's long-term public key — known ahead of time (Noise `IK`:
    /// the initiator already knows the responder's static key).
    remote_static_public: PublicKey,
    /// Pre-shared key (psk2 — mixed in message 2). All-zero if unconfigured.
    preshared_key: PresharedKey = @splat(0),

    /// Our ephemeral keypair for this attempt, generated on the first step
    /// we take (`createInitiation` for the initiator, `createResponse` for
    /// the responder).
    local_ephemeral: ?Keypair = null,
    /// The peer's ephemeral public key, learned from their message.
    remote_ephemeral: ?PublicKey = null,

    /// Noise chaining key `ck` — the running KDF ratchet state.
    chaining_key: noise.ChainKey = undefined,
    /// Noise transcript hash `h`.
    hash: noise.HandshakeHash = undefined,

    /// Our locally assigned session index (goes out as `sender_index` on
    /// our own messages).
    local_index: u32 = 0,
    /// The peer's session index, learned from their message (goes out as
    /// `receiver_index` on our replies / all transport packets to them).
    remote_index: u32 = 0,

    /// The initiator's decrypted TAI64N timestamp, recorded by
    /// `consumeInitiation` so the caller can do the required per-peer
    /// most-recent-handshake bookkeeping (this module keeps no cross-attempt
    /// state, so it cannot reject `StaleTimestamp` itself).
    remote_timestamp: ?[12]u8 = null,

    /// Which step this attempt has completed — enforces the call order
    /// (`createInitiation` → `consumeResponse` for the initiator,
    /// `consumeInitiation` → `createResponse` for the responder).
    state: enum { idle, initiation_sent, initiation_consumed, complete } = .idle,

    pub const InitiationError = error{
        /// `local_ephemeral`/`chaining_key` already set — call once per attempt.
        AlreadyStarted,
        /// `remote_static_public` is a low-order/identity X25519 point.
        InvalidPublicKey,
    };
    pub const ConsumeInitiationError = error{
        /// mac1 did not match `HASH(LABEL_MAC1 || our_static_public)`.
        InvalidMac1,
        /// The encrypted static key or timestamp failed AEAD authentication
        /// (or the peer's ephemeral/static key was a low-order X25519 point
        /// — fail closed, indistinguishably from a bad tag).
        DecryptionFailed,
        /// Decrypted static key does not match a known peer (caller-side
        /// peer lookup failed before/while calling this).
        UnknownPeer,
        /// Timestamp is not newer than the last one seen from this peer
        /// (replay / out-of-order handshake rejection). Never returned here
        /// — reserved for callers doing the cross-attempt bookkeeping over
        /// `remote_timestamp` (see that field).
        StaleTimestamp,
    };
    pub const ResponseError = error{
        /// A response was already created for this attempt.
        AlreadyStarted,
        /// `consumeInitiation` has not succeeded on this handshake yet.
        NoInitiationConsumed,
        /// A peer key is a low-order/identity X25519 point.
        InvalidPublicKey,
    };
    pub const ConsumeResponseError = error{
        InvalidMac1,
        /// The empty-plaintext AEAD tag failed to verify (also covers a
        /// low-order ephemeral from the peer and a PSK mismatch — all
        /// indistinguishable by design).
        DecryptionFailed,
        /// This handshake never sent a `MessageInitiation` to respond to.
        NoPendingInitiation,
    };

    /// `Ck0/H0` derivation shared by both roles (whitepaper 5.4.2 first
    /// three lines): `ck = HASH(CONSTRUCTION)`, `h = HASH(ck || IDENTIFIER)`,
    /// `h = HASH(h || responder_static_public)`.
    fn initialState(responder_static_public: PublicKey) struct { ck: noise.ChainKey, h: noise.HandshakeHash } {
        var ck: noise.ChainKey = undefined;
        noise.Blake2s.hash(noise.CONSTRUCTION, &ck, .{});
        var h: noise.HandshakeHash = ck;
        noise.mixHash(&h, noise.IDENTIFIER);
        noise.mixHash(&h, &responder_static_public);
        return .{ .ck = ck, .h = h };
    }

    /// The 12-byte AEAD nonce for a 64-bit counter: 4 zero bytes followed by
    /// the counter, little-endian (whitepaper 5.4.6). Handshake messages
    /// always use counter 0.
    fn counterNonce(counter: u64) [noise.Aead.nonce_length]u8 {
        var n: [noise.Aead.nonce_length]u8 = @splat(0);
        std.mem.writeInt(u64, n[4..12], counter, .little);
        return n;
    }

    /// Initiator step 1: derive `Ci`/`Hi` from `noise.CONSTRUCTION` +
    /// `noise.IDENTIFIER` + `remote_static_public`, generate an ephemeral
    /// keypair, and produce the encrypted static-key + timestamp message.
    /// `io` supplies entropy for the ephemeral keypair; `now_tai64n` is the
    /// caller-supplied current TAI64N timestamp (12 bytes) — kept out of
    /// this module so it stays platform-agnostic (no clock syscalls here,
    /// consistent with the rest of `wireguard` treating wire codecs as pure
    /// functions over bytes).
    /// (A pre-seeded `local_ephemeral` is used instead of generating one —
    /// deterministic-test hook; leave it null in production.)
    pub fn createInitiation(
        self: *Handshake,
        io: std.Io,
        now_tai64n: [12]u8,
    ) InitiationError!MessageInitiation {
        if (self.state != .idle) return error.AlreadyStarted;
        const eph = self.local_ephemeral orelse Keypair.generate(io);
        self.local_ephemeral = eph;

        var st = initialState(self.remote_static_public);
        var msg: MessageInitiation = undefined;
        msg.type = @intFromEnum(MessageType.handshake_initiation);
        msg.sender_index = self.local_index;

        // e: ephemeral in the clear, mixed into ck and h.
        msg.unencrypted_ephemeral = eph.public;
        noise.kdf1(&st.ck, &eph.public);
        noise.mixHash(&st.h, &eph.public);

        // es: DH(Ei, Sr) → key for the encrypted static.
        var es = noise.X25519.scalarmult(eph.private, self.remote_static_public) catch
            return error.InvalidPublicKey;
        var k = noise.mixKey(&st.ck, &es);
        std.crypto.secureZero(u8, &es);
        noise.Aead.encrypt(
            msg.encrypted_static[0..32],
            msg.encrypted_static[32..48],
            &self.static_keypair.public,
            &st.h,
            counterNonce(0),
            k,
        );
        noise.mixHash(&st.h, &msg.encrypted_static);

        // ss: DH(Si, Sr) → key for the encrypted timestamp.
        var ss = noise.X25519.scalarmult(self.static_keypair.private, self.remote_static_public) catch
            return error.InvalidPublicKey;
        k = noise.mixKey(&st.ck, &ss);
        std.crypto.secureZero(u8, &ss);
        noise.Aead.encrypt(
            msg.encrypted_timestamp[0..12],
            msg.encrypted_timestamp[12..28],
            &now_tai64n,
            &st.h,
            counterNonce(0),
            k,
        );
        std.crypto.secureZero(u8, &k);
        noise.mixHash(&st.h, &msg.encrypted_timestamp);

        self.chaining_key = st.ck;
        self.hash = st.h;
        std.crypto.secureZero(u8, &st.ck);

        msg.mac1 = self.computeMac1(std.mem.asBytes(&msg)[0..@offsetOf(MessageInitiation, "mac1")]);
        msg.mac2 = @splat(0);
        self.state = .initiation_sent;
        return msg;
    }

    /// Responder validates an incoming `MessageInitiation`: checks mac1,
    /// replays the initiator's transcript to decrypt+authenticate the
    /// static key and timestamp, and (on success) records the peer's
    /// ephemeral public key and session index so `createResponse` can reply.
    /// The caller is responsible for looking up which configured peer
    /// `remote_static_public` (decrypted here) belongs to, and for
    /// last-handshake/timestamp bookkeeping across repeated attempts.
    pub fn consumeInitiation(self: *Handshake, msg: MessageInitiation) ConsumeInitiationError!void {
        std.debug.assert(self.state == .idle); // one attempt per Handshake

        // mac1 first — cheap rejection before any DH (keyed with OUR static
        // public key: that is what the initiator derived the mac1 key from).
        const our_mac1_key = noise.mac1Key(self.static_keypair.public);
        const expected_mac1 = noise.keyedMac(
            &our_mac1_key,
            std.mem.asBytes(&msg)[0..@offsetOf(MessageInitiation, "mac1")],
        );
        if (!std.crypto.timing_safe.eql(noise.Mac, expected_mac1, msg.mac1))
            return error.InvalidMac1;

        // Replay the initiator's transcript (we are the responder — Ck0/H0
        // are derived from our own static public key).
        var st = initialState(self.static_keypair.public);
        noise.kdf1(&st.ck, &msg.unencrypted_ephemeral);
        noise.mixHash(&st.h, &msg.unencrypted_ephemeral);

        // es: DH(Sr, Ei) → decrypt the initiator's static public key.
        var es = noise.X25519.scalarmult(self.static_keypair.private, msg.unencrypted_ephemeral) catch
            return error.DecryptionFailed;
        var k = noise.mixKey(&st.ck, &es);
        std.crypto.secureZero(u8, &es);
        var peer_static: PublicKey = undefined;
        noise.Aead.decrypt(
            &peer_static,
            msg.encrypted_static[0..32],
            msg.encrypted_static[32..48].*,
            &st.h,
            counterNonce(0),
            k,
        ) catch return error.DecryptionFailed;
        noise.mixHash(&st.h, &msg.encrypted_static);
        if (!std.mem.eql(u8, &peer_static, &self.remote_static_public))
            return error.UnknownPeer;

        // ss: DH(Sr, Si) → decrypt + authenticate the timestamp.
        var ss = noise.X25519.scalarmult(self.static_keypair.private, peer_static) catch
            return error.DecryptionFailed;
        k = noise.mixKey(&st.ck, &ss);
        std.crypto.secureZero(u8, &ss);
        var ts: [12]u8 = undefined;
        noise.Aead.decrypt(
            &ts,
            msg.encrypted_timestamp[0..12],
            msg.encrypted_timestamp[12..28].*,
            &st.h,
            counterNonce(0),
            k,
        ) catch return error.DecryptionFailed;
        std.crypto.secureZero(u8, &k);
        noise.mixHash(&st.h, &msg.encrypted_timestamp);

        self.chaining_key = st.ck;
        self.hash = st.h;
        std.crypto.secureZero(u8, &st.ck);
        self.remote_ephemeral = msg.unencrypted_ephemeral;
        self.remote_timestamp = ts;
        self.remote_index = msg.sender_index;
        self.state = .initiation_consumed;
    }

    /// Responder step 2: generate our own ephemeral keypair, mix in the
    /// pre-shared key (psk2 — WireGuard's `Kdf3` step), and produce the
    /// empty-payload confirmation message. Requires `consumeInitiation` to
    /// have succeeded first.
    /// (A pre-seeded `local_ephemeral` is used instead of generating one —
    /// deterministic-test hook; leave it null in production.)
    pub fn createResponse(self: *Handshake, io: std.Io) ResponseError!MessageResponse {
        switch (self.state) {
            .initiation_consumed => {},
            .idle, .initiation_sent => return error.NoInitiationConsumed,
            .complete => return error.AlreadyStarted,
        }
        const remote_eph = self.remote_ephemeral.?; // set by consumeInitiation
        const eph = self.local_ephemeral orelse Keypair.generate(io);
        self.local_ephemeral = eph;

        var msg: MessageResponse = undefined;
        msg.type = @intFromEnum(MessageType.handshake_response);
        msg.sender_index = self.local_index;
        msg.receiver_index = self.remote_index;

        // e: our ephemeral in the clear.
        msg.unencrypted_ephemeral = eph.public;
        noise.kdf1(&self.chaining_key, &eph.public);
        noise.mixHash(&self.hash, &eph.public);

        // ee: DH(Er, Ei) — chaining-key only, no key output.
        var ee = noise.X25519.scalarmult(eph.private, remote_eph) catch
            return error.InvalidPublicKey;
        noise.kdf1(&self.chaining_key, &ee);
        std.crypto.secureZero(u8, &ee);

        // se: DH(Er, Si) — chaining-key only.
        var se = noise.X25519.scalarmult(eph.private, self.remote_static_public) catch
            return error.InvalidPublicKey;
        noise.kdf1(&self.chaining_key, &se);
        std.crypto.secureZero(u8, &se);

        // psk2: (ck, tau, k) = KDF3(ck, psk); h = HASH(h || tau).
        var psk_out = noise.kdf3(&self.chaining_key, &self.preshared_key);
        noise.mixHash(&self.hash, &psk_out.out1);

        // Empty-plaintext AEAD — proves agreement on every key derived so far.
        noise.Aead.encrypt(
            msg.encrypted_nothing[0..0],
            msg.encrypted_nothing[0..16],
            "",
            &self.hash,
            counterNonce(0),
            psk_out.out2,
        );
        std.crypto.secureZero(u8, std.mem.asBytes(&psk_out));
        noise.mixHash(&self.hash, &msg.encrypted_nothing);

        msg.mac1 = self.computeMac1(std.mem.asBytes(&msg)[0..@offsetOf(MessageResponse, "mac1")]);
        msg.mac2 = @splat(0);
        self.state = .complete;
        return msg;
    }

    /// Initiator validates the incoming `MessageResponse`: replays the
    /// responder's derivation (ephemeral DHs + psk2 mix) and authenticates
    /// the empty-payload AEAD tag. On success the handshake is complete and
    /// `deriveTransportKeys` may be called.
    pub fn consumeResponse(self: *Handshake, msg: MessageResponse) ConsumeResponseError!void {
        if (self.state != .initiation_sent) return error.NoPendingInitiation;
        const eph = self.local_ephemeral.?; // set by createInitiation

        // mac1 — keyed with OUR static public key (the responder derived it
        // from ours, since the message is addressed to us).
        const our_mac1_key = noise.mac1Key(self.static_keypair.public);
        const expected_mac1 = noise.keyedMac(
            &our_mac1_key,
            std.mem.asBytes(&msg)[0..@offsetOf(MessageResponse, "mac1")],
        );
        if (!std.crypto.timing_safe.eql(noise.Mac, expected_mac1, msg.mac1))
            return error.InvalidMac1;

        // Work on copies so a failed (possibly forged) response cannot
        // corrupt the pending handshake state.
        var ck = self.chaining_key;
        var h = self.hash;

        noise.kdf1(&ck, &msg.unencrypted_ephemeral);
        noise.mixHash(&h, &msg.unencrypted_ephemeral);

        // ee: DH(Ei, Er), then se: DH(Si, Er) — chaining-key only.
        var ee = noise.X25519.scalarmult(eph.private, msg.unencrypted_ephemeral) catch
            return error.DecryptionFailed;
        noise.kdf1(&ck, &ee);
        std.crypto.secureZero(u8, &ee);
        var se = noise.X25519.scalarmult(self.static_keypair.private, msg.unencrypted_ephemeral) catch
            return error.DecryptionFailed;
        noise.kdf1(&ck, &se);
        std.crypto.secureZero(u8, &se);

        // psk2 mix, then authenticate the empty payload.
        var psk_out = noise.kdf3(&ck, &self.preshared_key);
        defer std.crypto.secureZero(u8, std.mem.asBytes(&psk_out));
        noise.mixHash(&h, &psk_out.out1);
        var empty: [0]u8 = .{};
        noise.Aead.decrypt(
            &empty,
            msg.encrypted_nothing[0..0],
            msg.encrypted_nothing[0..16].*,
            &h,
            counterNonce(0),
            psk_out.out2,
        ) catch return error.DecryptionFailed;
        noise.mixHash(&h, &msg.encrypted_nothing);

        self.chaining_key = ck;
        self.hash = h;
        std.crypto.secureZero(u8, &ck);
        self.remote_ephemeral = msg.unencrypted_ephemeral;
        self.remote_index = msg.sender_index;
        self.state = .complete;
    }

    /// Final step, either side, once the handshake completed (initiator
    /// after `consumeResponse`, responder after `createResponse`): split
    /// the chaining key into the two directional transport keys.
    /// `Kdf2(ck, ε) = (k1, k2)`; the initiator's `send` is the responder's
    /// `recv` and vice versa — WireGuard fixes this by having the
    /// *initiator* take `(send, recv) = (k1, k2)` and the *responder* take
    /// `(send, recv) = (k2, k1)`, so both sides must know which role they
    /// played to call this correctly.
    /// Consumes the handshake: the chaining key, transcript hash and the
    /// ephemeral private key are wiped — only the returned keys survive.
    pub fn deriveTransportKeys(self: *Handshake, is_initiator: bool) struct { send: [32]u8, recv: [32]u8 } {
        std.debug.assert(self.state == .complete);
        // Kdf2(ck, ε) = (T1, T2): kdf2 leaves T1 in the chaining key and
        // returns T2.
        const t2 = noise.kdf2(&self.chaining_key, "");
        const t1 = self.chaining_key;
        std.crypto.secureZero(u8, &self.chaining_key);
        std.crypto.secureZero(u8, &self.hash);
        if (self.local_ephemeral) |*kp| std.crypto.secureZero(u8, &kp.private);
        return if (is_initiator)
            .{ .send = t1, .recv = t2 }
        else
            .{ .send = t2, .recv = t1 };
    }

    /// `MAC(mac1_key(remote_static_public), msg_bytes_before_mac1)` — the
    /// mac1 field of any message we send to this peer. `msg_bytes_before_mac1`
    /// is the wire encoding of the message up to (not including) its mac1
    /// field.
    pub fn computeMac1(self: *const Handshake, msg_bytes_before_mac1: []const u8) noise.Mac {
        const key = noise.mac1Key(self.remote_static_public);
        return noise.keyedMac(&key, msg_bytes_before_mac1);
    }

    /// `MAC(cookie, msg_bytes_before_mac2)` if `cookie` is a currently-valid
    /// cookie received from this peer, else an all-zero mac2 (per protocol,
    /// only computed under load after receiving a `CookieReply`).
    pub fn computeMac2(
        self: *const Handshake,
        msg_bytes_before_mac2: []const u8,
        cookie: [16]u8,
    ) noise.Mac {
        _ = self;
        return noise.keyedMac(&cookie, msg_bytes_before_mac2);
    }
};

// ── dark-tests: pulled into the aggregator via ../root.zig `test { }` ──────

const testing = std.testing;

test "message type wire values" {
    try testing.expectEqual(@as(u32, 1), @intFromEnum(MessageType.handshake_initiation));
    try testing.expectEqual(@as(u32, 2), @intFromEnum(MessageType.handshake_response));
    try testing.expectEqual(@as(u32, 3), @intFromEnum(MessageType.cookie_reply));
    try testing.expectEqual(@as(u32, 4), @intFromEnum(MessageType.transport_data));
}

test "wire message sizes match the WireGuard protocol exactly" {
    try testing.expectEqual(@as(usize, 148), @sizeOf(MessageInitiation));
    try testing.expectEqual(@as(usize, 92), @sizeOf(MessageResponse));
    try testing.expectEqual(@as(usize, 64), @sizeOf(CookieReply));
    try testing.expectEqual(@as(usize, 16), @sizeOf(MessageTransportHeader));
}

test "key type widths" {
    try testing.expectEqual(@as(usize, 32), @sizeOf(PrivateKey));
    try testing.expectEqual(@as(usize, 32), @sizeOf(PublicKey));
    try testing.expectEqual(@as(usize, 32), @sizeOf(PresharedKey));
}

// ── known-answer test (independent reference vector) ───────────────────────
//
// No official fixed-input full-handshake vector is published by the
// WireGuard project (wireguard-go's noise tests are self-consistency only;
// its published vectors cover just the KDF — used in noise.zig). This
// vector was therefore generated by an INDEPENDENT reference implementation
// (Python: hashlib BLAKE2s/HMAC + OpenSSL X25519/ChaCha20-Poly1305 via
// cryptography.io) written directly from whitepaper sec 5.4, and that
// reference was itself validated against the official wireguard-go KDF
// vectors before generating this. The kernel interop test below provides
// the non-derived, third-party oracle for the full wire protocol.

/// Hex-decode a compile-time string into a fixed byte array (test helper).
fn hex(comptime s: []const u8) [s.len / 2]u8 {
    var out: [s.len / 2]u8 = undefined;
    _ = std.fmt.hexToBytes(&out, s) catch unreachable;
    return out;
}

/// The fixed inputs of the known-answer vector (also reused as deterministic
/// keys by other tests below).
const kat = struct {
    // Private keys are raw seeds; X25519 clamps on use, identically in the
    // reference and here.
    const si_priv = hex("0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20");
    const sr_priv = hex("404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f");
    const ei_priv = hex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f");
    const er_priv = hex("c0c1c2c3c4c5c6c7c8c9cacbcccdcecfd0d1d2d3d4d5d6d7d8d9dadbdcdddedf");
    const psk: PresharedKey = @splat(0x55);
    const timestamp = hex("400000005e6b0d3d0e2f6b4a");
    const idx_i: u32 = 0x11111111;
    const idx_r: u32 = 0x22222222;

    const msg1 = hex(
        "0100000011111111493e82fc74464a59268817623d2053c5eb8e2cc4a988b4fe" ++
            "e179ec6b010d531dd05176bd13b73f6ff41b1954d28c67af91790e19d64a9030" ++
            "feed78efce91efb40d8a7b62a50bd07538b50822dff5bfb49f103fa19145fd4a" ++
            "8414b756bb2c8bfc4a84bb31c3e5e33f6cffb83bba50ec6761870416da24b7e4" ++
            "38717f2b00000000000000000000000000000000",
    );
    const msg2 = hex(
        "020000002222222211111111dc2cca31e8e43bbd91dff7e475cca3347eb47810" ++
            "7d5bd765aba4ae4a30c35d44a3d294a74fbd0353246e2063f25fddc75e975f76" ++
            "e9840213a22cbadcca574ff500000000000000000000000000000000",
    );
    const t_initiator_send = hex("6c6fbee3c6e669a8dcce54ea527169647f2d8b940f7ce7321cc5d8b334d3902a");
    const t_initiator_recv = hex("df5019942bc7d12e983a480f2136056a37e169fc54ef49c97b60ab90af76c4c7");

    fn initiator() Handshake {
        return .{
            .static_keypair = Keypair.fromPrivateKey(si_priv) catch unreachable,
            .remote_static_public = (Keypair.fromPrivateKey(sr_priv) catch unreachable).public,
            .preshared_key = psk,
            .local_index = idx_i,
            .local_ephemeral = Keypair.fromPrivateKey(ei_priv) catch unreachable,
        };
    }

    fn responder() Handshake {
        return .{
            .static_keypair = Keypair.fromPrivateKey(sr_priv) catch unreachable,
            .remote_static_public = (Keypair.fromPrivateKey(si_priv) catch unreachable).public,
            .preshared_key = psk,
            .local_index = idx_r,
            .local_ephemeral = Keypair.fromPrivateKey(er_priv) catch unreachable,
        };
    }
};

test "KAT: full handshake, byte-exact messages and transport keys" {
    const io = std.testing.io;
    var ini = kat.initiator();
    var rsp = kat.responder();

    const msg1 = try ini.createInitiation(io, kat.timestamp);
    try testing.expectEqualSlices(u8, &kat.msg1, std.mem.asBytes(&msg1));

    try rsp.consumeInitiation(msg1);
    try testing.expectEqual(kat.timestamp, rsp.remote_timestamp.?);
    try testing.expectEqual(kat.idx_i, rsp.remote_index);
    // Both transcripts agree mid-handshake.
    try testing.expectEqual(ini.chaining_key, rsp.chaining_key);
    try testing.expectEqual(ini.hash, rsp.hash);

    const msg2 = try rsp.createResponse(io);
    try testing.expectEqualSlices(u8, &kat.msg2, std.mem.asBytes(&msg2));

    try ini.consumeResponse(msg2);
    try testing.expectEqual(ini.chaining_key, rsp.chaining_key);
    try testing.expectEqual(ini.hash, rsp.hash);
    try testing.expectEqual(kat.idx_r, ini.remote_index);

    const ki = ini.deriveTransportKeys(true);
    const kr = rsp.deriveTransportKeys(false);
    try testing.expectEqual(kat.t_initiator_send, ki.send);
    try testing.expectEqual(kat.t_initiator_recv, ki.recv);
    try testing.expectEqual(ki.send, kr.recv);
    try testing.expectEqual(ki.recv, kr.send);

    // deriveTransportKeys wiped the session secrets.
    try testing.expectEqual(@as(noise.ChainKey, @splat(0)), ini.chaining_key);
    try testing.expectEqual(@as(PrivateKey, @splat(0)), ini.local_ephemeral.?.private);
}

test "self-consistency: full handshake with fresh random keys" {
    const io = std.testing.io;
    const si = Keypair.generate(io);
    const sr = Keypair.generate(io);
    var psk: PresharedKey = undefined;
    io.random(&psk);

    var ini: Handshake = .{
        .static_keypair = si,
        .remote_static_public = sr.public,
        .preshared_key = psk,
        .local_index = 7,
    };
    var rsp: Handshake = .{
        .static_keypair = sr,
        .remote_static_public = si.public,
        .preshared_key = psk,
        .local_index = 9,
    };

    const msg1 = try ini.createInitiation(io, @splat(0x42));
    try rsp.consumeInitiation(msg1);
    try testing.expectEqual(ini.chaining_key, rsp.chaining_key);
    try testing.expectEqual(ini.hash, rsp.hash);
    const msg2 = try rsp.createResponse(io);
    try ini.consumeResponse(msg2);
    try testing.expectEqual(ini.chaining_key, rsp.chaining_key);
    try testing.expectEqual(ini.hash, rsp.hash);

    const ki = ini.deriveTransportKeys(true);
    const kr = rsp.deriveTransportKeys(false);
    try testing.expectEqual(ki.send, kr.recv);
    try testing.expectEqual(ki.recv, kr.send);
    try testing.expect(!std.mem.eql(u8, &ki.send, &ki.recv));
}

test "auth failures: tampering, wrong PSK, wrong peer are all rejected" {
    const io = std.testing.io;

    // Tampered mac1 → InvalidMac1 (cheap rejection).
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        var msg1 = try ini.createInitiation(io, kat.timestamp);
        msg1.mac1[0] ^= 1;
        try testing.expectError(error.InvalidMac1, rsp.consumeInitiation(msg1));
    }
    // Tampered ciphertext with a fixed-up mac1 → DecryptionFailed.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        var msg1 = try ini.createInitiation(io, kat.timestamp);
        msg1.encrypted_timestamp[3] ^= 1;
        msg1.mac1 = ini.computeMac1(std.mem.asBytes(&msg1)[0..@offsetOf(MessageInitiation, "mac1")]);
        try testing.expectError(error.DecryptionFailed, rsp.consumeInitiation(msg1));
    }
    // Responder expecting a different peer → UnknownPeer.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        rsp.remote_static_public = (try Keypair.fromPrivateKey(kat.er_priv)).public;
        const msg1 = try ini.createInitiation(io, kat.timestamp);
        try testing.expectError(error.UnknownPeer, rsp.consumeInitiation(msg1));
    }
    // PSK mismatch → the responder's msg2 fails AEAD on the initiator.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        rsp.preshared_key = @splat(0x66);
        const msg1 = try ini.createInitiation(io, kat.timestamp);
        try rsp.consumeInitiation(msg1); // psk not mixed until message 2
        const msg2 = try rsp.createResponse(io);
        try testing.expectError(error.DecryptionFailed, ini.consumeResponse(msg2));
    }
    // Tampered response mac1 / ciphertext.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        const msg1 = try ini.createInitiation(io, kat.timestamp);
        try rsp.consumeInitiation(msg1);
        var msg2 = try rsp.createResponse(io);
        var bad = msg2;
        bad.mac1[5] ^= 1;
        try testing.expectError(error.InvalidMac1, ini.consumeResponse(bad));
        msg2.encrypted_nothing[0] ^= 1;
        msg2.mac1 = rsp.computeMac1(std.mem.asBytes(&msg2)[0..@offsetOf(MessageResponse, "mac1")]);
        try testing.expectError(error.DecryptionFailed, ini.consumeResponse(msg2));
    }
}

test "hostile: an all-zero ephemeral (X25519 identity element) is rejected, not crashed on" {
    // Every DH in this handshake feeds an attacker-controlled public key
    // (`unencrypted_ephemeral` travels in the clear) straight into
    // `X25519.scalarmult`, which is `IdentityElementError!` — std itself
    // rejects the all-zero output an all-zero/low-order input point
    // produces (RFC 7748's contributory-behaviour concern). Both `catch
    // return error.InvalidPublicKey`/`DecryptionFailed` sites this exercises
    // are real code, but nothing in the suite ever supplies a key that
    // trips them: every KAT and every other adversarial test uses a
    // genuine, non-degenerate ephemeral. This is the identity-element case
    // the module doc's own DH calls implicitly assume can't reach them
    // unhandled.
    const io = std.testing.io;

    // Responder side: initiator's message 1 carries an all-zero ephemeral.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        var msg1 = try ini.createInitiation(io, kat.timestamp);
        msg1.unencrypted_ephemeral = @splat(0);
        msg1.mac1 = ini.computeMac1(std.mem.asBytes(&msg1)[0..@offsetOf(MessageInitiation, "mac1")]);
        try testing.expectError(error.DecryptionFailed, rsp.consumeInitiation(msg1));
    }
    // Initiator side: responder's message 2 carries an all-zero ephemeral.
    {
        var ini = kat.initiator();
        var rsp = kat.responder();
        const msg1 = try ini.createInitiation(io, kat.timestamp);
        try rsp.consumeInitiation(msg1);
        var msg2 = try rsp.createResponse(io);
        msg2.unencrypted_ephemeral = @splat(0);
        msg2.mac1 = rsp.computeMac1(std.mem.asBytes(&msg2)[0..@offsetOf(MessageResponse, "mac1")]);
        try testing.expectError(error.DecryptionFailed, ini.consumeResponse(msg2));
    }
}

test "auth failure does not corrupt pending initiator state" {
    const io = std.testing.io;
    var ini = kat.initiator();
    var rsp = kat.responder();
    const msg1 = try ini.createInitiation(io, kat.timestamp);
    try rsp.consumeInitiation(msg1);
    const msg2 = try rsp.createResponse(io);

    var forged = msg2;
    forged.encrypted_nothing[7] ^= 1;
    forged.mac1 = rsp.computeMac1(std.mem.asBytes(&forged)[0..@offsetOf(MessageResponse, "mac1")]);
    try testing.expectError(error.DecryptionFailed, ini.consumeResponse(forged));

    // The genuine response still completes the handshake afterwards.
    try ini.consumeResponse(msg2);
    const ki = ini.deriveTransportKeys(true);
    try testing.expectEqual(kat.t_initiator_send, ki.send);
}

test "call-order errors" {
    const io = std.testing.io;
    var ini = kat.initiator();
    _ = try ini.createInitiation(io, kat.timestamp);
    try testing.expectError(error.AlreadyStarted, ini.createInitiation(io, kat.timestamp));

    var rsp = kat.responder();
    try testing.expectError(error.NoInitiationConsumed, rsp.createResponse(io));

    var idle = kat.initiator();
    const msg2: MessageResponse = std.mem.zeroes(MessageResponse);
    try testing.expectError(error.NoPendingInitiation, idle.consumeResponse(msg2));
}

// ── integration test (real kernel WireGuard as the protocol oracle) ────────
//
// Gated like root.zig's netlink integration tests: Linux + euid 0 (run under
// `unshare -rn` for an isolated netns with CAP_NET_ADMIN) + the `ip`/`wg`
// tools + the wireguard kernel module, else `error.SkipZigTest`.
//
// The KERNEL plays the initiator (so it owns TAI64N clocking and retries);
// we are the responder on a plain UDP socket. Proof of key agreement: the
// kernel's post-handshake keepalive — a transport-data packet encrypted by
// the kernel under ITS T_send — must AEAD-decrypt under OUR derived
// `recv` key. That authenticates the entire handshake (both messages, PSK
// mix and transport-key split) against an implementation we did not write.

/// Run an external command; `error.SkipZigTest` when it cannot be spawned.
fn runCmd(gpa: std.mem.Allocator, io: std.Io, argv: []const []const u8) !u8 {
    const res = std.process.run(gpa, io, .{ .argv = argv }) catch return error.SkipZigTest;
    defer gpa.free(res.stdout);
    defer gpa.free(res.stderr);
    return switch (res.term) {
        .exited => |code| code,
        else => 255,
    };
}

test "integration (root): live handshake with kernel WireGuard, keepalive decrypts" {
    if (builtin.os.tag != .linux) return error.SkipZigTest;
    const linux = std.os.linux;
    if (linux.geteuid() != 0) return error.SkipZigTest; // needs CAP_NET_ADMIN
    const gpa = testing.allocator;

    var threaded = std.Io.Threaded.init(gpa, .{});
    defer threaded.deinit();
    const io = threaded.io();

    // Fresh identities: ours (userspace responder) and the kernel's.
    const our_kp = Keypair.generate(io);
    const kernel_kp = Keypair.generate(io);
    var psk: PresharedKey = undefined;
    io.random(&psk);

    // UDP socket on loopback; the kernel peer's endpoint points at it.
    const sock_rc = linux.socket(linux.AF.INET, linux.SOCK.DGRAM | linux.SOCK.CLOEXEC, 0);
    if (linux.errno(sock_rc) != .SUCCESS) return error.SkipZigTest;
    const fd: i32 = @intCast(sock_rc);
    defer _ = linux.close(fd);
    var bind_addr: linux.sockaddr.in = .{
        .port = 0,
        .addr = std.mem.nativeToBig(u32, 0x7f000001), // 127.0.0.1
    };
    if (linux.errno(linux.bind(fd, @ptrCast(&bind_addr), @sizeOf(linux.sockaddr.in))) != .SUCCESS)
        return error.SkipZigTest;
    var bound: linux.sockaddr.in = undefined;
    var bound_len: linux.socklen_t = @sizeOf(linux.sockaddr.in);
    try testing.expectEqual(
        .SUCCESS,
        linux.errno(linux.getsockname(fd, @ptrCast(&bound), &bound_len)),
    );
    const our_port = std.mem.bigToNative(u16, bound.port);

    // Kernel-side device: our public key as its peer, endpoint = our socket,
    // persistent keepalive so the kernel initiates immediately. Configured
    // through this module's OWN genl control plane (root.zig) — not the `wg`
    // tool, which Ubuntu's AppArmor profile confines to /etc/wireguard key
    // files — dogfooding both halves of the module in one test.
    const wgctl = @import("root.zig");
    const ifname = "zigwghs0";
    if (try runCmd(gpa, io, &.{ "ip", "link", "add", ifname, "type", "wireguard" }) != 0)
        return error.SkipZigTest; // wireguard module unavailable
    defer _ = runCmd(gpa, io, &.{ "ip", "link", "del", ifname }) catch {};
    _ = try runCmd(gpa, io, &.{ "ip", "link", "set", "lo", "up" }); // fresh netns has lo down
    var wg = wgctl.Wireguard.open(gpa) catch return error.SkipZigTest;
    defer wg.close();
    try wg.setDevice(.{
        .ifname = ifname,
        .private_key = kernel_kp.private,
        .peers = &.{.{
            .public_key = our_kp.public,
            .preshared_key = psk,
            .endpoint = .{ .v4 = .{ .addr = .{ 127, 0, 0, 1 }, .port = our_port } },
            .persistent_keepalive_interval = 1,
        }},
    });
    try testing.expectEqual(@as(u8, 0), try runCmd(gpa, io, &.{ "ip", "link", "set", ifname, "up" }));

    // Responder state: we know the kernel's static public key (Noise IK).
    var hs: Handshake = .{
        .static_keypair = our_kp,
        .remote_static_public = kernel_kp.public,
        .preshared_key = psk,
        .local_index = 0x5a5a5a5a,
    };
    var keys: ?struct { send: [32]u8, recv: [32]u8 } = null;

    // Drive the exchange: initiation in → response out → keepalive in.
    var buf: [2048]u8 = undefined;
    var polls_left: u32 = 40; // 40 × 500 ms = 20 s overall budget
    while (polls_left > 0) : (polls_left -= 1) {
        var pfd = [1]linux.pollfd{.{ .fd = fd, .events = linux.POLL.IN, .revents = 0 }};
        const prc = linux.poll(&pfd, 1, 500);
        try testing.expectEqual(.SUCCESS, linux.errno(prc));
        if (prc == 0) continue;

        var src: linux.sockaddr.in = undefined;
        var src_len: linux.socklen_t = @sizeOf(linux.sockaddr.in);
        const rrc = linux.recvfrom(fd, &buf, buf.len, 0, @ptrCast(&src), &src_len);
        try testing.expectEqual(.SUCCESS, linux.errno(rrc));
        const n = rrc;
        if (n < 4) continue;

        switch (std.mem.readInt(u32, buf[0..4], .little)) {
            @intFromEnum(MessageType.handshake_initiation) => {
                if (n != @sizeOf(MessageInitiation)) continue;
                if (hs.state != .idle) continue; // kernel retry — already answered
                var msg1: MessageInitiation = undefined;
                @memcpy(std.mem.asBytes(&msg1), buf[0..@sizeOf(MessageInitiation)]);
                try hs.consumeInitiation(msg1);
                var msg2 = try hs.createResponse(io);
                const k = hs.deriveTransportKeys(false);
                keys = .{ .send = k.send, .recv = k.recv };
                const src_len_const: linux.socklen_t = src_len;
                const wrc = linux.sendto(
                    fd,
                    std.mem.asBytes(&msg2),
                    @sizeOf(MessageResponse),
                    0,
                    @ptrCast(&src),
                    src_len_const,
                );
                try testing.expectEqual(.SUCCESS, linux.errno(wrc));
                try testing.expectEqual(@sizeOf(MessageResponse), wrc);
            },
            @intFromEnum(MessageType.transport_data) => {
                // Keepalive: 16-byte header + empty plaintext + 16-byte tag.
                if (n != @sizeOf(MessageTransportHeader) + noise.tag_len) continue;
                const k = keys orelse continue; // transport before our response? ignore
                try testing.expectEqual(hs.local_index, std.mem.readInt(u32, buf[4..8], .little));
                const counter = std.mem.readInt(u64, buf[8..16], .little);
                var empty: [0]u8 = .{};
                // THE oracle assertion: a kernel-encrypted packet decrypts
                // under our derived receive key.
                try noise.Aead.decrypt(
                    &empty,
                    buf[16..16],
                    buf[16..32].*,
                    "",
                    Handshake.counterNonce(counter),
                    k.recv,
                );
                return; // interop proven
            },
            else => continue,
        }
    }
    std.debug.print("kernel WireGuard interop: no decryptable keepalive within budget\n", .{});
    return error.TestUnexpectedResult;
}
