#!/usr/bin/env python3
"""Differential oracle for the UTF-8 / UTF-16 decoders: CPython's codecs as a black box.

CPython's `bytes.decode(codec, "replace")` replaces each maximal subpart of an
ill-formed sequence with one U+FFFD, which is what the WHATWG Encoding Standard's
UTF-8 and UTF-16 decoders do (checked by hand on the shapes listed in SPEC.md);
`encoding` must produce the same text for every input below.

Writes `src/testdata/codec_golden.txt`, one case per line:
`codec<TAB>input-hex<TAB>expected-hex<TAB>strict`, where for codec utf-8 /
utf-16le / utf-16be `expected` is the UTF-8 text `decode(codec, "replace")`
gives and `strict` is 1 when a strict decode succeeds (the fatal mode must
succeed exactly then); for enc-utf-16le / enc-utf-16be the input is UTF-8
(possibly ill-formed) and `expected` is `decode("utf-8", "replace")` encoded
as UTF-16 without BOM.
Inputs are built from valid sequences of every length, truncations, overlongs,
encoded surrogates, out-of-range leads, lone and swapped surrogates, odd
lengths, and random bytes, so both the clean path and every error path occur.

    modules/encoding/tools/codec-oracle.py > modules/encoding/src/testdata/codec_golden.txt
"""
import random
import sys

rng = random.Random(20261004)

U8_PIECES = [
    b"A", b",", b"\x00", b"\x7f", b"\xc2\xa9", b"\xdf\xbf", b"\xe2\x82\xac", b"\xef\xbf\xbf",
    b"\xf0\x9f\x98\x80", b"\xf4\x8f\xbf\xbf",
    # ill-formed
    b"\xc0\xaf", b"\xc1\xbf", b"\xe0\x80\xaf", b"\xe0\x9f\xbf", b"\xed\xa0\x80", b"\xed\xbf\xbf",
    b"\xf0\x80\x80\x80", b"\xf0\x8f\xbf\xbf", b"\xf4\x90\x80\x80", b"\xf5\x80\x80\x80", b"\xff",
    b"\xfe", b"\x80", b"\xbf", b"\xc2", b"\xe2", b"\xe2\x82", b"\xf0", b"\xf0\x9f", b"\xf0\x9f\x98",
]


def u16_unit(u, le):
    return u.to_bytes(2, "little" if le else "big")


def u16_pieces(le):
    units = [0x41, 0x2C, 0x00, 0xE9, 0x20AC, 0xFFFF, 0xFEFF]
    out = [u16_unit(u, le) for u in units]
    out += [u16_unit(0xD83D, le) + u16_unit(0xDE00, le)]  # a valid pair
    out += [u16_unit(0xD800, le), u16_unit(0xDBFF, le), u16_unit(0xDC00, le), u16_unit(0xDFFF, le)]
    out += [u16_unit(0xDC00, le) + u16_unit(0xD800, le)]  # swapped pair
    return out


def build(pieces):
    n = rng.randrange(1, 7)
    s = b"".join(rng.choice(pieces) for _ in range(n))
    if rng.random() < 0.15:
        s += bytes([rng.randrange(256)])  # odd tail / stray byte
    return s


def main():
    print("# CPython", sys.version.split()[0], "codecs, errors='replace'; generated by tools/codec-oracle.py")
    seen = set()
    for codec, pieces in [("utf-8", U8_PIECES), ("utf-16le", u16_pieces(True)), ("utf-16be", u16_pieces(False))]:
        cases = [b""] + [build(pieces) for _ in range(1500)]
        cases += [bytes(rng.randrange(256) for _ in range(rng.randrange(1, 9))) for _ in range(300)]
        for c in cases:
            if (codec, c) in seen:
                continue
            seen.add((codec, c))
            want = c.decode(codec, "replace").encode("utf-8")
            try:
                c.decode(codec)
                strict = 1
            except UnicodeDecodeError:
                strict = 0
            print(f"{codec}\t{c.hex()}\t{want.hex()}\t{strict}")
    for le in (True, False):
        name = "enc-utf-16le" if le else "enc-utf-16be"
        for c in [b""] + [build(U8_PIECES) for _ in range(600)]:
            if (name, c) in seen:
                continue
            seen.add((name, c))
            want = c.decode("utf-8", "replace").encode("utf-16-le" if le else "utf-16-be")
            print(f"{name}\t{c.hex()}\t{want.hex()}\t1")


main()
